### ISSUE TITLE
Errors in syslog

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2698] opened 2019-07-02 18:39 UTC
Error in syslog:
```
xJul  2 14:00:02 ntopng ntopng[3143]: 02/Jul/2019 14:00:02 [LuaEngine.cpp:8299] ERROR: Cannot complete SNMP caching in 5 minutes.                    x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/bytes.rrd][1562090403:112193:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/bytes.rrd: illegal attemx
pt to update using time 1562090403 when last update                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/active_flows.rrd][1562090403:0:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/active_flows.rrd: illex
gal attempt to update using time 1562090403 when la                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/total_flows.rrd][1562090403:136:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/total_flows.rrd: illex
gal attempt to update using time 1562090403 when la                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/anomalous_flows.rrd][1562090403:0:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/anomalous_flows.rrdx
: illegal attempt to update using time 1562090403 w                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/unreachable_flows.rrd][1562090403:0:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/unreachable_flowsx
.rrd: illegal attempt to update using time 15620904                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/a2cc_2bff_feb2_0000/host_unreachable_flows.rrd][1562090403:0:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/a2cc_2bff_feb2_0000/host_unreachx
able_flows.rrd: illegal attempt to update using tim                                                                                                  x
xJul  2 14:00:03 ntopng ntopng[3143]: 02/Jul/2019 14:00:03 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
```
------------
![image](https://user-images.githubusercontent.com/48565067/60537694-14a88180-9cd7-11e9-8466-ee2eff1a74ae.png)

**Comment by StewAlexander-com** [comment] 2019-07-02 18:50
```
Jul  2 14:00:02 ntopng ntopng[3143]: 02/Jul/2019 13:55:37 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/7/rrd/fe80/0000/0000/00x
00/7ec3_a1ff_fea0_0000/ndpi_categories/Network.rrd][1562090136:5960467:0] failed [/var/lib/ntopng/7/rrd/fe80/0000/0000/0000/7ec3_a1ff_fea0_0000/ndpi_x
categories/Network.rrd: illegal attempt to update u                                                                                                  x
xJul  2 14:00:02 ntopng ntopng[3143]: 02/Jul/2019 14:00:02 [housekeeping.lua:30] [lists_utils.lua:396] WARNING: Could not find '/var/lib/ntopng/categx
ory_lists/Cisco Talos Intelligence.txt'...         
```

**Comment by emanuele-f** [comment] 2019-07-04 07:49
Can you figure out the full ipv6 address which is causing the troubles? This should have been fixed in 005d56e5ddcd130297479bc497b029ea754f8dca

**Comment by emanuele-f** [comment] 2019-07-04 14:29
In particular, the IPv6 reported in the error message is for `fe80::a2cc:2bff:feb2:0000` so these are the possibilities:

1. Multiple host with that IPv6 address actually exists in your network (unlikely)
2. Multiple hosts with IPv6 starting with `fe80::a2cc:2bff:feb2` exists in your network and the last 4 hex digits reported are wrong due to a bug

**Comment by emanuele-f** [comment] 2019-07-05 14:44
@StewAlexanderACC any news?

**Comment by StewAlexander-com** [comment] 2019-07-05 15:19
Sorry @emanuele-f got a little distracted...

The issue here is that we do not have any policies that limit the things on our guest wireless network, a sore point with me, **_really_**.

So, as students come into and out of our college we get about 6,000 or so wireless devices on our guest network doing all sorts of nonsense - consisting of Apple, Google, Amazon, Samsung, even Hauwaei and others.

Even if I could track down if there were honestly two systems with the same  IPv6 address [a remarkable rarity considering how IPv6 works), there is nothing at the moment I could do about it, because we don't own it - or have policies to forbid it. - As in we don't own the IPv6 device.

NONE and mean **none** of our devices we (the information technology team) setup have IPv6 addresses (hard enough keeping track of the IPv4 stuff)

Again, **_unfortunately_** we can't keep our teachers and employees from plugging in devices to their PCs, Ethernet jacks, or using our protected wireless networks for their equipment (although they do know this is being monitored, and is for official college business, so there is much much less of this going on).

Your edge software might be useful as we don't have captive portals or any policies for our LAN

**Comment by emanuele-f** [comment] 2019-07-05 15:27
I see, anyway that IPv6 address is just a link local address, so it is something assigned automatically based on the device mac address, so it should not have collisions. It is more likely that the issue is point 2, but that was fixed in 005d56e5ddcd130297479bc497b029ea754f8dca on 1th of June, so your version should already be fixed. Just to be sure, please update ntopng to the latest version again and see if you still get the error.

**Comment by StewAlexander-com** [comment] 2019-07-05 15:33
ok will do

**Comment by StewAlexander-com** [comment] 2019-07-05 15:37
Apparently we had a few broken dependencies, fixing these and upgrading

**Comment by StewAlexander-com** [comment] 2019-07-05 15:43
Please keep the ticket open over the weekend and I will report back with what I see, on the new release

**Comment by StewAlexander-com** [comment] 2019-07-08 17:34
@emanuele-f 
```
Jul  8 13:30:29 ntopng ntopng[6567]: 08/Jul/2019 13:30:29 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00
00/4691_60ff_feeb_0000/Unknown.rrd][1562607029:1692:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/Unknown.rrd: illegal attx
empt to update using time 1562607029 when last upda                                                                                                  x
xJul  8 13:30:29 ntopng ntopng: [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpix
_categories/Unspecified.rrd][1562607029:1692:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpi_categories/Unspecified.rrdx
: illegal attempt to upd                                                                                                                             x
xJul  8 13:30:29 ntopng ntopng[6567]: 08/Jul/2019 13:30:29 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/4691_60ff_feeb_0000/ndpi_categories/Unspecified.rrd][1562607029:1692:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpix
_categories/Unspecified.rrd: illegal attempt to upd                                                                                                  x
xJul  8 13:30:29 ntopng ntopng: [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpix
_categories/Network.rrd][1562607029:2083:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpi_categories/Network.rrd: illegax
l attempt to update usin                                                                                                                             x
xJul  8 13:30:29 ntopng ntopng[6567]: 08/Jul/2019 13:30:29 [5min.lua:25] [rrd.lua:368] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/fe80/0000/0000/00x
00/4691_60ff_feeb_0000/ndpi_categories/Network.rrd][1562607029:2083:0] failed [/var/lib/ntopng/0/rrd/fe80/0000/0000/0000/4691_60ff_feeb_0000/ndpi_catx
egories/Network.rrd: illegal attempt to update usin                    
```
![image](https://user-images.githubusercontent.com/48565067/60830409-22518180-a185-11e9-8d90-dc21cb58bfb1.png)

**Comment by emanuele-f** [comment] 2019-08-02 09:54
This should be fixed in https://github.com/ntop/ntopng/commit/b365cd28df7abe8f7f4b3628d99fbf5aac163ccd . Please wait one hour until the new package is available, update and confirm that the issue is fixed for you.

**Comment by emanuele-f** [comment] 2019-08-06 12:23
@StewAlexanderACC were you able to upgrade and test it?

**Comment by StewAlexander-com** [comment] 2019-08-06 13:20
yes

**Comment by StewAlexander-com** [comment] 2019-08-06 13:22
i'll take a look i a minute

**Comment by StewAlexander-com** [comment] 2019-08-06 13:26
appears fixed

**Comment by emanuele-f** [comment] 2019-08-06 13:38
Thank you for reporting

**Closed as completed by emanuele-f** 2019-08-06 13:38 UTC
Labels: To Be Confirmed
