### ISSUE TITLE
HTTPs not functional although it's enabled

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#221] opened 2015-10-12 08:47 UTC
/Ntop/ntopng$ ntopng
12/Oct/2015 10:43:39 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
12/Oct/2015 10:43:39 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
12/Oct/2015 10:43:39 [Ntop.cpp:1178] Registered interface view p3p1 [id: 0]
12/Oct/2015 10:43:39 [Ntop.cpp:1148] Registered interface p3p1 [id: 0]
...
12/Oct/2015 10:43:39 [Utils.cpp:286] Privileges are not dropped as we're not superuser
12/Oct/2015 10:43:39 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
12/Oct/2015 10:43:39 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.

Although:
/Ntop/ntopng/httpdocs/ssl# ls -l
total 16
-rw-r--r-- 1 actionmystique actionmystique 3249 Oct 12 10:35 ntopng-cert.pem

**Comment by lucaderi** [comment] 2015-10-12 09:03
Duplicate of #220

**Closed by lucaderi** 2015-10-12 09:03 UTC

**Comment by jean-christophe-manciot** [comment] 2015-10-12 09:20
Really?
Ntop/ntopng$ ntopng --dont-change-user -i 1
12/Oct/2015 11:12:40 [Ntop.cpp:929] Setting local networks to 127.0.0.0/8
12/Oct/2015 11:12:40 [Redis.cpp:105] Successfully connected to redis 127.0.0.1:6379@0
12/Oct/2015 11:12:40 [Ntop.cpp:1178] Registered interface view p3p1 [id: 0]
12/Oct/2015 11:12:40 [Ntop.cpp:1148] Registered interface p3p1 [id: 0]
12/Oct/2015 11:12:40 [main.cpp:237] PID stored in file /var/tmp/ntopng.pid
12/Oct/2015 11:12:40 [HTTPserver.cpp:458] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
...

**Comment by lucaderi** [comment] 2015-10-12 09:50
Is ntopng our binary package or something you compiled? If the latter you might not have compiled it with SSL. Please use our packages.

**Comment by jean-christophe-manciot** [comment] 2015-10-12 09:59
What do you mean "you might not have compiled it with SSL"?: No configure option is available (or described)  to toggle SSL:
./configure --help
`configure' configures ntopng 2.1.151011 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.

Defaults for the options are specified in brackets.

Configuration:
  -h, --help              display this help and exit
      --help=short        display options specific to this package
      --help=recursive    display the short help of all the included packages
  -V, --version           display version information and exit
  -q, --quiet, --silent   do not print `checking ...' messages
      --cache-file=FILE   cache test results in FILE [disabled]
  -C, --config-cache      alias for `--cache-file=config.cache'
  -n, --no-create         do not create output files
      --srcdir=DIR        find the sources in DIR [configure dir or `..']

Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
                          [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
                          [PREFIX]

By default, `make install' will install all the files in
`/usr/local/bin', `/usr/local/lib' etc.  You can specify
an installation prefix other than `/usr/local' using `--prefix',
for instance `--prefix=$HOME'.

For better control, use the options below.

Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
  --mandir=DIR            man documentation [DATAROOTDIR/man]
  --docdir=DIR            documentation root [DATAROOTDIR/doc/ntopng]
  --htmldir=DIR           html documentation [DOCDIR]
  --dvidir=DIR            dvi documentation [DOCDIR]
  --pdfdir=DIR            pdf documentation [DOCDIR]
  --psdir=DIR             ps documentation [DOCDIR]

Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  LIBS        libraries to pass to the linker, e.g. -l<library>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CPP         C preprocessor

**Comment by jean-christophe-manciot** [comment] 2015-10-12 10:18
And of course openssl is installed on my system.

**Comment by lucaderi** [comment] 2015-10-12 10:21
it doens't matter if openssl is installed.

I like your questions, but we cannot support (lack of time) everyone. if you want support please use our packages.

**Comment by jean-christophe-manciot** [comment] 2015-10-13 08:34
I'm not asking for support: I'm reporting a bug.
Unfortunately, closing the report and ignoring the bug  does not solve it, so I won't be able to use your product & distribute it to my community. It's a lose/lose. Your choice.
