### ISSUE TITLE
Error "81: printf: 8+dfsg1-2: not completely converted" on apt-ntop-stable installation (Debian 10.7)

### ISSUE THREAD

**Issue by ctbfourone** [ntop/ntopng#5019] opened 2021-02-05 17:53 UTC
The postinst script bails on line 81, dpkg complains and exits.

```
$ sudo apt install ntopng
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  ntopng
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/7,868 kB of archives.
After this operation, 48.3 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package ntopng.
(Reading database ... 101451 files and directories currently installed.)
Preparing to unpack .../ntopng_4.2.210204-13054_amd64.deb ...
Unpacking ntopng (4.2.210204-13054) ...
Setting up ntopng (4.2.210204-13054) ...
Rebuilding ld cache...
(Re)Starting ntopng...
/var/lib/dpkg/info/ntopng.postinst: 81: printf: 8+dfsg1-2: not completely converted
dpkg: error processing package ntopng (--configure):
 installed ntopng package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 ntopng
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I was able to move past it by manually enabling ntopng (`systemctl enable ntopng`) and starting it, but the postinst hook tries to run any subsequent time apt/dpkg is called. This is on Debian 10.7. Thanks.

**Comment by ctbfourone** [comment] 2021-02-05 22:34
Works fine with the nightly build repo.

**Comment by lucaderi** [comment] 2021-02-06 14:30
@simonemainardi Can you please check on the continuous integration chain?

**Comment by simonemainardi** [comment] 2021-02-08 14:08
possible duplicate of https://github.com/ntop/ntopng/issues/4695

**Comment by simonemainardi** [comment] 2021-02-08 14:22
can you please post the output of 

```
bash -x /var/lib/dpkg/info/ntopng.postinst
```

**Comment by simonemainardi** [comment] 2021-02-08 14:34
seems the fix was not backported to stable. @cardigliano is taking care of this.

**Comment by ctbfourone** [comment] 2021-02-08 22:56
> can you please post the output of
> 
> ```
> bash -x /var/lib/dpkg/info/ntopng.postinst
> ```

```
$ sudo bash -x /var/lib/dpkg/info/ntopng.postinst
+ set -e
+ . /usr/share/debconf/confmodule
++ '[' '!' '' ']'
++ PERL_DL_NONLAZY=1
++ export PERL_DL_NONLAZY
++ '[' '' ']'
++ exec /usr/share/debconf/frontend /var/lib/dpkg/info/ntopng.postinst
Use of uninitialized value $action in string eq at /usr/share/debconf/frontend line 27.
dpkg-maintscript-helper: error: couldn't identify the package
```

That said, I wasn't able to reproduce the error after rolling back to stable just now. Perhaps it was fixed before I saw your comment.

**Comment by simonemainardi** [comment] 2021-02-09 07:40
> That said, I wasn't able to reproduce the error after rolling back to stable just now. Perhaps it was fixed before I saw your comment.

Yes. Thanks for this update.

**Closed as completed by simonemainardi** 2021-02-09 07:40 UTC
