### ISSUE TITLE
Auto-Generate Report

### ISSUE THREAD

**Issue by joonasak** [ntop/ntopng#6657] opened 2022-06-04 03:57 UTC
**What would you like to add or change?**:
I would like to request a feature that can let the nTopng auto generate the report by Daily, Weekly or Monthly.

**Why do you and others need this?**:
Most customer are asking about this because most of them need the report in everyday or every week.

**Comment by cardigliano** [comment] 2022-11-28 15:28
Duplicate of https://github.com/ntop/ntopng/issues/2295

**Closed as completed by cardigliano** 2022-11-28 15:28 UTC
Labels: Enhancement
