### ISSUE TITLE
THROUGHPUT fields in zero MySQL

### ISSUE THREAD

**Issue by rcarvalloh** [ntop/ntopng#1406] opened 2017-08-16 13:37 UTC
Hello,

I've started testing with the fields:

- SRC_TO_DST_MAX_THROUGHPUT
- SRC_TO_DST_MIN_THROUGHPUT
- SRC_TO_DST_AVG_THROUGHPUT
- SRC_TO_DST_AVG_THROUGHPUT
- DST_TO_SRC_MIN_THROUGHPUT
- DST_TO_SRC_AVG_THROUGHPUT

But I've been noticing that there are a lot of flows that have all of these in zero even though there are bytes/packets reported in the IN_BYTES and OUT_BYTES. Is there any explanation for this? 

I've also got a question regarding the throughputs and hope I could get help with this. How one could get the avg throughput calculated over all the flows using the throughput fields?

I want to calculate incoming and outgoing traffic as a whole over a time span (say 60 seconds) so I can print it to a graphics tool (grafana for instance) in near real time.

I tried something like this:

```
SELECT UNIX_TIMESTAMP(NOW()) INTO @endRange;
SELECT (@endRange-60) INTO @startRange;
SELECT tb1.time, SUM(tb1.outt)/(1024*1024*60), SUM(tb1.incc)/(1024*1024*60)
FROM(
   SELECT LAST_SWITCHED AS time, SRC_TO_DST_AVG_THROUGHPUT AS outt, 
   DST_TO_SRC_AVG_THROUGHPUT AS incc
   FROM netflow_v9_flows
   WHERE LAST_SWITCHED BETWEEN @startRange AND @endRange
   AND IPV4_SRC_ADDR BETWEEN 111111111 AND 222222222
   UNION
   SELECT LAST_SWITCHED AS time, DST_TO_SRC_AVG_THROUGHPUT AS outt, 
   SRC_TO_DST_AVG_THROUGHPUT AS incc
   FROM netflow_v9_flows
   WHERE LAST_SWITCHED BETWEEN @startRange AND @endRange
   AND IPV4_DST_ADDR BETWEEN 111111111 AND 222222222) tb1
GROUP BY tb1.time

```
But this doesn't provide accurate information as compared to the other systems that are monitoring using SNMP, I don't see any other way to group by minute flows and calculating the throughput of that span in mbps.

My reasoning is that if I group by LAST_SWITCHED I should get a consistent view of the flows up to 60 seconds prior to that moment (our routers have an active_timeout of 60 seconds). I do the UNION of two tables that get the information referenced to our local IPs (the values in the "BETWEEN" clausule) to view what's IN and OUT whether we started the connection or was started outside.

However I'm not 100% sure of my reasoning, specially by seeing the results.

Any suggestion about this? In the end I want to check the throughput in near real time in and out of the top 10 ASNs and Countries

Thank you in advance.

**Comment by simonemainardi** [comment] 2017-08-17 13:14
Please, report the software configurations used and an example of a flow that has all-zero throughput values.

As concerns the mysql query, why you didn't use the builtin mysql AVG() function?

By the way, did you know that ntopng features a grafana plugin? see https://github.com/ntop/ntopng/blob/dev/doc/README.grafana

**Comment by rcarvalloh** [comment] 2017-08-17 14:03
Hi,

I didn't know about the plugin, nice, I'll check it out. 

The actual DB writing is being done by NPROBE, here's its configuration:
```
-n=none
-i=none
--online-license-check
-t=60
-d=60
-a=0
-e=1
-B=10
-w=128000
-z=160
-S=1:1
-E=0:0
-g=/var/run/nprobe-file.pid
-3=1234
--zmq=tcp://127.0.0.1:5556
--vlanid-as-iface-idx=none
-T=%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %SRC_AS %DST_AS %LAST_SWITCHED %FIRST_SWITCHED %OUT_BYTES %OUT_PKTS %IPV6_SRC_ADDR %IPV6_DST_ADDR %DIRECTION %SRC_TO_DST_MAX_THROUGHPUT %SRC_TO_DST_MIN_THROUGHPUT %SRC_TO_DST_AVG_THROUGHPUT %DST_TO_SRC_MAX_THROUGHPUT %DST_TO_SRC_MIN_THROUGHPUT %DST_TO_SRC_AVG_THROUGHPUT %SRC_IP_COUNTRY %DST_IP_COUNTRY
-V=9
--mysql=192.168.1.2:ntopng:netflow_v9_:ntop-user:ntopng
--dump-stats=/var/log/nprobe/file-0_flows_stats.txt
```

And here's a PDF with some flows as reported by in MySQL

[flows in zero throughput.pdf](https://github.com/ntop/ntopng/files/1231427/flows.in.zero.throughput.pdf)

I'm using the latest versions in a fresh Ubuntu Server install. 

Concerning the query, I did try that, but I'm still not convinced about the values it's reporting. I'm still getting "wrong values" as compared by the other reporting tools. If you've got any other suggestion I'm open to this, seems I can't figure this out.

**Comment by rcarvalloh** [comment] 2017-08-17 14:19
Regarding the grafana plugin you mentioned, I did the things said in the link you sent me. However it isn't working, when trying to connect to Ntopng I get the following:

HTTP Error
Not Found

If I follow the link in a browser I get:
Page "/lua/modules/grafana" was not found

Is there anything else that should be done in Ntopng?

**Comment by Gelob** [comment] 2017-08-17 15:22
try a trailing slash '/lua/modules/grafana/'

**Comment by rcarvalloh** [comment] 2017-08-17 15:31
Hi I tried that already, thank you for the suggestion, however I got the same messages. 

I'm using the Small Business Edition  v.3.0.170719

**Comment by Gelob** [comment] 2017-08-17 17:23
Do you have a web server (nginx/apache) in front of ntopng or grafana? If you hit http://<yourntopngip>:3000/lua/modules/grafana/ directly you should get {"status":"OK"}. I know that without the trailing slash i get page not found. I've also had similar issues caused by bad proxy config in the frontend web server either on the grafana or ntopng side.

**Comment by rcarvalloh** [comment] 2017-08-17 17:33
Hey, no and they're both in different VPS, if I follow the link directly as in, pasting it in the browser I either get:

Page "/lua/modules/grafana" was not found
Or
Page "/lua/modules/grafana/" was not found

If I try it with Grafana:
HTTP Error
Not Found

The NTOPng server is not running anything else, I didn't build it from source, basically followed the repos found in:

http://packages.ntop.org/

The title of the page says "ntop" so I'm quite sure it's the one stating It doesn't find anything. I can access everything inside the ntopng menu with no issue.

**Comment by simonemainardi** [comment] 2017-08-19 18:28
Grafana is only supported in version 3.1, please move to the dev version to try it

**Comment by simonemainardi** [comment] 2017-08-28 14:12
@shaoranrch thanks for reporting.

Empty throughputs have been fixed -- that was an nProbe issue. A new build will be released overnight CEST, wait until tomorrow and update your nprobe.

Anyway, note that you are calculating throughputs from netflow flows. This will tend to smooth the values values (especially maximums) as nProbe can't do a packet-by-packet processing and has to update throughputs using the information received over netflow.

**Closed as completed by simonemainardi** 2017-08-28 14:12 UTC
