### ISSUE TITLE
Can't create an Host Alias (Custom Name)

### ISSUE THREAD

**Issue by ShagoY** [ntop/ntopng#4194] opened 2020-07-23 16:08 UTC
Hello,

Some hosts don't allow me to create a host alias.
When I fill in the field and validate, the field comes back empty.

Most of them are "unresolved" hosts which is rather unfortunate ^^

What could cause that? I can't find anything in the logs.

Regards.

**Comment by cardigliano** [comment] 2020-07-24 09:15
I am not able to reproduce this, you said it happens on "some" hosts, any additional hint to reproduce this? 
What ntopng version are you running?

**Comment by ShagoY** [comment] 2020-07-24 18:59
ntopng Community Edition v.4.1.200720 
but I had already noticed that on other versions, it's not recent.

Unfortunately, I did not find a "pattern" because I only notice it when I try to create a "Host Alias" on a host that doesn't have one.
The only sure thing is that it happens only on the hosts that have not been resolved by ntopng (By the way, I don't explain it either).

**Comment by simonemainardi** [comment] 2020-07-31 14:54
Currently unable to reproduce. Feel free to reopen when able to reproduce it consistently.

**Comment by ShagoY** [comment] 2020-08-25 13:30
After analysis, I think I have found the behavior that is causing my problem.
First of all, I don't encounter this problem with the stable version (4.0.x) and it only impacts hosts (IPv4/IPv6) under VLAN with the dev version (4.1.x).

So when I modify the Host Alias of a host under VLAN, the UI doesn't seem to have taken into account the modification and always displays "Custom Name".
While analyzing the redis database, I found a new key "ntopng.cache.host_labels.X@VLAN" with the desired string.
So I manually created a key of the type "ntopng.cache.host_labels.X" and added the alias and it worked.
The UI displays the alias correctly but of course any modification only affects the @VLAN key.

So there is a problem with the management of custom aliases under VLAN.

**Comment by cardigliano** [comment] 2020-08-25 16:42
@ShagoY please check the next build, I pushed a fix for this

**Comment by ShagoY** [comment] 2020-08-25 18:19
Np :) What time do you usually do updates?

**Comment by ShagoY** [comment] 2020-08-26 12:33
All good now ! thank you :)

**Closed as completed** 2020-08-26 12:35 UTC
Labels: Low-Priority Bug
