### ISSUE TITLE
Invalid handlerPeerBehaviour

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5128] opened 2021-03-24 10:04 UTC
alerts_api.handlerPeerBehaviour is invalid as it always triggers a single alert (single alert type) for 5 different alerts. This will likely cause unexpected behaviors.

Function is called here:

```
scripts/plugins/alerts/security/unexpected_host_behaviour/modules/active_flows_behaviour.lua:   alerts_api.handlerPeerBehaviour(params, stats["as_client"], stats["tot_num_anomalies"], host_ip, "client" --[[ as client --]], nil, "Active Flows Behaviour as Client")
scripts/plugins/alerts/security/unexpected_host_behaviour/modules/active_flows_behaviour.lua:   alerts_api.handlerPeerBehaviour(params, stats["as_server"], stats["tot_num_anomalies"], host_ip, "server" --[[ as server --]], nil, "Active Flows Behaviour as Server")
scripts/plugins/alerts/security/unexpected_host_behaviour/modules/score_behaviour.lua:   alerts_api.handlerPeerBehaviour(params, stats["as_client"], stats["tot_num_anomalies"], host_ip, "client" --[[ as client --]], 5, "Score Behaviour as Client")
scripts/plugins/alerts/security/unexpected_host_behaviour/modules/score_behaviour.lua:   alerts_api.handlerPeerBehaviour(params, stats["as_server"], stats["tot_num_anomalies"], host_ip, "server" --[[ as server --]], 5, "Score Behaviour as Server")
scripts/plugins/alerts/security/unexpected_host_behaviour/modules/contacted_hosts_behaviour.lua:   alerts_api.handlerPeerBehaviour(params, stats, nil, host_ip, nil --[[ as client --]], nil, "Contacts Behaviour")
```

if you want to use the same type, namely `alert_unexpected_behaviour`,  this is fine, but you need to differentiate using the subtype. e.g., 

subtype = "active_flows_anomaly_as_client"
subtype = "active_flows_anomoaly_as_server"

and so on for all the 5 cases. I suggest you to pass a unique subtype string that will be then always used in `alert_unexpected_behaviour:set_subtype`

Also note that the last parameter above lacks localization. It is requested to add it.

**Comment by simonemainardi** [comment] 2021-03-24 10:13
even better and more generic use the concatenation of script_key and either "as_client" or "as_server" as subtype

**Comment by MatteoBiscosi** [comment] 2021-03-24 14:42
As decided before the unexpected behaviour alert is divided into 5 new alerts. For this reason the subtype is not needed and it's removed from the current implementation.
Regarding the localization everything is fixed now and the "Behaviour Type" used inside the handlerPeerBehaviour function is not needed anymore, because the description is handled by the alert_definition format function

**Closed as completed** 2021-03-25 07:20 UTC
