### ISSUE TITLE
Top Applications: Different values in Last Day View and Traffic Report in the same period

### ISSUE THREAD

**Issue by rmorandell-pgum** [ntop/ntopng#5028] opened 2021-02-08 17:31 UTC
I do not have the same values in the Last Day View in the Traffic Dashboard and in the Traffic Report. The curves and peaks are the same but the values are only about half. Here e.g. filtered only on http.

Traffic Report

![image](https://user-images.githubusercontent.com/46994680/107258071-acd22500-6a3b-11eb-968a-e06d5a088d85.png)

Last Day View 

![image](https://user-images.githubusercontent.com/46994680/107258175-c83d3000-6a3b-11eb-9c94-0518a97acb04.png)

What could be the problem here?

**Comment by simonemainardi** [comment] 2021-02-10 13:31
Fix not enough.

Reproduced. Report charts are scaled when the current datetime is not a multiple of 300s.

**Comment by simonemainardi** [comment] 2021-02-10 14:20
Issue is now fixed in the lastest dev/stable. New builds are in progress.

Data ie correct, i.e., if you take the integral of the timeseries you get the total traffic in both cases. Issue was due to small differences in start/end timestamps which were causing different RRAs to be chosen when accessing underlying RRDs. However, now is fixed and you should get the same rate values in both charts.

**Closed as completed by simonemainardi** 2021-02-10 14:20 UTC
