### ISSUE TITLE
Write a guide to run ntopng on docker

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5511] opened 2021-06-16 15:41 UTC
Running ntopng on docker requires many paths to be mapped
- license
- redis
- influx
- ntopng

It is requested to write a short article/blog post to explain all this in detail

**Comment by cardigliano** [comment] 2022-11-28 15:51
Duplicate of https://github.com/ntop/ntopng/issues/6615

**Closed as completed by cardigliano** 2022-11-28 15:51 UTC
Labels: Feature Request
