### ISSUE TITLE
Interfaces names are repeated and misleading

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3596] opened 2020-03-20 10:00 UTC
![2020-03-20_10-59](https://user-images.githubusercontent.com/5488003/77153348-8147f400-6a91-11ea-9eb8-43997e60d107.png)

In contrast, Wireshark reports them with a unique and meaningful name
![photo_2020-03-20_11-00-09](https://user-images.githubusercontent.com/5488003/77153391-9c1a6880-6a91-11ea-8477-539f6cac81c8.jpg)

**Comment by lucaderi** [comment] 2020-03-21 16:37
Interface names are repeated as you have multiple interfaces as you can see from wireshark.

On my system, I am unable to reproduce the issue with WiFi. Closing it for the time being

**Closed as completed by lucaderi** 2020-03-21 16:37 UTC
Labels: Enhancement
