### ISSUE TITLE
Add number of records in addition to space

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6188] opened 2022-01-11 14:31 UTC
![Screen Shot 2022-01-11 at 15 29 55](https://user-images.githubusercontent.com/4493366/148961753-f73ac054-d821-417a-aa26-d76765d0f5b0.png)

**Comment by MatteoBiscosi** [comment] 2022-01-13 12:02
duplicate of #6199

**Closed as completed by MatteoBiscosi** 2022-01-13 12:02 UTC
Labels: Enhancement
