### ISSUE TITLE
Implement authenticated email delivery for alerts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2037] opened 2018-09-17 14:39 UTC
ntopng can deliver alerts via email. Unfortunately there are many mail services (e.g. gmail) that require SSL and authentication, features not currently support where only unencrypted and unauthenticated emails are be supported.

**Comment by simonemainardi** [comment] 2018-10-08 14:35
duplicate of #2044

**Closed as completed by simonemainardi** 2018-10-08 14:35 UTC
Labels: Duplicate
