### ISSUE TITLE
segmentation fault when reading pcap

### ISSUE THREAD

**Issue by tomarch** [ntop/ntopng#56] opened 2015-06-18 09:40 UTC
I just update my ntopng (bade on git dev repo) and now it segfault (it was working 2 week ago):

my command: 
ntopng --pid /var/tmp/ntopng2.pid -i /tmp/dump_firewall.txt -w 3000 -n 2 -A 2 -F "db" -m "192.168.201.0/24,192.168.202.0/24,192.168.203.0/24,192.168.204.0/24,192.168.205.0/24,192.168.206.0/24"

the log:
18/Jun/2015 11:37:58 [src/Ntop.cpp:785] Setting local networks to 192.168.201.0/24,192.168.202.0/24,192.168.203.0/24,192.168.204.0/24,192.168.205.0/24,192.168.206.0/24
18/Jun/2015 11:37:58 [src/Redis.cpp:93] Successfully connected to redis 127.0.0.1:6379@0
18/Jun/2015 11:37:58 [src/Ntop.cpp:1033] Registered interface view /tmp/dump_firewall.txt [id: 7]
18/Jun/2015 11:37:58 [src/Ntop.cpp:1003] Registered interface /tmp/dump_firewall.txt [id: 0]
18/Jun/2015 11:37:58 [src/Ntop.cpp:1033] Registered interface view Historical [id: 4]
18/Jun/2015 11:37:58 [src/Ntop.cpp:1003] Registered interface Historical [id: 1]
18/Jun/2015 11:37:58 [src/Utils.cpp:292] User changed to nobody
18/Jun/2015 11:37:58 [src/main.cpp:236] PID stored in file /var/tmp/ntopng2.pid
18/Jun/2015 11:37:58 [src/HTTPserver.cpp:449] HTTPS Disabled: missing SSL certificate /usr/local/share/ntopng/httpdocs/ssl/ntopng-cert.pem
18/Jun/2015 11:37:58 [src/HTTPserver.cpp:451] Please read https://svn.ntop.org/svn/ntop/trunk/ntopng/README.SSL if you want to enable SSL.
18/Jun/2015 11:37:58 [src/HTTPserver.cpp:492] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
18/Jun/2015 11:37:58 [src/HTTPserver.cpp:495] HTTP server listening on port 3000
18/Jun/2015 11:37:58 [src/main.cpp:287] Working directory: /var/tmp/ntopng
18/Jun/2015 11:37:58 [src/main.cpp:289] Scripts/HTML pages directory: /usr/local/share/ntopng
18/Jun/2015 11:37:58 [src/Ntop.cpp:271] Welcome to ntopng x86_64 v.2.0.150618 - (C) 1998-15 ntop.org
18/Jun/2015 11:37:58 [src/PeriodicActivities.cpp:53] Started periodic activities loop...
18/Jun/2015 11:37:58 [src/RuntimePrefs.cpp:32] Dumping alerts into syslog
18/Jun/2015 11:37:58 [src/NetworkInterface.cpp:1204] Setting affinity of interface /tmp/dump_firewall.txt to core 7
18/Jun/2015 11:37:58 [src/NetworkInterface.cpp:1208] Started packet polling on interface /tmp/dump_firewall.txt [id: 7]...
18/Jun/2015 11:37:58 [src/NetworkInterface.cpp:1208] Started packet polling on interface Historical [id: 4]...
18/Jun/2015 11:37:59 [src/PcapInterface.cpp:131] Reading packes from pcap file /tcpdump/firewall/dump_2015-06-01_00:17:34.pcap
Segmentation fault

**Comment by ariava** [comment] 2015-06-18 10:47
@tomarch any way to have the pcap you are using?

**Comment by tomarch** [comment] 2015-06-18 12:57
It the same pcap list that i use 2 week ago and which worked fine. I also try with another pcap and it the same issue.

**Comment by tomarch** [comment] 2015-06-19 09:24
here's the last log when enabling verbose :
19/Jun/2015 11:15:42 [src/Flow.cpp:1195] Emitting Flow: { "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }
19/Jun/2015 11:15:42 [src/DB.cpp:137] Dump Flow: { "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }
19/Jun/2015 11:15:42 [src/DB.cpp:159] [DB] INSERT INTO flows VALUES (NULL, 0, '192.168.206.2', 1831, '192.168.201.6', 53, 17, 604, 1433114989, 1433114989, 1, '{ "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }');
19/Jun/2015 11:15:42 [src/Flow.cpp:1195] Emitting Flow: { "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }
19/Jun/2015 11:15:42 [src/DB.cpp:137] Dump Flow: { "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }
19/Jun/2015 11:15:42 [src/DB.cpp:159] [DB] INSERT INTO flows VALUES (NULL, 0, '192.168.206.2', 1831, '192.168.201.6', 53, 17, 604, 1433114989, 1433114989, 1, '{ "8": "192.168.206.2", "7": 1831, "12": "192.168.201.6", "11": 53, "4": 17, "57590": 5, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433114989, "21": 1433114989, "DNS_QUERY": "3-68.e-1.10-1d.18-4b.19-e.5565fef3?a7e947b5181f062df975edbac1bd7d88d424155a4bb2f100004dc1d49a8a7df.g.00.s.sophosxl.net" }');
19/Jun/2015 11:15:42 [src/NetworkInterface.cpp:969] Purged 1/31 idle flows on /tmp/dump_vpn.txt
19/Jun/2015 11:15:42 [src/NetworkInterface.cpp:973] Purged 1/90 idle hosts on /tmp/dump_vpn.txt

with another pcap list:
19/Jun/2015 11:17:00 [src/Flow.cpp:1195] Emitting Flow: { "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 1, "1": 243, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }
19/Jun/2015 11:17:00 [src/DB.cpp:137] Dump Flow: { "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 1, "1": 243, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }
19/Jun/2015 11:17:00 [src/DB.cpp:159] [DB] INSERT INTO flows VALUES (NULL, 0, '192.168.201.132', 138, '192.168.201.255', 138, 17, 243, 1433111200, 1433111200, 1, '{ "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 1, "1": 243, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }');
19/Jun/2015 11:17:00 [src/Flow.cpp:1195] Emitting Flow: { "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }
19/Jun/2015 11:17:00 [src/DB.cpp:137] Dump Flow: { "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }
19/Jun/2015 11:17:00 [src/DB.cpp:159] [DB] INSERT INTO flows VALUES (NULL, 0, '192.168.201.132', 138, '192.168.201.255', 138, 17, 243, 1433111200, 1433111200, 1, '{ "8": "192.168.201.132", "7": 138, "12": "192.168.201.255", "11": 138, "4": 17, "57590": 10, "2": 0, "1": 0, "24": 0, "23": 0, "22": 1433111200, "21": 1433111200 }');
19/Jun/2015 11:17:00 [src/NetworkInterface.cpp:969] Purged 2/29 idle flows on /tmp/dump_firewall.txt
Segmentation fault

**Comment by ariava** [comment] 2015-06-19 13:06
@tomarch unfortunately I am not managing to reproduce the segfault with any of the pcaps I have. Could you please provide a "pcap of death", privately? It will be used only to debug this issue.

**Comment by lucaderi** [comment] 2015-06-28 13:46
Unable to reproduce the issues. Closing it.

**Closed by lucaderi** 2015-06-28 13:46 UTC
Labels: bug
