### ISSUE TITLE
Improve Host Top Talkers Calculation

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6940] opened 2022-10-21 08:02 UTC
![image](https://user-images.githubusercontent.com/4493366/197144948-778931fe-0394-4ef6-8056-ec756572b904.png)

21/Oct/2022 05:43:56 [LuaEngine.cpp:326] [tcp://127.0.0.1:5563] ERROR Cannot complete top talkers generation in 1 minute. Is there a huge number of hosts in the system?

144k local hosts are way too many to be handled in one minute, and this needs to be improved

**Comment by MatteoBiscosi** [comment] 2023-06-13 15:46
Duplicate of #7271

**Closed as completed by MatteoBiscosi** 2023-06-13 15:46 UTC
Labels: Enhancement
