### ISSUE TITLE
dark theme setting per user

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4893] opened 2021-01-07 11:16 UTC
Hello,
Currently the dark theme option is a global setting, i.e. if user A chooses dark them, user B will also have dark theme or vice versa.
Thanks.

**Comment by simonemainardi** [comment] 2021-01-07 11:17
duplicate of https://github.com/ntop/ntopng/issues/4397

**Closed as completed by simonemainardi** 2021-01-07 11:17 UTC
Labels: Duplicate
