### ISSUE TITLE
request bundle MAC adresse into single pc

### ISSUE THREAD

**Issue by tocks53** [ntop/ntopng#506] opened 2016-04-19 14:54 UTC
Actually each MAC is a different PC. i want to bundle them into a single PC.

Because, my pc is in dhcp and the laptop as 2 MAC, wifi and ethernet.

thanks

**Comment by simonemainardi** [comment] 2016-04-19 15:31
this can be the extension of flow profiles to hosts, aka communities.

**Comment by simonemainardi** [comment] 2016-10-27 08:57
duplicate of #289

**Closed as completed by simonemainardi** 2016-10-27 08:57 UTC
Labels: Feature Request
