### ISSUE TITLE
Deep Packet Inspection

### ISSUE THREAD

**Issue by waqar-ali-aziz** [ntop/ntopng#1957] opened 2018-08-28 11:13 UTC
Dear Simone Mainardi,
i am currently working on deep packet inspection in order to analyze internet packets to get packet information.
kindly help me in this regard, if you have some documents then it would be perfect and kindly share with me.
also let me know which tools i have to install for this purpose along with nDPI

best regards

**Comment by simonemainardi** [comment] 2018-08-28 12:19
duplicate of https://github.com/ntop/ntopng/issues/1955

**Closed as completed by simonemainardi** 2018-08-28 12:19 UTC
Labels: Duplicate
