### ISSUE TITLE
Can't display host timeseries since last update...

### ISSUE THREAD

**Issue by uwe-r** [ntop/ntopng#3829] opened 2020-04-23 17:32 UTC
Error is:
```
Script "/usr/share/ntopng/scripts/lua/host_details.lua" returned an error:
.../share/ntopng/pro/scripts/lua/modules/nv_graph_utils.lua:872: attempt to call a nil value (field 'isEnterpriseM')
```

Version is current Enterprise version (but purchased before there were M and L versions).

Any idea would be appreciated. Thanks!

**Comment by uwe-r** [comment] 2020-04-23 17:50
Hm, seems to go deeper than that... can't open Preferences either. Trace log shows dozens of lines with errors pointing out same nil value problem.

**Comment by jacotec** [comment] 2020-04-24 08:00
Seems to be related to my #3832 ... that also gives me this " attempt to call a nil value (field 'isEnterpriseM')" error in interface graphs.

Maybe less frequent updated but better tested ones would be not bad ...

**Comment by emanuele-f** [comment] 2020-04-24 12:01
Duplicate of #3832

**Closed as completed by emanuele-f** 2020-04-24 12:01 UTC
