### ISSUE TITLE
ntopng unexpected Exit since 1-2 days.  ntopng: third_party/src/ndpi_patricia.c:557: ndpi_patricia_search_best2: Assertion `prefix->bitlen <= patricia->maxbits' failed.

### ISSUE THREAD

**Issue by joverdijk** [ntop/ntopng#1949] opened 2018-08-27 12:39 UTC
Hi Ntop Team

Any idea why Ntopng is exiting all the time? It's doing this since 1-2 days tops....

Google'ing did not bring me any usefull info

Looks like problem around here:

Aug 27 14:12:21 ntopng-machine ntopng: [Alert] Started after anomalous termination (<a href="https://www.ntop.org/support/need-help-2/need-help/">bug report</a>) ntopng v.3.7.180827 (Debian GNU/Linux 8.2 (jessie)) [pid: 22396][options: --data-dir "/var/ntopng" --community --user "ntopng" --local-networks "192.168.34.0/24,192.168.134.0/24" --dns-mode "1" --packet-filter "ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100" --http-port "3000" --sticky-hosts "local" --local-networks "192.168.34.0/24,192.168.0.0/24" --dump-flows "[hidden]" --ndpi-protocols "/etc/ntopng/custom.protocols" --interface "eth0" --interface "eth1" --interface "tun0" ]

Aug 27 14:12:22 ntopng-machine ntopng[22396]: ntopng: third_party/src/ndpi_patricia.c:557: ndpi_patricia_search_best2: Assertion `prefix->bitlen <= patricia->maxbits' failed.
Aug 27 14:12:22 ntopng-machine kernel: [ 4637.367770] device tun0 left promiscuous mode
Aug 27 14:12:22 ntopng-machine kernel: [ 4637.432151] device eth1 left promiscuous mode
Aug 27 14:12:23 ntopng-machine kernel: [ 4637.640196] device eth0 left promiscuous mode

Any help would be great

Aug 27 14:12:16 ntopng-machine systemd[1]: Starting ntopng high-speed web-based traffic monitoring and analysis tool...
Aug 27 14:12:17 ntopng-machine systemd[1]: Started ntopng high-speed web-based traffic monitoring and analysis tool.
Aug 27 14:12:17 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:17 [Ntop.cpp:1544] Setting local networks to 192.168.34.0/24,192.168.0.0/24
Aug 27 14:12:17 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:17 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
Aug 27 14:12:17 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:17 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.3.0 interface eth0...
Aug 27 14:12:18 ntopng-machine kernel: [ 4632.496343] device eth0 entered promiscuous mode
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [PF_RINGInterface.cpp:308] Packet capture filter set to "ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100"
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth0...
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface eth0
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [Ntop.cpp:1638] Registered interface eth0 [id: 1]
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.3.0 interface eth1...
Aug 27 14:12:18 ntopng-machine kernel: [ 4633.320315] device eth1 entered promiscuous mode
Aug 27 14:12:18 ntopng-machine kernel: [ 4633.320410] r8152 2-4:1.0 eth1: Promiscuous mode enabled
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [PF_RINGInterface.cpp:308] Packet capture filter set to "ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100"
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth1...
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface eth1
Aug 27 14:12:18 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:18 [Ntop.cpp:1638] Registered interface eth1 [id: 2]
Aug 27 14:12:21 ntopng-machine kernel: [ 4635.623078] device tun0 entered promiscuous mode
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [PcapInterface.cpp:91] Reading packets from interface tun0...
Aug 27 14:12:21 ntopng-machine ntopng: [PcapInterface.cpp:285] ERROR: Unable to set on tun0 filter ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100. Filter ignored.
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [PcapInterface.cpp:285] ERROR: Unable to set on tun0 filter ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100. Filter ignored.
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface tun0...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface tun0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:1638] Registered interface tun0 [id: 3]
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [main.cpp:298] PID stored in file /var/run/ntopng.pid
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Utils.cpp:499] User changed to ntopng
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [HTTPserver.cpp:1114] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [HTTPserver.cpp:1117] HTTP server listening on 3000
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [MySQLDB.cpp:669] Disconnected from MySQL for interface eth0...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth0...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface eth0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [main.cpp:382] Working directory: /var/ntopng
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [main.cpp:384] Scripts/HTML pages directory: /usr/share/ntopng
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:387] Welcome to ntopng x86_64 v.3.7.180827 - (C) 1998-18 ntop.org
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:397] Built on Debian GNU/Linux 8.2 (jessie)
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:695] Adding 192.168.134.2/32 as IPv4 interface address for eth0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:703] Adding 192.168.134.0/24 as IPv4 local network for eth0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:695] Adding 192.168.34.1/32 as IPv4 interface address for eth1
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:703] Adding 192.168.34.0/24 as IPv4 local network for eth1
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:695] Adding 192.168.32.2/32 as IPv4 interface address for tun0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:703] Adding 192.168.32.2/32 as IPv4 local network for tun0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:722] Adding fe80::f64d:30ff:fe6a:ca62/128 as IPv6 interface address for eth0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:731] Adding fe80::f64d:30ff:fe6a:ca62/64 as IPv6 local network for eth0
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:722] Adding fe80::66d1:a3ff:fe4b:d503/128 as IPv6 interface address for eth1
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [Ntop.cpp:731] Adding fe80::66d1:a3ff:fe4b:d503/64 as IPv6 local network for eth1
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [PeriodicActivities.cpp:59] Started periodic activities loop...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [PeriodicActivities.cpp:103] Each periodic activity script will use 3 threads
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [NetworkInterface.cpp:2519] Started packet polling on interface eth0 [id: 1]...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [NetworkInterface.cpp:2519] Started packet polling on interface eth1 [id: 2]...
Aug 27 14:12:21 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:21 [NetworkInterface.cpp:2519] Started packet polling on interface tun0 [id: 3]...
Aug 27 14:12:21 ntopng-machine ntopng: [Alert] Started after anomalous termination (<a href="https://www.ntop.org/support/need-help-2/need-help/">bug report</a>) ntopng v.3.7.180827 (Debian GNU/Linux 8.2 (jessie)) [pid: 22396][options: --data-dir "/var/ntopng" --community --user "ntopng" --local-networks "192.168.34.0/24,192.168.134.0/24" --dns-mode "1" --packet-filter "ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8) and not host 192.168.1.100" --http-port "3000" --sticky-hosts "local" --local-networks "192.168.34.0/24,192.168.0.0/24" --dump-flows "[hidden]" --ndpi-protocols "/etc/ntopng/custom.protocols" --interface "eth0" --interface "eth1" --interface "tun0" ]
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth0...
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth1...
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface tun0...
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface eth0
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface eth1
Aug 27 14:12:22 ntopng-machine ntopng[22396]: 27/Aug/2018 14:12:22 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng@localhost:3306] for interface tun0
Aug 27 14:12:22 ntopng-machine ntopng[22396]: ntopng: third_party/src/ndpi_patricia.c:557: ndpi_patricia_search_best2: Assertion `prefix->bitlen <= patricia->maxbits' failed.
Aug 27 14:12:22 ntopng-machine kernel: [ 4637.367770] device tun0 left promiscuous mode
Aug 27 14:12:22 ntopng-machine kernel: [ 4637.432151] device eth1 left promiscuous mode
Aug 27 14:12:23 ntopng-machine kernel: [ 4637.640196] device eth0 left promiscuous mode
Aug 27 14:12:23 ntopng-machine systemd[1]: ntopng.service: main process exited, code=killed, status=6/ABRT
Aug 27 14:12:23 ntopng-machine systemd[1]: Unit ntopng.service entered failed state.
Aug 27 14:12:26 ntopng-machine systemd[1]: Stopping ntopng high-speed web-based traffic monitoring and analysis tool...

**Comment by simonemainardi** [comment] 2018-08-27 16:00
- are you building from source? are you using an installed package?
- can you try and remove every ntopng option specified, one after the other, to try and understand in this behavior is caused by a single option?
- can you provide the conten t of `/etc/ntopng/custom.protocols`

**Comment by joverdijk** [comment] 2018-08-27 21:40
Hi Simone

I use packages from the ntop repo:

root@ntop-machine:/etc/apt/sources.list.d# cat ntop.list 
deb http://packages.ntop.org/apt/jessie/ x64/
deb http://packages.ntop.org/apt/jessie/ all/
root@ntop-machine:/etc/apt/sources.list.d# 

Problem started after apt update/upgrade, so maybe introduced with kernel
root@ntop-machine:~# uname -a
Linux ntop-machine 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux
root@ntop-machine:~# 

My custom protocol list is not really that interesting:

root@ntop-machine:~# cat /etc/ntopng/custom.protocols
tcp:8200@My-MediaServer 
root@ntop-machine:~# 

Thanks for investigating

Gr,

**Comment by cardigliano** [comment] 2018-08-29 08:16
Hi @joverdijk, since we are not able to reproduce this in our lab with a similar configuration, and it seems that you are able to reproduce it immediately, while we keep testing, can you try removing options one after the other to try to isolate the issue and figure out where to look at? Thank you.

**Comment by simonemainardi** [comment] 2018-08-31 07:46
any feedback here?

**Comment by joverdijk** [comment] 2018-08-31 10:29
I spent a lot of time troubleshooting this but could not figure it out. In the end I did a complete clean remove, dist-upgraded to Debian9 stretch and another clean install from ntopng repositories and now it seems to run stable. Still have NO idea where there 'ndpi_patricia_search_best2' came from.

**Comment by cardigliano** [comment] 2018-08-31 16:37
@joverdijk please reopen this issue if you are able to reproduce it again. Thank you.

**Comment by DevPGSV** [comment] 2018-10-16 16:13
I am also getting the same error:

ntopng: src/../third-party/patricia/patricia.c:753: patricia_node_t* patricia_lookup(patricia_tree_t*, prefix_t*): Assertion `prefix->bitlen <= patricia->maxbits' failed.

I am on Debian stretch. I compiled ntopng with the following steps:
https://www.ntop.org/get-started/download/
```bash
# ntopng --version
v.3.7.181016    [Community build]
GIT rev:        dev:7b269a28daee1f225d7af9547b02299b926bd121:20181016
```
[This](http://mailman.icsi.berkeley.edu/pipermail/bro-dev/2012-November/005406.html) might be the problem.

I have lots of interfaces, most of them Ethernet Bridges like:
```
br-h64seh664: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:e3:0d:53:b4  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And I also have one 6to4 interface configured exactly like this:
https://wiki.debian.org/DebianIPv6#IPv6_6to4_Configuration

When executing ntop it gives the mentiones error, except if I specify the interfaces I want to monitor, as long as I dont choose the 6to4 interface. 

So, from what I could understand, the problem in my setup only is there if I use ntop to monitor the 6to4 intreface, or if I dont specify the interfaces (as this would by default include all interfaces, the 6to4 included).

I don't need to monitor the 6to4, so not a prolem for me. I hope this helps.

EDIT: 
BTW, in that setup everything works allright using the [debian package ntopng (2.4+dfsg1-3)](https://packages.debian.org/stretch/ntopng), including monitoring the 6to4 interface.

**Comment by simonemainardi** [comment] 2018-10-17 07:32
Thank you for this feedback, this is definitely helpful.

Can you please run a packet capture on the 6to4 interface, then start ntopng, wait until it crashes, and finally send the pcap here so we can use it to debug?

```
1. tcpdump -i <6to4 interface name> -s0 -w 6to4.pcap
2. ntopng -i <6to4 interface name>
3. wait until ntopng crashes
4. stop tcpdump at 1. and send file 6to4.pcap
```

thank you

**Comment by emanuele-f** [comment] 2019-12-23 14:17
Can be easily reproduced by repeatedly calling `ndpi_fill_ip_protocol_category` with 0 as both the saddr and daddr

**Comment by emanuele-f** [comment] 2019-12-23 14:24
Fixed in https://github.com/ntop/nDPI/commit/73c7ccdb65a1e13e3fb1726af7882dd34534906f

**Closed as completed by emanuele-f** 2019-12-23 14:24 UTC
