### ISSUE TITLE
Duplicate of #6785 - NTOP does not recognise or send alerts

### ISSUE THREAD

**Issue by darrenp2022a** [ntop/ntopng#6894] opened 2022-09-22 22:59 UTC
Environment:

OS name: Centos
OS version: Stream 8
Architecture: Intel
ntopng version/revision: 5.5.220713 and current 5.4.220711
What happened:
NTOP does not send alerts, this has been the case since before August 2021. This was reported to:

Luca, who created ticket 6405
Alfredo
Matteo

What did you expect to happen?
For it to send alerts

How did you reproduce it?
Turn the product on,
Configure it to active monitoring Continuous ICMP
Configure the product to send an email or teams webhook alert

Product functions when using IP addresses, or DNS entries.

Debug Information:

See previous emails as I've sent this multiple times.

**Comment by cardigliano** [comment] 2022-09-23 07:44
Duplicate of #6785

**Closed as completed by cardigliano** 2022-09-23 07:44 UTC
