### ISSUE TITLE
Multiple interface selections in user preferences

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4873] opened 2020-12-28 16:10 UTC
![image](https://user-images.githubusercontent.com/61453908/103227726-b2febd00-4937-11eb-96dd-e6182ec79712.png)

Is it possible to select two or more interfaces for a user's preferences.  I don't want to create two user accounts?
Some of the other preferences elsewhere allow those types of choices.

**Comment by simonemainardi** [comment] 2020-12-29 09:26
Currently, this is not supported. I can mark it as a feature request.

**Comment by simonemainardi** [comment] 2020-12-29 09:33
by the way, this is a duplicate of https://github.com/ntop/ntopng/issues/2525

**Comment by amastelek** [comment] 2020-12-29 14:54
> 
> 
> Currently, this is not supported. I can mark it as a feature request.

Thanks.  Please make a feature request.
I have 4 sites in Cape Town and 4 sites in Joburg sending IPFIX to a nprobe in Joburg which then connects to a NTOPNG in the IBM Cloud.  There are separate users in Cape Town and Joburg.
Some of the sites have an overlapping private IP, so a filter will not work.  I disaggregate based on IP probed which works.
Is there any other way to do it???  The current nprobe is working fine with resources to spare so I don't want to install another one.

**Comment by simonemainardi** [comment] 2020-12-30 13:43
Is it ok for you to have:

- A first set of users, say U1, U2, U3, accessing any of the 4 sites in Cape Town
- Another set of users, say U4, U5, U6, accessing any of the 4 sites in Joburg

Would this solve your use case?

**Comment by amastelek** [comment] 2021-01-04 09:41
Yes,

That will work.



*From:* Simone Mainardi <notifications@github.com>
*Sent:* Wednesday, 30 December 2020 15:44
*To:* ntop/ntopng <ntopng@noreply.github.com>
*Cc:* amastelek <ronald@amastelek.com>; Author <author@noreply.github.com>
*Subject:* Re: [ntop/ntopng] Multiple interface selections in user
preferences (#4873)



Is it ok for you to have:

   - A first set of users, say U1, U2, U3, accessing any of the 4 sites in
   Cape Town
   - Another set of users, say U4, U5, U6, accessing any of the 4 sites in
   Joburg

Would this solve your use case?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ntop/ntopng/issues/4873#issuecomment-752619916>, or
unsubscribe

**Comment by simonemainardi** [comment] 2021-01-04 13:46
So you don't need to have multiple interfaces per user.

Do as follow:

1. Spawn two nprobe instances, say one collecting flows on port 2055 and another one collecting flows on port 2056. You don't need two licenses. See https://www.ntop.org/guides/nprobe/how_to_start.html#init-based-systems to start multiple instances. Eg.

```
nprobe -i none -n none --collector-port 2055 --zmq tcp://127.0.0.1:5556
nprobe -i none -n none --collector-port 2056 --zmq tcp://127.0.0.1:5557
```

2. Configure Cape Town devices to export to 2055 and Jozi to export to 2056
3. Start ntopng with two interfaces `-i tcp://127.0.0.1:5556 -i tcp://127.0.0.1:5557` and with NO disaggregation
4. Specify `tcp://127.0.0.1:5556` as allowed interface for users U1, U2, U3, and specify `tcp://127.0.0.1:5557` as allowed interface for users U4, U5, U6.

**Closed as completed by simonemainardi** 2021-01-04 13:46 UTC
Labels: Duplicate, Feature Request

**Comment by amastelek** [comment] 2021-01-14 10:34
Please update as a feature request again.

I added another user with a couple of new sites which means that with each user and sites I need to add more ports and instances which is clumsy and difficult to maintain.
