### ISSUE TITLE
Unable to save multiple traffic profiles

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3696] opened 2020-04-02 17:49 UTC
When adding multiple traffic profiles it is impossible to save. Clicking on save is ineffective, nothing happens

advanced_features_traffic_profiles_edit
![image](https://user-images.githubusercontent.com/3397663/78281492-0b28a000-751b-11ea-9cae-3fd8f9b61972.png)

**Comment by lucaderi** [comment] 2020-04-02 18:43
I suggest not to fix this bug, but to redo the table using the DataTable

**Comment by emanuele-f** [comment] 2020-04-03 08:55
The bug was caused by a missing `disabled` class on the button, now fixed

**Closed as completed by emanuele-f** 2020-04-03 08:55 UTC
Labels: In Progress
