### ISSUE TITLE
ntopng consumes memory and then becomes unresponsive

### ISSUE THREAD

**Issue by mjgehrmann** [ntop/ntopng#157] opened 2015-09-10 01:45 UTC
Platform: Ubuntu 12.04LTS x64
Version: v2.0.150908

The memory issue seems to have started from libnetfilter-queue1 was required. Not sure what version required it but since then we have run out of ram for flow rates of 5000 flows and ~2000 hosts.

Limiting flows and hosts and changing sticky-hosts made no difference. Survival time was around 3-4 hours until all memory consumed and host required reboot.

pidstat output:
09:40:09 AM     32244    713.20     87.95 4119068 3000268  79.24  ntopng
09:50:09 AM     32244    746.70     86.73 4124956 3043680  80.38  ntopng
10:00:09 AM     32244    633.08     91.43 4188188 3081044  81.37  ntopng
10:10:09 AM     32244    724.90     78.90 4255132 3122048  82.45  ntopng
10:20:09 AM     32244    578.03     67.78 4254364 3160532  83.47  ntopng
10:30:09 AM     32244    723.12     72.02 4321800 3199860  84.51  ntopng

**Comment by lucaderi** [comment] 2015-09-10 09:01
Please report how you have started (CLI) ntopng

**Comment by kargh** [comment] 2015-09-16 11:20
I will second the insane memory usage. I'm hitting 30GB within 24 hours.

Here is my ntopng.conf
-n=1
-W=0
-g=-1
-m="10.0.1.0/24, 10.0.11.0/24"
-d=/storage/ntopng/
-C
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556

**Comment by lucaderi** [comment] 2015-09-16 22:27
I believe the problem is fixed by now. Please resync your code (a new binary package will be built overnight) and give it a try. Thanks for reporting the problem.

**Closed by lucaderi** 2015-09-16 22:27 UTC
Labels: bug
