### ISSUE TITLE
LDAP Auth: User are only "unprivileged user" if they are in both the User and the admin group

### ISSUE THREAD

**Issue by philimnorden** [ntop/ntopng#1323] opened 2017-06-21 09:48 UTC
When users are in the normal user group and in the admin group the user only get unprivileged  access. Wouldn't it be smarter if user would get admin rights?

We are using our usual "IT-Staff"-Group as LDAP User Group and a special "IT-Admin"-Group as LDAP Admin Group. But all our Admins are in the "IT-Staff"-Group too and they dont have the correct admin rights in ntopng.

**Comment by ValentinaViscarelli** [comment] 2017-06-21 21:07
@philimnorden 
I cannot reproduce this behaviour. If I create an account and assign it to user_group and also admin_group, the user will log in as admin.
Are you sure you have assign the user to admin group properly? If you remove the user just from user_group, are you able to log in as admin?

**Comment by philimnorden** [comment] 2017-06-22 13:57
Yes, the admin group is properly assigned and if i remove the user from the user_group  im am able to log in as admin again.

**Comment by ValentinaViscarelli** [comment] 2017-06-22 14:25
@philimnorden 
I checked the code and It's strange in fact it works for me..... what ntopng version are you using?

ntopng --version

**Comment by philimnorden** [comment] 2017-06-27 07:24
```
root@XXXXXXXX:~# ntopng --version
v.3.1.170606 [Community Edition]
GIT rev:   dev:3603f3b6c85b9fa884101ba6e4a1b351787b12f9:20170606
```

**Comment by ValentinaViscarelli** [comment] 2017-06-29 12:37
@philimnorden 
Ldap authentication is a functionality just for ntopng pro. It should not have worked for community edition.
I have made a change in order to change this behavior. Please try to authenticate with ntopng professional edition. 
If you have still the problem I need to access to your machine in order to debug the problem because I'm not able to reproduce it.

**Closed as completed by ValentinaViscarelli** 2017-06-29 12:37 UTC

**Comment by philimnorden** [comment] 2017-07-03 11:12
The real question is: Why does it say "Community Edition" while i use a valid enterprise licence.

**Comment by ValentinaViscarelli** [comment] 2017-07-03 11:17
From your output I see:

root@XXXXXXXX:~# ntopng --version
v.3.1.170606 [**Community Edition**]
GIT rev:   dev:3603f3b6c85b9fa884101ba6e4a1b351787b12f9:20170606

**Comment by simonemainardi** [comment] 2017-07-03 11:19
@philimnorden does it show community edition also inside the web UI? Please, follow up privately with us, send an email with the order id so we can check.
