### ISSUE TITLE
Error when trying to display flows

### ISSUE THREAD

**Issue by jasonamorrow** [ntop/ntopng#3669] opened 2020-03-30 11:56 UTC
I'm receiving the error "SyntaxError: Unexpected token H in JSON at position 0" when I try to view flows via /lua/flows_stats.lua on ntopng Community Edition v.4.1.200327. This is running on Raspbian Buster.

Errors in the system trace log:
30/Mar/2020 07:48:43 [system_stats.lua:104] [ts_utils_core.lua:596] ERROR: Schema not found: process:resident_memory
30/Mar/2020 07:47:15 [LuaEngine.cpp:12687] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:247: attempt to index a nil value (field 'status_normal')]
30/Mar/2020 07:46:54 [system_stats.lua:104] [ts_utils_core.lua:596] ERROR: Schema not found: process:resident_memory
30/Mar/2020 07:36:25 [NetworkInterface.cpp:2343] Started packet polling on interface eth0 [id: 3]...

**Comment by emanuele-f** [comment] 2020-03-30 12:14
This should be a duplicate of #3663 , the new raspbian package will be available in one hour.

**Closed as completed by emanuele-f** 2020-03-30 12:14 UTC
