### ISSUE TITLE
Traffic History for host doesn't show traffic, when there is, and has been.

### ISSUE THREAD

**Issue by nate-byrnes** [ntop/ntopng#678] opened 2016-08-06 14:27 UTC
ON the dashboard I see traffic (this is my top host)
![dashboard](https://cloud.githubusercontent.com/assets/19349744/17457234/ec8a4e90-5bc0-11e6-81d3-e9ac231fd1dc.png)

On the host specific page, I see there has been traffic for quite a while
![host_top](https://cloud.githubusercontent.com/assets/19349744/17457220/25ada83a-5bc0-11e6-8289-b118e6a1a45d.png)

But, in the traffic history graph, I only see one spike of 26bps, when I have watched this host's traffic on the dashboard staying above 20Mbps for 30 minutes....
![host_traff](https://cloud.githubusercontent.com/assets/19349744/17457235/f1f74c16-5bc0-11e6-9d60-b3977395687f.png)

**Comment by simonemainardi** [comment] 2016-08-08 08:32
Hi, I noticed you've already had a similar issue (perhaps the same?) https://github.com/ntop/ntopng/issues/582

we crafted a fix but didn't receive any feedback from you. Are you sure you are using the latest dev version?

**Comment by nate-byrnes** [comment] 2016-08-08 13:23
Hi Simone,

I thought we agreed to close 582, my apologies if that was not the case. 
The last fix was to correct entirely missing traffic history. This issue 
seems to be incorrect traffic history.

I updated to: v.2.5.160718 about 3 weeks ago. (I typically try not to 
upgrade too frequently... should I avoid that notion with regards to 
ntop-ng?)

```
 Thanks and Regards,

 Nate
```

_Nathanial A. Byrnes_

_Elm Datacenter_ http://www.elmdc.com - CTO

_Mobile:_(716) 949.7656

_eMail:_nate@elmdc.com mailto:nate@elmdc.com

**Comment by simonemainardi** [comment] 2016-08-08 13:41
check if the proper interface is correctly selected (dropdown menu 'Interface'). If that is the case, please, provide us remote login details and we'll give it a look

**Comment by nate-byrnes** [comment] 2016-08-09 14:03
I'm not sure if you've seen it, but I sent web UI credentials to your 
ntopng account. Do you need SSH access as well?

_Nathanial A. Byrnes_

_Elm Datacenter_ http://www.elmdc.com - CTO

_Mobile:_(716) 949.7656

_eMail:_nate@elmdc.com mailto:nate@elmdc.com

**Comment by simonemainardi** [comment] 2016-08-11 09:47
@nate-byrnes  please re-send the credential as I can't find them in my email. Also yes SSH access would be nice as well.

**Comment by nate-byrnes** [comment] 2016-08-11 17:57
Just sent to your mainardi@ntop.org email.

**Comment by simonemainardi** [comment] 2016-08-12 14:09
thank you, I'm trying to connect

**Comment by simonemainardi** [comment] 2016-08-12 18:50
hi, I spent a lot of time on your machine trying to understand what's going on. This is a brief summary:
1. after a first restart of ntopng everything works smoothly and host statistics are properly saved
2. I tried by removing several options from the configuration (one after the other) but statistics are always properly stored
3. You told that you are experiencing performance drops. I argue the reason is that you have an elasticsearch that is not able to ingest data at the right speed. This is confirmed by the following

```
12/Aug/2016 14:29:42 [ElasticSearch.cpp:57] WARNING: [ES] Export queue too long [32768]: expect drops
```

so please go back in the past issues and on the mailing lists and look for previous discussions as you should tune your ES.

Again, you may be experiencing a gradual performance dropdown as you ES becomes slower and slower with larger indices.

Flow drops and a slow ES may also be the cause of the missing statistics as, I argue, ntopng was stuck in trying to send data to the ES and wasn't able to timely compute the other statistics. Also the ntopng web interface becomes much much faster without ES export.

Please, let me know what do you think. It should be safe to close this issue.

**Comment by nate-byrnes** [comment] 2016-08-12 19:00
Hi Simone,

```
 Thanks for looking into this. What, if anything, is the web 
```

interface using ES for? (or to put it another way, what do I miss out on 
if I turn off ES?)

```
 Thanks,

 Nate
```

**Comment by simonemainardi** [comment] 2016-08-12 19:32
The web interface doesn't use ES. That is, ntopng sends flows to ES but doesn't read them back. So I assume you have your own software that queries ES for further flow processing.

Note that, even if the web interface doesn't use it, it may suffer a slow down when the whole system is overloaded. In your case, the load average was between 3 and 5 that is too much.

**Comment by nate-byrnes** [comment] 2016-08-12 20:33
Got it. Thanks again. In that case, It looks like this issue is 
resolved. Good to know about the ES causing a backlog. For now, I'll do 
without it.

**Closed as completed** 2016-08-13 09:24 UTC

**Comment by nate-byrnes** [comment] 2016-08-17 15:07
It seems that disabling the data writes to elastic search did not solve the problem. The traffic history worked for a few hours at most, then stopped working. I've since updated to build 160817, (and restarted the daemon). I'll check again in a couple hours, but at present, on the few top hosts I've checked, there is not yet any historical data...

**Comment by nate-byrnes** [comment] 2016-08-17 16:15
Yep, still missing historical data....
