### ISSUE TITLE
Wrong OS fingerprint for Android TV

### ISSUE THREAD

**Issue by fsamareanu** [ntop/ntopng#1755] opened 2018-04-23 05:36 UTC
An Android TV box is identified as "iPhone". Latest dev release on Ubuntu. PCAP provided as part of #1731 .
![image](https://user-images.githubusercontent.com/38040820/39108538-c56e5d28-46d9-11e8-822a-11624cbee467.png)

**Comment by emanuele-f** [comment] 2018-04-23 07:58
The pcap file does not contain the information ntopng uses to determine the OS. One of such information is the DHCP fingerprint. If you click on the mac address in that page, into the device page can you see the `DHCP Fingerprint` field? Can you post it?

**Comment by fsamareanu** [comment] 2018-04-23 08:45
![image](https://user-images.githubusercontent.com/38040820/39115966-3a727eaa-46f4-11e8-8578-32a31528f0ce.png)

**Comment by emanuele-f** [comment] 2018-04-30 08:16
That firgerprint does not match any of the ntopng os fingerprints. The operating system has probably been extracted from the user agent inside an HTTP request. Since the user agent based OS detection is saved on the L3 Host rather then Mac device, I think that the address 192.168.1.10 was previously assigned to an iPhone device due to DHCP al later to the android tv device. You could verify this by assigning the tv device to a possibly never used IP address and waiting some time to see the it's never shown as an iphone

**Comment by fsamareanu** [comment] 2018-04-30 08:21
Hello,

Since before I deployed ntopng the device had a static DHCP mapping.

**Comment by emanuele-f** [comment] 2018-04-30 08:32
Can you provide a pcap with a capture of HTTP traffic of the 192.168.1.10 device? You can add the following filter to the tcpdump command: `host 192.168.1.10 and tcp port 80`

**Comment by emanuele-f** [comment] 2018-05-07 15:27
@fsamareanu any news?

**Comment by fsamareanu** [comment] 2018-05-08 06:04
Hello,

I captured the pcap and will upload it once i'm home.

**Comment by emanuele-f** [comment] 2018-05-08 08:40
Thank you.

**Comment by emanuele-f** [comment] 2018-05-11 09:49
I've reviewed the pcap, the device reports multiple user agents while accessing particular pages, (including iPhone and Linux x86/64), let's see if we can exclude them to improve the detection, thank you!

**Comment by lucaderi** [comment] 2018-06-14 17:22
@fsamareanu The pcap you sent us is unable to reproduce the issue. However I have made some code changes that IMHO should improve the situation and fix the misclassification. Please give it a try. I will now close this ticket and in case it is still not working, please resubmit me a different pcap we can use to troubleshoot. Many thanks for your support.

**Closed as completed by lucaderi** 2018-06-14 17:22 UTC
