### ISSUE TITLE
Trigger alerts for Expired TLS Certificates

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2834] opened 2019-09-10 06:47 UTC
Recently nDPI has been enhanced with TLS certificate validity (notAfter/notBefore). It is requested to use this information to generate a new flow alert when TLS certificates have invalida dates.

**Comment by simonemainardi** [comment] 2019-09-18 12:59
duplicate of #2513

**Closed as completed by simonemainardi** 2019-09-18 12:59 UTC
Labels: Duplicate
