### ISSUE TITLE
Fails to start after autoupdate to  6.1.240121

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#8182] opened 2024-01-21 18:30 UTC
**Environment**:
* OS name: Rasbian
* OS version: 12 (Bookworm)
* Architecture: aarch64
* ntopng version/revision: 6.1.240121

**What happened**:
System was working and stable.  Autoupdate to 6.1.240121 happened overnight. ntopng will no long longer start.  Fails with exit code 255 and the message `21/Jan/2024 13:20:20 [NetworkInterface.cpp:423] ERROR: Error ndpi_set_config: -2`

**How did you reproduce it?**
Try to start ntopng, either from systemd or manually with `/usr/bin/ntopng /etc/ntopng/ntopng/conf`

**Debug Information**:
```
    Process: 5888 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
    Process: 5909 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 5911 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 5913 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SUCCESS)
    Process: 5915 ExecStart=/usr/bin/ntopng /run/ntopng.conf (code=exited, status=255/EXCEPTION)
    Process: 5930 ExecStopPost=/bin/rm -rf /run/ntopng.conf /run/ntopng.conf.raw /run/ntopng.pid (code=exited, status=0/SUCCESS)
   Main PID: 5915 (code=exited, status=255/EXCEPTION)
        CPU: 283ms
```

and when starting manually:
```
$ sudo /usr/bin/ntopng /etc/ntopng/ntopng.conf
21/Jan/2024 13:29:49 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Jan/2024 13:29:49 [Redis.cpp:164] Successfully connected to redis 127.0.0.1:6379@0
21/Jan/2024 13:29:49 [NtopPro.cpp:343] [LICENSE] No license file found /etc/ntopng.license: reading license from redis
21/Jan/2024 13:29:49 [NtopPro.cpp:523] [LICENSE] Unable to validate license [Empty license file]
21/Jan/2024 13:29:49 [NtopPro.cpp:592] WARNING: [LICENSE] Invalid license [Empty license file]
21/Jan/2024 13:29:49 [NtopPro.cpp:613] WARNING: [LICENSE] ntopng will now run in Enterprise XL edition for 10 minutes
21/Jan/2024 13:29:49 [NtopPro.cpp:619] WARNING: [LICENSE] before returning to community mode
21/Jan/2024 13:29:49 [NtopPro.cpp:621] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
21/Jan/2024 13:29:49 [NtopPro.cpp:625] WARNING: [LICENSE] or run ntopng in community mode starting
21/Jan/2024 13:29:49 [NtopPro.cpp:627] WARNING: [LICENSE] ntopng --community
21/Jan/2024 13:29:49 [NtopCloud.cpp:43] ERROR: Unable to connect to the ntop cloud
21/Jan/2024 13:29:49 [NtopPro.cpp:674] Succefully connected to the ntop cloud
21/Jan/2024 13:29:49 [NetworkInterface.cpp:423] ERROR: Error ndpi_set_config: -2
```

**Comment by dpkano** [comment] 2024-01-21 18:40
Same thing happened to me (same config)

**Comment by MatteoBiscosi** [comment] 2024-01-22 10:52
Hi, the issue should be fixed in the latest version, please update and in case the issue is still there reopen the ticket

**Closed as completed by MatteoBiscosi** 2024-01-22 10:52 UTC
