### ISSUE TITLE
Invalid Layout 

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7772] opened 2023-08-18 17:37 UTC
<img width="1529" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/c1e1bfe6-1d0b-454e-8707-3425e426c753">

Try can reproduce it as

http://<HSOL>:3000/lua/pro/enterprise/network_maps.lua?map=service_map&ifid=2&host=89.31.72.65

**Comment by MatteoBiscosi** [comment] 2023-09-20 14:21
The issue is now fixed

**Closed as completed by MatteoBiscosi** 2023-09-20 14:21 UTC
Labels: In Progress
