### ISSUE TITLE
flows not loading

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3530] opened 2020-03-10 09:24 UTC
hello,
my ntop reaches a point and I cant get flow. I get "SyntaxError: Unexpected token H in JSON at position 0" and I have to restart. but I it happened so frequently.

**Comment by emanuele-f** [comment] 2020-03-10 09:44
Please report the output of `ntopng --version` and the contents of `/etc/ntopng/ntopng.conf`

**Comment by Claireshan** [comment] 2020-03-10 11:58
Sent from Mail for Windows 10

**Comment by Claireshan** [comment] 2020-03-10 12:17
![ntop2](https://user-images.githubusercontent.com/22081659/76311512-2d474d80-62e2-11ea-95be-8baaec9b0c60.PNG)

**Comment by emanuele-f** [comment] 2020-03-10 16:24
This may be a problem with the zmq flows reported by nprobe. Please upgrade to the development version of the software as we are in the process of releasing the new stable version. Please check out http://packages.ntop.org/apt .

**Comment by simonemainardi** [comment] 2020-03-18 14:59
duplicate of #3549

**Closed as completed by simonemainardi** 2020-03-18 14:59 UTC
Labels: Duplicate
