### ISSUE TITLE
Unknown traffic missing from host timeseries (InfluxDB)

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#2310] opened 2019-01-13 13:43 UTC
host has sent traffic at 1Gbps approx.

![image](https://user-images.githubusercontent.com/3397663/51085976-ddeaa900-1740-11e9-87ad-7e223afb5b70.png)

showing the top protocols chart yields a traffic that is 1/50 of the original traffic

![image](https://user-images.githubusercontent.com/3397663/51085986-01155880-1741-11e9-9441-13920e75ff49.png)

so it seems that the vast majority of traffic is missing.

From the interface page, it can be verified that protocol 'Unknown' is responsible for the missing traffic

![image](https://user-images.githubusercontent.com/3397663/51085998-3a4dc880-1741-11e9-9e08-d24606b5396c.png)

However, selecting the 'Unknown' protocol from the host yields no results

![image](https://user-images.githubusercontent.com/3397663/51086004-57829700-1741-11e9-9370-0e52464c3d29.png)

I would expect to see 'Unknown' also in the stacked view of host protocols.

Data obtained with influxdb, didn't check if this behavior also occurs with RRDs.

![image](https://user-images.githubusercontent.com/3397663/51086029-99abd880-1741-11e9-9942-867eb3b2b227.png)

**Comment by emanuele-f** [comment] 2019-01-15 10:21
Could not reproduce this in the same testing environment, closing for now

**Closed as completed by emanuele-f** 2019-01-15 10:21 UTC
Labels: Priority Ticket
