### ISSUE TITLE
Restore inactive hosts via search

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#3209] opened 2020-01-09 19:53 UTC
In /lua/host_details.lua?host=X.X.X.X if host X.X.X.X is not active but it used to be active, ntopng will restore it to memory and show a limited representation of the host, including historical data. it is requested that putting X.X.X.X in the search field, the host X.X.X.X is also restored in memory (if previously serialised)

**Comment by simonemainardi** [comment] 2020-01-24 13:27
duplicate of #2898

**Closed as completed by simonemainardi** 2020-01-24 13:27 UTC
Labels: Duplicate
