### ISSUE TITLE
Logstash errors when parsing data from ntopng

### ISSUE THREAD

**Issue by jevonearth** [ntop/ntopng#1144] opened 2017-04-08 18:53 UTC
Hi,

I have been testing the ntopng to logstash feature, and I'm getting some good data passed from: mikrotik -> nprobe -> ntopng -> logstash -> elasticsearch

But I get regular json parse errors where there are spurious characters (such as `\u00004` and `\u0000` ) in the json. See two log samples below, along with version information and copies of my configs. 

Please let me know if I can test anything specific in order to help you further. 

Thanks,
-Jev

## Logstash errors on stdout:
```[2017-04-08T18:41:10,831][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: 4, "FIRST_SWITCHED": 1491676739, "LAST_SWITCHED": 1491676739, "json": { "15": "184.70.24.213", "10": "2", "14": "12", "5": "0", "16": "15169", "17": "0" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -122.057404, 37.419201 ], "NTOPNG_INSTANCE_NAME": "ntop-redder-dev", "INTERFACE": "tcp:\/\/127.0.0.1:5559c [probeIP: 10.60.58.1]" }; line: 1, column: 2]>, :data=>"\u00004, \"FIRST_SWITCHED\": 1491676739, \"LAST_SWITCHED\": 1491676739, \"json\": { \"15\": \"184.70.24.213\", \"10\": \"2\", \"14\": \"12\", \"5\": \"0\", \"16\": \"15169\", \"17\": \"0\" }, \"CLIENT_NW_LATENCY_MS\": 0.000000, \"SERVER_NW_LATENCY_MS\": 0.000000, \"DST_IP_COUNTRY\": \"US\", \"DST_IP_LOCATION\": [ -122.057404, 37.419201 ], \"NTOPNG_INSTANCE_NAME\": \"ntop-redder-dev\", \"INTERFACE\": \"tcp:\\/\\/127.0.0.1:5559c [probeIP: 10.60.58.1]\" }"}
```
```
[2017-04-08T18:41:10,836][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: _LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -122.057404, 37.419201 ], "NTOPNG_INSTANCE_NAME": "ntop-redder-dev", "INTERFACE": "tcp:\/\/127.0.0.1:5559c [probeIP: 10.60.58.1]" }; line: 1, column: 2]>, :data=>"\u0000_LATENCY_MS\": 0.000000, \"SERVER_NW_LATENCY_MS\": 0.000000, \"DST_IP_COUNTRY\": \"US\", \"DST_IP_LOCATION\": [ -122.057404, 37.419201 ], \"NTOPNG_INSTANCE_NAME\": \"ntop-redder-dev\", \"INTERFACE\": \"tcp:\\/\\/127.0.0.1:5559c [probeIP: 10.60.58.1]\" }"}
```
```
[2017-04-08T18:58:21,387][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: 58.1]" }; line: 1, column: 2]>, :data=>"\u000058.1]\" }"}
```
```
[2017-04-08T18:58:21,389][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: 58.1]" }; line: 1, column: 2]>, :data=>"\u0000\u000058.1]\" }"}
```
```
[2017-04-08T18:58:21,389][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: }; line: 1, column: 2]>, :data=>"\u0000}"}
```
```
[2017-04-08T18:58:21,389][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: 58.1]" }; line: 1, column: 2]>, :data=>"\u000058.1]\" }"}
```

## % ntopng --version
```
v.2.5.170408 [Enterprise/Professional Edition]
GIT rev:   dev:d5e73f423c1d1421feaf2d76c128f55452a27bdb:20170408
Pro rev:   r1036
System Id: 39B3CB5200600F2D
Built on:  CentOS Linux release 7.3.1611 (Core)
```

## % nprobe --version
```
Welcome to nProbe v.7.5.170408 (r5717) for x86_64-unknown-linux-gnu
[snip]
Build OS:      CentOS Linux release 7.3.1611 (Core)
SystemID:      39B3CB5200600F2D
GIT rev:       dev:7f2b1b02fc599a445d0c5e62f732664ca9a64913:20170408
```

## ntopng config
```
-G=/var/run/ntopng.pid
--community
-i=tcp://127.0.0.1:5559c
-F "logstash;10.60.58.6;tcp;5000"
```

## logstash config
```
input { 
    tcp {
        port => 5000
        type => "ntopng-ls"
        codec => json
    }
}
filter {
   if [type] == "ntopng-ls" {
     if "" not in [IPV4_SRC_ADDR] and "" not in [IPV6_SRC_ADDR] {
        drop {}
     }
   }
}
output {
   if [type] == "ntopng-ls" {
    elasticsearch { hosts => ["elasticsearch-master:9200"]  }
    stdout { codec => rubydebug}
   }
}
```

**Comment by simonemainardi** [comment] 2017-04-10 09:49
+@bperian

**Comment by bperian** [comment] 2017-04-10 11:35
Issue should be fixed in https://github.com/ntop/ntopng/pull/1143 

EDIT: I also encountered the described warnings regarding encoding on the previous version of the code.

**Comment by jevonearth** [comment] 2017-04-10 21:11
Thanks, I will test and let you know the results!

**Comment by bperian** [comment] 2017-04-11 08:01
@jevonearth , also did some more extensive testing. Part of the issue is still present. 
I'll work on a fix today and post here an update afterwards.  

Update: Might be related to this issue: https://github.com/json-c/json-c/issues/108

**Comment by bperian** [comment] 2017-04-11 12:00
I tested the feature using the changes done in https://github.com/ntop/ntopng/pull/1147, could not reproduce the issue anymore.

**Comment by bperian** [comment] 2017-04-12 06:23
@simonemainardi thank you 
@jevonearth Please test the feature with the latest dev branch when you get the chance.

**Comment by jevonearth** [comment] 2017-04-13 00:53
Hi there,

I have tested:
```
v.2.5.170413 [Enterprise/Professional Edition]
GIT rev:   dev:e32e7aa0a925a15f45c18d050149e8da39e924ba:20170413
Pro rev:   r1038
System Id: 39B3CB5200600F2D
Built on:  CentOS Linux release 7.3.1611 (Core)
```

And I am no longer seeing json errors. Thanks for the prompt fix!
-Jev

**Comment by simonemainardi** [comment] 2017-04-13 12:36
credits go to @bperian ,  thank you!

**Closed as completed by simonemainardi** 2017-04-13 12:36 UTC
Labels: To Be Confirmed

**Comment by jevonearth** [comment] 2017-04-13 19:43
I hit one more json parse error. See log below. 

If you search the block of text for `SERVER_NW_LATEN` I think you will narrow down the source. It looks like one block of text is getting overwritten with another.

```
[2017-04-13T19:37:26,665][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Unexpected character ('n' (code 110)): was expecting a colon to separate field name and value
 at [Source: { "ntop_timestamp": "2017-04-13T18:20:03.0Z", "IN_SRC_MAC": "00:00:00:00:00:00", "OUT_DST_MAC": "00:00:00:00:00:00", "IPV4_SRC_ADDR": "151.101.0.133", "IPV4_DST_ADDR": "184.70.24.214", "L4_SRC_PORT": 443, "L4_DST_PORT": 35364, "PROTOCOL": 6, "L7_PROTO": 91, "L7_PROTO_NAME": "SSL", "TCP_FLAGS": 18,"IN_PKTS": 22, "IN_BYTES": 9449, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 1492107328, "LAST_SWITCHED": 1492107603, "json": { "15": "10.60.58.44", "10": "2", "14": "12", "5": "0", "16": "54113", "17": "6327" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATEN{ "ntop_timestamp": "2017-04-13T18:20:06.0Z", "IN_SRC_MAC": "00:00:00:00:00:00", "OUT_DST_MAC": "00:00:00:00:00:00", "IPV4_SRC_ADDR": "10.60.58.5", "IPV4_DST_ADDR": "104.244.46.167", "L4_SRC_PORT": 59408, "L4_DST_PORT": 443, "PROTOCOL": 6, "L7_PROTO": 120, "L7_PROTO_NAME": "SSL.Twitter", "TCP_FLAGS": 18, "IN_PKTS": 40, "IN_BYTES": 3173, "OUT_PKTS": 0, "OUT_BYTES": 0, "FIRST_SWITCHED": 1492107328, "LAST_SWITCHED": 1492107606, "json": { "15": "184.70.24.213", "10": "12", "14": "2", "5": "0", "16": "0", "17":"13414" }, "CLIENT_NW_LATENCY_MS": 0.000000, "SERVER_NW_LATENCY_MS": 0.000000, "DST_IP_COUNTRY": "US", "DST_IP_LOCATION": [ -122.412804, 37.775799 ], "NTOPNG_INSTANCE_NAME": "ntop-redder-dev", "INTERFACE": "tcp:\/\/127.0.0.1:5559c [probeIP: 10.60.58.39]" }; line: 1, column: 572]>, :data=>"{ \"ntop_timestamp\":\"2017-04-13T18:20:03.0Z\", \"IN_SRC_MAC\": \"00:00:00:00:00:00\", \"OUT_DST_MAC\": \"00:00:00:00:00:00\", \"IPV4_SRC_ADDR\": \"151.101.0.133\", \"IPV4_DST_ADDR\": \"184.70.24.214\", \"L4_SRC_PORT\": 443, \"L4_DST_PORT\": 35364, \"PROTOCOL\": 6, \"L7_PROTO\": 91, \"L7_PROTO_NAME\": \"SSL\", \"TCP_FLAGS\": 18, \"IN_PKTS\": 22, \"IN_BYTES\": 9449, \"OUT_PKTS\": 0, \"OUT_BYTES\": 0, \"FIRST_SWITCHED\": 1492107328, \"LAST_SWITCHED\": 1492107603, \"json\": { \"15\": \"10.60.58.44\", \"10\": \"2\", \"14\": \"12\", \"5\": \"0\", \"16\": \"54113\", \"17\": \"6327\" }, \"CLIENT_NW_LATENCY_MS\": 0.000000, \"SERVER_NW_LATEN{ \"ntop_timestamp\": \"2017-04-13T18:20:06.0Z\", \"IN_SRC_MAC\": \"00:00:00:00:00:00\", \"OUT_DST_MAC\": \"00:00:00:00:00:00\", \"IPV4_SRC_ADDR\": \"10.60.58.5\", \"IPV4_DST_ADDR\": \"104.244.46.167\", \"L4_SRC_PORT\": 59408, \"L4_DST_PORT\": 443, \"PROTOCOL\": 6, \"L7_PROTO\": 120, \"L7_PROTO_NAME\": \"SSL.Twitter\", \"TCP_FLAGS\": 18, \"IN_PKTS\": 40, \"IN_BYTES\": 3173, \"OUT_PKTS\": 0, \"OUT_BYTES\": 0, \"FIRST_SWITCHED\": 1492107328, \"LAST_SWITCHED\": 1492107606, \"json\": { \"15\": \"184.70.24.213\", \"10\": \"12\", \"14\": \"2\", \"5\": \"0\", \"16\": \"0\", \"17\": \"13414\" }, \"CLIENT_NW_LATENCY_MS\": 0.000000, \"SERVER_NW_LATENCY_MS\": 0.000000, \"DST_IP_COUNTRY\": \"US\", \"DST_IP_LOCATION\": [ -122.412804, 37.775799 ], \"NTOPNG_INSTANCE_NAME\": \"ntop-redder-dev\", \"INTERFACE\": \"tcp:\\/\\/127.0.0.1:5559c [probeIP: 10.60.58.39]\" }"}
```

**Comment by bperian** [comment] 2017-04-13 19:45
@jevonearth , I see it. Thanks for reporting it. I have a pretty clear idea of why is that happening.  I'll get back as soon as possible with a patch.

**Comment by bperian** [comment] 2017-04-14 08:29
@jevonearth   I opened a new issue for this problem https://github.com/ntop/ntopng/issues/1160
