### ISSUE TITLE
No access to User Script configuration.

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#5662] opened 2021-07-12 11:50 UTC
Hello.

Regarding the doc, user script should be available on:  Settings->User Scripts.
https://www.ntop.org/guides/ntopng/web_gui/user_scripts.html

I've no User Script into Settings menu: 
![image](https://user-images.githubusercontent.com/86605223/125266621-47de6c00-e306-11eb-9199-2db990a3beaa.png)

$ ntopng --version
Version:        4.3.210712 [Enterprise/Professional build]
GIT rev:        dev:d94034735289abd07087d7fc7cddd8f7bcf9cd91:20210712
Pro rev:        r3991
Built on:       Debian GNU/Linux 10 (buster)
System Id:      5404F99DB206AB13
Platform:       x86_64
Edition:        Enterprise M
License Type:   Permanent
Maintenance:    Until Sat May 14 16:07:24 2022 [306 days left]

Is there something that I should enable before having access to this interface ?

**Comment by MatteoBiscosi** [comment] 2021-07-12 15:37
Hi @thomasbruchet we recently changed 'User Scripts' into 'Checks' and we still have to update the documentation, so from now on you access the User Scripts by going into 'Settings->Checks'.
Sorry for the trouble.

**Comment by thomasbruchet** [comment] 2021-07-13 06:58
Hi.
Thank you for this answer. 
I'm looking for a way to whitelist a specific couple Host/event to have it in the flow as notice, not as an error.
I will looking on Discord for some help.

**Comment by simonemainardi** [comment] 2021-07-13 07:50
duplicate of https://github.com/ntop/ntopng/issues/5303

**Closed as completed by simonemainardi** 2021-07-13 07:50 UTC
Labels: question
