### ISSUE TITLE
Problem in service map visualization

### ISSUE THREAD

**Issue by jacoporusso-css** [ntop/ntopng#6965] opened 2022-11-04 10:31 UTC
**Environment**:
* ntopng version/revision: 5.4.221102

**What happened**:
Connections visible in the global service map ("all network" option selected) are not visible anymore when I select the specific network.
Example:

![immagine](https://user-images.githubusercontent.com/108343272/199951157-c3447b1b-dc25-409e-9685-be4d12d0be93.png)

Both of these hosts belong to the network 10.127.70.0/24.
Anyway if I select the specific network nothing is displayed

![immagine](https://user-images.githubusercontent.com/108343272/199951543-30132fa8-3d08-4113-92a3-14af91b633f4.png)

**Comment by MatteoBiscosi** [comment] 2022-11-07 09:33
Hi @jacoporusso-css could you please send me the map_handler request? 
Because as you can see i tried to reproduce the error and everything works as expected, please send me the request and i'll try to investigate
![image](https://user-images.githubusercontent.com/49585191/200276004-f0008500-693c-47ad-bbca-6ed17c82c79d.png)

**Comment by jacoporusso-css** [comment] 2022-11-07 14:16
Hello Matteo,
 thank you for checking on the issue. I did some further test and I noticed it's not a matter of visualization, since it's affecting table view as well (no result when filtering on the specific network).
  As requested here's the map_handler GET request 

http://<NTOPNG_URL>:3001/lua/pro/enterprise/map_handler.lua?unicast_only=false&network=7&map=service_map&page=graph&ifid=0&action=load_graph&map=service_map

Indeed the answer contains no data
{"nodes":[],"last_entry":"","layout":{"position":{"x":0,"y":0},"scale":1},"first_entry":"","edges":[]}

To give you some further info, here's how it appears when no network filter is applied:

![immagine](https://user-images.githubusercontent.com/108343272/200331401-84bae34e-1f04-49e0-bcac-c2b72ed2b873.png)

Thank you,
Jacopo

**Comment by MatteoBiscosi** [comment] 2022-11-16 17:18
Hi @jacoporusso-css in the next build, the issue should be fixed (this nightly build). Let me know

**Comment by MatteoBiscosi** [comment] 2022-11-23 10:47
Verified as fixed, please reopoen the ticket if needed

**Closed as completed by MatteoBiscosi** 2022-11-23 10:47 UTC
Labels: Ready to Test
