### ISSUE TITLE
Issues with same IP in sub-interfaces on view interface

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2708] opened 2019-07-04 10:35 UTC
When the same host (IP / IP+VLAN) is seen on multiple sub-interfaces, which the view interface is aggregating, the ntopng gui will just pick one of them. This is wrong as both the hosts should be accessible and have their own identity.

**Comment by simonemainardi** [comment] 2019-07-04 13:50
duplicate of #2696

**Closed as completed by simonemainardi** 2019-07-04 13:50 UTC
