### ISSUE TITLE
PeriodicityHash leaks

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5930] opened 2021-09-28 17:32 UTC
```
sudo gdb --args ./ntopng -i eno1 -i tcp://*:5556c   -i ../nDPI/tests/pcap/tls_certificate_too_long.pcap --disable-login 1 -p /tmp/custom -Z /maina -F "syslog"
```

```
28/Sep/2021 19:30:54 [AddressResolution.cpp:52] Address resolution stats [13 resolved][77 failures]

=================================================================
==30429==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2032 byte(s) in 1 object(s) allocated from:
    #0 0x4deb00 in calloc (/home/simone/ntopng/ntopng+0x4deb00)
    #1 0x7ffff1f288e0 in g_malloc0 (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4f8e0)

Direct leak of 504 byte(s) in 7 object(s) allocated from:
    #0 0x510240 in operator new(unsigned long, std::nothrow_t const&) (/home/simone/ntopng/ntopng+0x510240)
    #1 0x112f706 in PeriodicityHash::deserialize(char const*) /home/simone/ntopng/pro/PeriodicityHash.cpp:378:33
    #2 0xcfc7e9 in PeriodicityMap::PeriodicityMap(NetworkInterface*, unsigned int, unsigned int) /home/simone/ntopng/pro/PeriodicityMap.h:35:5
    #3 0xbfb15a in NetworkInterface::allocateStructures() /home/simone/ntopng/src/NetworkInterface.cpp:6742:31
    #4 0xa55188 in Ntop::start() /home/simone/ntopng/src/Ntop.cpp:524:5
    #5 0xb600f6 in main /home/simone/ntopng/src/main.cpp:423:3
    #6 0x7ffff2ceb83f in __libc_start_main /build/glibc-S7Ft5T/glibc-2.23/csu/../csu/libc-start.c:291

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x50ff40 in operator new(unsigned long) (/home/simone/ntopng/ntopng+0x50ff40)
    #1 0x1128d1c in PeriodicityHash::updateElement(Flow*, unsigned int, bool, PeriodicityStats**) /home/simone/ntopng/pro/PeriodicityHash.cpp:149:15
    #2 0xd14bc3 in PeriodicityHash::updateElement(Flow*, unsigned int) /home/simone/ntopng/pro/PeriodicityHash.h:43:12
    #3 0xcd5055 in NetworkInterface::updateFlowPeriodicity(Flow*) /home/simone/ntopng/src/NetworkInterface.cpp:8876:5
    #4 0x62c51c in Flow::processExtraDissectedInformation() /home/simone/ntopng/src/Flow.cpp:663:3
    #5 0x63718c in Flow::setExtraDissectionCompleted() /home/simone/ntopng/src/Flow.cpp:928:3
    #6 0x6323f2 in Flow::processPacket(unsigned char const*, unsigned short, unsigned long, unsigned char*, unsigned short) /home/simone/ntopng/src/Flow.cpp:744:5
    #7 0xc07ec1 in NetworkInterface::processPacket(unsigned int, bool, timeval const*, unsigned long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned int, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) /home/simone/ntopng/src/NetworkInterface.cpp:1571:7
    #8 0xc2115f in NetworkInterface::dissectPacket(unsigned int, bool, unsigned char*, pcap_pkthdr const*, unsigned char const*, unsigned short*, Host**, Host**, Flow**) /home/simone/ntopng/src/NetworkInterface.cpp:2246:17
    #9 0x9791e4 in packetPollLoop(void*) /home/simone/ntopng/src/PcapInterface.cpp:337:4
    #10 0x7ffff65a26b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Indirect leak of 320 byte(s) in 8 object(s) allocated from:
    #0 0x4de978 in __interceptor_malloc (/home/simone/ntopng/ntopng+0x4de978)
    #1 0x128bac1 in ndpi_alloc_data_analysis /home/simone/nDPI/src/lib/ndpi_analyze.c:57

Indirect leak of 96 byte(s) in 8 object(s) allocated from:
    #0 0x4de978 in __interceptor_malloc (/home/simone/ntopng/ntopng+0x4de978)
    #1 0x128ba18 in ndpi_init_data_analysis /home/simone/nDPI/src/lib/ndpi_analyze.c:49

Indirect leak of 72 byte(s) in 7 object(s) allocated from:
    #0 0x479480 in __interceptor_strdup (/home/simone/ntopng/ntopng+0x479480)
    #1 0x115fd81 in PeriodicityStats::setInfos(char const*) /home/simone/ntopng/pro/PeriodicityStats.h:109:83
    #2 0x115eea7 in PeriodicityStats::deserialize(json_object*) /home/simone/ntopng/pro/PeriodicityStats.cpp:463:69
    #3 0x112fa6e in PeriodicityHash::deserialize(char const*) /home/simone/ntopng/pro/PeriodicityHash.cpp:381:27
    #4 0xcfc7e9 in PeriodicityMap::PeriodicityMap(NetworkInterface*, unsigned int, unsigned int) /home/simone/ntopng/pro/PeriodicityMap.h:35:5
    #5 0xbfb15a in NetworkInterface::allocateStructures() /home/simone/ntopng/src/NetworkInterface.cpp:6742:31
    #6 0xa55188 in Ntop::start() /home/simone/ntopng/src/Ntop.cpp:524:5
    #7 0xb600f6 in main /home/simone/ntopng/src/main.cpp:423:3
    #8 0x7ffff2ceb83f in __libc_start_main /build/glibc-S7Ft5T/glibc-2.23/csu/../csu/libc-start.c:291
```

**Comment by MatteoBiscosi** [comment] 2021-09-30 07:52
Should be fixed, pro repo. This memory leak was due to a missed Lock, causing race conditions and thus unexpected behavior.

**Closed as completed** 2021-10-11 13:23 UTC
Labels: Low-Priority Bug, Ready to Test, Priority Ticket
