### ISSUE TITLE
ntopng stable versione: I can't update ntopng because depends on a wrong pfring version

### ISSUE THREAD

**Issue by bioteseo** [ntop/ntopng#1751] opened 2018-04-19 06:22 UTC
Hi,
I installed a ntopng stable version on a ubuntu server 14.04.
From some days I can't update ntopng because the package depends on pfring (= 7.0.0-1837) [UNAVAILABLE] 
The actual pfring version is 7.0.0-1846.
I tried to remove pfring and ntopng to reinstall them and now the situation is:
The following packages have unmet dependencies:
 ntopng : Depends: pfring (= 7.0.0-1837) but 7.0.0-1846 is to be installed
          Recommends: ntopng-data but it is not going to be installed
 pfring : Depends: dkms but it is not going to be installed
          Recommends: pfring-dkms (= 7.0.0) but it is not going to be installed
What do you suggest?

Thank you in advance

**Comment by bioteseo** [comment] 2018-04-19 07:13
I had brutally (I had to delete /etc/init.d/ntopng and /etc/ntopng dir ) to uninstall ntopng, then I reinstalled ntopng, now all is ok.

**Comment by zxyz** [comment] 2018-04-19 12:31
I had a similar problem running centos 7.4.
yum somehow thought that ntopng 3.2 was still installed, but downloading the 3.2.2 rpm file and trying to install it manually resulted in rpm complaining that the version was already installed. 

removing ntopng and pfring and reinstalling solved the problem for me.

**Comment by mzac** [comment] 2018-04-19 14:17
Same issue here as I also reported in https://github.com/ntop/ntopng/issues/1749#issuecomment-382468895

I have this issue on two Ubuntu 16.04 servers that were setup with nBox (so all packages)

I don't think that removing and re-installing should be the solution, however since nBox configures ntop, maybe it is the only way?

**Comment by melak** [comment] 2018-04-20 08:13
Package versioning gone completely bonkers.

```bash
apt-get install ntopng=3.2.2.180419-4336
```

**Comment by emanuele-f** [comment] 2018-04-20 10:03
Hi, the new ntopng stable package depends on pfring 7.0.0-1858 which is greater than 7.0.0-1846 so the pfring dependency should be fixed. If you still have the old ntopng version, can you verify if the upgrade works correctly now?

**Comment by melak** [comment] 2018-04-20 11:29
For what it's worth, from the "new" one, it does.
```
# apt-get -V dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
   ntopng (3.2.2.180419-4336 => 3.2.2.180420-4338)
   pfring (7.0.0-1856 => 7.0.0-1858)
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,132 kB of archives.
After this operation, 1,024 B disk space will be freed.
```

**Comment by emanuele-f** [comment] 2018-04-20 17:03
The problem was caused by the ntopng version number `3.2.2.x` which is lesser then `3.2.180...x`. We've changed the stable version to `3.4` to fix it. We're sorry for the inconvenient.

**Closed as completed by emanuele-f** 2018-04-20 17:03 UTC
