### ISSUE TITLE
Not possible to download records from history page

### ISSUE THREAD

**Issue by Niklasr69** [ntop/ntopng#6270] opened 2022-02-01 10:08 UTC
**Environment**:
* OS name: rocky
* OS version: 8.5
* Architecture: 
* ntopng version/revision: Enterprise L v.5.1.220201
* Browser: Chrome Version 97.0.4692.71

**What happened**:
When clicking "Download records button", chrome respond with "Failed - No file"

**What did you expect to happen?**
The download should start

**How did you reproduce it?**

**Debug Information**:

![image](https://user-images.githubusercontent.com/26242302/151949352-5edd2da6-b916-4c21-b224-4e0e9ec8164b.png)

**Comment by MatteoBiscosi** [comment] 2022-02-01 10:11
Hi @Niklasr69 , please report if there is some error in `journalctl -u ntopng -e` or in the js console (right click on the page, inspect, console tab, then rerun the download and you should see a red icon showing if there is an error)

**Comment by Niklasr69** [comment] 2022-02-01 10:17
No errors in journalctl -u ntopng -e
No information is added to console when clicking on download button

**Comment by MatteoBiscosi** [comment] 2022-02-01 10:20
Could you please open the downloaded file and check if some error is reported there?

**Comment by Niklasr69** [comment] 2022-02-01 10:21
No file is created
Same issue with Microsoft edge

**Comment by MatteoBiscosi** [comment] 2022-02-01 10:24
Please tell me the filters you are using (no need the value, just the filters selected). I'm not able to reproduce it currently, tried on firefox, chromium, edge and still working.

**Comment by Niklasr69** [comment] 2022-02-01 10:29
"Client IP" and "Flow exporter"

**Comment by MatteoBiscosi** [comment] 2022-02-01 10:35
Which columns have you selected? (still not able to reproduce)
![Screenshot from 2022-02-01 11-34-17](https://user-images.githubusercontent.com/49585191/151953369-942fe24c-e7c2-48d0-b8d7-dcb3a23a9283.png)
No error even from `systemctl status ntopng`?

**Comment by Niklasr69** [comment] 2022-02-01 10:50
![image](https://user-images.githubusercontent.com/26242302/151955284-2446c99d-8697-4722-a7b6-16a7a1673382.png)

**Comment by Niklasr69** [comment] 2022-02-02 08:23
Any more information from me to help the investigation?

**Comment by MatteoBiscosi** [comment] 2022-02-02 10:33
Hi @Niklasr69, no error from both front-end and back-end, it's difficult to debug this error, because if the download fails then an error is going to be show in the back end. I tried with our testing lab (1 Gb/s in both upload and download) and still downloaded 100k+ flows without problems. Does the download works with other records? Do you have some adblock configured in the browser (sometimes it blocks ntopng features)? Is the download of files enabled or is it blocked from the browser or  firewall?

**Comment by Niklasr69** [comment] 2022-02-02 15:05
I have found the reason.
The ntop part is missing before lua/pro..... in the url request
Faulty URL:
https://io.internal.domain.com/lua/pro/rest/v2/get/host/flows/download_flow_records.lua?ts_schema=host%3Atraffic&ifid=173&epoch_end=1643813762&query_preset=&version=4&ts_query=ifid%3A173&epoch_begin=1643811962&detail_view=flows&length=200&visible_columns=flow%2Cl4proto%2Cl7proto%2Cscore%2Cbytes%2Cthroughput%2Cfirst_seen%2Clast_seen%2Cl7cat%2Cstatus%2Cprobe_ip&format=txt

Right URL:
https://io.internal.domain.com/ntop/lua/pro/rest/v2/get/host/flows/download_flow_records.lua?ts_schema=host%3Atraffic&ifid=173&epoch_end=1643813762&query_preset=&version=4&ts_query=ifid%3A173&epoch_begin=1643811962&detail_view=flows&length=200&visible_columns=flow%2Cl4proto%2Cl7proto%2Cscore%2Cbytes%2Cthroughput%2Cfirst_seen%2Clast_seen%2Cl7cat%2Cstatus%2Cprobe_ip&format=txt

**Comment by MatteoBiscosi** [comment] 2022-02-02 15:15
Thx @Niklasr69 , finally found the problem, thanks a lot, i pushed a fix! In the next build it should be fixed.

**Comment by Niklasr69** [comment] 2022-02-03 07:54
Problem solved in v.5.3.220203
Issue can be closed

**Closed as completed** 2022-02-03 09:06 UTC
Labels: Ready to Test
