### ISSUE TITLE
ntopng is not posting alert info to webhook when it detects the alert

### ISSUE THREAD

**Issue by venkatramanh265** [ntop/ntopng#2894] opened 2019-10-01 10:47 UTC
Hi ,

I have created one webhook and I have configured it in the alert endpoint of ntopng preference when I click on send test message , it triggers the webhook and I am receiving the body as{"version":"0.2","sharedsecret":"","alerts":[ ]}. 
According to my understanding whenever an alert is detected the same should be sent to this webhook but even though I can see enaged alerts in the detected alerts tab , but at a alert detection ntopng is not triggering the webhook.
Please resolve this ASAP.

**Comment by emanuele-f** [comment] 2019-10-02 05:47
Could not reproduce. I can correctly receive flow and hosts alerts. The output above should only be sent if you press the "Send Test Message"

**Comment by simonemainardi** [comment] 2019-10-09 12:18
this has been fixed in the latest build.

**Closed as completed by simonemainardi** 2019-10-09 12:18 UTC
