### ISSUE TITLE
LUA Error and process failure during Network Discovery

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6629] opened 2022-05-24 21:08 UTC
**Environment**:
* OS name: OPNsense Business Edition
* OS version: 22.4, Based on FreeBSD 13.0-STABLE
* Architecture: amd64
* ntopng version/revision: v.5.3.220524

**What happened**:
Enabled Network Discovery, set SNMP community string and SNMPv3 user, and ran discovery and ntopng process terminated. Error message generated was:
```24/May/2022 16:00:34 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][index a stringstring value]```

**What did you expect to happen?**
Network discovery to complete without process stopping.

**How did you reproduce it?**
Restart ntopng.
Start Network Discovery via GUI

**Debug Information**:
N/A

**Comment by cardigliano** [comment] 2022-05-25 16:09
Duplicate of https://github.com/ntop/ntopng/issues/6578 (reopened)

**Closed as completed by cardigliano** 2022-05-25 16:09 UTC
