### ISSUE TITLE
"Purge Past Allerts" does not work

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1542] opened 2017-10-27 08:15 UTC
Hi,

when I try to purge the past allerts nothing gets deleted.

Version: ntopng Professional Edition v.3.1.171027

Matthias

**Comment by simonemainardi** [comment] 2017-10-27 12:49
duplicate of https://github.com/ntop/ntopng/issues/1534

**Closed as completed by simonemainardi** 2017-10-27 12:49 UTC
Labels: Duplicate
