### ISSUE TITLE
Trace user activity during configuration changes

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2153] opened 2018-11-17 10:59 UTC
Currently it is not possible to keep track *on a human readable format* of what has been changed in configuration. Example create a log file containing
- at time K, user X has modified LDAP configuration
- at time K1, user Y has extracted a pcap file with BPF filter "host X and port Y"

**Comment by simonemainardi** [comment] 2018-11-28 17:48
duplicate of #2143

**Closed as completed by simonemainardi** 2018-11-28 17:48 UTC
Labels: Duplicate
