### ISSUE TITLE
LUA script failure - not enough memory

### ISSUE THREAD

**Issue by wmorgan1** [ntop/ntopng#469] opened 2016-04-01 14:51 UTC
Hello!

My university currently has ntopng and nprobe set up on a server with 24 cores and 48 GB of ram, with a passive 10Gb/s link monitoring all internet traffic. We have standard licenses for both nprobe and ntopng.

We have set nprobe to export data to ntopng, which then exports the data to ES.

Ntopng is shutting down after only a few minutes of uptime. The "systemctl status ntopng" command states:
Mar 31 08:12:07 <our network> systemd[1]: Started Start/stop ntopng program.
Mar 31 08:17:58 <our network> ntopng[34948]: [Lua.cpp:4430] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][not enough memory]
Mar 31 09:10:39 <our network> systemd[1]: Stopping Start/stop ntopng program...

The command we use to start nprobe is:
./nprobe --zmq tcp://*:5556 -i p1p1 -n none -L <our network> -V 9 -r -G

And the ntopng.conf is:
-G=/var/tmp/ntopng.pid
-i tcp://127.0.0.1:5556
-F "es;ntopng;ntopng-%Y.%m.%d;<our network>:9200/_bulk;"
-e
-m "<our network>"
-S "all"
-X "2000000"
-x "2000000"

I've googled quite a bit, and I see that memory issues on Lua are common, but I do not see any fixes for it. Can anything be done?

**Comment by simonemainardi** [comment] 2016-04-01 14:55
please report ntopng version

**Comment by wmorgan1** [comment] 2016-04-01 15:00
Sorry!
[root@xxxxx ntopng]# ntopng -V
v.2.2.160323 [Professional Edition]
GIT rev:   2.2-stable:06306079a9f31f95143756e855b99ac968415763:20160323
Pro rev:   r524
System Id: xxxxxxx
Built on:  CentOS Linux release 7.1.1503 (Core) 

[root@xxxx bin]# ./nprobe -v

Welcome to nProbe v.7.2.160323 (r4473) for x86_64-unknown-linux-gnu
with native PF_RING acceleration.
Copyright 2002-15 ntop.org

Build OS:      CentOS Linux release 7.1.1503 (Core)
SystemID:      xxxxxxx
Edition:       nProbe Standard

**Comment by simonemainardi** [comment] 2016-04-01 15:15
this is a duplicate of https://github.com/ntop/ntopng/issues/26

please update to the latest dev version. Memory has been optimized.

**Closed as completed by simonemainardi** 2016-04-01 15:15 UTC
Labels: Duplicate
