### ISSUE TITLE
Active Flows - No Results Found

### ISSUE THREAD

**Issue by kargh** [ntop/ntopng#170] opened 2015-09-16 15:56 UTC
In one DC, everything is working as it should with ntopng, in another DC, with the same version installed, same configuration, I'm showing no Active Flows, Hosts, Networks, etc.  I am showing activity though (currently ~800 hosts, 12k flows).

Where might I look to resolve this issue?

**Comment by kYroL01** [comment] 2015-09-16 16:03
This is too generic to understand the problem. We need to know about configurations.

**Comment by kargh** [comment] 2015-09-16 18:08
Which configurations do you want?

On a side note, /lua/get_flows_data.lua returns { "currentPage" : 1, "data" : [ ], "perPage" : 10, "sort" : [ [ "column_", "desc" ] ], "totalRows" : 0 } on that server. I'm trying to trace back through the code to find out where the snag is at.

**Comment by lucaderi** [comment] 2015-09-17 07:58
@kargh Please update the app to the latest dev package as we have fixed a few issues.

**Comment by kargh** [comment] 2015-09-17 12:31
I've updated and the results are still the same.
[image](https://cloud.githubusercontent.com/assets/7748732/9933076/feddf6d0-5d0d-11e5-8209-4998a1460baf.png)

I'm not entirely sure when it stopped working -- I don't use it very often. It was my network guy who mentioned it to me yesterday.

**Comment by lucaderi** [comment] 2015-09-17 13:35
@kargh Any chance for me to connect?

**Comment by lucaderi** [comment] 2015-09-21 13:51
@kargh Any news? Can you please check in the browser's Javascript console if the re are errors and if so report them?

**Comment by kargh** [comment] 2015-09-22 11:13
@lucaderi Hello -- I was out of town all weekend. I just checked it again and there are no errors appearing. It is almost as if it is not reading from where ever flows are temporarily stored.

**Comment by lucaderi** [comment] 2015-09-22 18:52
Hard to help you. Can you please share a URL that does not work or better allow to connect to your box ?

**Comment by kargh** [comment] 2015-09-23 12:24
I'm sure you've seen it already but, if not, I emailed you your login information.

**Comment by ayera-hstack** [comment] 2015-09-23 20:15
I am having the same end result (no active flows when I try to list flows of a host). I can view all flows however when I try to list flows for a single host it comes back with no active flows. When I try to view the flows I get one error in the  ntopng.log file.

[Lua.cpp:4840] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:130: bad argument #1 to 'pairs' (table expected, got nil)]

Luca, I can provide access to the system if you believe it would help isolate the issue. Please send me an email (harley@ayera.com) with the IP you will originate from and I will permit the inbound connections.

**Comment by kargh** [comment] 2015-09-23 20:35
yeah, that same error is my log files and I have the same issue as well (can't list flows for an individual host).

**Comment by lucaderi** [comment] 2015-09-26 07:11
Hi all can you please refresh the code and see if its better now?

**Comment by ayera-hstack** [comment] 2015-09-26 07:29
I updated to 2.0.150926 just a bit ago with the same end results.

[Lua.cpp:4840] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:130: bad argument #1 to 'pairs' (table expected, got nil)]

**Comment by lucaderi** [comment] 2015-09-26 07:40
It looks like you do not have the fix installed. Packages will be built overnight again. Try copying the get_flows_data.lua from github

**Comment by ayera-hstack** [comment] 2015-09-28 03:12
No luck. I just updated to 150928 and the issue persists.

[Lua.cpp:4840] WARNING: Script failure [/usr/share/ntopng/scripts/lua/get_flows_data.lua][/usr/share/ntopng/scripts/lua/get_flows_data.lua:110: bad argument #1 to 'pairs' (table expected, got nil)]

Harley

**Comment by lucaderi** [comment] 2015-09-28 07:12
@ayera-hstack Can you please send me the whole URL that generates the problem

**Comment by ayera-hstack** [comment] 2015-09-28 20:54
http://ntopnghost.com:3000/lua/host_details.lua?ifname=0&host=1.2.3.4&page=flows

**Comment by lucaderi** [comment] 2015-10-06 20:17
The problem should be fixed by now

**Comment by ayera-hstack** [comment] 2015-10-08 16:43
The issue is not resolved. I am unable to view flows from individual hosts. Even though there are hundreds of active flows for this particular host, NTOPNG displays"No Results Found" when you try to list them while looking at a single IP.

Luca, Would you like to access my system so you can see what the issue is? I have a NTOPNG pro licence with the IXGBE ZC licences as well.

**Comment by lucaderi** [comment] 2015-10-08 19:02
I need access. Please mail me privately the details

**Comment by nazhu** [comment] 2015-10-20 13:38
I use current dev github source. The CentOS 6.7 have the same issue, but the debian 8 is  OK.

**Comment by lucaderi** [comment] 2015-10-20 13:44
@nazhu Are you saying that the Centos 6 package has the bug but not on the Debian package? Please explain in detail how to reproduce so we can close this issue.

**Comment by nazhu** [comment] 2015-10-21 14:33
Yes, I make install ntopng v2.1.151018 on there OS: the CentOS6.7 , the Debian Jessie i386 and x86_64. On the Debian Jessie i386 and x86_64, the  Active Flows of a host display normally. But on the CentOS6.7, the Active Flows of a host  is "No Results Found".

**Comment by lucaderi** [comment] 2015-10-21 15:41
Looks like there is a problem on CentOS 6

**Comment by nazhu** [comment] 2015-10-22 14:22
@lucaderi https://github.com/ntop/ntopng/issues/245

**Closed** 2015-10-26 18:17 UTC
Labels: Testing Needed

**Comment by DaveLafleur** [comment] 2016-01-26 19:28
Active Flows
No Results Found
Generated by ntopng Community v.2.2.160118

this system is ubuntu 14.04 installed from repo today.  how is this issue resolved?

**Comment by simonemainardi** [comment] 2016-01-28 15:44
can't reproduce with the very same configuration. Flows show normally both in the Flows page and in each host details.

please, provide additional details
