### ISSUE TITLE
Drop Google in favour of openstreetmap

### ISSUE THREAD

**Issue by HaleyACS** [ntop/ntopng#2746] opened 2019-07-25 20:59 UTC
Hi folks,

eventually you should drop google in favor of openstreetmaps for geolocalisation.
Kind of is crap google requiring a API Key to access that functionality.

**Comment by simonemainardi** [comment] 2019-07-26 08:16
duplicate of https://github.com/ntop/ntopng/issues/2433

**Closed as completed by simonemainardi** 2019-07-26 08:16 UTC
Labels: Duplicate
