### ISSUE TITLE
BT5: new installation, first login, unable to change password

### ISSUE THREAD

**Issue by alweiler** [ntop/ntopng#5385] opened 2021-05-20 09:19 UTC
![Screenshot from 2021-05-20 12-17-42](https://user-images.githubusercontent.com/714591/118953498-8b030b00-b965-11eb-95e4-17b50eb4e1ec.png)

**Comment by MatteoBiscosi** [comment] 2021-05-20 12:31
Hi @alweiler I'm sorry but I'm unable to reproduce the issue, could you please share your ntopng version and are you using community or Pro/Enterprise version?

**Comment by alweiler** [comment] 2021-05-20 12:39
@MatteoBiscosi  4.3.210520 [Enterprise/Professional build]
dev:13283eca4b00f9b5d7b6ad503acf5a31d1f85775:20210520

and I bought licence Enterprise L (Bundle)

**Comment by simonemainardi** [comment] 2021-05-20 12:47
@MatteoBiscosi please check the button it looks left-aligned.

**Comment by MatteoBiscosi** [comment] 2021-05-20 14:02
Hi @alweiler the issue should be fixed, soon builds are going to start and you should be able to update in some hour. However in the meantime you should be able to overcome the problem by typing the "enter" button from your keyboard (fixed in the upcoming update) instead of clicking with your mouse into the "change password" button

**Comment by alweiler** [comment] 2021-05-20 14:06
@MatteoBiscosi thanks, it works :)

**Closed as completed** 2021-05-20 14:14 UTC
Labels: In Progress
