### ISSUE TITLE
Sort alert by desription / Type

### ISSUE THREAD

**Issue by ListenNjoy** [ntop/ntopng#5319] opened 2021-05-11 14:45 UTC
I miss sorting out alert by choosing to click type and ex. threshold cross to view only those alerts.

Ntopn version: ntopng Enterprise M v.4.3.210511

Picture of old version
![NtopngAlertType](https://user-images.githubusercontent.com/43986547/117835894-85783780-b278-11eb-92ae-c4cd7c198886.jpg)

**Comment by simonemainardi** [comment] 2021-05-11 17:14
duplicate of https://github.com/ntop/ntopng/issues/5206

**Closed as completed by simonemainardi** 2021-05-11 17:14 UTC
