### ISSUE TITLE
2nd letter of SSL Certificate wrong

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#1795] opened 2018-05-24 14:12 UTC
ntopng Professional Edition v.3.5.180524

When I request a https server on my intranet. Lets say https://example.local, ntopng shows client requested the certificate eyample.local on the info tab. The second letter of the certificate is always the next in the alphabet of the actual letter.

**Comment by simonemainardi** [comment] 2018-05-24 14:17
do you mean flow info? can you attach a screenshot?

**Comment by Alestor** [comment] 2018-05-24 14:25
![grafik](https://user-images.githubusercontent.com/6898158/40491608-d1bef148-5f6e-11e8-8b5a-6a74e781cc31.png)

![grafik](https://user-images.githubusercontent.com/6898158/40491654-ea4e5f3c-5f6e-11e8-8d03-55b8687a0cb8.png)

The website of the screenshot above is running under the url monitor.sec

**Comment by fsamareanu** [comment] 2018-05-28 12:02
I can confirm this :)

![image](https://user-images.githubusercontent.com/38040820/40613653-7ac11c48-6290-11e8-9552-50256ffbb212.png)

**Comment by simonemainardi** [comment] 2018-05-28 13:45
thanks for reporting. issue is due to nDPI and has been reported at https://github.com/ntop/nDPI/issues/572

**Comment by emanuele-f** [comment] 2018-05-31 08:58
Fixed with commit 7bee732a76bde722128b97bc25b655d4ed492adf

**Closed as completed by emanuele-f** 2018-05-31 08:58 UTC
