### ISSUE TITLE
bad counter

### ISSUE THREAD

**Issue by dvachon2018** [ntop/ntopng#1912] opened 2018-08-13 14:15 UTC
hi!
using last ntopng (arm) v3.5.180802 - Enterprise/Embedded Edition
regulary have that kind of counter for traffic
16777216 TB
ex: in graph of eth0
setting for db is RRD (default)

![2018-08-13 10_06_13-welcome to ntopng](https://user-images.githubusercontent.com/33327149/44037050-628d5bfe-9ee1-11e8-86b5-4f7c290d2223.jpg)

**Comment by emanuele-f** [comment] 2018-08-13 14:20
If you zoom in into the graph, do you still see the error?

**Comment by emanuele-f** [comment] 2018-08-13 17:19
Please open the javascript inspector and zoom at the maximum resolution until the problem still reproduces. Then in the "network" tab of the inspector, copy and past here the get_ts.lua script query with parameters, e.g. `scripts/lua/get_ts.lua?epoch_begin=...`.

**Comment by dvachon2018** [comment] 2018-08-14 14:09
hi, i restarted with a new DB, so now waiting for the problem to be reproduced.......
what do you mean exactly by 'zoom at the maximum' ?? change the Timeframe ?? Because on the graph, there is a 'Zoom out' button but clicking it does nothing.

**Comment by dvachon2018** [comment] 2018-08-14 16:20
hi, i wish it is what you asked for

```
{"step":60,"additional_series":{"1h ago":[14204.45,76870.366666667,22928.583333333,204752.18333333,272348.93333333,78258.666666667,385111.26666667,629318.2,211696.9,272450.5,253318.88333333,344923.1,451300.96666667,794060.65,286318.7,143032.31666667,241295.41666667,280178.21666667,354908.48333333,227616.75,424144.2,411748,257377.76666667,465139.21666667,343617.6,231566.61666667,446133.15,273872.6,340245.53333333,109867.16666667,406922.86666667,376774.83333333,270019.85,467994.93333333,380602.9,116461.36666667,208959.53333333,162672.65,339131.1,229037.53333333,349991.93333333,197243.95,584460.78333333,494928.33333333,334662.31666667,5636863.9333333,3440258.4,841670.5,292175.18333333,567156.41666667,452818.23333333,612801.85,53107.8,374679.08333333,259667.85,178912.83333333,498606.91666667,124119.73333333,139155.25,183248.11666667]},"statistics":{"max_val":3.0744573449552e+17,"max_val_idx":32,"total":1.8446744072531e+19,"min_val_idx":13,"average":5.1240955757032e+15,"min_val":18647.366666667,"95th_percentile":4636860.1833333},"count":60,"start":1534259640,"series":[{"tags":{"ifid":"0"},"label":"bytes","data":[33019.316666667,216809.01666667,132107.35,116831.85,119441.4,153379.23333333,59483.983333333,210314,177304.73333333,125682.36666667,82300.416666667,119401.11666667,81579.866666667,18647.366666667,238512.93333333,124169.18333333,67947.883333333,26112.8,112765.55,416137.01666667,276271.38333333,155811.36666667,121769.38333333,190868.35,142405.08333333,256775.71666667,167120.06666667,104470.91666667,148743.63333333,5087177.6333333,676969.46666667,7654345.45,3.0744573449552e+17,664181.63333333,333363.26666667,3181681.3,1665636.5833333,296496.4,294749.05,256449.9,203582.1,205979.55,1147127.4666667,590808.6,658974.83333333,527124.88333333,264518.23333333,229617.36666667,226027.76666667,274345.95,248174.38333333,391900.06666667,150890.8,154597.08333333,2101399.6,4636860.1833333,3793668.4333333,6025249.4,402728.78333333,127280.35]}]}
```
![image](https://user-images.githubusercontent.com/33327149/44104258-652a9120-9fbc-11e8-90f5-45607edb6ffc.png)

**Comment by emanuele-f** [comment] 2018-08-15 08:58
Hi, thank you for the info. In order to zoom in, you can click and drag the mouse on the graph.
Can you please run the following command and post its output? I need understand if the underlying data is correct or not:
`sudo rrdtool fetch /var/tmp/ntopng/0/rrd/bytes.rrd AVERAGE -s 1534259640 -e 1534263180 -r 60`

Afterwards. please update to the new version and see if the problem still reproduces.

**Comment by dvachon2018** [comment] 2018-08-15 12:34
hi, i zoomed to the maximum and problem still there;
![image](https://user-images.githubusercontent.com/33327149/44148071-b7f48f0c-a064-11e8-8869-f2f2023666d2.png)

result for rrdtool fetch /var/tmp/ntopng/0/rrd/bytes.rrd AVERAGE -s 1534259640 -e 1534263180 -r 60
[rrdt.txt](https://github.com/ntop/ntopng/files/2290206/rrdt.txt)

i will do the upgrade.

**Comment by dvachon2018** [comment] 2018-08-16 02:52
hi
same problem with 3.5.180813 - Enterprise/Embedded Edition

**Comment by emanuele-f** [comment] 2018-08-17 08:12
So the value stored on disk is actually wrong
```
1534261620: 3.0744573450e+17
```

This is strange, I have to perform more tests to reproduce the issue

**Comment by emanuele-f** [comment] 2018-08-20 16:42
A workaround for this is available with commit 354dd697c0759e022e6ff761846c615928f823c4 . I'll update this post when the new package is available, so that you can test it.

**Comment by emanuele-f** [comment] 2018-08-21 10:21
@dvachon2018 the new package is now available. Please install it and report if the issue is solved.

**Comment by dvachon2018** [comment] 2018-08-23 22:25
Hello, appear to be ok now. Normal counter for 2 days.
:)

**Comment by emanuele-f** [comment] 2018-08-24 07:32
Thank you for reporting. I'm closing the issue for now.

**Closed as completed by emanuele-f** 2018-08-24 07:32 UTC

**Comment by dvachon2018** [comment] 2018-09-13 02:57
hello, the same problem reappear.
![image](https://user-images.githubusercontent.com/33327149/45464563-2f295400-b6df-11e8-9eda-eda88c8f2e4f.png)

**Comment by emanuele-f** [comment] 2018-09-13 08:41
Please open a new issue. The report uses a different code so it must be fixed too.
