### ISSUE TITLE
impossible to purge alerts

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1533] opened 2017-10-24 09:35 UTC
hi
I just upgraded my ntopng and I wanted to purge alerts... but that doesn't work
in logs have this message : 
ntop-racine ntopng: [AlertsManager.cpp:1150] ERROR: SQL Error: attempt to write a readonly database#012DELETE FROM closed_alerts WHERE 1=1

I did not change something on server or in my ntop config
any idea ?
I have the same issue on my second ntop server..
I hope no need to clean db

fyi: db is OK cause I can see data written in going to history

thanks

nico

**Comment by simonemainardi** [comment] 2017-10-24 09:56
duplicate of https://github.com/ntop/ntopng/issues/1517
please check before posting new issues

**Closed as completed by simonemainardi** 2017-10-24 09:56 UTC

**Comment by Niko78** [comment] 2017-10-24 10:42
ok sorry
I still have a small issue
in "engaged alerts" i have this line 

Wed Sep 20 18:29:00 2017 | 33 days, 18 h, 10 min, 21 sec | Error | Misconfigured App | Interface tcp://172.31.1.245:5556 has too many flows. Please extend the --max-num-flows/-X command line option

so I changed in my config with higher value but this entry can't be removed

nico
