### ISSUE TITLE
Local / Remote Panel, Application Panels all go blank after updating the reporting period and clicking the print button under the "Traffic Report" menu option 

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#2628] opened 2019-06-03 13:50 UTC
When I click the print button (see screen first screen capture, where I pointed the arrow), the local / remote, application panels under the traffic report menu option go blank in the print window, going back to the main traffic report menu it is also now missing, reloading the page does not bring the graphs back.

![image](https://user-images.githubusercontent.com/48565067/58806629-99bf4e80-85e4-11e9-9e1e-db4aa2e07d31.png)

-----

![image](https://user-images.githubusercontent.com/48565067/58806697-b9ef0d80-85e4-11e9-871d-07a8396a16dc.png)

-----

![image](https://user-images.githubusercontent.com/48565067/58806748-d428eb80-85e4-11e9-8cb0-0d737e641fbe.png)

------

![image](https://user-images.githubusercontent.com/48565067/58806818-f0c52380-85e4-11e9-8112-73c4f1084ce1.png)

**Comment by StewAlexander-com** [comment] 2019-06-03 13:56
Re-logging into ntopng brings the graphs back, by the way

**Comment by StewAlexander-com** [comment] 2019-06-03 14:00
## Details ...

![image](https://user-images.githubusercontent.com/48565067/58807488-2ae2f500-85e6-11e9-9f9e-a6de123d04cc.png)

----

![image](https://user-images.githubusercontent.com/48565067/58807619-67165580-85e6-11e9-9b46-e4449b87d096.png)

**Comment by emanuele-f** [comment] 2019-06-03 14:15
Any javascript errors?

**Comment by StewAlexander-com** [comment] 2019-06-03 14:22
Weird, it worked this time

On the first try clicking the print button under the traffic menu report menu option didn't open the Chrome Browser ***Print Dialog Menu***, on the second it did, when it did open the print dialog menu it showed all the panels with graphs.

Appears like a loading time-out or unexpected termination error where a process died before the rendering of all the panels and opening the print dialog menu completed...

Going back to the original menu now shows the graphs.

Looks perhaps like an issue that occurs if some function or sub function of the print process doesn't complete, or unexpectedly terminates ...

**Comment by emanuele-f** [comment] 2019-06-03 14:30
It works for me too. Closing for now. If it happens again please add the javascript error information.

**Comment by StewAlexander-com** [comment] 2019-06-03 14:44
Will do ...

**Comment by StewAlexander-com** [comment] 2019-06-03 14:50
Ok, when I change the reporting time from 1 hour to 1 week, then click the print menu button I get this javascript error when I use the Chrome Browser to inspect the lack of graphs showing up under the print window that appears (the chrome print dialog window never opens)...

```
Uncaught TypeError: Cannot read property 'y0' of undefined
    at nv.d3.js:17813
    at area (d3.v3.js:8400)
    at SVGPathElement.<anonymous> (nv.d3.js:17822)
    at SVGPathElement.attrFunction (d3.v3.js:669)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.d3_selectionPrototype.attr (d3.v3.js:652)
    at SVGGElement.<anonymous> (nv.d3.js:17821)
    at d3.v3.js:8869
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_transitionPrototype.each (d3.v3.js:8867)
    at Array.chart (nv.d3.js:17721)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at SVGSVGElement.<anonymous> (nv.d3.js:18345)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.chart (nv.d3.js:18103)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at Object.generate (report.lua?epoch=1559573100&num_minutes=1440&render=true:2137)
    at renderLoop (nv.d3.js:99)
```
Going back to the main ***Traffic Report*** window and the Local / Remote panels are now missing graphs

Seeing what appears to be the same javascript error on the main page now (didn't do a diff, but it appears the same):

```
Uncaught TypeError: Cannot read property 'y0' of undefined
    at nv.d3.js:17813
    at area (d3.v3.js:8400)
    at SVGPathElement.<anonymous> (nv.d3.js:17822)
    at SVGPathElement.attrFunction (d3.v3.js:669)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.d3_selectionPrototype.attr (d3.v3.js:652)
    at SVGGElement.<anonymous> (nv.d3.js:17821)
    at d3.v3.js:8869
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_transitionPrototype.each (d3.v3.js:8867)
    at Array.chart (nv.d3.js:17721)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at SVGSVGElement.<anonymous> (nv.d3.js:18345)
    at d3.v3.js:962
    at d3_selection_each (d3.v3.js:968)
    at Array.d3_selectionPrototype.each (d3.v3.js:961)
    at Array.chart (nv.d3.js:18103)
    at Array.d3_selectionPrototype.call (d3.v3.js:975)
    at Object.generate (report.lua?num_minutes=1440:2530)
    at renderLoop (nv.d3.js:99)
```

**Comment by StewAlexander-com** [comment] 2019-06-03 15:00
Apparently I didn't catch the requirement to change the reporting time period to see the error? Not sure, anyway I was able to produce the error after changing the reporting time period at the far upper left of the window from 1 hr to 1 week..

**Comment by emanuele-f** [comment] 2019-06-03 16:48
This occurs sometimes, both for RRD and InfluxDB when selecting 1d. In both cases it is caused by missing normalization (normalization is only performed in standard charts, but not in the report).

In RRD it's caused by different RRA picked (the current touchRRD does not help):

![2019-06-03_18-14](https://user-images.githubusercontent.com/5488003/58819141-12db9780-861f-11e9-8f6f-326c331f383e.png)

In Influxdb it's caused normally by a 1 point difference

![2019-06-03_18-10](https://user-images.githubusercontent.com/5488003/58819142-12db9780-861f-11e9-8bfd-d4c4268ca768.png)

**Comment by StewAlexander-com** [comment] 2019-06-03 17:22
Is it possible to fix this, or this working as designed?

**Comment by emanuele-f** [comment] 2019-06-04 10:21
Of course this is a bug and must be fixed

**Comment by emanuele-f** [comment] 2019-06-04 11:22
This should be fixed in the new build. Please wait an our and update ntopng.

**Comment by StewAlexander-com** [comment] 2019-06-04 12:31
Thank you for your support with these issues, very appreciated.

Just for your info: I worked with several companies that had sometimes a peculiar perspective on what was a "bug" and what was "working as designed", it's been a pleasure working with you and your team.

**Comment by StewAlexander-com** [comment] 2019-06-04 14:41
Scrolling down the "Traffic Report" page I came across one of the fields that is "missing" application data still, and I see this message is the Chrome Inspector Window (not sure what to make of it)

![image](https://user-images.githubusercontent.com/48565067/58888431-5e408500-86b5-11e9-9573-80fb43b21e45.png)

This ***Application Breakdown*** field that says "No Data Available" is under the "Network Interface tcp://127.0.0.1:1235 [10.210.8.5]" heading ...

**Comment by emanuele-f** [comment] 2019-06-04 14:58
If you select such interface from the Interfaces dropdown of the header bar and go into the interface charts, can you see any top applications show there?

**Comment by StewAlexander-com** [comment] 2019-06-04 15:19
Yes, thanks

![image](https://user-images.githubusercontent.com/48565067/58891461-8d0d2a00-86ba-11e9-8736-80159b1700ff.png)

**Comment by emanuele-f** [comment] 2019-06-04 15:20
This is traffic, please select top applications

**Comment by StewAlexander-com** [comment] 2019-06-04 15:22
Not in the list:

![image](https://user-images.githubusercontent.com/48565067/58891708-00af3700-86bb-11e9-89e1-4af8a7eb934e.png)

**Comment by StewAlexander-com** [comment] 2019-06-04 15:25
Top Protocols output:

![image](https://user-images.githubusercontent.com/48565067/58891946-669bbe80-86bb-11e9-9101-d7afb5186ee5.png)

**Comment by StewAlexander-com** [comment] 2019-06-04 15:28
Top Senders and Top Receivers is blank:

![image](https://user-images.githubusercontent.com/48565067/58892167-c1cdb100-86bb-11e9-9f3a-1ed202eafcbf.png)
--------
![image](https://user-images.githubusercontent.com/48565067/58892273-ea55ab00-86bb-11e9-8b0c-7297d0f7dc5c.png)

**Comment by emanuele-f** [comment] 2019-06-04 15:29
Top Protocols is correct, sorry we renamed it on dev. The chart however is for eth0, you should select "tcp://127.0.0.1:1235 [10.210.8.5]" from the interfaces dropdown before

**Comment by StewAlexander-com** [comment] 2019-06-04 15:31
Not Available:
![image](https://user-images.githubusercontent.com/48565067/58892507-5a643100-86bc-11e9-91c2-b7ca062169f1.png)

**Comment by emanuele-f** [comment] 2019-06-04 15:33
I think it is the first one, try to show its top protocols chart

**Comment by StewAlexander-com** [comment] 2019-06-04 15:34
Not available:
![image](https://user-images.githubusercontent.com/48565067/58892726-bf1f8b80-86bc-11e9-89f4-438149645f3e.png)

**Comment by emanuele-f** [comment] 2019-06-04 15:41
So there are no applications on this interface, probably because there is no traffic (the traffic on the chart is 0)

**Comment by StewAlexander-com** [comment] 2019-06-05 13:56
Oddly the above screen capture is from our ntopng instance, as in I am looking at the ntopng server output, correct me if I am wrong, but I would think this should be seeing quite a bit of traffic.

**Comment by emanuele-f** [comment] 2019-06-05 14:43
It should be the interface from nProbe, please check out https://www.ntop.org/nprobe/network-monitoring-101-a-beginners-guide-to-understanding-ntop-tools on how to properly setup ntopng and nprobe for communication. If you still have problems, then post the ntopng and nprobe configuration used

**Comment by StewAlexander-com** [comment] 2019-06-05 16:14
Ok, this is a separate issue anyway, sorry to include it in the bug ticket for the print issue.

Please let me know when the print issue bug (above) is fixed, thanks

**Comment by emanuele-f** [comment] 2019-06-05 17:20
It should be already solved in the latest stable

**Comment by StewAlexander-com** [comment] 2019-06-05 17:37
I tested it, mostly works ...

There is one thing I found @emanuele-f ...

I set the traffic report to a week, pressed the print button ...

When the print dialog box for chrome came up the local / remote interface graph hadn't completed drawing yet to the screen, so the panel graph was empty

Upon closing the Chrome print dialog box, the local / remote interface panel graph completed drawing on the page, and was subsequently there.

Not sure if you can do anything about that, but I did notice this behavior so wanted to post it.

**Comment by emanuele-f** [comment] 2019-06-06 15:12
You can close the print page and then print the report again via the print funciton of the browser. As a workaround I've added some delay. This enhancement is only available in the development version of ntopng. Properly handling this feature correctly would require a major rework which is not planned right now.

**Closed as completed by emanuele-f** 2019-06-06 15:12 UTC
Labels: In Progress

**Comment by StewAlexander-com** [comment] 2019-06-06 16:56
Understood, thank you again for your support
