### ISSUE TITLE
mysql and storage full

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#1568] opened 2017-11-14 09:15 UTC
hi
I'm using ntop with -F option to write in database, it works well
I have an issue because when partition is full, ntop can't write more and it writes ton of warning in syslog... so partition where syslog is becomes full :-(
 [MySQLDB.cpp:56] ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]
Nov 14 10:14:38 ntop-racine ntopng: [MySQLDB.cpp:56] ERROR: MySQL error: Out of range value for column 'idx' at row 1 [rc=-1]

So 2 questions 
1) why don't you introduce a mechanism which detect when a partition is full and in that case use rotating data in mysql (it removes older data to add new) ?
2) I tried to reduce mysql storage duration in ntop config, I thought ntop will "remove" old data to reduce mysql database but nothing happens
3) with the 2) now that I'm full what I can do without adding space ? clear database and I loose all datas ?

thanks for your advise

Nico

**Comment by emanuele-f** [comment] 2017-11-14 15:45
Hi, please check out the `MySQL storage` option under the ntopng Timeseries preferences. We delete old flows at midnight. This means that if your MYSQL db becomes full in less than one day, you will need to either incress your HDD size or reduce the amount of data ntopng analyzes.

Please note that MySQL is not intended to be a used as round robin db. You could write a python script or so to perform the db cleanup based on your needs.

If you do not want to lose data when moving to a new external storage, you can copy the datatabase file to the new storage and then do a symbolic link to it.

**Comment by Niko78** [comment] 2017-11-15 07:05
Hi
yep that's what I done and it doesn't change anything
my storage is full but as I changed settings to keep data for 2 weeks instead of 1 month, I thought at midnight, it would remove old data... it's not the case, my storage is still full this morning (I would say even no changes).

I have a storage size about 1TB, so should not be problem (not full in one day). I try to reduce again data retention to 1 week to see if it changes something.

thanks

**Comment by emanuele-f** [comment] 2017-11-15 09:03
Ok. Maybe you can manually connect to the ntopng mysql database and perform queries on the FIRST_SWITCHED field to see how hold is your data

**Comment by Niko78** [comment] 2017-11-16 09:04
well this morning no changes yet, it seems nothing happens at midnight

I think I found where is the problem
I peformed a query in database (in flowsv4) and older first_switched is 1510183930 => 09/11/2017 @ 00:32:10 so no problem here, it respects the mysql retention (7 days) I configured in ntop
BUT in performing the same thing in aggrflowsv4 older first_switched is 1498130654 => 22/06/2017 @ 13:24:14
I even counted the number of recording in aggrflowsv4 => about 6M

what do you think ?

**Comment by emanuele-f** [comment] 2017-11-16 09:32
What ntopng version are you using?

**Comment by Niko78** [comment] 2017-11-16 09:34
3.1.171115 - Professional Edition

**Comment by emanuele-f** [comment] 2017-11-16 09:42
What's the output of `SELECT INTERFACE_ID, FIRST_SWITCHED FROM aggrflowsv4 ORDER BY FIRST_SWITCHED ASC LIMIT 1` ? If think the problem is that some old flows in your db where registered on a network interface which you don't use anymore into ntopng.

Ps. currently, we only delete old flows for the currently available network interfaces of ntopng.

**Comment by Niko78** [comment] 2017-11-16 09:49
it's still the same interface for me, no changes

mysql> SELECT INTERFACE_ID, FIRST_SWITCHED FROM aggrflowsv4 ORDER BY FIRST_SWITCHED ASC LIMIT 1
    -> ;
+--------------+----------------+
| INTERFACE_ID | FIRST_SWITCHED |
+--------------+----------------+
|            1 |     1498130654 |
+--------------+----------------+
1 row in set (0,00 sec)

**Comment by emanuele-f** [comment] 2017-11-16 09:52
If you go into the ntopng gui, can you find a network interface whose id is 1? You can check this by selecting each interface from the Interfaces menu and looking at the "Id" field displayed into the page

**Comment by Niko78** [comment] 2017-11-16 09:55
I have only one interface and id is well 1
/lua/if_stats.lua?ifid=1

**Comment by emanuele-f** [comment] 2017-11-16 10:12
Flow aggregations are only available into the enterprise version of ntopng. You are using the pro version but maybe in the past you used the enterprise (or run the demo of enterprise), can you confirm this? What's the output of `SELECT FIRST_SWITCHED, NTOPNG_INSTANCE_NAME FROM aggrflowsv4 ORDER BY FIRST_SWITCHED DESC LIMIT 1` ?

**Comment by Niko78** [comment] 2017-11-16 10:14
always used pro version (I'm in Education entity)
mysql> SELECT FIRST_SWITCHED, NTOPNG_INSTANCE_NAME FROM aggrflowsv4 ORDER BY FIRST_SWITCHED DESC LIMIT 1;
+----------------+----------------------+
| FIRST_SWITCHED | NTOPNG_INSTANCE_NAME |
+----------------+----------------------+
|     1500461921 |                      |
+----------------+----------------------+
1 row in set (0,02 sec)

**Comment by emanuele-f** [comment] 2017-11-16 10:38
I see. Somehow the flows went into your database table aggrflowsv4 (which was not supposed to be used by your ntopng version), so you can safely delete them. You can do this with the query `DELETE FROM aggrflowsv4;`

**Closed as completed by emanuele-f** 2017-11-16 10:38 UTC

**Comment by Niko78** [comment] 2017-11-16 12:02
ok done but disk space is still full
I checked space in storage folder and I found that 

du -Sh | sort -hr | head -n 25
232G    ./mysql/ntopng
4,7G    ./tmp/1/json/min
4,6G    ./tmp/1/json/5mins
1,4G    ./tmp/1/json/hour
1,3G    ./tmp/1/activities/17/09/04
1,1G    ./tmp/1/activities/17/06/26
1005M   ./tmp/1/activities/17/06/27
789M    ./tmp/1/activities/17/06/08
788M    ./tmp/1/activities/17/06/06
771M    ./tmp/1/activities/17/06/02
723M    ./tmp/1/activities/17/09/15
714M    ./tmp/1/top_talkers
710M    ./tmp/1/activities/17/09/07
627M    ./tmp/1/activities/17/06/12
625M    ./tmp/1/activities/17/06/19
619M    ./tmp/1/activities/17/06/07
618M    ./tmp/1/activities/17/09/01
563M    ./tmp/1/activities/17/06/29
540M    ./tmp/1/activities/17/07/03
488M    ./tmp/1/activities/17/06/30
483M    ./tmp/1/activities/17/07/11
471M    ./tmp/1/activities/17/06/13
459M    ./tmp/1/activities/17/06/09
450M    ./tmp/1/activities/17/06/20
446M    ./tmp/1/activities/17/09/14

as you can see there are few folders dating from June, July and September
can I delete them ? that should be automatic...

**Comment by emanuele-f** [comment] 2017-11-16 13:14
You can safely remove the activities folder as they are not used anymore. We avoid deleting user data automatically when possible, but I agree that some sort of confirmation message should be provided to the user to automatically delete them.

**Comment by simonemainardi** [comment] 2017-11-17 11:42
@Niko78 what is the most recent last_switched that you see in aggrflowsv4? does that table still get updated?

**Comment by Niko78** [comment] 2017-11-17 11:52
@simonemainardi 
I removed aggrflowsv4 as requested by Emanuele, since that table has not been created.
