### ISSUE TITLE
Periodic counters reset

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#914] opened 2017-01-09 17:17 UTC
ntopng counters are absolute and they never reset. However it would be beneficial to add the option to periodically reset counters (e.g. at midnight) or on demand (e.g. via the GUI when logged in as administrator)

**Comment by simonemainardi** [comment] 2017-03-30 07:59
duplicate of #1054

**Closed as completed by simonemainardi** 2017-03-30 07:59 UTC
Labels: Enhancement
