### ISSUE TITLE
Search bar not working correctly 

### ISSUE THREAD

**Issue by Syl4r-v** [ntop/ntopng#5074] opened 2021-02-26 13:02 UTC
When writing an ip address to the search bar and hitting enter, instead of search it just gives [object object] text in the search field.

version: 4.2.210222 (13271) 

<img width="369" alt="Screenshot 2021-02-26 at 14 09 57" src="https://user-images.githubusercontent.com/77612587/109303513-96053e00-7843-11eb-8d2b-574e1f1871cb.png">

**Comment by simonemainardi** [comment] 2021-03-01 10:10
Do you have SNMP devices configured?

**Comment by Syl4r-v** [comment] 2021-03-01 11:50
Not anymore. I tested some devices some time ago, but have since removed them from ntop.

**Comment by simonemainardi** [comment] 2021-03-01 13:18
I can't reproduce the reported behavior. Please, try this:

1. Open the browser inspector
2. Start  typing in the search box until the [object] appears
3. Look at the network part of the inspector for a request to `find_host.lua`
4. Send the response you will see for `find_host.lua`

![image](https://user-images.githubusercontent.com/3397663/109502215-ff31bf00-7a98-11eb-8683-ca9c8ce63bd2.png)

**Comment by simonemainardi** [comment] 2021-03-03 07:31
@Syl4r-v can you please check

**Comment by Syl4r-v** [comment] 2021-03-03 09:11
I doesn't happen all the time, but this should be the right response. The "object" only appears after I hit enter to do the search, it doesnt appear by itself. (I had to remove the IPs because they are all public addresses)

<img width="544" alt="Screenshot 2021-03-03 at 11 07 10" src="https://user-images.githubusercontent.com/77612587/109782029-1e535c80-7c11-11eb-96bf-527b3975dcc5.png">

**Comment by simonemainardi** [comment] 2021-03-04 10:43
@MatteoBiscosi seems the issue is with view interfaces. @Syl4r-v can you confirm this is only happening with the view? Please, attach the ntopng configuration file.

**Comment by simonemainardi** [comment] 2021-03-04 10:46
@MatteoBiscosi also note that is is an issue with the stable.

**Comment by Syl4r-v** [comment] 2021-03-05 13:28
Yes, it was with with view:all interface.

**Comment by simonemainardi** [comment] 2021-03-05 14:06
can you arrange a remote teamviewer session with @MatteoBiscosi so he can debug?

**Comment by Syl4r-v** [comment] 2021-03-11 10:31
Actually, this happens also when view:all interface is disabled

**Comment by simonemainardi** [comment] 2021-03-11 18:21
can you arrange a remote teamviewer session with @MatteoBiscosi so he can debug?

**Comment by MatteoBiscosi** [comment] 2021-04-12 14:48
The issue should be fixed by @gabryon99 , if the problem is going to reappear please reopen the ticket

**Closed as completed by MatteoBiscosi** 2021-04-12 14:48 UTC
Labels: To Be Confirmed
