### ISSUE TITLE
all hosts report 47 years under seen since column

### ISSUE THREAD

**Issue by mAineAc-** [ntop/ntopng#926] opened 2017-01-14 21:02 UTC
All hosts, no matter when they showed up, report 47 years 25 days under the seen since column. 

v.2.5.170110 [Enterprise/Professional Edition]
GIT rev:   dev:be18732b91c6070fff3ec2bf5041757b7a531d8e:20170110
Pro rev:   r872
System Id: A413EC7B00040FB3
Built on:  Ubuntu 16.04.1 LTS

**Comment by ghost** [comment] 2017-01-14 21:08
possible duplicate of #873

**Comment by simonemainardi** [comment] 2017-01-14 21:24
@mAineAc- please, report ntopng configuration used

**Comment by mAineAc-** [comment] 2017-01-14 22:20
all I have in /etc/ntopng/ntopng.config this:
-G=/var/run/ntopng.pid
-i=tcp://127.0.0.1:5556

Is there something else you were looking for?

**Comment by simonemainardi** [comment] 2017-01-15 11:11
ok so my guess is that flows received from the nProbe don't contain first/last seen information and so they are set to zero.

is it possible to see nProbe configuration as well? If nprobe is configured to receive *flow from your devices ( --collector-port ) then you should make sure those devices export time information

**Comment by mAineAc-** [comment] 2017-01-15 13:35
nprobe config:

--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none

**Comment by simonemainardi** [comment] 2017-01-15 13:56
@mAineAc- send a pcap of traffic received on port 2055 for inspection

**Comment by mAineAc-** [comment] 2017-01-15 14:06
I figured it out. I had to add -V=9 in the nprobe config and it appears to be workinmg correctly. I am using netflow version 9.

**Comment by mAineAc-** [comment] 2017-01-15 14:23
To resolve the 47 years on the hosts 'last seen' column, when using Netflow V9 you need to add the flag -V=9 to the nprobe config file. 

Current nprobe config that works:

--zmq="tcp://*:5556"
--collector-port=2055
-n=none
-i=none
-V=9

**Comment by simonemainardi** [comment] 2017-01-15 14:23
I am not sure that is the solution. Flow version should be determined automatically from the incoming packet headers on port 2055.

Can you please try again with and without option V9?

**Comment by mAineAc-** [comment] 2017-01-15 14:31
![Uploading screen-of-interfaces.jpeg…]()
If I remove that option it goes back to showing 47 years for the hosts. Without that option I also have two interfaces. One shows no data, the other shows the data but with 47 years. I noticed that with that option everything on the live graphs seemed to refresh faster also.

**Comment by simonemainardi** [comment] 2017-01-15 14:34
Thanks for reporting.

Did you check @olliff suggestion

> possible duplicate of #873

?

What are the two interfaces you get?

**Comment by mAineAc-** [comment] 2017-01-15 14:35
I attached an image to my previous comment.

**Comment by simonemainardi** [comment] 2017-01-15 14:35
image is not visible please paste it from the github issue page

**Comment by mAineAc-** [comment] 2017-01-15 14:37
![image](https://cloud.githubusercontent.com/assets/8900504/21963283/27386d46-db06-11e6-8b90-7f36caf0e583.png)

**Comment by mAineAc-** [comment] 2017-01-15 14:38
When I use that option the only interface is the first one and everything is working as expected.

**Comment by mAineAc-** [comment] 2017-01-15 14:47
ok well, that doesn't make any sense to me. I re-added that option and it is not going back to just the one interface and the hosts still have 47 years.

**Comment by mAineAc-** [comment] 2017-01-15 14:50
![image](https://cloud.githubusercontent.com/assets/8900504/21963406/06152d82-db08-11e6-8448-b77af84f48cc.png)

Image showing the 47 years

**Comment by simonemainardi** [comment] 2017-01-15 16:43
@mAineAc- you have two interfaces because you enabled, from the "Network Interface" preferences, the dynamic creation of interfaces on the basis of the exporter address.

The fact that all the times are at zero can be a bug and I am investigating it.

**Comment by mAineAc-** [comment] 2017-01-15 16:53
@simonemainardi I have verified that the netflow packets do have the correct timestamp. I am using a cisco 2821 if that makes a difference.
> enabled, from the "Network Interface" preferences,

I wonder if that is where the issue is? I did't have the issue with that disabled. testing that now.

**Comment by mAineAc-** [comment] 2017-01-15 17:00
Yes if I disable that under network interface it does show normal timestamps. I selected the 'probe ip address' option.

**Comment by simonemainardi** [comment] 2017-01-15 17:02
we have made a fix for the issue "all hosts report 47 years under seen since column"

**Closed as completed** 2017-01-15 17:01 UTC

**Comment by mahescho** [comment] 2017-04-10 17:08
I've the same problem with "2.4.170215 - Pro Small Business Edition" on one of two interfaces which are both fed by NetFlow.

**Comment by simonemainardi** [comment] 2017-04-10 17:27
@mahescho problem is solved in version 2.5

**Comment by mahescho** [comment] 2017-04-10 17:48
Upgraded ... success: no traffic gets recorded :(
