### ISSUE TITLE
Traffic Report Page Doesn't Load

### ISSUE THREAD

**Issue by Gelob** [ntop/ntopng#1881] opened 2018-07-23 22:04 UTC
Trying to load traffic report page and I get the following error:

ntopng --version
v.3.5.180723    [Enterprise/Professional build]
GIT rev:        dev:594c0e4dc87f4f909093792ecb9869ff4f223c28:20180723
Pro rev:        r1753
Built on:       CentOS Linux release 7.5.1804 (Core)
System Id:      688F2ABE76056B01
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited
Validity:       Until Mon Jul 23 22:14:29 2018

HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close   Script "/usr/share/ntopng/scripts/lua/pro/report.lua" returned an error:
/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:85: bad argument #1 to 'ipairs' (table expected, got nil)

23/Jul/2018 22:04:09 [LuaEngine.cpp:8240] WARNING: Script failure [/usr/share/ntopng/scripts/lua/pro/report.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:85: bad argument #1 to 'ipairs'
(table expected, got nil)]

**Comment by dive76** [comment] 2018-07-24 11:43
Have the same issue on Ubuntu 18.04LTS, ntopng 3.5.180724 - Enterprise Edition
![2018-07-24 1](https://user-images.githubusercontent.com/41624349/43135980-c75fdb82-8f79-11e8-88d5-0f2953c48fd0.png)

**Comment by simonemainardi** [comment] 2018-07-25 10:22
hi, can you please check if the issue is still occurring also with the latest dev version?

**Comment by simonemainardi** [comment] 2018-07-25 11:14
can you also report any error/exception you may see in the logs?

**Comment by dive76** [comment] 2018-07-25 11:57
There is nothing in the log. This function stopped about last week.

**Comment by dive76** [comment] 2018-07-25 12:11
Fixed now.

**Comment by simonemainardi** [comment] 2018-07-25 12:27
thanks for reporting.

**Closed as completed by simonemainardi** 2018-07-25 12:27 UTC
