### ISSUE TITLE
Hosts Common Thresholds per Ntopng

### ISSUE THREAD

**Issue by zimbawe998** [ntop/ntopng#2573] opened 2019-05-10 09:39 UTC
It's better to move Hosts Common Thresholds settings under preference and not editable on every host.
You need to define only the delta from Main settings.

**Comment by simonemainardi** [comment] 2019-05-10 10:47
duplicate of https://github.com/ntop/ntopng/issues/2479

**Closed as completed by simonemainardi** 2019-05-10 10:47 UTC
