### ISSUE TITLE
Unable to see TOP sender data under interface 

### ISSUE THREAD

**Issue by adipadalwar** [ntop/ntopng#5693] opened 2021-07-19 17:42 UTC
![image](https://user-images.githubusercontent.com/87663746/126194052-1402afd7-9afc-4812-8148-80aecb773419.png)

**Comment by simonemainardi** [comment] 2021-07-22 15:44
Likely the interval is too tiny (see you have 5 minutes).

Try to enlarge a bit.

**Comment by simonemainardi** [comment] 2021-07-26 10:13
Duplicate of https://github.com/ntop/ntopng/issues/5691. Likely addressed in the pro part. Hold on a couple of hours, update to the latest 4.3 stable, and it will work.

**Closed as completed by simonemainardi** 2021-07-26 10:13 UTC
