### ISSUE TITLE
Implement custom protocols and categories

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#2034] opened 2018-09-17 14:24 UTC
Custom protocols are currently defined by hand with -p. This is not simple to handle as it pushes the user to go back to the console. It is requested to configure protocol configuration through the web interface, including the ability to define new categories. ntopng should use the new configuration as it is updated.

**Comment by simonemainardi** [comment] 2018-09-18 13:24
duplicate of #1974

**Closed as completed by simonemainardi** 2018-09-18 13:24 UTC
Labels: Enhancement
