### ISSUE TITLE
Change user perference not saving

### ISSUE THREAD

**Issue by amastelek** [ntop/ntopng#4980] opened 2021-01-28 09:00 UTC
I select an interface for a user and when I click Change user preference it does not save it for the user.

I'm on 4.2 stable.

**Comment by simonemainardi** [comment] 2021-01-28 15:44
attach screenshot as I cannot reproduce

**Comment by amastelek** [comment] 2021-01-29 06:48
I figured it out while taking the screenshot.  It fails to update when the slider for "Allow the user to download live traffic and pcap's" is on
Turning that off allows the change to save.  Its a netflow interface.

**Comment by MatteoBiscosi** [comment] 2021-02-04 11:39
Hi @amastelek, 
The issue should be fixed now, builds are in progress, bear with it for a couple of hours and update ntopng.
Let me know if everything is working fine after the update.

**Closed as completed** 2021-02-05 14:15 UTC
Labels: Low-Priority Bug, Priority Ticket
