### ISSUE TITLE
Add top level domain to exclusion list

### ISSUE THREAD

**Issue by MatteoBiscosi** [ntop/ntopng#6169] opened 2022-01-03 10:32 UTC
Add the possibility to exclude specific alert for a specific top level domain.
For example: Exclude all the 'No Data Exchanged' alerts for domain ending with 'microsoft.com'

**Comment by cardigliano** [comment] 2022-06-14 08:04
Duplicate of https://github.com/ntop/ntopng/issues/6634

**Closed as completed by cardigliano** 2022-06-14 08:04 UTC
Labels: Enhancement, Feature Request, Alerts
