### ISSUE TITLE
ntopng crashes every 5 minutes on Rasbian buster

### ISSUE THREAD

**Issue by LeoBolien** [ntop/ntopng#3715] opened 2020-04-08 10:04 UTC
Hello,
i run ntopng on an raspberry 4. So far so good.
When i setup ntopng to connect to a influxdb on another server everything works
as expected. The Problem is now that exactly every 5min ntopng chrashes:
Here the syslog entries:

```
ntopng[12817]: malloc(): mismatching next->prev_size (unsorted)
ntopng.service: Main process exited, code=killed, status=6/ABRT
```

ntopng restarts itself. Inside ntopng system history i see after restart:

`Started after anomalous termination (bug report) ntopng v.4.1.200330 (9629) [OS: Raspbian GNU/Linux 10 (buster)][pid: 23539][options: --http-port '0' --https-port '3010' ]
`

Any idea ?
I have a pro license, is an enterprice license needed for that feature ?
Thanks and regards

**Comment by LeoBolien** [comment] 2020-04-08 12:40
Sorry but in the meantime i have more infos.
I guess this error has nothing to do with influxdb.

My System is: raspberry PI 4 with OS raspbian buster
I reinstalled ntopng complete (apt-get purge ntopng).
Installed it new (apt-get install ntopng) 

my /etc/apt/sources.list looks like:

```
deb http://apt.ntop.org/buster_pi armhf/
deb http://apt.ntop.org/buster_pi all/
```
But if i than start ntopng by hand e.g.
`/usr/local/bin/ntopng /etc/ntopng/ntopng.conf`
it runs vor max 5 minutes and exactly at hh:00, hh:05, hh:10, hh:15, hh:20 etc.
it chrashes with error:
`malloc(): invalid next size (unsorted)`

Could it be that there is an internal script (plugin) that forces this error ?
In general if have no other problems with this raspberry pi 4 there only runs an nagios instance,
nothing else.

Thanks and regards Leo

**Comment by emanuele-f** [comment] 2020-04-08 12:49
Thank you for the information, trying to debug this.

**Comment by emanuele-f** [comment] 2020-04-08 13:12
what are the contents of your /etc/ntopng/ntopng.conf file?

**Comment by LeoBolien** [comment] 2020-04-08 13:22
> 
> 
> what are the contents of your /etc/ntopng/ntopng.conf file?
```
-G=/var/run/ntopng.pid
--http-port=0
--https-port=3010
```
i use https port 3010. I have installed certificates at
/usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
which works

**Comment by emanuele-f** [comment] 2020-04-08 13:29
Can you try to connect to the URL `/lua/test_alerts.lua` and see if the crash occurs?

**Comment by LeoBolien** [comment] 2020-04-08 13:36
> 
> 
> Can you try to connect to the URL `/lua/test_alerts.lua` and see if the crash occurs?

Hello,
i started at 15:31:24 again by
`/usr/local/bin/ntopng /etc/ntopng/ntopng.conf`
open browser with url:
`https://nagios.bolien.de:3010/lua/test_alerts.lua`
on the left side i see the menus but main page is white, nothing else.

now at exactly 15:35:00 error:
`malloc(): invalid next size (unsorted)`

hope this helps :-)

Thanks and regards Leo

**Comment by jackspeed84** [comment] 2020-04-08 13:58
I have the same problem on a Raspberry Pi 3B+ with Debian Buster. It appeared w/ ntopng 4.1 release from the 24th of march and is still there for the release of the 30th.

I already chatted w/ emanuele-f and simone from ntopng, but they couldn't reproduce it.

In my case, I did not see any malloc error, just the line 
`corrupted size vs. prev_size` in ntopng.log. 

To be honest, I did not recognize that it is happening exactly every five minutes, but it seems, you're right. 

Thx, 
jacks

**Comment by emanuele-f** [comment] 2020-04-08 13:58
Any chance for a teamviewer session on your machine to debug this? Please write at faranda@ntop.org

**Comment by LeoBolien** [comment] 2020-04-08 14:09
Hi,
in the meantime i did an self building of ntopng like described in:
https://www.ntop.org/get-started/download/
at the same raspberry PI 4

if i start now (installed in /usr/src/ntopng)
`/usr/src/ntopng/ntopng /etc/ntopng/ntopng.conf`
i do not have the problem.
okay my license (/etc/ntopng.license) do not work, can i use me license for this self build version or is this not possible ?

Sorry i do not have teamviewer installed, but if nothing else helps this is maybe a solution.

Can i do some debug stuff for you ?

regards Leo

**Comment by emanuele-f** [comment] 2020-04-08 14:14
So this probably means that the crash is linked with some of the pro features. If you manually build ntopng you can't use the pro/enterprise versions. We need to dig into the code of `/usr/share/ntopng/scripts/callbacks/interface/5min.lua` and its inner functions to understand where exactly it crashes, this is why I suggest the teamviewer/anydesk session, as @jackson-5 already tried to get a stack trace via gdb by the stack is corrupted so gdb won't help

**Comment by emanuele-f** [comment] 2020-04-08 16:43
@LeoBolien thank you for allowing me to troubleshoot this. The problem is related to the `ntop.snmpgetnext` function which, when called, makes ntopng crash. I can now reproduce the problem.  For a temporary workaround you can remove all the configured SNMP devices with `redis-cli del ntopng.prefs.snmp_devices`.

**Comment by LeoBolien** [comment] 2020-04-08 17:00
> 
> 
> @LeoBolien thank you for allowing me to troubleshoot this. The problem is related to the `ntop.snmpgetnext` function which, when called, makes ntopng crash. I can now reproduce the problem. For a temporary workaround you can remove all the configured SNMP devices with `redis-cli del ntopng.prefs.snmp_devices`.

Does this problem only exist in Raspberry 4 devices and / or OS raspbian buster ?
Anyway many thanks for your support. If needed we can try to check again on my system.

Regards Leo

**Comment by emanuele-f** [comment] 2020-04-09 09:33
The problem is not specific of the raspberry 4, however it seems like the ARM platform makes such errors visible. This should be addressed in 3f5bd04e7a335bd83d4c649df88dabf7af9808ca . A new package will be available in two hours. In order to test it, please run `redis-cli hset ntopng.prefs.snmp_devices 192.168.1.6 public` to add again the device I removed yesterday, then restart ntopng and wait the 5 minutes.

**Comment by LeoBolien** [comment] 2020-04-09 09:47
Hello @emanuele-f 
I will try as soon as the new packages available (by apt-get update; apt-get dist-upgrade)
Give feedback after.
regards Leo

**Comment by LeoBolien** [comment] 2020-04-09 11:17
Hello @emanuele-f 
installed new version ntopng Professional Edition v.4.1.200409 by using 
`apt-get dist-upgrade`
run:
`redis-cli hset ntopng.prefs.snmp_devices 192.168.1.6 public`

Then start again.
No chrashes anymore after 5min. Seems to work now.

Thanks you very much.
regards Leo

**Comment by emanuele-f** [comment] 2020-04-09 12:08
Great, thank you for your feedback and time!

**Closed as completed by emanuele-f** 2020-04-09 12:08 UTC

**Comment by jackspeed84** [comment] 2020-04-10 10:09
Thanks for fixing. Works here again as well. 
Thx, jacks
