### ISSUE TITLE
Info button not working

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#7740] opened 2023-08-07 13:08 UTC
**Environment**:
* OS name: [e.g. Ubuntu]

* OS version: [e.g. 18.04]
* Architecture: [e.g. amd64]
* ntopng version/revision: [ntopng Enterprise L v.5.7.230806 (Ubuntu 20.04.5 LTS) ]
**What happened**:
Hello ntop team!
In Alerts Explorer and Historical Flows the info button  / page is not working:
<img width="199" alt="Screenshot 2023-08-07 at 15 04 14" src="https://github.com/ntop/ntopng/assets/38549755/4a962921-0a19-4b70-b023-a47e42c8fe16">

It just opens a new page, but no content is displayed.

thank you.
**How did you reproduce it?**

**Debug Information**:

**Comment by martinscheu** [comment] 2023-08-07 13:18
seems to be browser related: firfox is working, brave not.

**Comment by cardigliano** [comment] 2023-08-09 13:27
Duplicate of #7742

**Closed as completed by cardigliano** 2023-08-09 13:27 UTC
