### ISSUE TITLE
Hourly queries failures with Clickhouse

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#6066] opened 2021-11-10 14:21 UTC
```
10/Nov/2021 15:00:01 [MySQLDB.cpp:867] Successfully connected to MySQL [default@127.0.0.1:9004] for interface stdin
10/Nov/2021 15:00:01 [MySQLDB.cpp:1015] ERROR: MySQL error: [Code: 62. DB::Exception: Syntax error: failed at position 1 ('VACUUM'): VACUUM. Expected one of: ALTER query, Query with output, ALTER PROFILE, RENAME DATABASE, SHOW PRIVILEGES query, TRUNCATE, KILL, KILL QUERY query, SELECT query, possibly with UNION, list of union elements, ALTER ROLE, SELECT subquery, DESCRIBE query, SELECT query, subquery, possibly with UNION, SHOW GRANTS, SHOW CREATE, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, WATCH, SHOW PROCESSLIST query, ALTER POLICY, ALTER USER, CREA][62][VACUUM]
10/Nov/2021 15:00:36 [MySQLDB.cpp:751] Disconnected from MySQL for interface stdin...
10/Nov/2021 15:00:36 [MySQLDB.cpp:844] Attempting to connect to MySQL for interface stdin...
10/Nov/2021 15:00:36 [MySQLDB.cpp:867] Successfully connected to MySQL [default@127.0.0.1:9004] for interface stdin
10/Nov/2021 15:00:36 [MySQLDB.cpp:1015] ERROR: MySQL error: [Code: 60. DB::Exception: Table ntopng.host_alerts doesn't exist. (UNKNOWN_TABLE) (version 21.10.2.15 (official build))][60][ SELECT COUNT(*) as num_alerts FROM `host_alerts` ]
```

**Comment by simonemainardi** [comment] 2021-11-11 11:18
Issue was due to a wrong initialization causing tables to be potentially created under a `default` database rather than the `ntopng` database.

**Comment by lucaderi** [comment] 2021-11-11 17:25
Unable to reproduce it, closing it for now

**Closed as completed by lucaderi** 2021-11-11 17:25 UTC
Labels: Ready to Test, Priority Ticket
