### ISSUE TITLE
Ntopng v3 stops collecting data and the dashboard stops responding

### ISSUE THREAD

**Issue by VC-IT** [ntop/ntopng#1316] opened 2017-06-14 20:51 UTC
Hello,

We upgraded ntop Business Pro to the latest version this morning and ever since that point the dashboard will stop responding every few minutes. If we restart, the dashboard will update for up to five minutes before stopping again. We do not see any errors generated. In addition, the webservice page will take 2-3 minutes to connect. There were no other changes made to the system beside the upgrade via apt.

I've also noticed that whenever it is experiencing issues I'll see negative values for the 'Actual Traffic' rate.

Versions:

> ii  apt-ntop-stable                    2.4-535                                    all          ntop stable apt package repository
ii  nbox                               2.4-535                                    all          Web management interface for ntop apps.
ii  ntopng                             3.0.170613-3044                            amd64        Web-based traffic monitoring.
ii  ntopng-data                        3.0.170613                                 all          Data files (geoip) for ntopng.
ii  pfring                             6.6.0-1268                                 amd64        PF_RING (http://www.ntop.org/pf_ring/) [6.6.0-stable:7714855899a375efd17a227bd62edea5559d8d73 (Tue Jun 13 17:52:18 2017 +0200)]

Log when manually run:
> sudo ntopng /etc/ntopng/ntopng.conf
14/Jun/2017 13:32:26 [Ntop.cpp:1359] Setting local networks to 172.16.0.0/12,10.0.0.0/8,192.168.100.0/24
14/Jun/2017 13:32:26 [Redis.cpp:109] Successfully connected to redis 127.0.0.1:6379@0
14/Jun/2017 13:32:26 [NtopPro.cpp:144] [LICENSE] Read license from Redis [92F072156968BE24D86A541522B397201522362084BEC1AF99]
14/Jun/2017 13:32:26 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface eth1...
14/Jun/2017 13:32:26 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface eth1
14/Jun/2017 13:32:26 [HostPools.cpp:65] Host Pools Available: 4
14/Jun/2017 13:32:26 [NetworkInterface.cpp:227] Executing ethtool -K eth1 gro off gso off tso off
14/Jun/2017 13:32:26 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.6.0 interface eth1...
14/Jun/2017 13:32:26 [Ntop.cpp:1464] Registered interface eth1 [id: 0]
14/Jun/2017 13:32:26 [main.cpp:250] PID stored in file /var/run/ntopng.pid
14/Jun/2017 13:32:26 [HTTPserver.cpp:760] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
14/Jun/2017 13:32:26 [Utils.cpp:371] User changed to nobody
14/Jun/2017 13:32:26 [HTTPserver.cpp:814] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
14/Jun/2017 13:32:26 [HTTPserver.cpp:817] HTTP server listening on port(s) 3000
14/Jun/2017 13:32:26 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface eth1...
14/Jun/2017 13:32:26 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface eth1
14/Jun/2017 13:32:26 [main.cpp:311] Working directory: /storage/ntopng
14/Jun/2017 13:32:26 [main.cpp:313] Scripts/HTML pages directory: /usr/share/ntopng
14/Jun/2017 13:32:26 [Ntop.cpp:307] Welcome to ntopng x86_64 v.3.0.170613 - (C) 1998-17 ntop.org
14/Jun/2017 13:32:26 [Ntop.cpp:312] Built on Ubuntu 16.04.2 LTS
14/Jun/2017 13:32:26 [PeriodicActivities.cpp:56] Started periodic activities loop...
14/Jun/2017 13:32:26 [NtopPro.cpp:273] [LICENSE] ntopng systemId: 50E7CDB976076B20
14/Jun/2017 13:32:26 [NtopPro.cpp:284] [LICENSE] ntopng license: 92F072156968BE24D86A541522B397201522362084BEC1AF99
14/Jun/2017 13:32:26 [NtopPro.cpp:306] [LICENSE] Maintenance is available until Thu Mar 29 15:21:24 2018 [288 days left]
14/Jun/2017 13:32:26 [Ntop.cpp:607] Adding fe80::225:90ff:fe93:730f/128 as IPv6 interface address for eth1
14/Jun/2017 13:32:26 [Ntop.cpp:616] Adding fe80::225:90ff:fe93:730f/64 as IPv6 local network for eth1
14/Jun/2017 13:32:26 [NetworkInterface.cpp:2045] Started packet polling on interface eth1 [id: 0]...
14/Jun/2017 13:32:27 [MySQLDB.cpp:626] Attempting to connect to MySQL for interface eth1...
14/Jun/2017 13:32:27 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface eth1
14/Jun/2017 13:50:42 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[199] ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.

Startup:
> -w=3000
-W=0
-m="172.16.0.0/12,10.0.0.0/8,192.168.100.0/24"
-d=/storage/ntopng
-G=/var/run/ntopng.pid
-F="mysqlstring"
-i=eth1
-q

The RRD error is new since the upgrade. I just noticed it after opening this.

**Comment by VC-IT** [comment] 2017-06-14 20:53
Kernel version:
Linux netflow 4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by emanuele-f** [comment] 2017-06-14 22:19
Hi, your local network segment (-m option) is huge, so you have a lot of local hosts, whose statistics are dumped to disk. The error you get into the console states that ntopng is not able to write all these stats 
in time. The heavy disk load is probably what causes the not responding web server.

Please disable the "Layer-7 Application" dump from the data retention preferences

**Comment by VC-IT** [comment] 2017-06-14 22:24
Hello Emanuele,

Thank you for your reply. Layer-7 Application was never enabled. iotop reports:

> Total DISK READ :       4.59 M/s | Total DISK WRITE :     394.55 K/s
Actual DISK READ:       4.59 M/s | Actual DISK WRITE:       6.73 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                            
 1693 be/4 nobody      3.47 M/s    0.00 B/s 58.52 %  1.83 % ntopng /etc/ntopng/ntopng.conf
   30 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.24 % [kswapd0]
 1775 be/4 nobody   1148.15 K/s  370.88 K/s 95.51 %  0.17 % ntopng /etc/ntopng/ntopng.conf
18916 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.03 % [kworker/u30:2]
 1770 be/4 nobody      0.00 B/s   23.67 K/s  0.00 %  0.00 % ntopng /etc/ntopng/ntopng.conf
 1304 be/4 redis       3.95 K/s    0.00 B/s  0.41 %  0.00 % redis-server 127.0.0.1:6379

Looks like ntop 3.0 increased memory usage. What would you recommend for reducing memory usage?

**Comment by stebbo63** [comment] 2017-06-15 04:26
I am now on .170613 and am having the same UI freezing issue.

**Comment by emanuele-f** [comment] 2017-06-15 08:42
@VC-IT does the ntopng footer green badge report a number of local hosts which is reasonable for your network? Please turn off any data retention setting and see if the gui bacomes responsive again.

**Comment by VC-IT** [comment] 2017-06-15 16:05
@emanuele-f 
Currently it shows over 36,000 IPs on our network which is almost x10 larger than our allocated IP space. Though the range is /12, we are only using small portions (mostly split into /24s). 

Additionally, when I progress through the pages it begins repeating the same addresses by page 9 and seems to pull up random results as I move through each page. I have it set to show 100 entries per page, but it's only showing 1 to 4 IPs.

**Comment by VC-IT** [comment] 2017-06-15 16:11
Here's page 7
![screen shot 2017-06-15 at 9 08 32 am](https://user-images.githubusercontent.com/29441496/27190821-908a767a-51aa-11e7-9170-fde83d1591e4.png)

Same IP on page9:
![screen shot 2017-06-15 at 9 10 27 am](https://user-images.githubusercontent.com/29441496/27190834-997b99e4-51aa-11e7-8988-bc3b184d96b2.png)

**Comment by VC-IT** [comment] 2017-06-15 21:31
Sorry, forgot to add, we turned off all the data retention yesterday. What we're seeing is an immense amount of reads while ntopng is running, even with mysql disabled. 

This is after restarting the server and ntopng. After 1 minute the disk trashing becomes intense and ntopng is no longer responsive. The webgui stops updating and then we see rrd errors in the logs.

> Total DISK READ :      25.85 M/s | Total DISK WRITE :    1148.41 K/s
Actual DISK READ:      26.13 M/s | Actual DISK WRITE:      22.01 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                              
14784 be/4 nobody   1564.96 K/s    0.00 B/s 10.42 % 15.05 % ntopng /etc/ntopng/ntopng.conf
14773 be/4 nobody    665.69 K/s    0.00 B/s  0.00 %  7.15 % ntopng /etc/ntopng/ntopng.conf
14776 be/4 nobody    330.90 K/s    0.00 B/s  0.00 %  4.70 % ntopng /etc/ntopng/ntopng.conf
14775 be/4 nobody    155.72 K/s    0.00 B/s  0.00 %  3.67 % ntopng /etc/ntopng/ntopng.conf
14774 be/4 nobody    190.75 K/s    0.00 B/s  0.03 %  2.93 % ntopng /etc/ntopng/ntopng.conf
14945 be/4 root        2.08 M/s    0.00 B/s  0.03 %  0.96 % python /usr/sbin/iotop
   30 be/4 root        0.00 B/s 1148.41 K/s  0.00 %  0.20 % [kswapd0]
 1327 be/4 redis     260.83 K/s    0.00 B/s  2.03 %  0.13 % redis-server 127.0.0.1:6379
14777 be/4 nobody     18.45 M/s    0.00 B/s 95.30 %  0.00 % ntopng /etc/ntopng/ntopng.conf

Here's the status a few minutes later:
>Total DISK READ :      10.32 M/s | Total DISK WRITE :      27.36 K/s
Actual DISK READ:      10.32 M/s | Actual DISK WRITE:       8.36 M/s

**Comment by simonemainardi** [comment] 2017-06-16 00:54
So it turned out that during the 5-minute statistics update, all the hosts were processed. Actually, the intended behaviour is to only process _local_ hosts. Fix is in 7332cc7c53afe7554e25bc944a6943b1804cc728 and new builds are in progress.

The above fix should solve the error
```
ERROR: Cannot complete local hosts RRD dump in 5 minutes. Please check your RRD configuration.
```

Can you please test and report the behaviour of the system using ntopng with the fix?

I still can't understand the issue reported with duplicated/missing hosts. I noticed you are using a filter, is that the 'local hosts only' filter? In addition, can you check the mac addresses reported in a seemingly duplicated ip address?

**Comment by VC-IT** [comment] 2017-06-16 01:39
@simonemainardi 
I now see the correct number of local hosts and iotop shows normal usage. The dashboard is running smoothly again. I'll update you tomorrow while we let it run. 

In answer to your question, that was from - http://server:3000/luahosts_stats.lua?mode=local
If I clicked on it, that was the strange result I was seeing.

**Comment by emanuele-f** [comment] 2017-06-16 07:22
@simonemainardi I think the host issue @VC-IT is experiencing is the same as issue #1315

**Comment by VC-IT** [comment] 2017-06-16 16:09
@simonemainardi 
After a few hours of operation we're once again experiencing the large number of local IPs and rrd failures:

> 15/Jun/2017 18:35:02 [MySQLDB.cpp:666] Successfully connected to MySQL [localhost:ntopng] for interface eth1
15/Jun/2017 19:26:53 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts R
RD dump in 5 minutes. Please check your RRD configuration.
15/Jun/2017 23:19:50 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts R
RD dump in 5 minutes. Please check your RRD configuration.
16/Jun/2017 00:45:41 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts R
RD dump in 5 minutes. Please check your RRD configuration.
16/Jun/2017 00:54:51 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts R
RD dump in 5 minutes. Please check your RRD configuration.
16/Jun/2017 06:40:20 [Lua.cpp:5500] [@/usr/share/ntopng/scripts/callbacks/5min.lua]:[156] ERROR: Cannot complete local hosts R
RD dump in 5 minutes. Please check your RRD configuration.
^C16/Jun/2017 08:58:51 [main.cpp:43] Shutting down...

At this point the dashboard is no longer updating. Restarting the service does not help. We also see > 71,000 local IPs reported on the dashboard. Our network only has ~ 700 active local ips.

**Comment by emanuele-f** [comment] 2017-06-18 23:23
@VC-IT prior to the 3.0 version a single host was identified by an IP address. Now, with the 3.0 version, an host is identified by an IP address *and* a MAC address. So, even if you have 700 active IP but each IP has multiple MAC address (e.g. multiple virtual machines running into a singel host), then you will see one host for each IP-MAC combination. Can this be your case?

**Comment by VC-IT** [comment] 2017-06-19 20:33
@emanuele-f  - We've updated to the latest ntopng and have had no issues so far.

**Comment by emanuele-f** [comment] 2017-06-20 07:58
Ok, I'm closing the issue for now, please reopen it if you still experience problems

**Closed as completed by emanuele-f** 2017-06-20 07:58 UTC
