### ISSUE TITLE
Missing required field 'alert_key' 

### ISSUE THREAD

**Issue by MaoPann** [ntop/ntopng#4561] opened 2020-10-10 13:30 UTC
Missing required field 'alert_key' in status_malicious_signature from /usr/share/ntopng/scripts/lua/modules/flow_status_definitions

**Comment by MaoPann** [comment] 2020-10-10 13:38
![image](https://user-images.githubusercontent.com/44804599/95656424-f3247f80-0b40-11eb-8276-a9b8a584f1bc.png)

**Comment by lucaderi** [comment] 2020-10-10 19:15
Duplicate of #4560

**Closed as completed by lucaderi** 2020-10-10 19:15 UTC

**Comment by MaoPann** [comment] 2020-10-10 23:04
Does the presence of this report affect the proper functioning of ntopng. Can it only be resolved by rebooting？
