### ISSUE TITLE
Alert filtering by name is not working

### ISSUE THREAD

**Issue by DGabri** [ntop/ntopng#8324] opened 2024-04-11 07:15 UTC
When filtering on this url: lua/alert_stats.lua?page=flow&epoch_begin=1712732952&epoch_end=1712819352&status=any&ifid=2&query_preset=&count=&severity=5%3Bgte&alert_id=53%3Beq

The filter is not working as expected

<img width="749" alt="Screenshot 2024-04-11 at 09 15 13" src="https://github.com/ntop/ntopng/assets/33870399/07a1304f-2b24-43ce-aeb8-4ddfaace3248">

**Comment by cardigliano** [comment] 2024-04-11 07:21
@DGabri I guess you are referring to the alert type which is matching items with "DGA Domain", could you check the "Additional Alerts" for those alert, it may be "Susp. DNS" is in the additional information

**Comment by cardigliano** [comment] 2024-04-17 08:23
Duplicate of https://github.com/ntop/ntopng/issues/8256

**Closed as completed** 2024-04-17 08:22 UTC
Labels: Priority Ticket, Alerts
