### ISSUE TITLE
Ntopng script failure

### ISSUE THREAD

**Issue by HH62** [ntop/ntopng#3193] opened 2020-01-06 11:55 UTC
Hi,

i'm getting this ntopng error regularly:

[LuaEngine.cpp:11750] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/discover.lua][attempt to index a function value]

Any ideas?
Ntopng version is 3.9.200103 (8545) - Professional Edition running under Ubuntu 18.04.3 LTS.

Greetings
Hendrik

**Comment by simonemainardi** [comment] 2020-01-07 08:26
Do you have periodic discovery enabled? Does this error occur every time the discovery runs?

**Comment by HH62** [comment] 2020-01-08 10:25
Network discovery is enabled and set to 15 min. The error occurs once, thereafter the data collection is terminated, Ntopng still running.

**Comment by simonemainardi** [comment] 2020-01-09 08:38
What do you mean with data collection is terminated? The discovery is terminated?

**Comment by simonemainardi** [comment] 2020-01-09 09:09
however, I can't reproduce on 

```
simone@ubuntu18:~$ ntopng --version
v.3.9.200109	[Enterprise/Professional build]
```

can you please update to the latest version and see if it is still occurring?

**Comment by cardigliano** [comment] 2020-01-14 12:04
@HH62 any update on this? Did you try with latest version?

**Comment by HH62** [comment] 2020-01-14 12:59
Yes, I did and I deactivated the discovery process. Running stable for 24 h so far, but I am still observing. I will keep you informed.

**Comment by cardigliano** [comment] 2020-01-14 13:47
@HH62 you experienced the issue with discovery enabled right? Thus you are not under the same conditions now..

**Comment by HH62** [comment] 2020-01-16 11:39
Yes that's true. But the interface is connected to a Port Mirror and I discovered in the preferences that it is not possible to turn Network Discovery on under such circumstances.
Ntopng is running stable now for 3 days without error.

**Comment by cardigliano** [comment] 2020-01-17 16:07
Ok got it. Let's close this for now, please reopen it if you are able te reproduce it again. Thank you.

**Closed as completed by cardigliano** 2020-01-17 16:07 UTC
