### ISSUE TITLE
Speedtest from NtopNG GUI does not match command line. (4.5X off)

### ISSUE THREAD

**Issue by jaytgagne** [ntop/ntopng#7410] opened 2023-04-18 17:30 UTC
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: MacBook (x86)
* ntopng version/revision: ntopng Community v.5.7.230414 rev.20110 (Ubuntu 22.04.2 LTS)

Output of Speedtest is way off from GUI to Command Line.

![image](https://user-images.githubusercontent.com/68092158/232856665-750c11a1-f587-4d62-a837-838ddafff6f4.png)

     Download:   939.17 Mbps (data used: 1.2 GB)
                123.66 ms   (jitter: 37.73ms, low: 44.86ms, high: 190.10ms)
      Upload:   466.01 Mbps (data used: 641.2 MB)
                 45.06 ms   (jitter: 0.79ms, low: 44.08ms, high: 51.11ms)
 Packet Loss:     0.0%

GUI has never gone above 200Mbs and command line is always over 900Mbs.

**Comment by MatteoBiscosi** [comment] 2023-04-19 10:00
Hi @jaytgagne could you please share the Speedtest command you are running from the command line (so i can simulate a couple of tests)

**Comment by jaytgagne** [comment] 2023-04-19 10:04
It's just a straight speedtest-cli with no options, so it is whatever the defaults are (I assumed that was what ntop was doing).

jgagne@drk-1:~$ speedtest-cli

**Comment by MatteoBiscosi** [comment] 2023-04-26 16:25
Hi @jaytgagne i'm trying to investigate your issue but i'm currently unable to reproduce.
If you zoom-in in a specific peak reported in the timeseries, which is the value?

**Comment by jaytgagne** [comment] 2023-04-26 17:30
![image](https://user-images.githubusercontent.com/68092158/234655323-8b4510a4-96ed-4fa6-b00e-acc4a56fa94c.png)

This is a capture of the most recent test from the GUI. It reports a speed of 184.79Mbps. Running speedtest-cli command a few seconds later returned a results of 914.36Mbps. That is fairly consisten all the time. The GUI reports 200-300 and the command line reports 800-950. The command line is more accurate.

**Comment by MatteoBiscosi** [comment] 2023-05-31 10:31
Hi @jaytgagne sorry for the delay. The issue should be partially fixed with the latest version, but not totally, and we are planning to let it like it is currently.
The reason is the following: we are currently using the same tool you used on your shell, however the tool from bash uses 10 threads to get the right speedtest results. Being a lot of threads (and so of resources), we decided to reduce the number to 1, meaning a less accurate data.
Now we increased the number of threads to 3, meaning that the speedtest is going to be more accurate then before (however not accurate as the one from shell).

**Closed as completed by MatteoBiscosi** 2023-05-31 10:31 UTC
Labels: To Be Confirmed
