### ISSUE TITLE
Some SNMP Interfaces are Missing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8369] opened 2024-04-30 08:39 UTC
Furthermore, note that some interfaces have empty names

<img width="1477" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/baf60a08-fedc-4734-83a0-1c2b69600f34">

You can reproduce this on hsol

**Comment by MatteoBiscosi** [comment] 2024-05-14 09:50
The issue is now fixed

**Closed as completed by MatteoBiscosi** 2024-05-14 09:50 UTC
Labels: In Progress
