### ISSUE TITLE
Last Day View charts start showing nonsensically small values after some time

### ISSUE THREAD

**Issue by qm2k** [ntop/ntopng#1402] opened 2017-08-14 14:56 UTC
Here's an example:
![1](https://user-images.githubusercontent.com/13719792/29277059-3ff60a64-8119-11e7-9f9a-2914ba18e6e5.png)
It looks like all traffic stopped after approximately 15:25.

However, if I refresh the page I see real picture:
![2](https://user-images.githubusercontent.com/13719792/29277099-669ea9d2-8119-11e7-90c6-99bdd1aa98be.png)

Unfortunately, refreshing the page also clears realtime traffic charts (upper two, not shown), therefore it is not good even as workaround.

**Comment by qm2k** [comment] 2017-08-23 09:45
Additional information: looks like this "some time" is the page refresh. I.e. historical values at the page refresh time are always drawn correctly, but everything that appear after that moment show downscaled.

**Comment by emanuele-f** [comment] 2017-08-23 14:44
@simonemainardi here is more information:

- The chart actually holds a day of data, while only the last hour is actually visualized.
- Graph is updated manually each 2 minutes, whereas the graph resolution should be 5 minutes. See `dashboard_top_applications.lua:216`
- Data points increase over time before reaching a stable length because of the two points above (inspect `topapps_lastday_data[0].values.length` for details), which increases memory usage

I think the correct way of updating the graph is to reload it every 5 minutes (thus avoiding pushing new javascript values to the existing graph) and to limit its range to the last hour.

**Comment by simonemainardi** [comment] 2017-08-28 17:10
Fixed. Thanks for reporting.

A new release will be built overnight CEST.

**Comment by qm2k** [comment] 2017-08-30 08:32
Top Application Traffic does not seem fixed, and Network Interfaces (both Last Day View and Realtime Traffic) fail to update at all. Tried different browsers, clearing cache and offline data. Did *not* try to clear databases (running with MySQL). v.3.1.170830.
![screenshot from 2017-08-30 11 26 25 cropped](https://user-images.githubusercontent.com/13719792/29862886-8d42ab38-8d76-11e7-9611-a70aa8ef3dd6.png)

**Comment by simonemainardi** [comment] 2017-08-31 09:03
Issue is now fixed also for top applications.

However, everything updates properly here (tested both with safari and chrome). Note that last day charts refresh once every 2 minutes and not every 3 seconds as the realtime charts.

Please, try to use the browser inspector to see if there are any errors on your side.

**Comment by qm2k** [comment] 2017-08-31 09:25
There're indeed errors in the Chromium console (still on v.3.1.170830):
```
dashboard.lua:3217 TypeError: Cannot read property 'values' of undefined
    at Number.<anonymous> (dashboard.lua:3195)
    at Function.each (jquery.js:368)
    at Object.success (dashboard.lua:3188)
    at fire (jquery.js:3317)
    at Object.fireWith [as resolveWith] (jquery.js:3447)
    at done (jquery.js:9272)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)
dashboard.lua:3195 Uncaught TypeError: Cannot read property 'values' of undefined
    at Number.<anonymous> (dashboard.lua:3195)
    at Function.each (jquery.js:368)
    at Object.success (dashboard.lua:3188)
    at fire (jquery.js:3317)
    at Object.fireWith [as resolveWith] (jquery.js:3447)
    at done (jquery.js:9272)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)
```

Interestingly, first update is successful (one bar is always drawn on `Network Interfaces: Realtime Traffic`), the error only appears on second and repeats from there on.

**Comment by simonemainardi** [comment] 2017-08-31 09:30
Can you follow the hyperlinks on the stacktrace and jump to the source code? Understanding the exact point in the lua or js file that causes the exception will be very helpful.

**Comment by qm2k** [comment] 2017-08-31 14:00
3195 is `iface_lastday_data.values.push([ epoch, num_bytes/epoch_diff ]);`, 3217 is `console.log(e);` in the catch block in the end.
```
/* *********************************** */

var chart_ifaces_lastday;

nv.addGraph(function() {
     chart_ifaces_lastday = nv.models.stackedAreaChart()
     .options({
	 transitionDuration: 10, duration: 10, /* Make sure the graph refreshes quickly */
	 margin: {left: 80, right: 30, bottom: 20 },
	 x: function(d,i) { return i },
	              showXAxis: true,
	              showYAxis: true,
	              transitionDuration: 0
	    })
	 .x(function(d) { return d[0] }).showControls(false)
         .y(function(d) { return d[1] }).showControls(false);

       chart_ifaces_lastday.xAxis.tickFormat(function(d) { return d3.time.format("%H:%M:%S")(new Date(d*1000)) });
       chart_ifaces_lastday.yAxis.tickFormat(function(d) { return fbits(d*8); });

       d3.select('#chart_ifaces_lastday').datum(ifaces_lastday_data).call(chart_ifaces_lastday);
       nv.utils.windowResize(chart_ifaces_lastday.update);

       return chart_ifaces_lastday;
});

var ifaces_begin_epoch_update = 0;
var ifaces_update_vals = { };
var ifaces_bytes = { };

setInterval(function() {
    $.ajax({
      type: 'GET',
	  url: '/lua/network_load.lua',
	  data: { iffilter: "all" },
          error: function(content) { console.log(content);  },
	  success: function(rsp) {
          var i;
	  var epoch;

	  try {
	    epoch = 0;
            i = 0;

	    $.each(rsp, function(_i, n) {
              if(n.is_view) return true;  // continue to the next row in rsp
              var if_name = n.ifname;

	      if(epoch == 0) epoch = n.epoch;
              if(!ifaces_update_vals[if_name]) ifaces_update_vals[if_name] = 0;

              if((!if_name.startsWith("as0")) && (!if_name.startsWith("vnet"))) {

	      if(ifaces_last_epoch > 0) {
                 var diff;

                 var epoch_diff;
                 var last_val = 0;

                 if(ifaces_bytes[if_name]) { last_val = ifaces_bytes[if_name]; }
		 epoch_diff = n.epoch - ifaces_last_epoch;	
		 if(epoch_diff == 0) { epoch_diff = 1; }

		 diff = (n.bytes - last_val) / epoch_diff;
                 diff = Math.max(0, diff);  // prevent <= values

                 if(n.remote_bps > 0) { /* This is a collector interface */
                   diff = Math.max(n.remote_bps, 0);
                   diff = Math.min(diff, n.speed * 1e6);
                   diff /= 8; /* To Bytes */
                 } else {
                   /* Do not exceed interface speed anyway */
                   diff = Math.min(diff, (n.speed / 8 * 1e6));
                 }

		 ifaces_realtime_data[i].values.push([ epoch, diff ]);

                 /* Re-integrate the diff with the time to provide last-day-view meaningful values */
		 ifaces_update_vals[if_name] += diff * epoch_diff;
	      }

              n.bytes = Math.max(0, n.bytes);
              ifaces_bytes[if_name] = n.bytes;
	      if (ifaces_realtime_data[i].values.length > 60) {
		 ifaces_realtime_data[i].values.shift();
	      }

	      i = i + 1;
	     }
	    }); /* each */

	    ifaces_last_epoch = epoch;
	    if(ifaces_begin_epoch_update == 0) {
	       ifaces_begin_epoch_update = epoch;
	    }

	    /* Update every 2 mins (120 seconds) */
	    var update_frequency = 120;
	    if((epoch - ifaces_begin_epoch_update) >= update_frequency) {

	       var epoch_diff = epoch - ifaces_begin_epoch_update;

	       $.each(ifaces_update_vals, function(if_name, num_bytes) {
		 var first_epoch, diff_epoch;

		 if (num_bytes < 0) { num_bytes = 0; }

		 var iface_lastday_data = ifaces_lastday_data.find(function(el){return el.key == if_name});

		 iface_lastday_data.values.push([ epoch, num_bytes/epoch_diff ]);
		 ifaces_update_vals[if_name] = 0;

		 while(true) {
		    first_epoch = iface_lastday_data.values[0][0];
		    diff_epoch = epoch - first_epoch;

		    if(diff_epoch > 86400)
		       iface_lastday_data.values.shift();
		    else
		       break;
		  } /* while */

	       });

	       ifaces_begin_epoch_update = epoch;
	       chart_ifaces_lastday.update();
	       /* console.log(epoch); */
	    }

	    chart_ifaces_realtime.update();
	  } catch(e) {
	     console.log(e);
	     throw e;
	  }
	}
      });
  }, 60 * 1000);
```

**Comment by simonemainardi** [comment] 2017-09-01 10:37
Thanks for submitting this info.

I tried on several installations and still can't reproduce.

Anyway, from the evidence provided I can see that `iface_lastday_data` is undefined. This implies that find() returned undefined here:

```
var iface_lastday_data = ifaces_lastday_data.find(function(el){return el.key == if_name});
```

Can you place a breakpoint in the console debugger right at that line? Check the contents of `ifaces_lastday_data` they must contain an element for every interface defined and that element must have a `key` equal to the interface name...

I suspect that there's at least one interface that doesn't have the corresponding entry in the array...

By the way, try to force the reload of all the javascript with CTRL+SHIFT+R

**Comment by qm2k** [comment] 2017-09-01 14:16
Did as you asked, found the problem. I assigned all my interfaces some names, so `key` doesn't equal `ifname` in `ifaces_lastday_data`:
```
> ifaces_lastday_data[0]
< {key: "ASA", ifname: "tcp://127.0.0.1:5556", area: true, values: Array(150), seriesIndex: 0, …}
> if_name
< "tcp://127.0.0.1:5556"
```
Thus condition `el.key == if_name` in `find` always fails. Quick local fix would probably be changing condition to `el.ifname == if_name` .

**Comment by simonemainardi** [comment] 2017-09-05 08:49
thanks for reporting, issue is fixed and a new build will be available in the next couple of hours.

**Closed as completed by simonemainardi** 2017-09-05 08:49 UTC

**Comment by qm2k** [comment] 2017-09-06 15:52
Looks fixed in v.3.1.170905
