### ISSUE TITLE
MySQL Dropping flows

### ISSUE THREAD

**Issue by henriqueps** [ntop/ntopng#830] opened 2016-11-21 12:47 UTC
In Mysql Flows Export Statistics, it's showing a bunch of dropped flows.
Is there any particular configuration to do in mysql to avoid this?
![droppedflows](https://cloud.githubusercontent.com/assets/23039111/20483158/bdce5ebe-afd7-11e6-88da-57d3fb8333ee.jpg)

**Comment by simonemainardi** [comment] 2016-11-21 19:08
duplicate of https://github.com/ntop/ntopng/issues/796

ntopng stores MySQL tables as MyISAM as it is faster in non-transactional environments such as that of the flows.

MySQL MyISAM parameters you should tune are the following:
```
key_buffer_size, key_cache_age_threshold, key_cache_block_size, key_cache_division_limit 


max_allowed_packet, max_connections, max_delayed_threads


myisam_max_sort_file_size , myisam_mmap_size, myisam_sort_buffer_size
```

There's not a single recipe. You should try them on your hardware and find a proper combination. Please feel free to report once done. Thank you.

**Closed as completed by simonemainardi** 2016-11-21 19:08 UTC
Labels: Duplicate

**Comment by henriqueps** [comment] 2016-11-21 19:39
@simonemainardi Thanks.
