### ISSUE TITLE
ntopng 5.3.220416 segfault on OPNsense 22.1.6

### ISSUE THREAD

**Issue by Batnun** [ntop/ntopng#6513] opened 2022-04-16 10:10 UTC
Hi,

I've tried to install ntopng enterprise edition on my OPNsense firewall, but after the installation it just refuses to run.

I've followed the instructions on the ntopng website:
https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html

added the ntop repository 
install os-ntopng-enterprise and os-redis

Redis service started successfully
ntopng just don't start

I've performed the following steps trying to resolve the problem:

Removed both os-ntopng-enterprise and os-redis
Removed the following directories and files:
/etc/rc.conf.d/redis
/var/mail/redis
/var/log/redis
/etc/rc.conf.d/ntopng
/usr/local/etc/ntopng
/var/mail/ntopng
/var/run/ntopng
/var/db/ntopng

Reboot the firewall and tried to install again, but no luck

OS: OPNsense 22.1.6 (latest)
ntopng version: 5.3.220416 (latest)
redis version: 6.2.6

Any ideas? I can't find anything in the logs (or maybe I don't know where to look?)

**Comment by Batnun** [comment] 2022-04-16 10:17
I should add that the ntopng version coming from the OPNsense repository (slightly older version) works as expected...

**Comment by lucaderi** [comment] 2022-04-17 16:58
Do you have /usr/local/etc/ntopng/ntopng.conf ? If not this is the problem. If yes please start from a shell
/usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf and report (as text) the whole startup log.

**Comment by Batnun** [comment] 2022-04-18 09:42
root@opnsense:~ # cat /usr/local/etc/ntopng/ntopng.conf
-i=igb2
-i=igb1
-i=igb0
-w=0
-W=3000
-n=1
--community=
-d=/var/db/ntopng-enterprise

root@opnsense:~ # /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf
18/Apr/2022 10:37:50 [Redis.cpp:156] Successfully connected to redis 127.0.0.1@0
18/Apr/2022 10:37:50 [Redis.cpp:156] Successfully connected to redis 127.0.0.1@0
18/Apr/2022 10:37:50 [PcapInterface.cpp:93] Reading packets from igb2 [id: 0]
18/Apr/2022 10:37:50 [Ntop.cpp:2572] Registered interface DMZ [id: 0]
18/Apr/2022 10:37:50 [PcapInterface.cpp:93] Reading packets from igb1 [id: 1]
18/Apr/2022 10:37:50 [Ntop.cpp:2572] Registered interface LAN [id: 1]
18/Apr/2022 10:37:50 [PcapInterface.cpp:93] Reading packets from igb0 [id: 2]
18/Apr/2022 10:37:50 [Ntop.cpp:2572] Registered interface WAN [id: 2]
18/Apr/2022 10:37:50 [main.cpp:337] PID stored in file /var/run/ntopng.pid
18/Apr/2022 10:37:50 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/local/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
18/Apr/2022 10:37:50 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/local/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
18/Apr/2022 10:37:50 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
18/Apr/2022 10:37:50 [HTTPserver.cpp:1684] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
18/Apr/2022 10:37:50 [HTTPserver.cpp:1693] HTTPS server listening on 3000
18/Apr/2022 10:37:50 [Utils.cpp:784] User changed to ntopng
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface DMZ [id: 0]...
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface DMZ [id: 0]...
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface LAN [id: 1]...
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface LAN [id: 1]...
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface WAN [id: 2]...
18/Apr/2022 10:37:50 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface WAN [id: 2]...
18/Apr/2022 10:37:50 [main.cpp:407] Working directory: /var/db/ntopng-enterprise
18/Apr/2022 10:37:50 [main.cpp:409] Scripts/HTML pages directory: /usr/local/share/ntopng
18/Apr/2022 10:37:50 [Ntop.cpp:457] Welcome to ntopng amd64 v.5.3.220418 - (C) 1998-22 ntop.org
18/Apr/2022 10:37:50 [Ntop.cpp:467] Built on FreeBSD 13.0
18/Apr/2022 10:37:50 [Ntop.cpp:871] Adding 141.133.57.154/32 as IPv4 interface address for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:871] Adding 141.133.57.155/32 as IPv4 interface address for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:871] Adding 141.133.57.156/32 as IPv4 interface address for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
18/Apr/2022 10:37:50 [Ntop.cpp:871] Adding 10.10.10.1/32 as IPv4 interface address for igb1
18/Apr/2022 10:37:50 [Ntop.cpp:880] Adding 10.10.10.0/24 as IPv4 local network for igb1
18/Apr/2022 10:37:50 [Ntop.cpp:871] Adding 10.10.50.1/32 as IPv4 interface address for igb2
18/Apr/2022 10:37:50 [Ntop.cpp:880] Adding 10.10.50.0/24 as IPv4 local network for igb2
18/Apr/2022 10:37:50 [PeriodicActivities.cpp:109] Started periodic activities loop...
Bus error

root@opnsense:~ #

**Comment by init098** [comment] 2022-04-18 15:25
Hi, I have the same problem, os-ntopng-enterprise 5.3.220418 and opnsense 22.1.6. The log is similar to the report, only in my case it gives a segfault

```
18/Apr/2022 11:22:45 [PeriodicActivities.cpp:109] Started periodic activities loop...
Segmentation fault
```

**Comment by Batnun** [comment] 2022-04-18 16:14
> Hi, I have the same problem, os-ntopng-enterprise 5.3.220418 and opnsense 22.1.6. The log is similar to the report, only in my case it gives a segfault


Hi, which hardware are you using for OPNsense? Mime is running on AMD EPYC 3201 CPU and I thought that maybe someone compiled it with a specific optimizations for Intel CPUs...

**Comment by init098** [comment] 2022-04-18 17:01
It is a virtual machine over KVM, the configuration is passing all the characteristics of the CPU, in this case it is an Intel(R) Core(TM) i5-8265U.

I had been using ntopng for several months without problems, but apparently an update to opnsense or ntopng itself broke the package.

**Comment by ToqQrrl** [comment] 2022-04-18 21:08
Hi guys… the problem seems to have started (gradually) starting with ntopng version 5.3.220412 on OPNsense 22.1.5 / 22.1.6

And while this DEV version of ntopng (5.3.2204xx) doesn’t work … the crippled version that ships with OPNsense … ntopng version 5.2.2203xx (from a stable branch) still works.

But not all OPNsense boxes on 22.1.6 have this problem with the DEV version (5.3.2204xx) … it seems to stop working with time.

Execution stops here as well —-> [PeriodicActivities.cpp:109] Started periodic activities loop...

It would be interesting to test a 5.2.2204xx version from a stable branch (if it existed) for OPNsense boxes

**Comment by Batnun** [comment] 2022-04-19 08:22
Still the same with version 5.3.220419 :(

**Comment by cardigliano** [comment] 2022-04-19 10:03
We are trying to reproduce this in our lab, also on VMs, using ntopng 5.3.220415 on OPNsense 22.1.6, with no success so far (it's working with no segfault or bus errors). We used a configuration file similar to the one provided by @Batnun 
Did you try flushing redis? (redis-cli flushall)

**Comment by Batnun** [comment] 2022-04-19 10:11
I just tried to flush redis, but still no luck. I'm now getting the "Segmentation fault" error:

root@opnsense:~ # redis-cli flushall
OK
root@opnsense:~ # /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf
19/Apr/2022 11:07:43 [Redis.cpp:156] Successfully connected to redis 127.0.0.1@0
19/Apr/2022 11:07:43 [Redis.cpp:156] Successfully connected to redis 127.0.0.1@0
19/Apr/2022 11:07:43 [PcapInterface.cpp:93] Reading packets from igb2 [id: 0]
19/Apr/2022 11:07:43 [Ntop.cpp:2572] Registered interface DMZ [id: 0]
19/Apr/2022 11:07:43 [PcapInterface.cpp:93] Reading packets from igb1 [id: 1]
19/Apr/2022 11:07:43 [Ntop.cpp:2572] Registered interface LAN [id: 1]
19/Apr/2022 11:07:44 [PcapInterface.cpp:93] Reading packets from igb0 [id: 2]
19/Apr/2022 11:07:44 [Ntop.cpp:2572] Registered interface WAN [id: 2]
19/Apr/2022 11:07:44 [main.cpp:337] PID stored in file /var/run/ntopng.pid
19/Apr/2022 11:07:44 [Geolocation.cpp:149] Loaded database dbip-city-lite.mmdb [/usr/local/share/ntopng/httpdocs/geoip//dbip-city-lite.mmdb][ip_version: 6]
19/Apr/2022 11:07:44 [Geolocation.cpp:149] Loaded database dbip-asn-lite.mmdb [/usr/local/share/ntopng/httpdocs/geoip//dbip-asn-lite.mmdb][ip_version: 6]
19/Apr/2022 11:07:44 [Geolocation.cpp:95] Using geolocation provided by DB-IP (https://db-ip.com)
19/Apr/2022 11:07:44 [HTTPserver.cpp:1684] Web server dirs [/usr/local/share/ntopng/httpdocs][/usr/local/share/ntopng/scripts]
19/Apr/2022 11:07:44 [HTTPserver.cpp:1693] HTTPS server listening on 3000
19/Apr/2022 11:07:44 [Utils.cpp:784] User changed to ntopng
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface DMZ [id: 0]...
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface DMZ [id: 0]...
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface LAN [id: 1]...
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface LAN [id: 1]...
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3033] Started flow user script hooks loop on interface WAN [id: 2]...
19/Apr/2022 11:07:44 [NetworkInterface.cpp:3070] Started host user script hooks loop on interface WAN [id: 2]...
19/Apr/2022 11:07:44 [main.cpp:407] Working directory: /var/db/ntopng-enterprise
19/Apr/2022 11:07:44 [main.cpp:409] Scripts/HTML pages directory: /usr/local/share/ntopng
19/Apr/2022 11:07:44 [Ntop.cpp:457] Welcome to ntopng amd64 v.5.3.220419 - (C) 1998-22 ntop.org
19/Apr/2022 11:07:44 [Ntop.cpp:467] Built on FreeBSD 13.0
19/Apr/2022 11:07:44 [Ntop.cpp:871] Adding 141.133.57.154/32 as IPv4 interface address for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:871] Adding 141.133.57.155/32 as IPv4 interface address for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:871] Adding 141.133.57.156/32 as IPv4 interface address for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:880] Adding 141.133.57.152/29 as IPv4 local network for igb0
19/Apr/2022 11:07:44 [Ntop.cpp:871] Adding 10.10.10.1/32 as IPv4 interface address for igb1
19/Apr/2022 11:07:44 [Ntop.cpp:880] Adding 10.10.10.0/24 as IPv4 local network for igb1
19/Apr/2022 11:07:44 [Ntop.cpp:871] Adding 10.10.50.1/32 as IPv4 interface address for igb2
19/Apr/2022 11:07:44 [Ntop.cpp:880] Adding 10.10.50.0/24 as IPv4 local network for igb2
19/Apr/2022 11:07:44 [PeriodicActivities.cpp:109] Started periodic activities loop...
**Segmentation fault**
root@opnsense:~ #

**Comment by Batnun** [comment] 2022-04-19 10:21
Searching "Segmentation fault" in Google I'm getting the impressions that is something to do with how ntopng was compiled. Is something changed recently with the compilation process, like a different compiler or C/C++ library? (I'm not a developer)

**Comment by init098** [comment] 2022-04-19 13:11
@cardigliano Could the output of the **truss /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf** command help?

**Comment by cardigliano** [comment] 2022-04-19 13:18
@init098 not sure it helps, but worth checking it..
Is anyone able to provide ssh access to a system affected by this? That would help debugging

**Comment by Batnun** [comment] 2022-04-19 18:17
Attached is the output of **truss /usr/local/bin/ntopng /usr/local/etc/ntopng/ntopng.conf**
[truss_ntopng.txt](https://github.com/ntop/ntopng/files/8515533/truss_ntopng.txt)

**Comment by init098** [comment] 2022-04-20 02:56
@cardigliano I can't give you access, but if you tell me what to look at, I can send you the information.

**Comment by Batnun** [comment] 2022-04-21 19:06
Working again for me with version 5.3.220421 😎

**Comment by ToqQrrl** [comment] 2022-04-21 19:21
I also confirm that the latest DEV release 5.3.220421 works on OPNsense 22.1.6

**Comment by init098** [comment] 2022-04-21 19:30
In my case, it still doesn't work and gives the message "bus error" and the process crashes. How can I install the DEV version? I currently have version 5.3.220421

**Comment by ToqQrrl** [comment] 2022-04-21 22:29
Hello …

5.3.xxyyzz is the DEV version 
5.2.xxyyzz would be the STABLE version if it existed on OPNsense/PFSense

**Comment by cardigliano** [comment] 2022-04-22 10:03
@Batnun thank you for the truss output, but it didn't help. 
In the meantime I tried on different platforms but I was not able to reproduce the issue so far, using the same OPNsense version, with latest ntopng. I will build a binary with debug symbols to provide you. 
If some of you can run it, please drop an email to cardigliano at ntop.org

**Comment by ToqQrrl** [comment] 2022-04-27 03:20
Alfredo ... I have unfortunately updated from version 5.3.220421 to 5.3.220426 and it is not working anymore ... same problem came back

ntopng stops executing after this ... just like before 

[PeriodicActivities.cpp:109] Started periodic activities loop...

We would really need to have access to the stable 5.2.22xxyy branch on OPNsense/PFsense OS platform 

It's is not viable having a "firewall production box" depend on the DEV version of ntopng.

**Comment by cardigliano** [comment] 2022-04-27 07:17
@ToqQrrl we are working on this, we will release a stable version for FreeBSD-based platform on the next stable release, please note FreeBSD support has been introduced a few months ago thus this is taking a bit due to the release cycle.

**Comment by Batnun** [comment] 2022-04-28 02:14
I can also confirm it stops working again for me, after upgrading to version 5.3.220428 ☹️

**Comment by cardigliano** [comment] 2022-04-28 07:45
@Batnun we will get access to a box affected by this soon, where we can debug this, I will come back soon

**Comment by cardigliano** [comment] 2022-04-29 07:43
@Batnun we pushed a fix that was causing a segfault on OPNsense, please update and let us know. Thank you.

**Comment by Batnun** [comment] 2022-04-29 08:50
@cardigliano  Thanks for that! Just updated to version 5.3.220429 and it's working again :)

Do you mind sharing what was the problem?

**Comment by cardigliano** [comment] 2022-04-29 09:00
@Batnun it was due to an access to an uninitialized variable on FreeBSD (https://github.com/ntop/ntopng/commit/5bfacca8b25413214df57b4e72e883b154cb0aea)

**Comment by Batnun** [comment] 2022-04-29 09:09
@cardigliano Thanks again and have a great weekend :)

**Comment by cardigliano** [comment] 2022-04-29 09:22
Closing this. Please reopen in case.

**Closed as completed by cardigliano** 2022-04-29 09:22 UTC

**Comment by ToqQrrl** [comment] 2022-04-30 18:25
I also confirm that it works.

Thank you Alfredo for your great support … good job !
