### ISSUE TITLE
Flows logged in MySQL vs Portal 

### ISSUE THREAD

**Issue by alberk8** [ntop/ntopng#864] opened 2016-12-21 10:26 UTC
Hi,

I am aggregating the data flows from the MySQL (flowsv4) table and the sum for in_bytes and out_bytes is way off that shown on screen.

For example, I have client running for 9hrs  on the Portal is showing  received as 3.56G where as the sum in the DB only shows 2.3GB and the same goes for sent bytes.  This happens for all local clients.  

The second thing is the data in the FlowsV4 table is recording out_bytes as the received data (seen on portal) and via versa for in_bytes.  Is this intentional?

There are no drop packets as I am testing with a low bandwidth WAN (5Mbps), low CPU usage and low disk activity.

**Comment by simonemainardi** [comment] 2016-12-21 18:54
Hi, thanks for reporting. There was an issue fixed in https://github.com/ntop/ntopng/commit/ff7c61bb9de9f18564e9e45b4189651fd38f52f2 that could result in partial losses for long lived flows. The issue is now solved and new packages will be available tomorrow.

> For  example, I have client running for 9hrs on the Portal is showing received as 3.56G where as the sum in the DB only shows 2.3GB and the same goes for sent bytes. This happens for all local clients.

physiological differences that you should expect are between 5 and 10%

> The second thing is the data in the FlowsV4 table is recording out_bytes as the received data (seen on portal) and via versa for in_bytes. Is this intentional?

this is the standard widely acknowledged way to handle the directions even if I have to admit that it can be confusing.

**Closed as completed by simonemainardi** 2016-12-21 18:54 UTC
