### ISSUE TITLE
Broken Behaviour Exceptions with View Interfaces

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#8073] opened 2023-11-30 17:25 UTC
Behavioural exceptions with view interfaces do not work as they should be applied to physical interfaces.

Consider making behavioural exceptions global to all interfaces.

**Comment by NicoMaio** [comment] 2023-12-14 10:22
To reproduce it, add a behavioural check exclusion by selecting Flow Alerts `DNS Invalid Characters` and insert the machine's IP Address where ntopng is running.

Run `dig https://www.repubblica.it`

**Comment by MatteoBiscosi** [comment] 2024-07-01 08:19
The issue is fixed with the latest ntopng version
![image](https://github.com/ntop/ntopng/assets/49585191/74f29af9-5981-4468-92a3-fce8061169b2)

**Closed as completed by MatteoBiscosi** 2024-07-01 08:19 UTC
Labels: In Progress, Priority Ticket
