### ISSUE TITLE
Invalid Spinner Behaviour

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7946] opened 2023-10-24 13:48 UTC
<img width="1132" alt="Screenshot 2023-10-24 at 15 46 43" src="https://github.com/ntop/ntopng/assets/4493366/7e26dcfd-c36e-4262-8880-a831a54d7106">

when no hosts are found, the spinner remains on screen even when you change page

<img width="1161" alt="Screenshot 2023-10-24 at 15 46 48" src="https://github.com/ntop/ntopng/assets/4493366/041bf374-09f6-4f27-abd1-d85cec64f7df">

**Comment by MatteoBiscosi** [comment] 2023-10-31 14:14
The issue is fixed in the latest ntopng version

**Closed as completed by MatteoBiscosi** 2023-10-31 14:14 UTC
