### ISSUE TITLE
I am using Netegate SG 3100 pfsense firewall i have tried to compile with update version but i am unable to compile. i have installed ntopng using package manage option in pfsense. there is old version 3.4 is stored. i want to update 3.6 for stability. with 3.4 i am facing issue. ntopng service stop automatically after some time. when i restart its removed all stored data. i want to monitor my employees internet usage.

### ISSUE THREAD

**Issue by gamujtaba** [ntop/ntopng#2119] opened 2018-10-23 04:37 UTC
kindly help me to fix this

_Originally posted by @gamujtaba in https://github.com/ntop/ntopng/issues/2107#issuecomment-432078515_

**Comment by simonemainardi** [comment] 2018-10-23 06:35
Duplicate of https://github.com/ntop/ntopng/issues/2107

If you need support to compile, please, report the exact steps you've done and the compilation errors you're getting.

**Closed as completed by simonemainardi** 2018-10-23 06:35 UTC
Labels: Duplicate
