### ISSUE TITLE
Missed Top Talker

### ISSUE THREAD

**Issue by paoloB132** [ntop/ntopng#38] opened 2015-06-01 10:06 UTC
Just install 2.0.150601 on CentOS 6.6

RPM version do not start, so compiled and installed from source

Still Top Talkers are not showed (like was on previous version) on Historical NIC Activity.
This is a very useful feature!
See also bug 538 on https://kpn.ntop.org/bugzilla/show_bug.cgi?id=538

It's also be mentioned that this windows in noticeably slower than previous version, when moving cursor on  Traffic part. 

Regards,
Paolo.

**Comment by ariava** [comment] 2015-06-01 10:12
@paoloB132 could you please provide you configuration? Unfortunately we are still not managing to reproduce the issue.

**Comment by paoloB132** [comment] 2015-06-01 10:51
Hi Arianna,

thanks to reply so fast !

Here some cons:

[root@ntop ntopng-2.0]# uname -a
Linux ntop.rfx.local 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

ntopng Community v.2.0.150601

[root@ntop ntopng-2.0]# more /etc/ntopng/ntopng.conf 
-G=/var/tmp/ntopng.pid
-m="192.168.0.0/16, 150.178.3.0/24, 150.178.32.0/24, 150.178.33.0/24, 150.178.34.0/24"
-i=eth1

[root@ntop ntopng-2.0]# ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:17:A4:10:A8:0A  
          inet addr:192.168.60.21  Bcast:192.168.60.255  Mask:255.255.255.0
          inet6 addr: fe80::217:a4ff:fe10:a80a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:46053770 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10540526 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:57165211403 (53.2 GiB)  TX bytes:6713569384 (6.2 GiB)
          Interrupt:28 

eth1      Link encap:Ethernet  HWaddr 00:17:A4:10:A8:09  
          inet6 addr: fe80::217:a4ff:fe10:a809/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:872360463 errors:0 dropped:18431 overruns:0 frame:0
          TX packets:6 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:658390266419 (613.1 GiB)  TX bytes:492 (492.0 b)
          Interrupt:29 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:123777891 errors:0 dropped:0 overruns:0 frame:0
          TX packets:123777891 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:10399132293 (9.6 GiB)  TX bytes:10399132293 (9.6 GiB)

NIC eth1 is connected to our HP5412 on a mirrored port.
 
Please take a look on attached screen shot, and let me know if you need some other information .

Regards,
Paolo.


> On 01/giu/2015, at 12:12, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 could you please provide you configuration? Unfortunately we are still not managing to reproduce the issue.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by paoloB132** [comment] 2015-06-04 09:24
Arianna,

I can try to help to debug the problem of missed "Minute
Top Talkers" i last NTOPNG, can you point me to the scripts that fetch/calculate and display  those information ?

Ciao,
aolo.

**Comment by ariava** [comment] 2015-06-04 12:30
@paoloB132 to aid in debugging the issue, could you please check the javascript console of your browser when you try to display top talkers? This could definitely give a hint if a javascript error was the issue.

**Comment by paoloB132** [comment] 2015-06-04 13:04
Hi Ariannna,

1) I’m using Google Chrome
2) Go to Historical Activity of my nic  that is eth1
3) When I move curse over right panel with red traffic graph, it comes up following error:

jquery.js:9592 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

that should correspond to :

// Open the socket
					xhr.open( options.type, options.url, options.async, options.username, options.password );

No idea if this is related to missed “Minute Top Talker”


Looking at the  lua scripts it seems that this form be managed by graph_utilty.lua and in particular the variable infoHTML that is never filled.

Ciao,
Paolo.


 

> On 04/giu/2015, at 14:30, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> to aid in debugging the issue, could you please check the javascript console of your browser when you try to display top talkers? This could definitely give a hint if a javascript error was the issue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-108873165>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by ariava** [comment] 2015-06-04 20:03
@paoloB132 I think the issue is not in the javascript warning but in the script. Could you please check if the top talkers database was correctly created in the interface folder? (e.g. /var/tmp/ntopng/0/top_talkers/top_talkers.db) Would it be for instance possible to have remote access to your machine to debug the issue?

**Comment by paoloB132** [comment] 2015-06-05 06:16
Hi Arianna,

> On 04/giu/2015, at 22:03, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> I think the issue is not in the javascript warning but in the script.
> 

agree..
> Could you please check if the top talkers database was correctly created in the interface folder? (e.g. /var/tmp/ntopng/0/top_talkers/top_talkers.db)
> 
[root@ntop ~]# ls -l /var/tmp/ntopng/0/top_talkers/top_talkers.db 

> Would it be for instance possible to have remote access to your machine to debug the issue?
> 
> 

Sure…thanks !

I need to know the remote IP address from where you plan to connect …ssh and tcp/3000.

Regards,
Paolo.

> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-109032908>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by paoloB132** [comment] 2015-06-05 06:18
Arianna … I need also a private email (no github thread !) where send  access credential.

> On 04/giu/2015, at 22:03, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> I think the issue is not in the javascript warning but in the script. Could you please check if the top talkers database was correctly created in the interface folder? (e.g. /var/tmp/ntopng/0/top_talkers/top_talkers.db) Would it be for instance possible to have remote access to your machine to debug the issue?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-109032908>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by ariava** [comment] 2015-06-09 20:55
@paoloB132 sorry for the delay in coming back to you. I'll access from kpn.ntop.org if that's OK. My e-mail is avanzini@ntop.org. Thanks to be willing to help.

**Comment by paoloB132** [comment] 2015-06-16 08:36
Dear Arianna,

any news on this subject ?

Regards,
Paolo.

> On 09/giu/2015, at 22:55, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> sorry for the delay in coming back to you. I'll access from kpn.ntop.org if that's OK. My e-mail is avanzini@ntop.org <mailto:avanzini@ntop.org>. Thanks to be willing to help.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-110501719>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by ariava** [comment] 2015-06-16 10:28
Hi @paoloB132, I sent out a private e-mail.

**Comment by paoloB132** [comment] 2015-06-16 10:31
…I’ve really replied to that email with requested information… do you see any email from me ?


> On 16/giu/2015, at 12:28, Arianna Avanzini <notifications@github.com> wrote:
> 
> Hi @paoloB132 <https://github.com/paoloB132>, I sent out a private e-mail.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-112378402>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by ariava** [comment] 2015-06-16 10:33
@paoloB132 I mean I sent out a private e-mail now :-)

**Comment by paoloB132** [comment] 2015-06-23 06:45
Arianna ...did you be able to reproduce this issue ?

**Comment by ariava** [comment] 2015-06-23 11:05
@paoloB132 I have just pushed a fix for top talkers to the dev branch (9e5d3f9). It will be in tonight's nightly. After updating please also remove the top_talkers folders for each interface as there was a flaw in the format of stored JSONs. There was also a permissions issue which I fixed (folders under /var/tmp/ntopng must be writable by nobody or by the user you specify with the -U option).

**Comment by paoloB132** [comment] 2015-06-24 14:46
Hi Arianna,

download compile and install last development and really now I see top talkers showed when moving on the graph traffic window but only for initial 3/4 minutes, then they are missed again .

Regards,
Paolo.

> On 23/giu/2015, at 13:05, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> I have just pushed a fix for top talkers to the dev branch (9e5d3f9 <https://github.com/ntop/ntopng/commit/9e5d3f93457747179c8c94a5dd8b1efe245fcfe8>). It will be in tonight's nightly. After updating please also remove the top_talkers folders for each interface as there was a flaw in the format of stored JSONs. There was also a permissions issue which I fixed (folders under /var/tmp/ntopng must be writable by nobody or by the user you specify with the -U option).
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-114445702>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by paoloB132** [comment] 2015-07-03 06:39
Hi Arianna,

Any news ?

Installed v.2.0.150702

Traffic graph in Historical Activity form disappears.

When move on Traffic Windows some numbers come up on Minute Top Talkers frame, but honestly it’s not clear what they mean.

Min, Max, Average, Total Traffic always show “0”.

Regards,
Paolo.


  
> On 24/giu/2015, at 16:46, Paolo Barbato <paolo.barbato@igi.cnr.it> wrote:
> 
> Hi Arianna,
> 
> download compile and install last development and really now I see top talkers showed when moving on the graph traffic window but only for initial 3/4 minutes, then they are missed again .
> 
> Regards,
> Paolo.
> 
>> On 23/giu/2015, at 13:05, Arianna Avanzini <notifications@github.com> wrote:
>> 
>> @paoloB132 I have just pushed a fix for top talkers to the dev branch (9e5d3f9). It will be in tonight's nightly. After updating please also remove the top_talkers folders for each interface as there was a flaw in the format of stored JSONs. There was also a permissions issue which I fixed (folders under /var/tmp/ntopng must be writable by nobody or by the user you specify with the -U option).
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> ------------------------------------------------------------------------------------------------
> Paolo Barbato
> 
> Consorzio RFX
> corso Stati Uniti,4                                  
> 35127 Padova - Italy                     	                 
> Network Administrator 
> phone: +39 049 8295097 fax: +39 049 8700718
> ------------------------------------------------------------------------------------------------
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by ariava** [comment] 2015-07-03 10:44
@paoloB132 there was again an issue with permissions of the top talkers database. I do not know if that is the cause of the troubles you're experiencing, but even if I can ssh correctly to the server I still am not able to access the web interface: do I have to access via kpn.ntop.org as well?

**Comment by paoloB132** [comment] 2015-07-03 11:20
> On 03/lug/2015, at 12:44, Arianna Avanzini <notifications@github.com> wrote:
> 
> @paoloB132 <https://github.com/paoloB132> there was again an issue with permissions of the top talkers database. I do not know if that is the cause of the troubles you're experiencing, but even if I can ssh correctly to the server I still am not able to access the web interface: do I have to access via kpn.ntop.org as well?
> 
> 
yes …actually I don't see any attempt 


> —
> Reply to this email directly or view it on GitHub <https://github.com/ntop/ntopng/issues/38#issuecomment-118313683>.
> 

------------------------------------------------------------------------------------------------
Paolo Barbato

Consorzio RFX
corso Stati Uniti,4                                  
35127 Padova - Italy                     	                 
Network Administrator 
phone: +39 049 8295097 fax: +39 049 8700718
------------------------------------------------------------------------------------------------

**Comment by lucaderi** [comment] 2015-07-25 09:58
@paoloB132 @ariava Hi all can we close this issue?

**Closed** 2015-08-15 17:19 UTC
Labels: bug
