### ISSUE TITLE
recurring ERROR: Number out of integers range

### ISSUE THREAD

**Issue by popmonkey** [ntop/ntopng#3398] opened 2020-02-08 18:49 UTC
i upgraded to 3.9.x yesterday from ... i'm actually not sure, sadly but whatever was available on 2019.10.1 (http://packages.ntop.org/RaspberryPI/buster_pi/armhf/ntopng/ doesn't have the version anymore)

got this in the logs

```syslog
Feb 08 00:41:11 pitrak ntopng[511]: [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073708e+19
Feb 08 00:41:11 pitrak ntopng[511]: 08/Feb/2020 00:41:11 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744073708e+19
Feb 08 00:41:11 pitrak ntopng[511]: [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:
                                            /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'
                                            ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>
                                            (...tail calls...)
                                            .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'
                                            /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'
                                            /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'
                                            /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
Feb 08 00:41:11 pitrak ntopng[511]: 08/Feb/2020 00:41:11 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:
Feb 08 00:41:11 pitrak ntopng[511]:         /usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'
Feb 08 00:41:11 pitrak ntopng[511]:         ...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>
Feb 08 00:41:11 pitrak ntopng[511]:         (...tail calls...)
Feb 08 00:41:11 pitrak ntopng[511]:         .../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'
Feb 08 00:41:11 pitrak ntopng[511]:         /usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'
Feb 08 00:41:11 pitrak ntopng[511]:         /usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'
Feb 08 00:41:11 pitrak ntopng[511]:         /usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
```
i also got 50,000+ flows marked `This flow is no longer active and it should have been purged from memory` and i'm guessing it has something to do with that script not running?

restarting `ntopng` made the `This flow is no longer active and it should have been purged from memory` flows go away (for now) - i'll report if the script crashes again tonight.

```sh
v.3.9.200205	[Enterprise/Professional/Embedded build]
GIT rev:	dev:5f2d9a1dd2c463dfdae4566f671e55acf714e651:20200205
Pro rev:	r2697
Built on:	Raspbian GNU/Linux 10 (buster)
System Id:	FD9B86E0499602D2
Platform:	armv7l
Edition:	Enterprise Embedded
License Type:	Time-Limited [Empty license file]
Validity:	Until Sat Feb  8 10:48:13 2020
```

**Comment by popmonkey** [comment] 2020-02-08 18:55
oh ouch, actually this is happening every second right now!

```
Feb  8 10:54:34 pitrak ntopng: [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744070973e+19
Feb  8 10:54:34 pitrak ntopng[9526]: 08/Feb/2020 10:54:34 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744070973e+19
Feb  8 10:54:34 pitrak ntopng: [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:#012#011/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'#012#011...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>#012#011(...tail calls...)#012#011.../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'#012#011/usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'#012#011/usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'#012#011/usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
Feb  8 10:54:34 pitrak ntopng[9526]: 08/Feb/2020 10:54:34 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:
Feb  8 10:54:34 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'
Feb  8 10:54:34 pitrak ntopng[9526]: #011...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>
Feb  8 10:54:34 pitrak ntopng[9526]: #011(...tail calls...)
Feb  8 10:54:34 pitrak ntopng[9526]: #011.../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'
Feb  8 10:54:34 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'
Feb  8 10:54:34 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'
Feb  8 10:54:34 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
Feb  8 10:54:35 pitrak ntopng: [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744070973e+19
Feb  8 10:54:35 pitrak ntopng[9526]: 08/Feb/2020 10:54:35 [second.lua:26] [ntop_utils.lua:204] ERROR: Number out of integers range: 1.8446744070973e+19
Feb  8 10:54:35 pitrak ntopng: [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:#012#011/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'#012#011...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>#012#011(...tail calls...)#012#011.../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'#012#011/usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'#012#011/usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'#012#011/usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
Feb  8 10:54:35 pitrak ntopng[9526]: 08/Feb/2020 10:54:35 [second.lua:26] [ntop_utils.lua:205] ERROR: stack traceback:
Feb  8 10:54:35 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/lua/modules/ntop_utils.lua:205: in function 'tolongint'
Feb  8 10:54:35 pitrak ntopng[9526]: #011...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:340: in function <...re/ntopng/scripts/lua/modules/timeseries/drivers/rrd.lua:319>
Feb  8 10:54:35 pitrak ntopng[9526]: #011(...tail calls...)
Feb  8 10:54:35 pitrak ntopng[9526]: #011.../ntopng/scripts/lua/modules/timeseries/ts_utils_core.lua:256: in function 'ts_utils_core.append'
Feb  8 10:54:35 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/callbacks/system/second.lua:32: in local 'callback'
Feb  8 10:54:35 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/lua/modules/callback_utils.lua:27: in function 'callback_utils.foreachInterface'
Feb  8 10:54:35 pitrak ntopng[9526]: #011/usr/share/ntopng/scripts/callbacks/system/second.lua:26: in main chunk
```

**Comment by popmonkey** [comment] 2020-02-08 19:04
wth?

```
ntopng-data/unknown 3.9.200205 all [upgradable from: 3.9.190913]
```
```
The following packages have unmet dependencies:
 ntopng-data : Depends: geoipupdate but it is not installable
```

so i
```
apt remove ntopng-data
```

restarted everything and so far no integer errors...

does any of this make sense?  is this just a user upgrade error?

**Comment by popmonkey** [comment] 2020-02-08 19:19
closing - will reopen if this recurs

**Comment by popmonkey** [comment] 2020-02-12 19:55
this didn't have anything to do with `ntopng-data` (of course) and has also been reported in: https://github.com/ntop/ntopng/issues/3332

**Comment by popmonkey** [comment] 2020-02-12 20:51
this happened again in my setup so i am re-opening.

note that this is also reported in #3332 but that issue seems rather generic (lots of errors being noted there)

**Comment by popmonkey** [comment] 2020-02-12 20:54
```sh
$ ntopng --version
v.3.9.200205	[Enterprise/Professional/Embedded build]
GIT rev:	dev:5f2d9a1dd2c463dfdae4566f671e55acf714e651:20200205
Pro rev:	r2697
Built on:	Raspbian GNU/Linux 10 (buster)
System Id:	FD9B86E0499602D2
Platform:	armv7l
Edition:	Enterprise Embedded
License Type:	Time-Limited [Empty license file]
Validity:	Until Wed Feb 12 13:03:36 2020
```

restarting `ntopng` and `redis-server` seems to be a _temporary_ workaround.

**Comment by emanuele-f** [comment] 2020-02-13 09:10
For some reason, the interface bytes counter on your system is exceeding the maximum 64 bit integer of lua. Can you post a screenshot of the eth0 Interface page?

**Comment by popmonkey** [comment] 2020-02-13 09:21
it's running on a raspberry 3b with buster.  the eth0 interface is in promiscuous mode and i had to configure it to not filter vlans (`rx-vlan-filter: off`) otherwise the system is standard

<img width="1299" alt="eth0" src="https://user-images.githubusercontent.com/287170/74419359-9da3a180-4dfe-11ea-9091-5c328f48f116.png">

**Comment by popmonkey** [comment] 2020-02-13 09:22
note that this screenshot is while ntopng is working (i restarted it as per https://github.com/ntop/ntopng/issues/3398#issuecomment-585412783) - i'll post another when it breaks again

**Comment by emanuele-f** [comment] 2020-02-13 10:25
You can see in the picture that the total traffic counter is completely out of any reasonable range, we need to understand what's going on

**Comment by popmonkey** [comment] 2020-02-13 15:44
ya i see what you mean!  yikes.

my ntopng is monitoring eth0 which is connected to a mirrored port on a switch.

```sh
eth0: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        ether b8:27:eb:98:80:de  txqueuelen 1000  (Ethernet)
        RX packets 167029492  bytes 1870144406 (1.7 GiB)
        RX errors 1169  dropped 130635  overruns 0  frame 1169
        TX packets 12  bytes 1356 (1.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

when i go `lua/if_stats.lua?ifid=1&page=traffic_report` i get this error:
```
HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close  Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:

...are/ntopng/pro/scripts/lua/enterprise/traffic_report.lua:1: unexpected symbol near '<\135>'
```

**Comment by popmonkey** [comment] 2020-02-13 15:53
`traffic_report.lua` is totally encrypted which i'm guessing is because of the licensing.  note that i _am_ running with the `--community` flag tho.  i would say unrelated except that it _is_ called from `if_stats`

**Comment by popmonkey** [comment] 2020-02-13 15:55
```
-G=/var/run/ntopng.pid
--interface eth0
--http-port 3000
--local-networks "192.168.X.0/24,192.168.XX.0/24"
--community
--ignore-vlans
```

**Comment by emanuele-f** [comment] 2020-02-13 16:17
> when i go `lua/if_stats.lua?ifid=1&page=traffic_report` i get this error:
> 
> ```
> HTTP/1.1 500 Internal server error Content-Type: text/html Connection: close  Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error:
> 
> ...are/ntopng/pro/scripts/lua/enterprise/traffic_report.lua:1: unexpected symbol near '<\135>'
> ```

This is fixed in 70da6923a5a6882d323e866c7325cb387b58ab17 .

**Comment by emanuele-f** [comment] 2020-02-25 14:27
Can you post the output of `cat /proc/net/dev`?

**Comment by emanuele-f** [comment] 2020-02-25 15:06
Bug is caused by the counters wrapping inside `/proc/net/dev`

**Closed as completed** 2020-02-25 16:47 UTC
Labels: In Progress

**Comment by emanuele-f** [comment] 2020-02-25 16:49
A new package containing the fix will be available in two hours.

**Comment by popmonkey** [comment] 2020-02-25 18:44
awesome - thanks @emanuele-f - i've had to keep restarting nightly

and fwiw
```sh
$ cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
 wlan0: 800896276 3783739    0    0    0     0          0   2193858 346385773 1382169    0    0    0     0       0          0
  eth0: 3135174178 366096343 2089 289399    0  2088          0         0     1286      11    0    0    0     0       0          0
    lo: 2175031057 11909597    0    0    0     0          0         0 2175031057 11909597    0    0    0     0       0          0
```

**Comment by popmonkey** [comment] 2020-02-25 18:48
i'm installing `3.9.200225-9086` now - will report back in 24 hours (usually i get overflowed ~12 hours in)

**Comment by popmonkey** [comment] 2020-02-26 21:01
still looking good 24 hours later!  success.  ty!
