### ISSUE TITLE
ERROR: rrd_update_r()

### ISSUE THREAD

**Issue by sunshiros** [ntop/ntopng#5507] opened 2021-06-16 08:25 UTC
When i start ntopng using : sudo ntopng -debug i get these errors which keep going every second non stop  :

16/Jun/2021 11:21:28 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831688:161684] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831688]
16/Jun/2021 11:21:29 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831689:161768] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831689]
16/Jun/2021 11:21:30 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831690:161852] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831690]
16/Jun/2021 11:21:31 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831691:162020] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831691]
16/Jun/2021 11:21:32 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831692:162227] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831692]
16/Jun/2021 11:21:33 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831693:162563] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831693]
16/Jun/2021 11:21:34 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831694:164249] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831694]
16/Jun/2021 11:21:35 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831695:170347] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831695]
16/Jun/2021 11:21:36 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831696:170347] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831696]
16/Jun/2021 11:21:37 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831697:173992] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831697]
16/Jun/2021 11:21:38 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831698:174160] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831698]
16/Jun/2021 11:21:39 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831699:176341] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831699]
16/Jun/2021 11:21:40 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831700:178541] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831700]
16/Jun/2021 11:21:41 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831701:179773] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831701]
16/Jun/2021 11:21:42 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [ebug/4/rrd/bytes.rrd][1623831702:179857] failed [ebug/4/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623831702]

My machine is a raspberry pi 4 with Raspbian GNU/Linux 10 (buster)

**Comment by lucaderi** [comment] 2021-06-16 09:44
Can you please delete ebug/4/rrd/bytes.rrd and report?

**Comment by sunshiros** [comment] 2021-06-16 09:50
I have renamed the file and re issued sudo ntopng -debug and the errors have gone now !

**Comment by sunshiros** [comment] 2021-06-16 12:11
Actually after a few hours it appeared again :(


16/Jun/2021 15:07:15 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845235:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845235]16/Jun/2021 15:07:14 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845234:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845234]16/Jun/2021 15:07:13 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845233:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845233]16/Jun/2021 15:07:12 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845232:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845232]16/Jun/2021 15:07:11 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845231:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845231]16/Jun/2021 15:07:10 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845230:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845230]16/Jun/2021 15:07:09 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845229:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845229]16/Jun/2021 15:07:08 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845228:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845228]16/Jun/2021 15:07:07 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845227:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845227]16/Jun/2021 15:07:06 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845226:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845226]16/Jun/2021 15:07:05 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845225:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845225]16/Jun/2021 15:07:04 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845224:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845224]16/Jun/2021 15:07:03 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845223:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845223]16/Jun/2021 15:07:02 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845222:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845222]16/Jun/2021 15:07:01 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845221:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845221]16/Jun/2021 15:07:00 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845220:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845220]16/Jun/2021 15:06:59 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845219:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845219]16/Jun/2021 15:06:58 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845218:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845218]16/Jun/2021 15:06:57 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845217:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845217]16/Jun/2021 15:06:56 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845216:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845216]16/Jun/2021 15:06:55 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845215:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845215]16/Jun/2021 15:06:54 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845214:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845214]16/Jun/2021 15:06:53 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845213:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845213]16/Jun/2021 15:06:52 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845212:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845212]16/Jun/2021 15:06:51 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845211:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845211]16/Jun/2021 15:06:50 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845210:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845210]16/Jun/2021 15:06:49 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845209:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845209]16/Jun/2021 15:06:48 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845208:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845208]16/Jun/2021 15:06:47 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845207:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845207]16/Jun/2021 15:06:46 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845206:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845206]16/Jun/2021 15:06:45 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845205:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845205]16/Jun/2021 15:06:44 [second.lua:27] [rrd.lua:437]&nbsp;ERROR&nbsp;rrd_update_r() [ebug/2/rrd/bytes.rrd][1623845204:194859] failed [ebug/2/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1623845204]
--

**Comment by lucaderi** [comment] 2021-06-18 08:27
What is this interface 2 ? Is it an ethernet or ZMQ? Did you change something when the problem appeared?

**Comment by sunshiros** [comment] 2021-06-18 12:22
I'm made a fresh installation of ntopng using a vanilla raspberry pi 4 with latest rasbian buster and i get these error messages : (the pi is connected using ethernet. Problem appeared after a day of the installation)

18/Jun/2021 15:17:34 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018654:243743009] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018654]
18/Jun/2021 15:17:33 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018653:243736944] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018653]
18/Jun/2021 15:17:32 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018652:243732470] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018652]
18/Jun/2021 15:17:31 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018651:243730029] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018651]
18/Jun/2021 15:17:30 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018650:243679373] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018650]
18/Jun/2021 15:17:29 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018649:243598854] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018649]
18/Jun/2021 15:17:28 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018648:243568088] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018648]
18/Jun/2021 15:17:27 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018647:243567756] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018647]
18/Jun/2021 15:17:26 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018646:243567630] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018646]
18/Jun/2021 15:17:25 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018645:243567630] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018645]
18/Jun/2021 15:17:24 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018644:243567630] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018644]
18/Jun/2021 15:17:23 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018643:243567630] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018643]
18/Jun/2021 15:17:22 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018642:243567156] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018642]
18/Jun/2021 15:17:21 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018641:243532054] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018641]
18/Jun/2021 15:17:20 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018640:243531718] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018640]
18/Jun/2021 15:17:19 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018639:243530794] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018639]
18/Jun/2021 15:17:18 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018638:243528285] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018638]
18/Jun/2021 15:17:17 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018637:243527576] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018637]
18/Jun/2021 15:17:16 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018636:243526348] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018636]
18/Jun/2021 15:17:15 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018635:243521146] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018635]
18/Jun/2021 15:17:14 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018634:243518798] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018634]
18/Jun/2021 15:17:13 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018633:243518798] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018633]
18/Jun/2021 15:17:12 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018632:243518798] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018632]
18/Jun/2021 15:17:11 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018631:243518529] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018631]
18/Jun/2021 15:17:10 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018630:243518469] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018630]
18/Jun/2021 15:17:09 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018629:243518469] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018629]
18/Jun/2021 15:17:08 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018628:243518100] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018628]
18/Jun/2021 15:17:07 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018627:243518100] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018627]
18/Jun/2021 15:17:06 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018626:243515716] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018626]
18/Jun/2021 15:17:05 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018625:243515380] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018625]
18/Jun/2021 15:17:04 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018624:243514456] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018624]
18/Jun/2021 15:17:03 [second.lua:27] [rrd.lua:437] ERROR rrd_update_r() [/var/lib/ntopng/1/rrd/bytes.rrd][1624018623:243512706] failed [/var/lib/ntopng/1/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624018623]

**Comment by sunshiros** [comment] 2021-06-18 12:28
I removed the /var/lib/ntopng/1/rrd/bytes.rrd as adviced before and i will report back

**Comment by sunshiros** [comment] 2021-06-20 08:44
I removed the /var/lib/ntopng/1/rrd/bytes.rrd and/var/lib/ntopng/2/rrd/bytes.rrd restarted but still the same

**Comment by simonemainardi** [comment] 2021-06-22 10:49
we are not able to reproduce. Check:

- File Permissions
- System date and time to see if they are correctly set

Attach `/var/lib/ntopng/1/rrd/bytes.rrd`  if necessary

**Comment by sunshiros** [comment] 2021-06-22 18:46
OK  i will. After running the ntopng form terminal i notice before the GUI administration from browser becomes unresponsive it get this last messages in terminal : 

21/Jun/2021 21:26:01 [AnalysisBehavior.cpp:40] [ANOMALY] eth0 [Network 3 | score] [value: 3196478356]
21/Jun/2021 21:26:01 [AnalysisBehavior.cpp:40] [ANOMALY] eth0 [������`����ᅾ] [value: 14976976]
^C21/Jun/2021 21:26:39 [main.cpp:50] Shutting down...
21/Jun/2021 21:26:39 [PcapInterface.cpp:357] Terminated packet polling for lo
21/Jun/2021 21:26:39 [PcapInterface.cpp:357] Terminated packet polling for tun0
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2779] Host dump thread completed for eth0 [VLAN Id: 109]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2748] Flow dump thread completed for eth0 [VLAN Id: 108]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2748] Flow dump thread completed for eth0 [VLAN Id: 107]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2779] Host dump thread completed for lo
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2779] Host dump thread completed for eth0 [VLAN Id: 108]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2779] Host dump thread completed for eth0 [VLAN Id: 107]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2748] Flow dump thread completed for eth0 [VLAN Id: 109]
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2748] Flow dump thread completed for tun0
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2779] Host dump thread completed for tun0
21/Jun/2021 21:26:40 [NetworkInterface.cpp:2748] Flow dump thread completed for lo
21/Jun/2021 21:26:41 [Ntop.cpp:2821] Terminating periodic activities

**Comment by simonemainardi** [comment] 2021-06-23 06:32
> ^C21/Jun/2021 21:26:39 [main.cpp:50] Shutting down...

It's not the guy unresponsive. It's ntopng that has been shut down with a ctrl C.

**Comment by simonemainardi** [comment] 2021-06-24 08:23
I am able to reproduce on ubuntu as well

```
24/Jun/2021 10:21:27 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522888:26376] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522888]
24/Jun/2021 10:21:28 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522889:2459828] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522889]
24/Jun/2021 10:21:29 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522890:2629781] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522890]
24/Jun/2021 10:21:30 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522891:2631513] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522891]
24/Jun/2021 10:21:31 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522892:2837972] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522892]
24/Jun/2021 10:21:32 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522893:2900555] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522893]
24/Jun/2021 10:21:33 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522894:2904581] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522894]
24/Jun/2021 10:21:34 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522895:2905674] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522895]
24/Jun/2021 10:21:35 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522896:2913305] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522896]
24/Jun/2021 10:21:36 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522897:2914429] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522897]
24/Jun/2021 10:21:37 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522898:2941892] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522898]
24/Jun/2021 10:21:38 [second.lua:27] [rrd.lua:437] ERROR: rrd_update_r() [/var/lib/ntopng/0/rrd/bytes.rrd][1624522899:2946215] failed [/var/lib/ntopng/0/rrd/bytes.rrd: expected 3 data source readings (got 1) from 1624522899]
```

This is happening after ungraceful restart of the machine.

**Comment by simonemainardi** [comment] 2021-06-24 10:21
Thanks for providing this info. I have pushed some fixes that may affect this. I was only able to reproduce this one time. 

Please, wait until new pi builds are generated - this will take a couple of hours - then stop ntopng, delete `/var/lib/ntopng/0/rrd/bytes.rrd`, update ntopng to the latest version and restart it.

Report the behaviour. If it happens again, we can arrange a remote session.

**Comment by sunshiros** [comment] 2021-06-24 19:12
I've uninstalled completely ntopng and tried to reinnstall just now but i get errors on installation this time :

sudo dpkg -i apt-ntop_1.0.190416-469_all.deb

resulted : 

dpkg: error processing package apt-ntop (--install):
 installed apt-ntop package post-installation script subprocess returned error exit status 100
Errors were encountered while processing:
 apt-ntop

I proceed anyway and got errors again : 

sudo apt-get update
sudo apt-get install ntopng nprobe n2n

resulted : 

Rebuilding ld cache...
Invalid unit name "edge@*.service" was escaped as "edge@\x2a.service" (maybe you should use systemd-escape?)
edge@*.service is a disabled or a static unit not running, not starting it.
Invalid unit name "edge-ntopng@*.service" was escaped as "edge-ntopng@\x2a.service" (maybe you should use systemd-escape?)
edge-ntopng@*.service is a disabled or a static unit not running, not starting it.
Setting up ntopng-data (4.3.210624) ...
Processing triggers for systemd (241-7~deb10u7+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for rsyslog (8.1901.0-1) ...
Errors were encountered while processing:
 apt-ntop
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simonemainardi** [comment] 2021-07-08 08:30
Fixed in the lasted build.

**Closed as completed by simonemainardi** 2021-07-08 08:30 UTC
Labels: In Progress
