### ISSUE TITLE
Can't save users account info

### ISSUE THREAD

**Issue by EAnsy** [ntop/ntopng#503] opened 2016-04-19 10:53 UTC
After some working ntopng rejects normal login/password to get in.
_**ntopng restart**_ get it restarted, but without any created users and with default _admin/admin_ only.
It's nor useful neither secure at all.
_ntopng Community v.2.3.151210_

**Comment by simonemainardi** [comment] 2016-04-19 11:25
please update to the latest dev version and report again.

**Comment by EAnsy** [comment] 2016-04-19 13:18
Well... now I can't **_make_** ntopng:

```
src/Flow.o: In function `Flow::dissectBittorrent(char*, unsigned short)':
/root/ntopng/src/Flow.cpp:1974: undefined reference to `ndpi_strnstr'
src/NetworkInterface.o: In function `NetworkInterface::processPacket(timeval const*, unsigned long long, ndpi_ethhdr*, unsigned short, ndpi_iphdr*, ndpi_ipv6hdr*, unsigned short, unsigned short, pcap_pkthdr const*, unsigned char const*, bool*, unsigned short*)':
/root/ntopng/src/NetworkInterface.cpp:863: undefined reference to `ndpi_detection_giveup'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [ntopng] Error 1
```

Two different servers (with working previous ntopng versions), all running SMS (sms.it-ccs.com) with all current updates. Compiled as described in www.ntop.org/get-started/download/#ntopng (with nDPI section first -- else got error message -- and with ./autogen.sh there skipped).

**Comment by simonemainardi** [comment] 2016-04-21 15:09
make sure nDPI and ntopng sources are in the same directory. You can then run `./configure` inside ntopng to get the list of commands required to download and build nDPI.

Alternatively, rather than building from source, install a packaged version

**Comment by simonemainardi** [comment] 2016-04-21 16:39
Closing since the issue cannot be reproduced with the latest dev version. Solution to properly compile from sources has been given. Re-open another issue with full configuration details if you still experience login troubles with the latest dev.

**Closed as completed by simonemainardi** 2016-04-21 16:39 UTC

**Comment by EAnsy** [comment] 2016-04-25 12:05
Latest ntopng Community v.2.3.160425
Problem is still here.
Redis has been upgraded too.
