### ISSUE TITLE
issue with trafic detection

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#590] opened 2016-05-29 12:28 UTC
I had opened an issue in ndpi but it seems to be an issue in ntopng
thanks to check here 
https://github.com/ntop/nDPI/issues/194

Nico

**Comment by Niko78** [comment] 2016-05-29 15:38
I followed a link to be more clean and simple
=> http://www.ntop.org/nprobe/why-nprobejsonzmq-instead-of-native-sflownetflow-support-in-ntopng/

so in entering
nprobe --zmq "tcp://*:5556" -i none -n none --collector-port 2055
then
ntopng -i tcp://127.0.0.1:5556 -w 3000

I have same issue, netflow is not well detected, anyconnect vpn ssl same... and I don't have graph in bottom
BUT if I change ntopng command by
ntopng -i eth0 -w 3000
this time, protocols are well detected and graph is alive... but I don't get all data that I got with first command

Nico
<img width="453" alt="ntopng no graph and protocols not ok" src="https://cloud.githubusercontent.com/assets/17108017/15634453/28930ce8-25c4-11e6-9b7d-a65cbf036387.PNG">

**Comment by lucaderi** [comment] 2016-05-30 06:38
The graph you highlighted indicates traffic local->remote and remote->local. As you use ZMQ, ntopng has no clue what are your local networks. Please specify them with -m and it will work. Using -i eth0 works because ntopng reads it from the interface

**Comment by Niko78** [comment] 2016-05-30 07:28
the issue is not really the small graph, I can do without
my issue is that I don't get all data, same with your "-m"
I just took a screenshot when there is -m and without
as you can see I don't get the same amount flows

<img width="431" alt="ntop1" src="https://cloud.githubusercontent.com/assets/17108017/15642622/cbff2536-2648-11e6-94c8-ba4365d53733.PNG">
<img width="459" alt="ntop2" src="https://cloud.githubusercontent.com/assets/17108017/15642620/cbb101ee-2648-11e6-97e0-0aef0b3fc1c2.PNG">

**Comment by lucaderi** [comment] 2016-05-30 07:35
Looks odd to me. @ValentinaViscarelli can you please get in touch and see if you can reproduce it?

**Comment by Niko78** [comment] 2016-05-30 07:40
I can give more info 
I have around 50 cisco routers configured to send netflow stream to my server on port 7002

I start nprobe as service : /etc/init.d/nprobe start
I have nprobe-none.conf with 
-n=none
-i=none
-g=/var/run/nprobe-none.pid
-3=7002
--zmq=tcp://192.168.6.35:5556

and an empty file nprobe-none.start

then I start ntop
ntopng -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 >> /dev/null &

it seems to me that with "-m" or "-i eth0", ntopng shows me only stream from routers themselves, I mean where source/destination are the routers and not all stream passing through routers

**Comment by simonemainardi** [comment] 2016-05-30 15:33
Duplicate of https://github.com/ntop/ntopng/issues/536 please upgrade ntopng to the latest nightly build

**Closed as completed by simonemainardi** 2016-05-30 15:33 UTC
Labels: Duplicate
