### ISSUE TITLE
installing ntopng on centos 7 breaks tcpdump, tshark, etc.

### ISSUE THREAD

**Issue by brianjmurrell** [ntop/ntopng#381] opened 2016-02-07 02:11 UTC
After installing ntopng on CentOS 7, pcap tools like `tcpdump` and `tshark` break:

```
tcpdump: error while loading shared libraries: libsnf.so.0: cannot open shared object file: No such file or directory
```

**Comment by simonemainardi** [comment] 2016-02-09 12:40
duplicate of #369

**Closed as completed by simonemainardi** 2016-02-09 12:40 UTC
Labels: Duplicate
