### ISSUE TITLE
"Top Application Traffic Last Day View" empty

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1265] opened 2017-05-26 08:06 UTC
For me "Top Application Traffic Last Day View" does not get updated. The graph area is empty.

ntopng Pro [Small Business Edition] v.2.5.170524

**Comment by emanuele-f** [comment] 2017-05-26 12:42
Hi, can you your full ntopng log from startup? If you run ntopng as a service, it should be located at `/var/log/ntopng/ntopng.log`

**Comment by mahescho** [comment] 2017-05-26 16:43
Sorry :-) you want me to send my ntopng.log to you, right?

**Comment by emanuele-f** [comment] 2017-05-26 16:46
Yes, sorry I've missed the "post" word :)

**Comment by mahescho** [comment] 2017-05-26 16:48
sent by mail

**Comment by emanuele-f** [comment] 2017-05-26 17:32
I've just committed a patch to the error shown in the log, which is the cause of your issue.
A new build will be available in one hour, please update, restart ntopng and check the new log file for this error:
```
26/May/2017 06:45:01 [Lua.cpp:6078] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/minute.lua][/usr/share/ntopng/scripts/lua/modules/alert_utils.lua:1806: attempt to index local 'alert_source' (a nil value)]
```

If you don't see it any more, then the problem is fixed and since tomorrow you will be able to see last day view correctly updated.

**Comment by mahescho** [comment] 2017-05-27 10:16
error is gone, I will report back tomorrow about the data

**Comment by mahescho** [comment] 2017-05-27 11:19
"Top Application Traffic Last Day View" shows the first data. Problem solved, thanks!

**Comment by emanuele-f** [comment] 2017-05-27 13:32
Thank you

**Closed as completed by emanuele-f** 2017-05-27 13:32 UTC
