### ISSUE TITLE
Set Ingress Shaper Id: how it works?

### ISSUE THREAD

**Issue by atlanteinformatica** [ntop/ntopng#800] opened 2016-10-27 12:56 UTC
Today there was an host that was using all the traffic band. We decided to limit it by setting the Ingress Shaper Id from "Manage Traffic Filtering Policies" page.
Unfortunately, after this action, all our office can't using the web.
To solve we selected the Network who rapresent of our entire office from the drop menu, and clicked on the button "Set protocol policy and shaper".

Why this happen? Is it normal?

**Comment by emanuele-f** [comment] 2016-11-16 15:12
This should be caused by the same bug affecting #786, now fixed. Please reopen if necessary. Thank you.

**Closed as completed by emanuele-f** 2016-11-16 15:12 UTC
