### ISSUE TITLE
"Detected {client,server} score anomaly for host ... score: nil"

### ISSUE THREAD

**Issue by rreiner** [ntop/ntopng#5218] opened 2021-04-22 17:49 UTC
Seeing recurring alerts of the forms ""Detected client score anomaly for host ... score: nil" and ""Detected server score anomaly for host ... score: nil"

Screenshot attached.  The redacted IPs in the screenshot are those of internal hosts -- they are all different, not always the same.

![image](https://user-images.githubusercontent.com/12399329/115762095-17bfa680-a371-11eb-8c50-26d743c46602.png)

Using ntopng current on Raspbian current:
Version:        4.3.210419 [Enterprise/Professional/Embedded build]
GIT rev:        dev:c46634d3ea424a81e569c5c97293906ef99021e3:20210419
Pro rev:        r3725
Built on:       Raspbian GNU/Linux 10 (buster)
System Id:      130FA343499602D2
Platform:       armv7l
Edition:        Enterprise Embedded
License Type:   Time-Limited [Empty license file]
Validity:       Until Thu Apr 22 13:58:40 2021

**Comment by MatteoBiscosi** [comment] 2021-04-23 07:56
Hi @rreiner the fix is done, please wait until the next raspbian update

**Comment by rreiner** [comment] 2021-04-24 15:54
The new version no longer shows nil scores, but still generates large numbers of not-useful alerts.  It's not clear how the scores and bounds are being determined, but they are not sensible.
See attached:

![image](https://user-images.githubusercontent.com/12399329/115964716-c25fd280-a4f3-11eb-8a75-40d737222191.png)

**Comment by simonemainardi** [comment] 2021-04-26 06:47
Fixes have been done in another branch that will be merged shortly.

**Comment by cardigliano** [comment] 2021-04-29 12:59
Branch merged, this is also a duplicate of #5248 which has been addressed.

**Closed as completed by cardigliano** 2021-04-29 12:59 UTC
Labels: Ready to Test
