### ISSUE TITLE
[Ntop.cpp:201] ERROR: Unable to open lock file: No such file or directory

### ISSUE THREAD

**Issue by andrema2** [ntop/ntopng#4013] opened 2020-06-01 14:33 UTC
Hi

After installing ntopng 4 on a MacOS High Sierra, when I try to run ntopng I get this error message
[Ntop.cpp:201] ERROR: Unable to open lock file: No such file or directory

I tried to reinstall it, and got it again, even running with sudo I get this error. 

Any ideas ?

**Comment by cardigliano** [comment] 2020-06-01 14:43
@andrema2 how did you install it? Could you try running it with sudo ntopng -s -i en0 ?

**Comment by andrema2** [comment] 2020-06-01 17:25
So, now I downloaded the pkg file and installed from it. 
The error remains, but it changed to 
01/Jun/2020 14:24:48 [Ntop.cpp:2255] Setting local networks to 127.0.0.0/8
01/Jun/2020 14:24:48 [Redis.cpp:99] ERROR: Connection error [Connection refused]
01/Jun/2020 14:24:49 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 14]

Redis is installed

**Comment by cardigliano** [comment] 2020-06-01 17:41
Please run redis-server

**Comment by lucaderi** [comment] 2020-06-09 16:06
This is a duplicate of issue #3890. Please upgrade and reopen this ticket if not working

**Closed as completed by lucaderi** 2020-06-09 16:06 UTC
