### ISSUE TITLE
SNMP Graphs have incorrect dates in  Weekly Monthly, Yearly Charts

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8791] opened 2024-11-01 12:59 UTC
**Environment**:
* OS name: Ubuntu
* OS version: 22.04
* Architecture: amd64
* ntopng version/revision: 6.3.241028 Enterprise L

 Last Week charts add 7 days to the recent day, Last Month Charts add a month, Last Year charts add a year for the display dates.

**Current to Last Day is fine**
![image](https://github.com/user-attachments/assets/b68a770a-91d2-403e-99c0-2c4aea6531c9)

**Weekly Chart adds 7 days to the date  (11/08/2024 should be 11/01/2024)**
![image](https://github.com/user-attachments/assets/172c2ae3-96e9-41b4-976b-1c9ef318f064)

**Monthly Charts ad a month (12/01/2024 should be 11/01/2024**
![image](https://github.com/user-attachments/assets/589f6b33-f22f-442c-b929-1926b0ffd00c)

**Comment by MatteoBiscosi** [comment] 2024-11-04 14:47
Hi @dkggpeters sorry but i'm unable to reproduce, so i need some assistance.
Could you please right click on the page, inspect and send me the ts_multi.lua answer? (it should be a json, see the image below)
![image](https://github.com/user-attachments/assets/df43d1cd-9333-478b-817d-7590c0be2a6a)

**Comment by dkggpeters** [comment] 2024-11-04 15:21
![image](https://github.com/user-attachments/assets/e90ca2ab-6057-4128-a43e-4a87fa6e266c)




{
    "rsp": [
        {
            "metadata": {
                "epoch_begin": 1730125002,
                "schema": "snmp_if:traffic",
                "num_point": 337,
                "epoch_end": 1730733402,
                "epoch_step": 3600,
                "query": {
                    "device": "10.57.1.175",
                    "ifid": "-1"
                }
            },
            "series": [
                {
                    "id": "bytes",
                    "data": [
                        215699,
                        198839,
                        333273,
                        560532,
                        530678,
                        95960,
                        59606,
                        107117,
                        81634,
                        2152694,
                        3473826,
                        4717793,
                        2665461,
                        128755,
                        502549,
                        825579,
                        1490821,
                        1493320,
                        717499,
                        532117,
                        422297,
                        681418,
                        517653,
                        386907,
                        388329,
                        355788,
                        385883,
                        624919,
                        397334,
                        352898,
                        404820,
                        2520602,
                        2342004,
                        335096,
                        4087356,
                        3974131,
                        490158,
                        1091507,
                        484129,
                        528376,
                        560193,
                        415274,
                        497219,
                        774557,
                        1302056,
                        1431092,
                        1292581,
                        1602397,
                        1235744,
                        834805,
                        994239,
                        442459,
                        583556,
                        1858096,
                        8962000,
                        3474073,
                        1014466,
                        1272681,
                        544448,
                        532055,
                        525053,
                        1166719,
                        769719,
                        753070,
                        281967,
                        90464,
                        321909,
                        143459,
                        1883757,
                        5223345,
                        1091771,
                        158949,
                        54150,
                        317288,
                        86519,
                        241955,
                        36982,
                        56931,
                        599883,
                        2407160,
                        2328426,
                        27335,
                        3741985,
                        3392698,
                        89160,
                        186713,
                        199788,
                        599394,
                        787148,
                        120645,
                        142641,
                        720868,
                        526365,
                        359959,
                        376562,
                        247009,
                        1215092,
                        1382504,
                        234611,
                        250348,
                        726049,
                        315638,
                        128112,
                        100361,
                        139691,
                        192419,
                        171560,
                        212524,
                        202396,
                        128207,
                        104373,
                        48160,
                        622132,
                        502190,
                        840454,
                        89365,
                        130436,
                        8412793,
                        6400282,
                        341633,
                        130816,
                        105680,
                        96094,
                        320133,
                        176779,
                        86370,
                        82066,
                        2422475,
                        2279884,
                        123962,
                        3721322,
                        3945299,
                        102800,
                        214207,
                        261194,
                        224037,
                        325000,
                        695283,
                        1270088,
                        1346625,
                        1108809,
                        1498373,
                        1770401,
                        2260553,
                        1354350,
                        1319092,
                        1454631,
                        2149487,
                        1735125,
                        1581966,
                        1638710,
                        1522272,
                        1395248,
                        2016901,
                        2044374,
                        1454086,
                        890125,
                        502812,
                        700233,
                        2124093,
                        2092243,
                        576560,
                        769785,
                        1244099,
                        1044246,
                        888453,
                        1084457,
                        1803965,
                        804295,
                        589475,
                        572692,
                        924305,
                        567287,
                        592753,
                        542656,
                        2497870,
                        2675632,
                        584561,
                        3881408,
                        4706091,
                        531675,
                        584431,
                        1098942,
                        910516,
                        683568,
                        725821,
                        798004,
                        1615959,
                        2419535,
                        913985,
                        711483,
                        1254410,
                        1166282,
                        912013,
                        2661888,
                        0,
                        0,
                        2524955,
                        2283459,
                        1534172,
                        1024565,
                        1942859,
                        1533452,
                        1722055,
                        3321164,
                        2096942,
                        1310677,
                        2055096,
                        1508745,
                        2815119,
                        2041019,
                        1598924,
                        1196448,
                        1390031,
                        1199359,
                        1515518,
                        682673,
                        642994,
                        530724,
                        784278,
                        593948,
                        593031,
                        501322,
                        2651384,
                        2647161,
                        600750,
                        4021504,
                        4821519,
                        515823,
                        694095,
                        1087538,
                        1006315,
                        618438,
                        919721,
                        741128,
                        2588571,
                        12324392,
                        1870374,
                        1139509,
                        1373545,
                        533465,
                        621118,
                        541820,
                        827170,
                        1289256,
                        1535124,
                        2841067,
                        3651541,
                        3579075,
                        3375300,
                        2952150,
                        3561874,
                        2955300,
                        3542209,
                        3173337,
                        17691079,
                        3491835,
                        3825557,
                        2725301,
                        1547111,
                        1350292,
                        1345693,
                        1696587,
                        1482824,
                        810477,
                        2387536,
                        2105924,
                        2279396,
                        1098555,
                        822086,
                        720157,
                        800964,
                        2739157,
                        4084457,
                        2556951,
                        18718,
                        3496081,
                        3230569,
                        287431,
                        103445,
                        39854,
                        2224219,
                        13414048,
                        17582782,
                        1048467,
                        895209,
                        970877,
                        5252372,
                        7450531,
                        15131702,
                        7072410,
                        1930779,
                        1666277,
                        10579147,
                        12262111,
                        782299,
                        535753,
                        1793258,
                        7530663,
                        7189361,
                        390881,
                        597105,
                        713204,
                        1063613,
                        2019984,
                        4640682,
                        2344088,
                        2494403,
                        1324972,
                        1961991,
                        1703536,
                        2105576,
                        4360373,
                        1814777,
                        500985,
                        571316,
                        507388,
                        727657,
                        897459,
                        597661,
                        513999,
                        2454738,
                        2631086,
                        550178,
                        4195765,
                        4787953,
                        466067,
                        496743,
                        421374,
                        476594,
                        583786,
                        1376957,
                        1469859,
                        3341960,
                        3815267,
                        8788169,
                        6568279
                    ],
                    "ext_label": "Port 1 (Slot: 0 Port: 1 Gigabit - Level)",
                    "statistics": {
                        "average": 1732888.2878338,
                        "min_val_idx": 195,
                        "95th_percentile": 4821519,
                        "total": 2102340070800,
                        "max_val_idx": 255,
                        "min_val": 0,
                        "max_val": 17691079
                    },
                    "tags": {
                        "if_index": "1",
                        "ifid": "-1",
                        "device": "10.57.1.175"
                    },
                    "name": "1"
                },
                {
                    "id": "bytes",
                    "data": [
                        217000,
                        201339,
                        334446,
                        638660,
                        540010,
                        100201,
                        59714,
                        108906,
                        81896,
                        454028,
                        586048,
                        732969,
                        388799,
                        117018,
                        503990,
                        827099,
                        1493727,
                        1524931,
                        725891,
                        529910,
                        418510,
                        676110,
                        518009,
                        390775,
                        389384,
                        357244,
                        389049,
                        627129,
                        398472,
                        352960,
                        404993,
                        341318,
                        344059,
                        335360,
                        347889,
                        477190,
                        492581,
                        1090681,
                        483517,
                        530001,
                        561860,
                        416188,
                        498491,
                        776474,
                        1304877,
                        1432814,
                        1295504,
                        1607152,
                        1248547,
                        846432,
                        999935,
                        530417,
                        597570,
                        1864296,
                        8978232,
                        3475253,
                        1020539,
                        1281544,
                        551993,
                        538518,
                        529404,
                        1173537,
                        767200,
                        750163,
                        281247,
                        82892,
                        318894,
                        141082,
                        712534,
                        2294642,
                        1085949,
                        157964,
                        56339,
                        318817,
                        87667,
                        242704,
                        37647,
                        56200,
                        25540,
                        60247,
                        186773,
                        26633,
                        24465,
                        35153,
                        93396,
                        183363,
                        195341,
                        590218,
                        784315,
                        122234,
                        144744,
                        726904,
                        537881,
                        364256,
                        386216,
                        256253,
                        1222450,
                        1399363,
                        240734,
                        401504,
                        757789,
                        319909,
                        130281,
                        103711,
                        143323,
                        196188,
                        174433,
                        218960,
                        206164,
                        132425,
                        108190,
                        51346,
                        625007,
                        505925,
                        840479,
                        90187,
                        135159,
                        8417101,
                        6403031,
                        349149,
                        134007,
                        108849,
                        98623,
                        324377,
                        178446,
                        90326,
                        89192,
                        136642,
                        83706,
                        127200,
                        142206,
                        93159,
                        105053,
                        219313,
                        262234,
                        224690,
                        328131,
                        699836,
                        1277202,
                        1356116,
                        1116813,
                        1507970,
                        1775989,
                        2268626,
                        1361701,
                        1326835,
                        1462492,
                        2239508,
                        1757566,
                        1596112,
                        1647881,
                        1534237,
                        1414338,
                        2029348,
                        2053659,
                        1472243,
                        904756,
                        510690,
                        881137,
                        3343107,
                        2352879,
                        580111,
                        771815,
                        1238296,
                        1040466,
                        886336,
                        1084746,
                        1804782,
                        803231,
                        587714,
                        573213,
                        926046,
                        566228,
                        590754,
                        540607,
                        568238,
                        540663,
                        582018,
                        527863,
                        560500,
                        530275,
                        582733,
                        1097963,
                        905292,
                        680405,
                        724004,
                        797449,
                        1610153,
                        2420126,
                        913649,
                        712532,
                        1250180,
                        1163604,
                        906854,
                        2670969,
                        0,
                        0,
                        2525965,
                        2281918,
                        1531366,
                        1024424,
                        1940223,
                        1534572,
                        1723943,
                        3319396,
                        2092537,
                        1306314,
                        2050855,
                        1506571,
                        2812747,
                        2039985,
                        1599043,
                        1194819,
                        1388878,
                        1201589,
                        1523229,
                        684384,
                        645422,
                        533668,
                        786704,
                        595666,
                        594394,
                        502142,
                        547790,
                        492837,
                        601985,
                        680659,
                        563410,
                        516639,
                        697250,
                        1089742,
                        1002844,
                        613258,
                        916467,
                        737770,
                        2588134,
                        12321052,
                        1864518,
                        1134048,
                        1375589,
                        534769,
                        622314,
                        542051,
                        852439,
                        1346547,
                        1583399,
                        2876859,
                        3658405,
                        3578702,
                        3372377,
                        2952883,
                        3558708,
                        2950909,
                        3538248,
                        3188261,
                        6608642,
                        3287896,
                        3827872,
                        2726974,
                        1550038,
                        1352719,
                        1346782,
                        1694023,
                        1482589,
                        806377,
                        2387014,
                        2103447,
                        2282139,
                        1101118,
                        823106,
                        720045,
                        801665,
                        719459,
                        801831,
                        291427,
                        19628,
                        18925,
                        42584,
                        289765,
                        104998,
                        41317,
                        2224572,
                        13419396,
                        17571489,
                        1049404,
                        895124,
                        971721,
                        5252847,
                        7452125,
                        15133756,
                        7070454,
                        1925742,
                        1664654,
                        10772297,
                        12293485,
                        783380,
                        531827,
                        1788977,
                        7528664,
                        7186951,
                        390521,
                        597022,
                        713424,
                        1063503,
                        2020113,
                        4636836,
                        2340943,
                        2493373,
                        1326655,
                        1962659,
                        1703996,
                        2109934,
                        4361043,
                        1817325,
                        504778,
                        574869,
                        510682,
                        730156,
                        899053,
                        599753,
                        516090,
                        608611,
                        517838,
                        552662,
                        496878,
                        537991,
                        467204,
                        499607,
                        422824,
                        478628,
                        586333,
                        1380942,
                        1472673,
                        3349559,
                        3823316,
                        8794144,
                        6577472
                    ],
                    "ext_label": "SFP_ 1 (Slot: 0 Port: 25 10G - Level)",
                    "statistics": {
                        "average": 1411802.2344214,
                        "min_val_idx": 195,
                        "95th_percentile": 4361043,
                        "total": 1712798470800,
                        "max_val_idx": 283,
                        "min_val": 0,
                        "max_val": 17571489
                    },
                    "tags": {
                        "if_index": "25",
                        "ifid": "-1",
                        "device": "10.57.1.175"
                    },
                    "name": "25"
                },
                {
                    "id": "bytes",
                    "data": [
                        55545,
                        62216,
                        55231,
                        138944,
                        64827,
                        64438,
                        55402,
                        61246,
                        56095,
                        2342097,
                        3759249,
                        5033862,
                        2849544,
                        77232,
                        59705,
                        70575,
                        57997,
                        65818,
                        60371,
                        63705,
                        63487,
                        71147,
                        60713,
                        63651,
                        54664,
                        60948,
                        56751,
                        63274,
                        55089,
                        61242,
                        54368,
                        2242111,
                        2056311,
                        63808,
                        56782,
                        64203,
                        58522,
                        70207,
                        59640,
                        66358,
                        57390,
                        63917,
                        56873,
                        63759,
                        58774,
                        65520,
                        57621,
                        66267,
                        63450,
                        66754,
                        59480,
                        150266,
                        66428,
                        68692,
                        61723,
                        69104,
                        59964,
                        67275,
                        61251,
                        68104,
                        60038,
                        76112,
                        63708,
                        73391,
                        60569,
                        73553,
                        63142,
                        69612,
                        2207030,
                        5437108,
                        63607,
                        70658,
                        57151,
                        64654,
                        57650,
                        67099,
                        56618,
                        65080,
                        630734,
                        2411281,
                        2204200,
                        65076,
                        58070,
                        66189,
                        60830,
                        65176,
                        58422,
                        72192,
                        61816,
                        64739,
                        56752,
                        66990,
                        64402,
                        67092,
                        57535,
                        65984,
                        58651,
                        75527,
                        59622,
                        209740,
                        79994,
                        65452,
                        56944,
                        63818,
                        56873,
                        63365,
                        56440,
                        65854,
                        57282,
                        64370,
                        57527,
                        64923,
                        57402,
                        64621,
                        59043,
                        67481,
                        62947,
                        69556,
                        63366,
                        69626,
                        58560,
                        64816,
                        58812,
                        66131,
                        58821,
                        64752,
                        58703,
                        2363124,
                        2262426,
                        65145,
                        59152,
                        64189,
                        59096,
                        64400,
                        59046,
                        68995,
                        59032,
                        66319,
                        62773,
                        69830,
                        61646,
                        68396,
                        59354,
                        66605,
                        60495,
                        66720,
                        60192,
                        146871,
                        70591,
                        69951,
                        61766,
                        70044,
                        68798,
                        70952,
                        60972,
                        76855,
                        59787,
                        64742,
                        236079,
                        1283289,
                        321067,
                        65986,
                        60244,
                        72416,
                        66634,
                        75538,
                        63940,
                        75505,
                        61884,
                        69031,
                        62373,
                        73149,
                        61011,
                        69991,
                        60735,
                        1996715,
                        2196863,
                        69019,
                        62047,
                        69754,
                        60929,
                        69642,
                        63025,
                        73271,
                        61342,
                        67975,
                        60154,
                        72430,
                        63269,
                        68403,
                        59793,
                        71198,
                        62538,
                        70203,
                        63226,
                        0,
                        0,
                        69622,
                        65176,
                        68929,
                        60519,
                        69067,
                        58130,
                        65350,
                        61212,
                        68316,
                        60253,
                        71215,
                        64203,
                        72047,
                        63229,
                        71351,
                        62078,
                        70451,
                        57739,
                        69776,
                        57837,
                        63492,
                        57459,
                        64797,
                        56559,
                        63839,
                        57393,
                        2169982,
                        2216072,
                        65609,
                        59243,
                        66606,
                        58799,
                        65971,
                        60278,
                        73540,
                        66746,
                        70418,
                        62018,
                        68130,
                        63167,
                        72108,
                        63503,
                        66999,
                        59135,
                        66443,
                        59417,
                        90360,
                        118340,
                        121194,
                        104473,
                        77910,
                        62551,
                        71037,
                        62091,
                        69186,
                        63543,
                        71576,
                        169515,
                        16894431,
                        268747,
                        67607,
                        60798,
                        67442,
                        62218,
                        71589,
                        63369,
                        74651,
                        67311,
                        75224,
                        63348,
                        69445,
                        61788,
                        67883,
                        59573,
                        66065,
                        2079401,
                        3350679,
                        2325012,
                        65713,
                        58634,
                        65561,
                        58775,
                        66148,
                        58095,
                        68067,
                        61453,
                        68363,
                        59382,
                        68139,
                        60307,
                        69086,
                        58635,
                        67551,
                        60901,
                        74731,
                        63000,
                        271199,
                        94423,
                        69478,
                        62234,
                        73427,
                        63186,
                        71011,
                        61382,
                        70163,
                        62468,
                        72250,
                        63289,
                        73719,
                        65827,
                        71108,
                        63422,
                        73290,
                        63187,
                        73431,
                        64240,
                        68522,
                        61423,
                        69610,
                        60867,
                        68784,
                        59513,
                        66218,
                        59608,
                        1914785,
                        2176622,
                        66807,
                        60604,
                        65883,
                        59435,
                        67252,
                        59571,
                        67580,
                        60525,
                        66995,
                        60876,
                        69942,
                        63524,
                        68534,
                        53742
                    ],
                    "ext_label": "Port 2 (Slot: 0 Port: 2 Gigabit - Level)",
                    "statistics": {
                        "average": 284864.31750742,
                        "min_val_idx": 195,
                        "95th_percentile": 2079401,
                        "total": 345597390000,
                        "max_val_idx": 255,
                        "min_val": 0,
                        "max_val": 16894431
                    },
                    "tags": {
                        "if_index": "2",
                        "ifid": "-1",
                        "device": "10.57.1.175"
                    },
                    "name": "2"
                },
                {
                    "id": "bytes",
                    "data": [
                        60846,
                        68544,
                        60377,
                        67662,
                        60509,
                        67148,
                        59354,
                        66508,
                        59289,
                        65204,
                        60200,
                        66230,
                        62813,
                        66333,
                        66407,
                        78010,
                        65890,
                        113376,
                        95201,
                        76159,
                        67850,
                        74400,
                        68243,
                        66452,
                        60142,
                        65558,
                        60461,
                        67279,
                        60084,
                        65431,
                        59069,
                        67071,
                        61603,
                        67999,
                        3800712,
                        3566791,
                        62589,
                        78911,
                        67787,
                        69455,
                        62454,
                        68521,
                        62367,
                        69521,
                        64219,
                        71476,
                        63507,
                        72893,
                        70043,
                        82644,
                        69278,
                        80177,
                        69373,
                        78195,
                        73406,
                        81586,
                        69417,
                        79426,
                        72879,
                        77310,
                        64216,
                        78188,
                        76379,
                        83498,
                        69958,
                        87255,
                        77989,
                        79269,
                        68979,
                        79239,
                        81845,
                        82883,
                        65082,
                        73224,
                        65929,
                        73052,
                        64338,
                        72173,
                        64095,
                        71969,
                        68582,
                        72004,
                        3782535,
                        3431088,
                        66064,
                        79124,
                        72710,
                        88470,
                        73562,
                        71302,
                        62440,
                        73211,
                        71814,
                        75824,
                        70817,
                        79081,
                        69395,
                        78388,
                        69177,
                        80826,
                        74461,
                        73719,
                        63597,
                        71021,
                        64335,
                        71320,
                        63454,
                        76153,
                        65160,
                        72755,
                        65108,
                        69611,
                        63712,
                        72488,
                        67564,
                        78889,
                        65936,
                        76312,
                        73490,
                        78008,
                        65278,
                        71978,
                        64812,
                        71880,
                        64146,
                        71892,
                        69377,
                        71346,
                        63435,
                        71676,
                        3644985,
                        3926491,
                        65598,
                        72536,
                        67690,
                        79475,
                        66350,
                        74227,
                        66531,
                        73985,
                        72970,
                        81998,
                        69169,
                        78738,
                        72201,
                        78627,
                        72567,
                        86925,
                        83502,
                        88106,
                        74854,
                        85048,
                        78608,
                        81894,
                        74703,
                        82982,
                        76022,
                        76801,
                        65520,
                        74399,
                        73289,
                        74891,
                        71645,
                        88458,
                        78495,
                        88904,
                        74263,
                        82932,
                        68497,
                        74360,
                        67053,
                        73654,
                        66276,
                        73445,
                        65322,
                        73810,
                        66619,
                        73224,
                        3418458,
                        4217131,
                        66037,
                        73706,
                        71580,
                        86394,
                        75329,
                        79051,
                        72798,
                        91133,
                        77239,
                        77906,
                        72382,
                        87581,
                        77335,
                        87278,
                        79556,
                        0,
                        0,
                        80251,
                        78931,
                        82006,
                        71966,
                        82867,
                        67901,
                        74069,
                        73300,
                        83005,
                        72969,
                        83628,
                        76897,
                        85400,
                        75877,
                        83088,
                        73170,
                        78771,
                        65355,
                        74302,
                        64804,
                        69969,
                        64291,
                        68627,
                        61767,
                        68406,
                        62220,
                        70434,
                        63145,
                        70624,
                        3405489,
                        4332215,
                        63585,
                        73050,
                        68342,
                        85306,
                        79868,
                        85947,
                        75431,
                        78177,
                        73963,
                        82316,
                        72600,
                        75028,
                        65497,
                        74062,
                        65896,
                        74946,
                        71203,
                        85583,
                        77905,
                        82801,
                        73695,
                        86460,
                        72537,
                        83348,
                        76406,
                        86686,
                        73691,
                        82180,
                        72641,
                        77140,
                        69529,
                        77748,
                        69689,
                        78076,
                        76927,
                        86227,
                        80114,
                        88715,
                        74248,
                        77158,
                        68404,
                        74219,
                        65961,
                        73195,
                        65715,
                        73915,
                        63603,
                        69688,
                        3539671,
                        3259378,
                        64123,
                        69704,
                        62543,
                        74893,
                        73335,
                        79660,
                        67716,
                        74723,
                        69413,
                        78351,
                        65110,
                        74699,
                        71952,
                        84317,
                        71471,
                        81879,
                        70772,
                        75787,
                        71495,
                        85613,
                        73345,
                        78814,
                        67865,
                        76591,
                        69171,
                        78201,
                        70749,
                        84890,
                        76121,
                        78625,
                        69494,
                        77456,
                        69978,
                        78358,
                        71229,
                        74316,
                        67402,
                        73725,
                        66368,
                        71800,
                        64848,
                        71869,
                        65134,
                        71705,
                        64642,
                        71820,
                        3764741,
                        4322706,
                        64081,
                        71807,
                        64240,
                        72921,
                        67438,
                        74757,
                        67134,
                        80803,
                        75704,
                        78593,
                        66397
                    ],
                    "ext_label": "Port 6 (Slot: 0 Port: 6 Gigabit - Level)",
                    "statistics": {
                        "average": 225070.22848665,
                        "min_val_idx": 195,
                        "95th_percentile": 88715,
                        "total": 273055201200,
                        "max_val_idx": 227,
                        "min_val": 0,
                        "max_val": 4332215
                    },
                    "tags": {
                        "if_index": "6",
                        "ifid": "-1",
                        "device": "10.57.1.175"
                    },
                    "name": "6"
                },
                {
                    "id": "bytes",
                    "data": [
                        1189,
                        1276,
                        1184,
                        1309,
                        1180,
                        1276,
                        1176,
                        1259,
                        1178,
                        1258,
                        1160,
                        1289,
                        1200,
                        1283,
                        1285,
                        1427,
                        1297,
                        1404,
                        1267,
                        1341,
                        1204,
                        1335,
                        1254,
                        1339,
                        1225,
                        1342,
                        1287,
                        1395,
                        1233,
                        1340,
                        1239,
                        1337,
                        1235,
                        1356,
                        1220,
                        1347,
                        1285,
                        1384,
                        1285,
                        1385,
                        1185,
                        1299,
                        1203,
                        1339,
                        1231,
                        1336,
                        1201,
                        1337,
                        1221,
                        1317,
                        1192,
                        1359,
                        1221,
                        1309,
                        1188,
                        1322,
                        1192,
                        1327,
                        1208,
                        1390,
                        1192,
                        1405,
                        1316,
                        1413,
                        1257,
                        1376,
                        1252,
                        1397,
                        1244,
                        1379,
                        1257,
                        1380,
                        1244,
                        1371,
                        1250,
                        1412,
                        1248,
                        1360,
                        1244,
                        1366,
                        1408,
                        1367,
                        1236,
                        1377,
                        1257,
                        1392,
                        1268,
                        1412,
                        1272,
                        1364,
                        1185,
                        1335,
                        1194,
                        1304,
                        1220,
                        1329,
                        1237,
                        1320,
                        1226,
                        1372,
                        1225,
                        1321,
                        1221,
                        1315,
                        1164,
                        1305,
                        1184,
                        1309,
                        1173,
                        1339,
                        1165,
                        1318,
                        1182,
                        1385,
                        1251,
                        1379,
                        1245,
                        1386,
                        1242,
                        1381,
                        1227,
                        1355,
                        1249,
                        1410,
                        1232,
                        1367,
                        1212,
                        1355,
                        1217,
                        1364,
                        1219,
                        1343,
                        1212,
                        1359,
                        1262,
                        1431,
                        1294,
                        1430,
                        1228,
                        1334,
                        1208,
                        1320,
                        1193,
                        1341,
                        1223,
                        1348,
                        1229,
                        1380,
                        1202,
                        1311,
                        1205,
                        1397,
                        1283,
                        1389,
                        1235,
                        1348,
                        1200,
                        1354,
                        1321,
                        1481,
                        1266,
                        1338,
                        1252,
                        1377,
                        1259,
                        1473,
                        1276,
                        1389,
                        1268,
                        1380,
                        1219,
                        1367,
                        1218,
                        1320,
                        1215,
                        1318,
                        1208,
                        1325,
                        1199,
                        1325,
                        1214,
                        1330,
                        1250,
                        1412,
                        1298,
                        1394,
                        1286,
                        1425,
                        1314,
                        1398,
                        1240,
                        1387,
                        1259,
                        1361,
                        1312,
                        0,
                        0,
                        1727,
                        1529,
                        1640,
                        1481,
                        1622,
                        1456,
                        1648,
                        1537,
                        1677,
                        1442,
                        1681,
                        1515,
                        1650,
                        1526,
                        1635,
                        1478,
                        1632,
                        1459,
                        1622,
                        1471,
                        1535,
                        1421,
                        1561,
                        1385,
                        1485,
                        1377,
                        1498,
                        1393,
                        1491,
                        1386,
                        1524,
                        1382,
                        1514,
                        1481,
                        1552,
                        1409,
                        1553,
                        1404,
                        1553,
                        1494,
                        1578,
                        1427,
                        1538,
                        1458,
                        1541,
                        1361,
                        1566,
                        1439,
                        1590,
                        1454,
                        1580,
                        1450,
                        1608,
                        1445,
                        1557,
                        1406,
                        1553,
                        1415,
                        1609,
                        1464,
                        1610,
                        1445,
                        1590,
                        1429,
                        1534,
                        1410,
                        1542,
                        1423,
                        1566,
                        1561,
                        1603,
                        1447,
                        1538,
                        1416,
                        1569,
                        1418,
                        1557,
                        1337,
                        1497,
                        1376,
                        1521,
                        1330,
                        1519,
                        1378,
                        1580,
                        1420,
                        1587,
                        1414,
                        1559,
                        1400,
                        1548,
                        1400,
                        1542,
                        1415,
                        1539,
                        1408,
                        1635,
                        1432,
                        1543,
                        1415,
                        1652,
                        1439,
                        1634,
                        1466,
                        1659,
                        1508,
                        1628,
                        1513,
                        1907,
                        1904,
                        1788,
                        1430,
                        1580,
                        1432,
                        1559,
                        1505,
                        2327,
                        2208,
                        2611,
                        2313,
                        1766,
                        1370,
                        1501,
                        1360,
                        1511,
                        1361,
                        1521,
                        1363,
                        1507,
                        1364,
                        1553,
                        1404,
                        1606,
                        1428,
                        1566,
                        1362,
                        1535,
                        1385,
                        1551,
                        1150
                    ],
                    "ext_label": " CPU Interface for Slot:… (CPU Interface:
 5/1)",
                    "statistics": {
                        "average": 1385.9198813056,
                        "min_val_idx": 195,
                        "95th_percentile": 1634,
                        "total": 1681398000,
                        "max_val_idx": 315,
                        "min_val": 0,
                        "max_val": 2611
                    },
                    "tags": {
                        "if_index": "65",
                        "ifid": "-1",
                        "device": "10.57.1.175"
                    },
                    "name": "65"
                },
                {
                    "id": "bytes",
                    "data": [
                        864,
                        927,
                        867,
                        942,
                        859,
                        933,
                        850,
                        909,
                        863,
                        917,
                        845,
                        948,
                        880,
                        947,
                        1000,
                        1082,
                        988,
                        1068,
                        956,
                        1002,
                        892,
                        996,
                        937,
                        997,
                        914,
                        1003,
                        973,
                        1037,
                        919,
                        1009,
                        926,
                        1014,
                        921,
                        1018,
                        903,
                        1016,
                        972,
                        1048,
                        970,
                        1025,
                        866,
                        961,
                        883,
                        1009,
                        939,
                        1010,
                        902,
                        1019,
                        913,
                        978,
                        879,
                        1000,
                        895,
                        974,
                        875,
                        980,
                        876,
                        980,
                        893,
                        1052,
                        868,
                        1069,
                        1001,
                        1051,
                        934,
                        1031,
                        932,
                        1055,
                        936,
                        1043,
                        946,
                        1042,
                        929,
                        1026,
                        930,
                        1047,
                        926,
                        1024,
                        928,
                        1024,
                        1228,
                        1026,
                        919,
                        1037,
                        942,
                        1054,
                        958,
                        1053,
                        942,
                        1020,
                        870,
                        984,
                        875,
                        964,
                        892,
                        981,
                        913,
                        977,
                        905,
                        1013,
                        902,
                        978,
                        902,
                        977,
                        852,
                        969,
                        882,
                        976,
                        867,
                        1001,
                        852,
                        955,
                        868,
                        1061,
                        934,
                        1041,
                        931,
                        1050,
                        932,
                        1047,
                        918,
                        1023,
                        929,
                        1048,
                        903,
                        1020,
                        903,
                        1018,
                        904,
                        1025,
                        900,
                        1006,
                        902,
                        1023,
                        949,
                        1063,
                        975,
                        1101,
                        921,
                        1005,
                        900,
                        995,
                        885,
                        1012,
                        912,
                        1015,
                        921,
                        1022,
                        879,
                        973,
                        896,
                        1061,
                        971,
                        1065,
                        930,
                        1018,
                        891,
                        1015,
                        1017,
                        1137,
                        953,
                        1001,
                        935,
                        1032,
                        935,
                        1123,
                        951,
                        1048,
                        951,
                        1037,
                        900,
                        1004,
                        898,
                        979,
                        894,
                        975,
                        891,
                        977,
                        883,
                        976,
                        900,
                        980,
                        932,
                        1050,
                        977,
                        1057,
                        966,
                        1079,
                        994,
                        1059,
                        923,
                        1047,
                        950,
                        1065,
                        12988,
                        0,
                        0,
                        1224,
                        1070,
                        1131,
                        1021,
                        1111,
                        994,
                        1144,
                        1070,
                        1171,
                        983,
                        1149,
                        1045,

**Comment by MatteoBiscosi** [comment] 2024-11-04 16:06
Hi @dkggpeters the issue should be fixed, in a couple of hours a new build should be available, please update and let me know

**Comment by dkggpeters** [comment] 2024-11-05 01:08
Fixed.  Thank you.

**Closed as completed** 2024-11-05 08:19 UTC
Labels: Ready to Test
