### ISSUE TITLE
No "Realtime Traffic" Graph in v2.1.151015 - Professional Edition

### ISSUE THREAD

**Issue by mineumann** [ntop/ntopng#238] opened 2015-10-15 11:43 UTC
View interface has been removed from graphs - thank you - but now there are no graphs at all for "Realtime Traffic". "Realtime Top Application Traffic" works.

**Comment by simonemainardi** [comment] 2015-10-15 23:01
@mineumann I can't reproduce this issue on Ubuntu 14.04. See The image attached.
I would suggest you to: clean `/var/tmp/ntopng` and flush redis.
If the issue persists, try to right click on the missing chart and inspect the element, using either the browser builtin debugger or third-party tools such as firebug. Please, report any error or warning that may  appear.


![screenshot](https://cloud.githubusercontent.com/assets/3397663/10529789/4ca99dc0-73a1-11e5-9676-28e9ada31d28.png)

**Comment by mineumann** [comment] 2015-10-16 06:19
i  ntopng                                                2.1.151016-635                  amd64                           Web-based traffic monitoring.

my box is a nbox2:
lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

TypeError: ifaces_realtime_data[i] is undefined
Stack-Trace:
.success/<@http://ntop01:3000/lua/pro/dashboard.lua:1328:1
.each@http://ntop01:3000/js/jquery.js:383:14
.success@http://ntop01:3000/lua/pro/dashboard.lua:1305:6
jQuery.Callbacks/fire@http://ntop01:3000/js/jquery.js:3119:10
jQuery.Callbacks/self.fireWith@http://ntop01:3000/js/jquery.js:3231:7
done@http://ntop01:3000/js/jquery.js:9275:5
.send/callback@http://ntop01:3000/js/jquery.js:9685:8
 dashboard.lua:1370:7
TypeError: ifaces_realtime_data[i] is undefined
Stack-Trace:
.success/<@http://ntop01:3000/lua/pro/dashboard.lua:1328:1
.each@http://ntop01:3000/js/jquery.js:383:14
.success@http://ntop01:3000/lua/pro/dashboard.lua:1305:6
jQuery.Callbacks/fire@http://ntop01:3000/js/jquery.js:3119:10
jQuery.Callbacks/self.fireWith@http://ntop01:3000/js/jquery.js:3231:7
done@http://ntop01:3000/js/jquery.js:9275:5
.send/callback@http://ntop01:3000/js/jquery.js:9685:8
 dashboard.lua:1370:7
TypeError: ifaces_realtime_data[i] is undefined

**Comment by simonemainardi** [comment] 2015-10-16 16:15
fixed in 866d849

update script for real time traffic was not skipping interface views

**Closed by simonemainardi** 2015-10-16 16:15 UTC
Labels: bug
