### ISSUE TITLE
Increase of usage memory to 100%

### ISSUE THREAD

**Issue by thomasbruchet** [ntop/ntopng#6320] opened 2022-02-16 13:49 UTC
Hello,

I would like to report a problem with memory usage since my last update on January 28. I could not update the system until March because I have a degree exam and I need ntopng to work even in case of error. 

Version	ntopng Enterprise M v.5.1.220128 rev.16608 (Debian GNU/Linux 10 (buster)) |
Platform	Debian 10.8 [x86_64][Debian GNU/Linux 10 (buster)] - 64 bit

There was a previous restart of ntopng service on february 10th to correct the same issue, so in 6 days, the memory is full. According to the graph, this never append before.
![image](https://user-images.githubusercontent.com/86605223/154277101-31242d0b-19f2-4652-b89b-84bcc6193497.png)
![image](https://user-images.githubusercontent.com/86605223/154275553-61854634-f955-4d89-a8e6-b3e9fa46a0fa.png)

System
CPU Load 	0
CPU States 	iowait: 5.8% / active: 16.5% / idle: 77.7%
RAM 	Used: 93.17% / Available: 1.07 GB / Total: 15.61 GB
ntopng
PID (Process ID)	19777
RAM 	Used: 13.87 GB
Alerts 	Queries: 738,960 / Stored: 0 / Dropped: 0

![image](https://user-images.githubusercontent.com/86605223/154276760-12af83a6-8d9c-409c-90d3-e14eb26c0b4b.png)
The service clickhouse is running but ntopng don't use it because on my last try to set it up, I failed to start ntopng with it.

Are you aware of this memory issue ? 
Is there something that I give to you to help to troubleshoot ?

**Comment by lucaderi** [comment] 2022-02-16 17:24
This looks a problem similar to #6295

**Comment by thomasbruchet** [comment] 2022-02-17 07:50
Hello. 
I will follow the resolution of this incident.
Thank you.

**Comment by cardigliano** [comment] 2022-02-25 09:07
Closing as duplicate of #6295

**Closed as completed by cardigliano** 2022-02-25 09:07 UTC
