### ISSUE TITLE
problem to ntopng config

### ISSUE THREAD

**Issue by guebre80** [ntop/ntopng#306] opened 2015-12-07 02:25 UTC
Hello everyone!!! I just ask for your help concerning ntopng configuration. I installed it with no problem but when I run the following command, I have this:

#sudo service redis-server restart && sudo service ntopng restart 
Stopping redis-server: redis-server. Starting redis-server: redis-server.
Unable to start ntopng [fail]

Stopping ntopng /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments
Starting ntopng /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments /etc/init.d/ntopng: line 64: [: too many arguments /etc/init.d/ntopng: line 68: [: too many arguments

I really need your help. thank you in advance!!!

**Comment by lucaderi** [comment] 2015-12-07 03:08
Can you please share your ntopng.conf file? I think there is a problem with the PID_FILE entry

**Comment by guebre80** [comment] 2015-12-07 03:18
ok. thank for your request. 

# /etc/ntopng/ntopng.conf
#
#        The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -G|--pid-path
#        Specifies the path where the PID (process ID) is saved.
#
-G=/var/tmp/ntopng.pid
#
#       -e|--daemon
#        This  parameter  causes ntop to become a daemon, i.e. a task which runs in the background
#        without connection to a specific terminal. To use ntop other than as a casual  monitoring
#        tool, you probably will want to use this option.
#
-e=
#
#       -i|--interface
#        Specifies  the  network  interface or collector endpoint to be used by ntopng for network
#        monitoring. On Unix you can specify both the interface name  (e.g.  lo)  or  the  numeric
#        interface id as shown by ntopng -h. On Windows you must use the interface number instead.
#        Note that you can specify -i multiple times in order to instruct ntopng to create  multi‐
#        ple interfaces.
#
-i=1
#
#       -w|--http-port
#        Sets the HTTP port of the embedded web server.
#
-w=3000
#
#       -m|--local-networks
#        ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
#        those  networks  is considered local. This parameter allows the user to define additional
#        networks and subnetworks whose traffic is also considered local in  ntopng  reports.  All
#        other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
#        Commas  separate  multiple  network  values.  Both netmask and CIDR notation may be used,
#        even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
-m=192.168.1.0/24
#
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 0 - Decode DNS responses  and  resolve  only  local
#        (-m)  numeric  IPs  1  -  Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
#        responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't  resolve
#
-n=1
#
#       -S|--sticky-hosts
#        ntopng  periodically purges idle hosts. With this option you can modify this behaviour by
#        telling ntopng not to purge the hosts specified by -S. This parameter requires  an  argu‐
#        ment  that  can  be  "all"  (Keep  all hosts in memory), "local" (Keep only local hosts),
#        "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
-S=
#
#       -d|--data-dir
#        Specifies the data directory (it must be writable). Default directory is ./data
#
-d=/var/tmp/ntopng
#
#       -q|--disable-autologout
#        Disable web interface logout for inactivity.
#
-q=

**Comment by guebre80** [comment] 2015-12-07 03:21
# /etc/ntopng/ntopng.conf
#
#        The  configuration  file is similar to the command line, with the exception that an equal
#        sign '=' must be used between key and value. Example:  -i=p1p2  or  --interface=p1p2  For
#        options with no value (e.g. -v) the equal is also necessary. Example: "-v=" must be used.
#
#
#       -G|--pid-path
#        Specifies the path where the PID (process ID) is saved.
#
-G=/var/tmp/ntopng.pid
#
#       -e|--daemon
#        This  parameter  causes ntop to become a daemon, i.e. a task which runs in the background
#        without connection to a specific terminal. To use ntop other than as a casual  monitoring
#        tool, you probably will want to use this option.
#
-e=
#
#       -i|--interface
#        Specifies  the  network  interface or collector endpoint to be used by ntopng for network
#        monitoring. On Unix you can specify both the interface name  (e.g.  lo)  or  the  numeric
#        interface id as shown by ntopng -h. On Windows you must use the interface number instead.
#        Note that you can specify -i multiple times in order to instruct ntopng to create  multi‐
#        ple interfaces.
#
-i=1
#
#       -w|--http-port
#        Sets the HTTP port of the embedded web server.
#
-w=3000
#
#       -m|--local-networks
#        ntopng determines the ip addresses and netmasks for each active interface. Any traffic on
#        those  networks  is considered local. This parameter allows the user to define additional
#        networks and subnetworks whose traffic is also considered local in  ntopng  reports.  All
#        other hosts are considered remote. If not specified the default is set to 192.168.1.0/24.
#
#        Commas  separate  multiple  network  values.  Both netmask and CIDR notation may be used,
#        even mixed together, for instance "131.114.21.0/24,10.0.0.0/255.0.0.0".
#
-m=192.168.1.0/24
#
#       -n|--dns-mode
#        Sets the DNS address resolution mode: 0 - Decode DNS responses  and  resolve  only  local
#        (-m)  numeric  IPs  1  -  Decode DNS responses and resolve all numeric IPs 2 - Decode DNS
#        responses and don't resolve numeric IPs 3 - Don't decode DNS responses and don't  resolve
#
-n=1
#
#       -S|--sticky-hosts
#        ntopng  periodically purges idle hosts. With this option you can modify this behaviour by
#        telling ntopng not to purge the hosts specified by -S. This parameter requires  an  argu‐
#        ment  that  can  be  "all"  (Keep  all hosts in memory), "local" (Keep only local hosts),
#        "remote" (Keep only remote hosts), "none" (Flush hosts when idle).
#
-S=
#
#       -d|--data-dir
#        Specifies the data directory (it must be writable). Default directory is ./data
#
-d=/var/tmp/ntopng
#
#       -q|--disable-autologout
#        Disable web interface logout for inactivity.
#
-q=

**Comment by lucaderi** [comment] 2015-12-07 04:22
Please try https://github.com/ntop/ntopng/commit/79987215556890ff60f03b3e8d08182ff299cce0 or send me (deri@ntop.org) your config file via email so I make sure its format is not changed

**Comment by guebre80** [comment] 2015-12-07 23:40
#! /bin/bash 
# 
# (C) 2003-13 - ntop.org 
# 
# chkconfig: 2345 80 30 
# 
### BEGIN INIT INFO 
# Provides:          ntopng 
# Required-Start:    $local_fs $remote_fs $network $syslog $pf_ring 
# Required-Stop:     $local_fs $remote_fs $network $syslog 
# Default-Start:     2 3 4 5 
# Default-Stop:      0 1 6 
# Short-Description: Start/stop ntopng web 
### END INIT INFO 

if [ -f /lib/lsb/init-functions ]; then 
   DISTRO="debian" 
   . /lib/lsb/init-functions 
fi 
if [ -f /etc/init.d/functions ]; then 
   DISTRO="centos" 
   . /etc/init.d/functions 
fi 

ERROR=0 
NTOPNG_BINARY=/usr/bin/ntopng 

# 
# This to avoid issues in case there are local files 
# (Example when ntopng has been cloned from git) 
# 
cd / 

error_handler() { 
    EXIT_ON_END=$0 

    if [ -n "${MSG}" ]; then 
	if [ ${ERROR} -gt 0 ]; then 
	    if [ ${DISTRO} == "debian" ]; then 
		log_failure_msg "${MSG}" 
		log_end_msg $ERROR 
	    elif [ ${DISTRO} == "centos" ]; then 
		echo -n ${MSG} 
		echo_failure; echo 
	    fi 
	else 
	    [ ${DISTRO} == "debian" ] && log_end_msg $ERROR 
	    [ ${DISTRO} == "centos" ] && echo_success && echo 
	fi 
    fi 

    if [ "$EXIT_ON_END" == "quit" ]; then 
	exit 99 
    fi 
} 

get_ntopng_pid() { 
    if [ -f "/etc/ntopng/ntopng.conf" ]; then 
        PID_FILE=$(cat /etc/ntopng/ntopng.conf | grep -E '\-G=|--pid'|cut -d '=' -f 2) 
    else 
        PID_FILE="/var/tmp/ntopng.pid" 
    fi 
 
    if [ -z $PID_FILE ]; then 
	return 0 
    fi 

    if [ -f $PID_FILE ]; then 
 	PID=$(cat $PID_FILE) 
        if [ -z "${PID}" ]; then 
	    /bin/rm $PID_FILE 
	else 
	    echo ${PID} 
            if [ $PID -gt 0 ]; then 
		IS_EXISTING=$(ps auxw | grep -w $PID | grep -v grep | wc -l) 
		if [ ${IS_EXISTING} -gt 0 ]; then 
		    return $PID 
		else 
		    /bin/rm $PID_FILE 
		fi 
	    fi 
        fi 
    fi 

    PID=0 
    return 0 
} 

start_ntopng() { 
   RETVAL=0 
   FORCE=$1 

    if [ ! -d "/etc/ntopng" ]; then 
	#echo "Configuration directory /etc/ntopng does not exist: quitting..." 
	#echo "This package is designed to be used from within the nBox package that" 
	#echo "configures ntopng using a web GUI. Please install the nBox package" 
	#echo "from http://packages.ntop.org" 
        #MSG="Default directory is missing. Exiting" 
        #ERROR=1 
        #RETVAL=1 
	echo "Creating directory /etc/ntopng" 
	mkdir /etc/ntopng 
    fi 

    if [ ! -f "/etc/ntopng/ntopng.conf" ]; then 
	echo "Generating configuration file /etc/ntopng/ntopng.conf" 
	echo "-G=/var/tmp/ntopng.pid" > /etc/ntopng/ntopng.conf 
        if [ -d /storage ]; then 
            if [ ! -d /storage/ntopng ]; then 
                mkdir /storage/ntopng 
                chmod gou+rxw /storage/ntopng 
            fi 

            echo "-d=/storage/ntopng" >> /etc/ntopng/ntopng.conf 
        fi 
	CHECK_P4P1=`grep p4p1 /proc/net/dev|wc -l` 
        if [ $CHECK_P4P1 -eq 1 ]; then 
            echo "-i=p4p1" >> /etc/ntopng/ntopng.conf 
        fi 
	touch /etc/ntopng/ntopng.start 
    fi 

    if [ -f /etc/ntopng/ntopng.start ] || [ $FORCE -eq 1 ]; then 
	[ ${DISTRO} == "debian" ] && log_daemon_msg "Starting ntopng" 
	[ ${DISTRO} == "centos" ] && echo -n "Starting ntopng: " 
 
	get_ntopng_pid 
	if [ ${PID} -gt 0 ]; then 
	    MSG="ntopng already running. Exiting" 
	    ERROR=1 
	    RETVAL=1 
	    error_handler "quit" 
	    exit 99 
	fi 
	if [ ! -d /var/log/ntopng/ ]; then 
	   mkdir -p /var/log/ntopng/ 
	   touch  /var/log/ntopng/ntopng.log 
	   chmod 777  /var/log/ntopng/ntopng.log 
	fi 
	$NTOPNG_BINARY /etc/ntopng/ntopng.conf >> /var/log/ntopng/ntopng.log & 

	for i in {1..5} 
	do 
	    get_ntopng_pid 
	    if [ $PID -gt 0 ]; then 
		MSG="Started ntopng with PID $PID" 
		ERROR=0 
		break 
	    else 
		MSG="Unable to start ntopng" 
		ERROR=1 
		sleep 1 
	    fi 
	done 

        if [ $ERROR -gt 0 ]; then 
	    error_handler "quit" 
	else 
	    [ ${DISTRO} == "debian" ] && log_end_msg $ERROR 
	    [ ${DISTRO} == "centos" ] && echo_success && echo 
	fi 
    else 
        MSG="Missing /etc/ntopng/ntopng.start. Exiting" 
        ERROR=1 
        RETVAL=1 
	error_handler "quit" 
    fi 
} 


stop_ntopng() { 
    RETVAL=0 
    [ ${DISTRO} == "debian" ] && log_daemon_msg "Stopping ntopng" 
    [ ${DISTRO} == "centos" ] && echo -n "Stopping ntopng: " 

    get_ntopng_pid 

    if [ -z "${PID}" ]; then 
	return 0 
    fi 

    if [ ${PID} -eq 0 ]; then 
        if [ ! -f "/etc/ntopng/ntopng.conf" ]; then 
            MSG="Missing /etc/ntopng/ntopng.conf" 
	    ERROR=1 
	    RETVAL=1 
	    error_handler 
	fi 
 
	return 0 
    fi 

    # Do we really need this check? 
    #if [ ! -d "/etc/ntopng" ]; then 
    #    MSG="Default directory is missing. Exiting" 
    #    error_handler "quit" 
    # 	[ ${DISTRO} == "debian" ] && log_end_msg $ERROR 
    # 	[ ${DISTRO} == "centos" ] && echo_success && echo 
    #	return 0 
    #fi 

    MSG= 
    for i in {1..5} 
    do  
        get_ntopng_pid 
        if [ $PID -gt 0 ]; then 
            kill -15 $PID > /dev/null 
            MSG="Sent kill to ntop PID $PID" 
            sleep 1 
        else 
            MSG="Stopped ntopng PID $PID" 
            break 
        fi  
    done 
    ERROR=0 

    error_handler 
} 

status_ntopng() { 
    if [ ! -d "/etc/ntopng" ]; then 
        MSG="Default directory is missing. Exiting" 
        ERROR=1 
        RETVAL=1 
        error_handler "quit" 
    fi 

    if [ ! -f "/etc/ntopng/ntopng.conf" ]; then 
        MSG="Configuration file is missing. Exiting" 
        ERROR=1 
        RETVAL=1 
        error_handler "quit" 
    fi 

    get_ntopng_pid 
    if [ $PID -gt 0 ]; then 
        echo "ntopng running as ${PID}" 
    else 
	echo "ntopng is not running" 
	exit 1 
    fi 

    return 0 
} 


######## 

logger "ntopng $1" 

case "$1" in 
  start) 
	start_ntopng 0; 
	;; 

  force-start) 
	if [ ! -f /etc/ntopng/ntopng.conf ]; then 
	    echo "ERROR: No configuration file found" 
	    exit 1 
	fi 
	start_ntopng 1; 
	;; 

  stop) 
       	stop_ntopng; 
	;; 

  status) 
	status_ntopng; 
	;; 

  restart) 
        stop_ntopng; 
	start_ntopng 0; 
	;; 

  *) 
	echo "Usage: /etc/init.d/ntopng {start|force-start|stop|restart|status}]" 
	exit 1 
esac 

exit 0

**Comment by guebre80** [comment] 2015-12-07 23:49
how I can do by sending the file directly by 7998721?

**Comment by lmangani** [comment] 2015-12-07 23:52
just drag the file on the comment form and it will upload as attachment - do not copy and paste it

**Comment by guebre80** [comment] 2015-12-08 00:02
[init.d.txt](https://github.com/ntop/ntopng/files/54761/init.d.txt)

**Comment by guebre80** [comment] 2015-12-08 00:04
thank you for all your support

**Comment by lucaderi** [comment] 2015-12-08 00:16
You have sent the wrong file. Let's close this bug, the issue is on the config file you use. Please use the nbox GUI to generate it

**Closed by lucaderi** 2015-12-08 00:16 UTC

**Comment by guebre80** [comment] 2015-12-09 03:51
Hello. after your help, I'm not able to do it live with you. I go to nbox but good prudence I have touched nothing. I expect your help to alleviate the problem. it is about the problems of arguments on line 64 and 68 of /etc/init.d/ntopng. thank you beforehand!!!                                                                                                                                                                                                   Envoyé de mon smartphone BlackBerry 10.                                                                                                                                                                                                                De: Luca DeriEnvoyé: mardi 8 décembre 2015 00:16À: ntop/ntopngRépondre à: ntop/ntopngCc: guebre80Objet: Re: [ntopng] problem to ntopng config (#306)You have sent the wrong file. Let's close this bug, the issue is on the config file you use. Please use the nbox GUI to generate it

—Reply to this email directly or view it on GitHub.

**Comment by lucaderi** [comment] 2015-12-09 04:21
Please send the config file via email if you expect help.

**Comment by guebre80** [comment] 2015-12-09 04:28
For the config file, it's the /etc/init.d/ntopng or /etc/ntopng/ntopng.conf.                                                                                                                                                                                                                                                                                                                                         Envoyé de mon smartphone BlackBerry 10.                                                                                                                                                                                                                De: Luca DeriEnvoyé: mercredi 9 décembre 2015 04:21À: ntop/ntopngRépondre à: ntop/ntopngCc: guebre80Objet: Re: [ntopng] problem to ntopng config (#306)Please send the config file via email if you expect help.

—Reply to this email directly or view it on GitHub.

**Comment by guebre80** [comment] 2015-12-09 04:47
sorry, here is the configuration file.                                                                                                                                                                                                    Envoyé de mon smartphone BlackBerry 10.                                                                                                                                                                                                                De: Luca DeriEnvoyé: mercredi 9 décembre 2015 04:21À: ntop/ntopngRépondre à: ntop/ntopngCc: guebre80Objet: Re: [ntopng] problem to ntopng config (#306)Please send the config file via email if you expect help.

—Reply to this email directly or view it on GitHub.

**Comment by guebre80** [comment] 2015-12-09 15:03
Hello. I have sent you the file. if this is not the right tell me please.                                                                                                                                                                                                                De: Luca DeriEnvoyé: mercredi 9 décembre 2015 04:21À: ntop/ntopngRépondre à: ntop/ntopngCc: guebre80Objet: Re: [ntopng] problem to ntopng config (#306)Please send the config file via email if you expect help.

—Reply to this email directly or view it on GitHub.
