### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by IT-W** [ntop/ntopng#67] opened 2015-06-30 09:40 UTC
We use our NTOP installation as part of our NOC. While running the main page (Top Talkers with actual traffic and the graphs corresponding those) we get this message after a few hours: 
![image](https://cloud.githubusercontent.com/assets/13116221/8428068/335dbd08-1f1c-11e5-90cf-f6206cdea11a.png)
We use Firefox version 37.0.2. Also, if we run this page in IE, after a while the screen freezes without any error.

Anyone else that had this issue?

**Comment by lucaderi** [comment] 2015-06-30 10:12
@IT-W What version of ntopng are you using?

**Comment by IT-W** [comment] 2015-06-30 10:13
2.0.150531 - Professional Edition

**Comment by lucaderi** [comment] 2015-07-02 14:02
Please try the latest dev- build that works for me

**Comment by lucaderi** [comment] 2015-07-06 21:04
No answer. I close it for the time being and perhaps re-open it if you are able to reproduce it

**Closed by lucaderi** 2015-07-06 21:04 UTC
Labels: bug
