### ISSUE TITLE
Historical data aggregation (1W) is broken

### ISSUE THREAD

**Issue by notyourcommy** [ntop/ntopng#6307] opened 2022-02-14 07:37 UTC
**Environment**:
* OS name: Centos 8 Stream
* ntopng version/revision: 
Version:        5.3.220209 [Enterprise/Professional build]
GIT rev:        dev:3485160133149ae4d6559d2a3cc544513e4224e5:20220209

Historical data for 1 week is broken on all hosts. This time it just missing some of the days all of a sudden.

![ntop-1m](https://user-images.githubusercontent.com/56963978/153820113-e2a1203d-b0c0-4208-89c5-3bed3e3bb1d3.png)
![ntop-1w](https://user-images.githubusercontent.com/56963978/153820120-8e5e91a7-ddcf-49cb-9587-0aef54290f3c.png)

**Comment by MatteoBiscosi** [comment] 2022-02-14 09:35
Hi @alexiff I'm not able to reproduce this behavior; could you please try to reduce the time frame from 1 month to 2 weeks and check if the problem still persists? (just to understand where it could be the problem)

**Comment by notyourcommy** [comment] 2022-02-14 11:18
Updated to : 
Version:        5.3.220214 [Enterprise/Professional build]
GIT rev:        dev:b7d97b73d3fc19d8bb8533eaa0d795f3fa85779d:20220214

Now every every historical graph tells me " The query is taking a long time to complete " and now showing any data.

Dropped all data ( Delete interface data) - btw, influx database was not dropped bye this action (bug?)
Dropped influx data with "drop database ntop", created new DB.
Still every historical data dont work and writes   " The query is taking a long time to complete "  - even for 30m single ip
What is going on? Why ntopng is so fragile 

upd. there is data in "download current chart data" but ntopng just can't draw it for some reason and Writes that query is taking a long time.

**Comment by MatteoBiscosi** [comment] 2022-02-14 16:04
we already know about that issue and it's already fixed in the last release

**Comment by notyourcommy** [comment] 2022-02-14 16:10
Ok, since I dropped all data I believe I need a 2-3 days to collect it again and report back with results (regarding week charts)

**Comment by notyourcommy** [comment] 2022-02-21 09:05
I'm back. So 2 pictures - month and week. As you can see week is constructed out of per day avg (and it should be constructed out of 30m avg or something like this) .p.s. Per month stats are 1h avg. 
![new-ntop-1m](https://user-images.githubusercontent.com/56963978/154921447-30cd501d-36ec-4d3a-9f2c-10fa35f797de.png)
![new-ntop-1w](https://user-images.githubusercontent.com/56963978/154921453-41eb770b-7236-480a-85b6-08a983d0f72f.png)

**Comment by notyourcommy** [comment] 2022-02-28 20:02
Values in 1M graph also become 1d avg. What is happening ? 
![1mbroken](https://user-images.githubusercontent.com/56963978/156050584-e42fdbdf-052f-48aa-98c5-6eebb3af2cb3.png)

**Comment by lucaderi** [comment] 2022-03-02 18:01
Please report sudo rrdtool fetch /var/lib/ntopng/X/rrd/Y/Y/Y/Y/bytes.rrd AVERAGE -s 1645574400 -e 1646179200

where X is the interface and Y.Y.Y.Y is the IP address of your host you are depicting

**Comment by notyourcommy** [comment] 2022-03-02 18:56
And what if we are on Influx?

**Comment by notyourcommy** [comment] 2022-03-06 07:04
@lucaderi ? We are on Influx and it's not hosts, it AS, Host Pools and everything.

**Comment by MatteoBiscosi** [comment] 2022-03-14 10:26
Hi @alexiff I doubled the time aggregation requested on influxdb, the per month values should be around 1 per hour and the per week, around 1 per 30 minute.
In a couple of hours a new update should be available, update and let me know.
Just to be sure, could you please reload the chart page and send me the query received by influxDB?

![Screenshot from 2022-03-14 10-53-32](https://user-images.githubusercontent.com/49585191/158148714-4c8d50b1-2812-4eb9-a669-104d7072406b.png)
![Screenshot from 2022-03-14 10-53-46](https://user-images.githubusercontent.com/49585191/158148719-33110178-2437-4fe6-a96b-77795c733740.png)

**Comment by notyourcommy** [comment] 2022-03-14 10:37
@MatteoBiscosi  
>Just to be sure, could you please reload the chart page and send me the query received by influxDB?
How can I do this?

**Comment by MatteoBiscosi** [comment] 2022-03-14 10:45
https://docs.influxdata.com/influxdb/v1.8/troubleshooting/query_management/#

This is for influxdb 1.8 version, I don't know if there are other ways for the latest influxdb versions.
Otherwise you can check it out partially from ntopng by right click the ntopng web gui, click inspect and switch to the network tab.
![Screenshot from 2022-03-14 11-42-09](https://user-images.githubusercontent.com/49585191/158156643-80850d2e-2b29-4b8c-a513-2d6c2a99e061.png)
Reload the page and select the latest ts.lua request, go in the response tab and send me back the whole output of that tab (like the one in the screenshot). Send me the answer via e-mail cause there could be sensible information (`biscosi at ntop.org`)

**Comment by notyourcommy** [comment] 2022-03-14 10:58
@MatteoBiscosi sent (via email)

**Comment by MatteoBiscosi** [comment] 2022-03-14 11:09
Hi @alexiff, like expected, you have a lot of data and in order to do not overexert the browser and influxdb by asking for a possibly really huge query, ntopng aggregate the time in a basis of daily aggregation (`"raw_step":86400`) please let me know if the new update you are going to see a more granular chart or not (you can easily check it by check the `raw_step` data, e.g. in my case it's 3600, in fact i have a per hour aggregation)

**Comment by notyourcommy** [comment] 2022-03-14 11:39
@MatteoBiscosi 
Updated but something not quite right. As you can see on screenshot 1M graph now have 2 points per day - One at 02:00 that has value and another at 14:00 that is empty
![ntop-newnew](https://user-images.githubusercontent.com/56963978/158164549-84b0315b-e3ee-4536-be8e-47541e1b5c06.png)
t

**Comment by MatteoBiscosi** [comment] 2022-03-14 11:42
Hi @alexiff please send me via email both the headers and response tab of ts.lua request (like before)

**Comment by notyourcommy** [comment] 2022-03-14 11:47
Sent

**Comment by notyourcommy** [comment] 2022-03-18 08:24
Fixed. Thank you.

**Closed as completed** 2022-03-18 08:24 UTC
Labels: Ready to Test
