### ISSUE TITLE
/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>'

### ISSUE THREAD

**Issue by ascaris5** [ntop/ntopng#3278] opened 2020-01-21 21:29 UTC
Continually receive this error:

Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error: 

/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>'

Goes away after restart, then reappears after a few clicks.

**Comment by simonemainardi** [comment] 2020-01-21 21:50
duplicate of https://github.com/ntop/ntopng/issues/3213

**Closed as completed by simonemainardi** 2020-01-21 21:50 UTC
Labels: Duplicate
