### ISSUE TITLE
Implement in/out Interface Traffic Stats

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1066] opened 2017-03-18 10:19 UTC
As of today (mostly because of inability of pcap of doing this) ntopng is unable to report ingress and egress interface traffic but only local/remote. While this information is important in/out is more effective. It is requested to implement it and report it on the page footer page.

**Comment by simonemainardi** [comment] 2017-04-04 08:30
duplicate of #1114

**Closed as completed by simonemainardi** 2017-04-04 08:30 UTC
Labels: Feature Request
