### ISSUE TITLE
Inability to filter/sort alerts using alert type

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#5314] opened 2021-05-11 07:11 UTC
![Screen Shot 2021-05-11 at 09 08 18](https://user-images.githubusercontent.com/4493366/117773415-90ab7300-b238-11eb-8fd8-8e072cbab001.png)

It is missing the ability to filter/sort alerts based on their type, contrary to other fields

**Comment by simonemainardi** [comment] 2021-05-11 08:28
Duplicate of https://github.com/ntop/ntopng/issues/5206

**Closed as completed by simonemainardi** 2021-05-11 08:28 UTC
Labels: Feature Request
