### ISSUE TITLE
Not able to change the Interface Custom Name in version v.4.3.201103

### ISSUE THREAD

**Issue by daxrob** [ntop/ntopng#4839] opened 2020-12-15 16:17 UTC
Hi,

I just installed version v.4.3.201103 and I have two interfaces. Their name is the same so I need to modify the Custom Name as I always did in the past. 
The problem is that now the software doesn't keep the changes. 

Regards
Roberto

**Comment by simonemainardi** [comment] 2020-12-15 17:02
duplicate of https://github.com/ntop/ntopng/issues/4750

**Closed as completed by simonemainardi** 2020-12-15 17:02 UTC
Labels: Duplicate
