### ISSUE TITLE
Bug: ntopng network aliases overlap

### ISSUE THREAD

**Issue by iSchluff** [ntop/ntopng#5435] opened 2021-06-02 22:03 UTC
When specifying multiple local networks via the -m switch the resulting names overlap if the previous alias is longer than the current one. Example:

When starting ntopng with ```-m="172.18.0.0/16=LAN_FOOBAR123,172.18.192.0/18=LAN_2"```
the resulting network names are:
  - LAN_FOOBAR123
  - LAN_2OOBAR123

![Screenshot_2021-06-02 ntopng - Networks](https://user-images.githubusercontent.com/1429641/120557918-ef5ea980-c3fe-11eb-89fb-d0c5890043b9.png)

ntopng version
Version:        4.3.210602 [Enterprise/Professional build]
GIT rev:        dev:5d294f7cabc9b80cf2c54010f340cba31206101a:20210602

**Comment by MatteoBiscosi** [comment] 2021-06-03 11:11
Hi @iSchluff thanks for reporting the problem, the issue is now fixed, please wait for the next update (in 2/3 hours), update and everything should be alright.

**Closed as completed by MatteoBiscosi** 2021-06-03 11:11 UTC
Labels: Low-Priority Bug, In Progress
