### ISSUE TITLE
Redis Connection error [Connection refused]

### ISSUE THREAD

**Issue by branchnetconsulting** [ntop/ntopng#2429] opened 2019-02-27 18:52 UTC
This issue has come up with newer version(s) of the ntopng deb.  Specifically I was just now testing with this deb:

`http://packages.ntop.org/apt-stable/16.04/x64/ntopng_3.8.190219-6179_amd64.deb`

and using this /etc/ntopng/ntopng.conf

```
--http-port=0
--https-port=3000
--data-dir=/usr/local/ntopng
--local-networks="192.168.0.0/16,10.0.0.0/8,172.16.0.0/12"
--interface=eth1
--interface=eth2
--dns-mode=1
--community
--daemon
--disable-login=1
-G=/var/tmp/ntopng.pid
```

If I try to start it with "systemctl start ntopng", it fails with this complaint even through stock Ubuntu redis-server is indeed running:

```
Feb 20 19:29:35 nsm.server.org ntopng[7443]: 20/Feb/2019 19:29:35 [Redis.cpp:111] ERROR: ntopng requires redis server to be up and running
Feb 20 19:29:35 nsm.server .org ntopng[7443]: 20/Feb/2019 19:29:35 [Redis.cpp:112] ERROR: Please start it and try again or use -r
Feb 20 19:29:35 nsm.server .org ntopng[7443]: 20/Feb/2019 19:29:35 [Redis.cpp:113] ERROR: to specify a redis server other than the default
```
I even fired up a dedicated new redis service on port 6380, confirmed it was working with "redis-cli -p 6380" and added this to ntopng.conf, but systemctl still fails in exactly the same way

`redis=127.0.0.1:6380`

But if I start it ntopng the manual way, it starts up, daemonizes, and works just fine in my web browser:

`/usr/local/bin/ntopng /etc/ntopng/ntopng.conf`

In either case, my redis-server is installed and running just fine

```
root@nsm:~# apt info redis-server
E: Invalid operation info
root@nsm:~# apt show redis-server
Package: redis-server
Version: 2:3.0.6-1ubuntu0.3
Priority: optional
Section: universe/misc
Source: redis
Origin: Ubuntu
...

root@nsm:~# systemctl status redis-server
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-02-20 18:31:08 UTC; 56min ago
```
   ...

Somehow it appears that the running redis-server process is invisible to systemd where ntopng is involved, thus preventing my from using systemctl to start it.

Do you have any idea what might be going on?

**Comment by emanuele-f** [comment] 2019-02-28 09:37
Are you running ubuntu 16? It works fine in my test system with a modified version of the configuration above

**Comment by branchnetconsulting** [comment] 2019-02-28 13:24
Yes, Ubuntu 16.04 Server.  I am not sure how to further diagnose this as it only comes up when systemctl tries to start ntopng.  I actually find that on another Ubuntu 16.04 server in a very similar role, that the version of ntopng installed via the same exact deb does not exhibit this problem.  Any ideas on how I could test this further?

**Comment by emanuele-f** [comment] 2019-03-01 09:13
You can try to inspect the loopback interface communication on port 6379 and see how ntopng and redis communicate and what goes wrong. ntopng sends a "PING" message to redis to verify the communication. The other option is to reinstall ntopng or install the dev version as this issue is really weird

**Comment by branchnetconsulting** [comment] 2019-03-01 15:34
Hi, I inspected the loopback interface and zero packets on 6379 are seen when I run "systemctl start ntopng" while when I just run "ntopng /etc/ntopng/ntopng.conf" I do see the expected redis packets.

I then tried using strace when starting up ntopng with systemctl but nothing particularly interesting stood out to me when inspecting all the noisy output of that.

Lastly I switched to installing the daily build deb rather than the stable deb for ntopng and it still fails with systemctl while working with a manual call, but the error output is a bit different:

```
root@NSM-WBT:/etc/ntopng# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2019-03-01 15:22:44 UTC; 4min 55s ago
  Process: 16559 ExecStart=/usr/local/bin/ntopng (code=exited, status=1/FAILURE)
 Main PID: 16559 (code=exited, status=1/FAILURE)

Mar 01 15:22:42 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:42 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 1]
Mar 01 15:22:42 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:42 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 01 15:22:43 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:43 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 0]
Mar 01 15:22:43 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:43 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 01 15:22:44 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:44 [Redis.cpp:143] ERROR: ntopng requires redis server to be up and running
Mar 01 15:22:44 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:44 [Redis.cpp:144] ERROR: Please start it and try again or use -r
Mar 01 15:22:44 nsm.wycliffe.org ntopng[16559]: 01/Mar/2019 15:22:44 [Redis.cpp:145] ERROR: to specify a redis server other than the default
Mar 01 15:22:44 nsm.wycliffe.org systemd[1]: ntopng.service: Main process exited, code=exited, status=1/FAILURE
Mar 01 15:22:44 nsm.wycliffe.org systemd[1]: ntopng.service: Unit entered failed state.
Mar 01 15:22:44 nsm.wycliffe.org systemd[1]: ntopng.service: Failed with result 'exit-code'.
```

and this is seen in syslog output

```
Mar  1 15:22:28 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:29 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:30 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:31 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:32 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:33 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:34 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:35 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:36 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:37 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:38 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:39 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:40 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:41 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:42 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:43 nsm ntopng: [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar  1 15:22:44 nsm ntopng: [Redis.cpp:143] ERROR: ntopng requires redis server to be up and running
Mar  1 15:22:44 nsm ntopng: [Redis.cpp:144] ERROR: Please start it and try again or use -r
Mar  1 15:22:44 nsm ntopng: [Redis.cpp:145] ERROR: to specify a redis server other than the default
```

One other thing I tried was to blow away ntopng.conf entirely and run ntopng that way so it just takes default settings only, which when I start manually does result in the daemon coming up.  When I tweaked /etc/systemd/system/ntopng.service to remove the reference to ntopng.conf, the same failure occurs with a systemctl start attempt, so it appears clear there is nothing in my unique ntopng.conf breaking things.

This really is perplexing and I welcome any other diagnostic suggestions you might have.

Thanks,
Kevin

**Comment by simonemainardi** [comment] 2019-03-04 17:50
`Connection error [Connection refused]` that seems more a firewall issue.....

Please, check and make sure there's nothing blocking such connections.... maybe iptables?

**Comment by branchnetconsulting** [comment] 2019-03-04 18:36
It is only reaching out to localhost to reach the running redis service.
When I run **/usr/local/bin/ntopng /etc/ntopng/ntopng.conf** it works
but when I run **systemctl start ntopng** it fails
so I can't see how iptables could be interfering

**Comment by simonemainardi** [comment] 2019-03-05 09:12
I've just tried to reproduce using your exact config and 

```
simone@devel:~$ ntopng --version
v.3.8.190304	[Enterprise/Professional build]
```

... it works perfectly on ubuntu16...

Note that it doesn't matter if it's on localhost ... if there's something (e.g., a firewall) preventing ntopng from connecting on localhost.... the connection will fail...


By the way:

- try and remove option `--daemon`
- are you sure the `/etc/systemd/system/ntopng.service` hasn't been changed/tampered?

Regular output is 

```
* ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-03-05 10:08:28 CET; 3s ago
  Process: 17389 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 17386 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 17419 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 17413 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 17401 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/SUCCESS)
  Process: 17394 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 17418 (ntopng)
```

That is, there is a series of ExecStartPre, ExecStopPost that don't show up in your output..

Try with an `apt-get install --reinstall ntopng`

**Comment by simonemainardi** [comment] 2019-03-07 13:59
any news?

**Comment by branchnetconsulting** [comment] 2019-03-07 14:21
I purged and reinstalled ntopng, making sure the ntopng.service file was untouched and now it shows the missing lines you mentioned.  Yes I had commented those lines out experimentally earlier.

This time I also completely disabled ufw and flushed iptables.
```
# iptables --list
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
Then while running "systemctl start ntopng" in one terminal I ran "tcpdump -i lo port 6389 -nn" in another terminal and caught zero packets.

It still fails with the same mysterious complaint.  Is there perhaps some specific way I might use strace to see more details about the attempt to connect to redis?  I am not very good with that tool but open to suggestions.

```
 ● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
   Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-03-07 14:05:51 UTC; 15s ago
  Process: 17854 ExecStopPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StopPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 17849 ExecStopPost=/bin/rm -rf /run/ntopng.conf (code=exited, status=0/SUCCESS)
  Process: 19990 ExecStartPost=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPost" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
  Process: 19984 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|^[ ]*--pid.*/s/^/#/" /etc/ntopng/ntopng.conf > /run/ntopng.conf (code=exited,
  Process: 19966 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, st
  Process: 19960 ExecStartPre=/bin/sh -c /bin/echo "$(/bin/date) ntopng StartPre" >> /var/log/ntop-systemd.log (code=exited, status=0/SUCCESS)
 Main PID: 19989 (ntopng)
    Tasks: 1
   Memory: 5.9M
      CPU: 50ms
   CGroup: /system.slice/ntopng.service
           └─19989 /usr/local/bin/ntopng /run/ntopng.conf

Mar 07 14:06:01 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:01 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 5]
Mar 07 14:06:01 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:01 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 07 14:06:02 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:02 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 4]
Mar 07 14:06:02 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:02 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 07 14:06:03 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:03 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 3]
Mar 07 14:06:03 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:03 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 07 14:06:04 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:04 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 2]
Mar 07 14:06:04 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:04 [Redis.cpp:94] ERROR: Connection error [Connection refused]
Mar 07 14:06:05 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:05 [Redis.cpp:78] Redis has disconnected, reconnecting [remaining attempts: 1]
Mar 07 14:06:05 172.18.2.12 ntopng[19989]: 07/Mar/2019 14:06:05 [Redis.cpp:94] ERROR: Connection error [Connection refused]
```

Thanks for sticking with me on this,
Kevin

**Comment by simonemainardi** [comment] 2019-03-08 08:31
redis default port is 6379.

Please, post the output of:

```
netstat -polenta | grep 6379
ps aux | grep redis-server
redis-cli (then type ping)
```

Then stop ntopng, start  capture (`sudo tcpdump -i lo port 6379`) with the capture started restart ntopng and send me the output of tcpdump.

**Comment by simonemainardi** [comment] 2019-03-12 16:41
any news here?

**Comment by branchnetconsulting** [comment] 2019-03-12 17:05
Sorry about the delay on that...

root@NSM:~# netstat -polenta | grep 6379
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN
    115        152136334   17585/redis-server  off (0.00/0/0)
root@NSM:~# ps aux | grep redis-server | grep -v grep
redis    17585  0.0  0.0  40136  3804 ?        Ssl  Mar07   4:27
/usr/bin/redis-server 127.0.0.1:6379
root@NSM:~# redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>

**Comment by simonemainardi** [comment] 2019-03-13 16:58
what about the second part with the capture?

**Comment by branchnetconsulting** [comment] 2019-03-13 17:10
Sorry, every time I run "sudo tcpdump -i lo port 6379" while restarting
ntopng with "systemctl restart ntopng" I see zero packets.  I see other
packets on the lo interface if I tcpdump without filtering on port 6379 but
I never see any port 6379 packets.
However when I start ntopng manually with "/usr/local/bin/ntopng
/etc/ntopng/ntopng.conf" while tcpdumping on the lo port looking for port
6379, I see lots of packets then.
These are consistent results from having run these kind of tests numerous
times.

Kevin

**Comment by simonemainardi** [comment] 2019-03-14 13:53
Unfortunately this issue is not reproducible. Again as I stated in my first comment

> Please, check and make sure there's nothing blocking such connections

Apart from iptables, you should check systemd, especially the new systemd Access Lists that may be the source of the trouble.

Indeed, systemd allows to perform per-unit traffic control with options that are just wrappers around kernel functionality introduced with Linux 4.11: the control group eBPF hooks.

Specifically, those options are `IPAddressAllow=`  and `IPAddressDeny=`. Those could have been set by someone to be effective for all the units, including ntopng.

Check this out and refer to for additional details http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html

**Comment by simonemainardi** [comment] 2019-03-20 14:53
hey, did you check the suggestions above?

**Comment by branchnetconsulting** [comment] 2019-03-20 16:22
Hi Simone,

I checked and find no signs of any IPAddressAllow= or IPAddressDeny= strings
anywhere in my systemd config, tested with:

grep -r "IPAddress" /etc/systemd/*


Also, I'm on a 4.4 kernel, so that may or may not apply:

root@NSM:~# uname -a
Linux nsm 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018
x86_64 x86_64 x86_64 GNU/Linux


Kevin

**Comment by simonemainardi** [comment] 2019-03-20 18:14
At this point there's much else I can do. The issue is not reproducible and it seems there's no one else with this issue. Indeed, ntopng is working and connecting if you start it from the command line so it's something related to your systemd.

If you can't find it out, I can propose to connect to your box if you give me ssh access. Otherwise I am going to close this issue.

**Comment by branchnetconsulting** [comment] 2019-03-20 19:23
Thanks for your help Simone.  I appreciate your perseverance on this
issue.  There indeed must be something really unusual going on with this
particular server.  At this point let's just close the issue and perhaps
later on I might reach out for you to take a remote look at it if it
remains a problem.

Kevin

**Comment by simonemainardi** [comment] 2019-03-21 10:44
ok, if necessary contact me privately at mainardi ntop org for the login credentials

**Closed as completed by simonemainardi** 2019-03-21 10:44 UTC
Labels: To Be Confirmed
