### ISSUE TITLE
Edit button must be disabled for disabled scripts

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4461] opened 2020-09-21 19:50 UTC
![Screen Shot 2020-09-21 at 21 50 18](https://user-images.githubusercontent.com/4493366/93814186-79415a80-fc54-11ea-81c4-d9f837da4e22.png)

**Comment by gabryon99** [comment] 2020-09-24 20:38
this is a duplicate of #4464

**Closed as completed by gabryon99** 2020-09-24 20:38 UTC
Labels: Low-Priority Bug
