### ISSUE TITLE
Implement ntopng/nEdge Central Console

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#1991] opened 2018-09-06 19:30 UTC
When running many ntopng/nEdge instances it is not currently possible to have an overview of all instances and know their state, performance, alerts and issues.

It is requested to implement a central console able to provide an outlook of the various instances running in the network. Consider if #1864 could be used as base for creating the network overlay on top of which the instance will run

**Comment by simonemainardi** [comment] 2019-07-03 15:49
duplicate of #2222

**Closed as completed by simonemainardi** 2019-07-03 15:49 UTC
Labels: Enhancement
