### ISSUE TITLE
[ARMHF] Unable to install/update ntopng

### ISSUE THREAD

**Issue by filemoon** [ntop/ntopng#1528] opened 2017-10-19 15:15 UTC
Hi

Can you help me with this issue.
Looks like pf_ring.service issue is still there.

apt-get install ntopng
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ntopng:armhf is already the newest version (3.1.171018-3582).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up ntopng:armhf (3.1.171018-3582) ...
Rebuilding ld cache...
Adding the ntopng startup script [configure]
Synchronizing state of ntopng.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ntopng
(Re)Starting ntopng...
Failed to restart ntopng.service: Unit pf_ring.service not found.
dpkg: error processing package ntopng:armhf (--configure):
 subprocess installed post-installation script returned error exit status 5
Errors were encountered while processing:
 ntopng:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)

When I'm trying to start this manually I can see following error.
systemctl start ntopng
Failed to start ntopng.service: Unit pf_ring.service not found.

**Comment by lucaderi** [comment] 2017-10-20 06:12
This is a duplicate of #1521, please monitor that issue. WE're reworking the systemd script.

**Comment by simonemainardi** [comment] 2017-10-24 08:06
@filemoon please try to update the pi package now and report

**Comment by filemoon** [comment] 2017-10-24 16:15
Issue sorted.

**Comment by emanuele-f** [comment] 2017-10-25 09:09
Thank you for reporting

**Closed as completed by emanuele-f** 2017-10-25 09:09 UTC
