### ISSUE TITLE
Cant count correct traffic in Elasticsearch/Kibana

### ISSUE THREAD

**Issue by fprr** [ntop/ntopng#966] opened 2017-02-05 12:38 UTC
Hi, I export flows with the ntopng free version to Elasticsearch like this:

`-F="es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;"`

After dowloading a file I can see the correct amount of traffic in the ntopng WebGUI, but when I calculate the traffic for that connection in Kibana there is a much smaller amount of traffic.

Is ntopng doing sampling when exporting flows to Elasticsearch. If yes - how can I disable this?

**Comment by fprr** [comment] 2017-02-05 15:17
Hhm , the sums of sended and received packets are correct calculated in kibana. So there is no sampling ...

**Comment by simonemainardi** [comment] 2017-02-06 10:03
No sapling is ever done by ntopng before sending to ES.

Please report an example so we can discuss.

Thanks.

**Comment by fprr** [comment] 2017-02-06 14:42
I am running ntopng for Ubuntu 16 from the stable repositores.
This is the simple Kibana vertical bar chart for sums of in and out bytes sorted by IP:

```
{
  "title": "sum_transfer",
  "type": "histogram",
  "params": {
    "addTooltip": true,
    "addLegend": true,
    "legendPosition": "right",
    "scale": "linear",
    "mode": "stacked",
    "times": [],
    "addTimeMarker": false,
    "defaultYExtents": false,
    "setYExtents": false
  },
  "aggs": [
    {
      "id": "1",
      "enabled": true,
      "type": "sum",
      "schema": "metric",
      "params": {
        "field": "IN_BYTES"
      }
    },
    {
      "id": "2",
      "enabled": true,
      "type": "sum",
      "schema": "metric",
      "params": {
        "field": "OUT_BYTES"
      }
    },
    {
      "id": "3",
      "enabled": true,
      "type": "terms",
      "schema": "segment",
      "params": {
        "field": "IPV4_SRC_ADDR",
        "size": 5,
        "order": "desc",
        "orderBy": "1"
      }
    }
  ],
  "listeners": {}
}
```
After dowlnoading a file with 6MB from a client, it shows only about 0,70MB of traffic for this client. 
Today I tried it with a ntopng version from the development builds and there i got the correct results - seems to be a problem with the stable version.

My ntopng.conf

```
--community=
-e
-G=/var/run/ntopng.pid
-w=172.16.255.254:3000
-m="172.16.0.0/12"
-i=enp3s0
-F="es;flows;ntopng-%Y.%m.%d;http://172.16.255.254:9200/_bulk;"
```

**Comment by simonemainardi** [comment] 2017-02-06 14:46
ok, now I see. The issue is not connected with the ES export itself. It is due to a bug that prevented some flows from being exported. This is fixed in the dev release.

**Closed as completed by simonemainardi** 2017-02-06 14:46 UTC
Labels: To Be Confirmed
