### ISSUE TITLE
/usr/bin/ntopng: error while loading shared libraries: libntapi.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Doemela** [ntop/ntopng#670] opened 2016-07-30 17:28 UTC
When I want to start ntopng I get 

> /usr/bin/ntopng: error while loading shared libraries: libntapi.so: cannot open shared object file: No such file or directory

OS:  Ubuntu 14.04 LTS

**Comment by lucaderi** [comment] 2016-07-30 21:19
This library is part pf the pfring package that sound hai ve bene installed as dependency. Is this the case? What version of the packages have you installed?

**Comment by Doemela** [comment] 2016-07-30 23:07
http://apt-stable.ntop.org/14.04/all/apt-ntop-stable.deb
Module:  pfring
Version: 6.5.0

**Comment by lucaderi** [comment] 2016-07-31 07:13
Please provide the whole installation log that reports the problem as I have just tried and it works for me

**Comment by Doemela** [comment] 2016-07-31 14:58
I did:
wget http://apt-stable.ntop.org/14.04/all/apt-ntop-stable.deb
dpkg -i apt-ntop-stable.deb
apt-get clean all
apt-get update
apt-get install pfring nprobe ntopng ntopng-data n2disk cento nbox
[install.txt](https://github.com/ntop/ntopng/files/392459/install.txt)
[dpkglog.txt](https://github.com/ntop/ntopng/files/392463/dpkglog.txt)

> ldd /usr/local/bin/ntopng
> [installed-libs.txt](https://github.com/ntop/ntopng/files/392460/installed-libs.txt)
> 
> ldd /usr/local/bin/nprobe
> [nprobe.txt](https://github.com/ntop/ntopng/files/392530/nprobe.txt)

Thats all I can find

**Comment by lucaderi** [comment] 2016-08-13 13:02
I believe this problem has been fixed days ago. I cannot reproduce it using it https://github.com/ntop/packager. Closing it for now, but if you can reproduce it with the packager, please send the log error.

**Closed as completed by lucaderi** 2016-08-13 13:02 UTC
