### ISSUE TITLE
BT5: Remove broken <optgroup>

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#5381] opened 2021-05-19 12:21 UTC
As per https://github.com/ntop/ntopng/issues/5374#issuecomment-843938834 it seems optgroup is no longer supported with BS5. It is requested to remvove all opt groups

Do a grep to locate them all

```
httpdocs/templates/pages/components/ifaces-dropdown.template:  {% -- The Interfaces optgroup %}
httpdocs/templates/pages/components/ifaces-dropdown.template:  <optgroup label="{{ i18n('interfaces') }}">
httpdocs/templates/pages/components/ifaces-dropdown.template:    </optgroup>
httpdocs/templates/pages/components/ifaces-select.template:        <optgroup label="{{ i18n("system_interface") }}">
httpdocs/templates/pages/components/ifaces-select.template:        </optgroup>
httpdocs/templates/pages/components/ifaces-select.template:        <optgroup label="{{ i18n("interfaces") }}">
httpdocs/templates/pages/components/ifaces-select.template:        </optgroup>
httpdocs/bootstrap/css/bootstrap-reboot.rtl.css:optgroup,
httpdocs/bootstrap/css/bootstrap.css:optgroup,
httpdocs/bootstrap/css/bootstrap-reboot.css:optgroup,
httpdocs/bootstrap/css/bootstrap.rtl.css:optgroup,
httpdocs/js/jquery-ui.js:			.not( ".ui-selectmenu-optgroup" )
httpdocs/js/jquery-ui.js:			if ( item.optgroup !== currentOptgroup ) {
httpdocs/js/jquery-ui.js:					text: item.optgroup
httpdocs/js/jquery-ui.js:				that._addClass( li, "ui-selectmenu-optgroup", "ui-menu-divider" +
httpdocs/js/jquery-ui.js:					( item.element.parent( "optgroup" ).prop( "disabled" ) ?
httpdocs/js/jquery-ui.js:				currentOptgroup = item.optgroup;
httpdocs/js/jquery-ui.js:		var optgroup = option.parent( "optgroup" );
httpdocs/js/jquery-ui.js:			optgroup: optgroup.attr( "label" ) || "",
httpdocs/js/jquery-ui.js:			disabled: optgroup.prop( "disabled" ) || option.prop( "disabled" )
httpdocs/js/config_callbacks/scripts-list-utils.js:         const $group = $(`<optgroup label='${category.label}'></optgroup>`);
```

**Comment by MatteoBiscosi** [comment] 2021-05-26 08:50
The problem with the optgroup and BS5 is the following: we noticed that multiple optgroup into the same select (like it was the interface dropdown, divided into interfaces and system) is currently bugged, so I removed the multiple optgroup into the same select one by one, collapsed together and currently the problem is solved. Please reopen the ticket if needed.

**Comment by simonemainardi** [comment] 2021-05-26 09:10
In the commit, not only the optgroup but also the system interface has been removed.

I am not sure if file `ifaces-select.template` touched in the commit is necessary or if it is a semi-duplicate of `ifaces-dropdown.template` only used in mobile versions (https://github.com/ntop/ntopng/issues/5407).

Verify this, check if `ifaces-select.template` can be removed, and if it cannot be removed re-add the system interface and test it.

**Comment by MatteoBiscosi** [comment] 2021-05-26 15:02
Already tested, the ifaces-select.template is used by the mobile version and the same problem with the double optgroup persisted in the mobile version so I removed only from there because it was already fixed in the "pc" version. Please close the ticket if everything is fine.

**Comment by simonemainardi** [comment] 2021-05-26 16:33
> In the commit, not only the optgroup but also the system interface has been removed.

please comment this

**Comment by MatteoBiscosi** [comment] 2021-05-26 17:14
Re-added system interface now all the interfaces are present and the double optgroup has been removed correctly

**Closed as completed by MatteoBiscosi** 2021-05-26 17:14 UTC
Labels: Priority Ticket
