### ISSUE TITLE
Impossible delete Alerts when ntopng is run with "-l 1" option

### ISSUE THREAD

**Issue by gianogli** [ntop/ntopng#164] opened 2015-09-11 13:24 UTC
When I run ntopng with "-l 1" option ("Disable user login authentication") I can't delete the alerts shown by the show_alerts.lua script.
I don't know if this behavior is correct or not but I think it would be better give to the users the possibility to add the "nologin" user into the administrator group (with a specific command line option?) or add it by default.

Now, however, the function "bool Utils::isUserAdministrator(lua_State* vm)" (Utils.cpp) return that the "nologin" user is not an Administrator.
Is it possible to change this behavior?

Thanks...

**Comment by kYroL01** [comment] 2015-09-14 11:52
The behavior is so deliberately implemented because if you are not an administrator ntopng does not allow the purge of alerts.
This is not an issue, so i close it, but we'll take on mind your question for future developments.

Thank you

**Comment by lucaderi** [comment] 2015-09-14 11:56
@kYroL01 Your comment is correct, but I think we should modify the Utils::isUserAdministrator behaviour as indicated. I'll take a note.

**Comment by kYroL01** [comment] 2015-09-14 11:58
@lucaderi Ok Luca, good point.

**Comment by lucaderi** [comment] 2015-09-14 12:15
@gianogli I have just checked wand with -l 1 you have admin rights. So to me all works as designed. I will modify the about page to report the user role (admin or unprivileged)

**Comment by gianogli** [comment] 2015-09-14 12:31
@lucaderi When I try to purge all the alerts nothing happen. To find the problem I tried to uncomment the warning messages into the Utils::isUserAdministrator function and when I try to purge the alerts I obtain:
14/Sep/2015 14:25:57 [Utils.cpp:614] WARNING: isUserAdministrator(nologin): NO

If I open the Users page (users.lua script) I can see only the "admin" user. No "nologin" user is defined.

**Comment by lucaderi** [comment] 2015-09-14 12:38
@gianogli Please report how you started ntopng. I assume you are using the code in GIT correct?

**Comment by gianogli** [comment] 2015-09-14 12:47
@lucaderi Yes. I'm using the community version 2.0.150914.
I run ntopng with:
./ntopng -i zc:2@0 -i zc:2@1 -i zc:2@2 -i zc:2@3 -i view:zc:2@0,zc:2@1,zc:2@2,zc:2@3 -u -n0 -d /var/tmp/ntopng/ -m "X.X.X.X/18,1X.X.X.X/19,X.X.X.X/21,X.X.X.X.0/20,X.X.X.X/21,X.X.X.X/25,X.X.X.X/24,X.X.X.X/24,X.X.X.X/24,X.X.X.X/23,X.X.X.X/23,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8" -r 127.0.0.1:6379 -g 3,4,5,6 -l 1 -X 262144 -x 131072 -B "not (udp and src host 0.0.0.0 and dst port 8116)" -S local

(I modified only the -m parameter by changing my public networks with X.X.X.X)

**Closed** 2015-09-15 16:46 UTC
