### ISSUE TITLE
Historical interface chart is missing in v.3.1.171029

### ISSUE THREAD

**Issue by ummeegge** [ntop/ntopng#1544] opened 2017-11-01 05:31 UTC
Hello,
i wanted to report/ask that "/lua/if_stats.lua?ifid=1&page=historical" is under 

```
v.3.1.171029	[Community build]
GIT rev:	dev:3e88f9a0ac3ba5b058f57596d19aedce89d12812:20171029
```

[not present anymore](https://people.ipfire.org/~ummeegge/screenshoots/ntopng/ntopng_no_historical_tab.png)
whereby ntopng version 
 
```
v.3.1.171006	[Community build]
GIT rev:	dev:c58efebb7a69bf1dd018b17d9b46bd8e439b0e99:20171006
```

[do provides the historical interface charts](https://people.ipfire.org/~ummeegge/screenshoots/ntopng/ntopng_with_hostorical_tab.png).

So my question is, are this feature not available anymore in the community version or is it only temporarily not available ?

Thanks for clarification. 

Best regards,

Erik

**Comment by simonemainardi** [comment] 2017-11-01 12:47
please, update to the lastest version as we believe the issue is fixed there

**Comment by ummeegge** [comment] 2017-11-02 13:21
Hello,
i can not confirm this, the historical interface tab do not appears here. Have used the sources from yesterday (nDPI and ntopng):

```
v.3.1.171102	[Community build]
GIT rev:	dev:a21e7eeb9fa0e9737c5c47a556e660ffe5baf5d8:20171102
```
`
./ntopng: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped, with debug_info`

Have started it with GDB which points the following out:

```
(gdb) run
Starting program: /tmp/ntopng/ntopng 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
[New Thread 0x7ffff0a6c700 (LWP 3264)]
[New Thread 0x7ffff026b700 (LWP 3265)]
[New Thread 0x7fffefa6a700 (LWP 3266)]
[New Thread 0x7fffef269700 (LWP 3267)]
[New Thread 0x7fffeea68700 (LWP 3268)]
[New Thread 0x7fffee267700 (LWP 3269)]
[New Thread 0x7fffeda66700 (LWP 3270)]
[New Thread 0x7fffed265700 (LWP 3271)]
02/Nov/2017 13:11:19 [Ntop.cpp:1435] Setting local networks to 127.0.0.0/8
02/Nov/2017 13:11:19 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
02/Nov/2017 13:11:19 [Redis.cpp:111] Successfully connected to redis 127.0.0.1:6379@0
02/Nov/2017 13:11:20 [PcapInterface.cpp:88] Reading packets from interface enp0s10...
02/Nov/2017 13:11:20 [Ntop.cpp:1561] Registered interface enp0s10 [id: 0]
02/Nov/2017 13:11:20 [PcapInterface.cpp:88] Reading packets from interface lo...
02/Nov/2017 13:11:20 [Ntop.cpp:1561] Registered interface lo [id: 1]
02/Nov/2017 13:11:21 [PcapInterface.cpp:88] Reading packets from interface wlp3s0...
02/Nov/2017 13:11:21 [Ntop.cpp:1561] Registered interface wlp3s0 [id: 2]
02/Nov/2017 13:11:21 [main.cpp:312] PID stored in file /var/run/ntopng.pid
02/Nov/2017 13:11:21 [HTTPserver.cpp:839] HTTPS Disabled: missing SSL certificate /tmp/ntopng/httpdocs/ssl/ntopng-cert.pem
02/Nov/2017 13:11:21 [HTTPserver.cpp:841] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
02/Nov/2017 13:11:21 [Utils.cpp:449] User changed to nobody
[New Thread 0x7fffec052700 (LWP 3315)]
[New Thread 0x7fffeb851700 (LWP 3316)]
[New Thread 0x7fffeb050700 (LWP 3317)]
[New Thread 0x7fffea84f700 (LWP 3318)]
[New Thread 0x7fffea04e700 (LWP 3319)]
[New Thread 0x7fffe984d700 (LWP 3320)]
02/Nov/2017 13:11:21 [HTTPserver.cpp:912] Web server dirs [/tmp/ntopng/httpdocs][/tmp/ntopng/scripts]
02/Nov/2017 13:11:21 [HTTPserver.cpp:915] HTTP server listening on port(s) 3000
02/Nov/2017 13:11:21 [main.cpp:394] Working directory: /var/tmp/ntopng
02/Nov/2017 13:11:21 [main.cpp:396] Scripts/HTML pages directory: /tmp/ntopng
02/Nov/2017 13:11:21 [Ntop.cpp:349] Welcome to ntopng x86_64 v.3.1.171102 - (C) 1998-17 ntop.org
02/Nov/2017 13:11:21 [Ntop.cpp:635] Adding 127.0.0.1/32 as IPv4 interface address for lo
02/Nov/2017 13:11:21 [Ntop.cpp:643] Adding 127.0.0.0/8 as IPv4 local network for lo
02/Nov/2017 13:11:21 [Ntop.cpp:635] Adding 192.168.5.5/32 as IPv4 interface address for enp0s10
02/Nov/2017 13:11:21 [Ntop.cpp:643] Adding 192.168.5.0/24 as IPv4 local network for enp0s10
02/Nov/2017 13:11:21 [Ntop.cpp:662] Adding ::1/128 as IPv6 interface address for lo
02/Nov/2017 13:11:21 [Ntop.cpp:671] Adding ::1/128 as IPv6 local network for lo
02/Nov/2017 13:11:21 [Ntop.cpp:662] Adding fe80::b8ef:f3e6:4455:91b1/128 as IPv6 interface address for enp0s10
02/Nov/2017 13:11:21 [Ntop.cpp:671] Adding fe80::b8ef:f3e6:4455:91b1/64 as IPv6 local network for enp0s10
[New Thread 0x7fffe904c700 (LWP 3321)]
[New Thread 0x7fffe884b700 (LWP 3322)]
02/Nov/2017 13:11:21 [PeriodicActivities.cpp:51] Started periodic activities loop...
[New Thread 0x7fffcbfff700 (LWP 3323)]
[New Thread 0x7fffcb7fe700 (LWP 3324)]
[New Thread 0x7fffcaffd700 (LWP 3325)]
[New Thread 0x7fffca7fc700 (LWP 3326)]
[New Thread 0x7fffc9ffb700 (LWP 3327)]
[New Thread 0x7fffc97fa700 (LWP 3328)]
[New Thread 0x7fffc8ff9700 (LWP 3329)]
02/Nov/2017 13:11:21 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:21 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/daily.lua][/tmp/ntopng/scripts/lua/modules/alert_utils.lua:1714: bad argument #1 to 'pairs' (table expected, got nil)]
02/Nov/2017 13:11:22 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:23 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:24 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:25 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:26 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
[New Thread 0x7fffa7fff700 (LWP 3336)]
02/Nov/2017 13:11:26 [NetworkInterface.cpp:2285] Started packet polling on interface enp0s10 [id: 0]...
02/Nov/2017 13:11:27 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:28 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:29 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:30 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:31 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
[New Thread 0x7fffa77fe700 (LWP 3337)]
02/Nov/2017 13:11:31 [NetworkInterface.cpp:2285] Started packet polling on interface lo [id: 1]...
02/Nov/2017 13:11:32 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:33 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:34 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:35 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:36 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
[New Thread 0x7fffa6ffd700 (LWP 3338)]
02/Nov/2017 13:11:36 [NetworkInterface.cpp:2285] Started packet polling on interface wlp3s0 [id: 2]...
02/Nov/2017 13:11:37 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:38 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:39 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:40 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:41 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:42 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
02/Nov/2017 13:11:43 [Lua.cpp:6634] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/second.lua][/tmp/ntopng/scripts/lua/modules/graph_utils.lua:982: /var/tmp/ntopng/2/rrd/bytes.rrd: illegal attempt to update using time 0 when last update time is 1509541881 (minimum one second step)]
....

```

whereby the last line repeats and seems to hangs there.

Best regards,

Erik

**Comment by emanuele-f** [comment] 2017-11-13 14:41
Hi, can you double check the executable you are running? It seems like you are mixing `/tmp/ntopng/ntopng`, `/usr/bin/ntopng` and `./ntopng` (gdb). The error above should be fixed with the current ntopng version..

**Comment by ummeegge** [comment] 2017-11-13 15:51
Hello emanuele-f,
thanks for looking over this. I needed to compile ntopng with the debug flag, the compilation and GDB tests has been made in /tmp that´s why the ntopng directory has been located in /tmp. Have also a regular compiled version (CFLAGS -O2) in my productive system where i do not have GDB or GCC available. Both system are on version

```
v.3.1.171102	[Community build]
GIT rev:	dev:a21e7eeb9fa0e9737c5c47a556e660ffe5baf5d8:20171102
```
and have both the same behavior where the historical interface charts are missing. Do you mean the current version after 20171102 ? In that case i need to build it again which takes a little.

Best,

Erik

**Comment by emanuele-f** [comment] 2017-11-13 16:16
Ok, but please note that if you run ntopng with`/tmp/ntopng/ntopng` from outside the `/tmp/ntopng` directory, it will still use your system wide (possibly outdated) scripts directory (located at '/usr/local/share/ntopng`). So, what I suggest is to remove any custom system wide installation of ntopng and try the binary version from the ntopng repository. This way, you'll know for sure you are using the latest ntopng binary version and scripts.

**Comment by ummeegge** [comment] 2017-11-13 17:42
Thank you for clarification. But i think this should be here not the problem since the interface history do not work on the productive machine too. Also if i make a clean build, which i did in that case, i need to make a complete new build of the whole distribution (IPFire in that case) to get the new ROOTFILES (which includes then also possible new files or deletion of old files) to generate an updated package (ntopng-{version}.ipfire) so /usr/share/ntopng (in my case) equals to the content under /tmp/ntopng . The only exception was the debug flag.

Again thanks for your work.

Best,

Erik

**Comment by emanuele-f** [comment] 2017-11-14 14:26
Can you please post a screenshot of your ntopng preferences, page Timeseries?
Does the file `/var/tmp/ntopng/1/rrd/bytes.rrd` exist in your system?

**Comment by emanuele-f** [comment] 2017-11-16 13:47
@ummeegge please also check out the `Create Interface Timeseries` flag under the cog icon into the network interface page

**Comment by ummeegge** [comment] 2017-11-18 06:31
Hi emanuele-f,
> Can you please post a screenshot of your ntopng preferences, page Timeseries?

shure

![Timeseries page](https://people.ipfire.org/~ummeegge/screenshoots/ntopng/ntopng_timeseries1.png)

tests has also been made with the default settings after installation with the same results.

> Does the file /var/tmp/ntopng/1/rrd/bytes.rrd exist in your system?

My installation paths differs here a little (nst instead of tmp) but the rrd/ dir is here missing

```
-> ll /var/nst/ntopng/{0,1,2,3}
/var/nst/ntopng/0:
total 8
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 alerts
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 top_talkers

/var/nst/ntopng/1:
total 8
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 alerts
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 top_talkers

/var/nst/ntopng/2:
total 8
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 alerts
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 top_talkers

/var/nst/ntopng/3:
total 8
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 alerts
drwx------ 2 ntopng ntopng 4096 Nov 17 08:29 top_talkers
```

> please also check out the Create Interface Timeseries flag under the cog icon into the network interface page

The only section which includes a 'creation of network interfaces' was the 'TCP Out of Order, Lost and Retransmitted Segments' if you do mean that, it has been activated (see the screenshoot).

Sorry for my late answer but am currently from time to time some days on tour.

Best,

Erik

**Comment by emanuele-f** [comment] 2017-11-20 14:13
The log you posted previously (`WARNING: Script failure`) reports `/var/tmp/ntopng/2/rrd/bytes.rrd'. What ntopng options are you using?

**Comment by ummeegge** [comment] 2017-11-21 05:00
Hello emanuele-f,
 
> The log you posted previously (WARNING: Script failure) reports `/var/tmp/ntopng/2/rrd/bytes.rrd'. 

this was a testing version in IPFire´s chroot (building) environment not the productive one.
Have build an actual version:
 
```
v.3.1.171120	[Community build]
GIT rev:	dev:e1132d2d5adfcba60f64d98bbc36d880fc93aa36:20171120
```

and this version seems to have fixed the problem, the interface history tab appears and works again.
The directories looks also good now:

```
-> ll /var/nst/ntopng/{0,1,2}
/var/nst/ntopng/0:
total 12
drwx------  2 ntopng ntopng   25 Nov 21 04:55 alerts
drwx------ 86 ntopng ntopng 4096 Nov 21 04:55 asnstats
drwx------  5 ntopng ntopng 4096 Nov 21 06:25 rrd
drwx------  3 ntopng ntopng   16 Nov 20 17:51 subnetstats
drwx------  2 ntopng ntopng 4096 Nov 21 06:25 top_talkers

/var/nst/ntopng/1:
total 12
drwx------   2 ntopng ntopng   25 Nov 21 06:17 alerts
drwx------ 150 ntopng ntopng 4096 Nov 21 06:20 asnstats
drwx------   5 ntopng ntopng 4096 Nov 21 06:00 rrd
drwx------   3 ntopng ntopng   16 Nov 20 17:51 subnetstats
drwx------   2 ntopng ntopng 4096 Nov 21 06:25 top_talkers

/var/nst/ntopng/2:
total 12
drwx------   2 ntopng ntopng   25 Nov 20 23:49 alerts
drwx------ 121 ntopng ntopng 4096 Nov 21 06:00 asnstats
drwx------   5 ntopng ntopng 4096 Nov 21 04:35 rrd
drwx------   3 ntopng ntopng   16 Nov 20 17:51 subnetstats
drwx------   2 ntopng ntopng 4096 Nov 21 06:25 top_talkers

```

This bug is solved here.

Thanks for your work and you effort.

Best regards,

Erik

**Comment by emanuele-f** [comment] 2017-11-21 09:04
Thank you for reporting Erik

**Closed as completed by emanuele-f** 2017-11-21 09:04 UTC
