### ISSUE TITLE
Reopening ticket #6578

### ISSUE THREAD

**Issue by Taralas** [ntop/ntopng#6630] opened 2022-05-24 21:09 UTC
**Environment**:
* OS name: OPNsense Business Edition
* OS version: 22.4, Based on FreeBSD 13.0-STABLE
* Architecture: amd64
* ntopng version/revision: v.5.3.220524

**What happened**:
At startup, ntopng process throws the following errors:

```09/May/2022 07:59:11 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/notifications.lua][...png/scripts/lua/modules/alert_store/host_alert_store.lua:67: bad argument #21 to 'format' (number expected, got nil)]
09/May/2022 07:59:18 [LuaEngine.cpp:595] WARNING: Script failure [/usr/local/share/ntopng/scripts/callbacks/5second/system/network_discovery.lua][attempt to index a string value]
```

**What did you expect to happen?**
Startup with no script errors

**How did you reproduce it?**
Clean install of ntopng on OPNsense, restart process

**Debug Information**:

**Comment by cardigliano** [comment] 2022-05-25 16:09
Duplicate of https://github.com/ntop/ntopng/issues/6578 (reopened)

**Closed as completed by cardigliano** 2022-05-25 16:09 UTC
