### ISSUE TITLE
Host Historical Time Series not Populating Traffic RX/TX Graph

### ISSUE THREAD

**Issue by dkggpeters** [ntop/ntopng#8207] opened 2024-02-07 16:57 UTC
**Environment**:
* OS name: FreeBSD (on PFSense 23.09.1)
* OS version: 14.0
* Architecture: amd64
* ntopng version/revision: 6.1.2.240207

**What happened**:
When viewing host histroical data, the Traffic RX/TX timeseries graph is not being populated.  Data is stored in InfluxDB which is working properly per the monitor.  All Timeseries options were selected with a resolution of 1 minute.

No errors appear in the System Log

Clickhouse is also setup and working properly.

**Debug Information**:

![image](https://github.com/ntop/ntopng/assets/63671969/642c19e2-8bd0-4c84-8263-8a0004021084)

![image](https://github.com/ntop/ntopng/assets/63671969/8eadb426-cc8e-4dc3-81c4-600740e1352d)

![image](https://github.com/ntop/ntopng/assets/63671969/48b3b24b-1b1b-4e7a-8de9-c6d906f58d61)

![image](https://github.com/ntop/ntopng/assets/63671969/c4b5df91-e166-4c52-ad53-dfd1893ec3db)

**Comment by dkggpeters** [comment] 2024-02-07 20:41
I also noticed that other options are not available as well and only "Traffic RX/TX" show up in the selections.

![image](https://github.com/ntop/ntopng/assets/63671969/e90cc9a5-cede-4762-9b91-3dee0b8708f8)

**Comment by dkggpeters** [comment] 2024-02-15 15:16
In the interim, I added the computer to a host pool and can get the information that way.  The added benefit is I can also now get any option in historical flows that have graphs which now populate for only this device.

![image](https://github.com/ntop/ntopng/assets/63671969/9d4bb132-4e57-4cca-a77b-b82d8864252d)

**Comment by MatteoBiscosi** [comment] 2024-02-27 10:54
Hi @dkggpeters are you currently using the disaggregation? in case pls tell me which one are u currently using

**Comment by dkggpeters** [comment] 2024-02-28 10:49
I am using disaggregation.  Should I turn it off?

**Comment by MatteoBiscosi** [comment] 2024-02-28 13:47
nono, please tell me which kind of disaggregation you are currently using, i'd try to reproduce your issue on my lab in this way

**Comment by dkggpeters** [comment] 2024-02-28 19:47
I am using it on the Lan interface for VLAN's only

![image](https://github.com/ntop/ntopng/assets/63671969/4c021cbf-1958-4f91-8b13-e58963ca0bde)

**Comment by MatteoBiscosi** [comment] 2024-03-04 18:05
Hi @dkggpeters if u were using influxdb, the issue should now be fixed. Please update and let me know

**Comment by dkggpeters** [comment] 2024-03-05 14:21
@MatteoBiscosi Yes I am using influxdb and clickhouse.  I am getting hit and miss of data being populated:

I am on version Interprise L 6.1.240305 (FreeBSD 14.0)

This did populate this morning but does not now using Hosts -> Hosts:

![image](https://github.com/ntop/ntopng/assets/63671969/4dba2078-81ff-4f13-8eb4-f69f65b1f542)

If I use Host -> Device/MAC Address Tracking everything works:

![image](https://github.com/ntop/ntopng/assets/63671969/39068985-a67b-489b-bb7d-1c4dcf043146)

Some IP's work using Host -> Host and some do not.

I do have the interface setup using Local Broadcast Domain Hosts Identifer = MAC Address

![image](https://github.com/ntop/ntopng/assets/63671969/08ee251d-872c-4052-a5c7-8b38c7891768)

I am also noticing that Flows - Historical is no longer working if I filter using IP Address or MAC Address which worked before.  Clickhouse is operational just appear I cannot filter using Client Data.  It just spins

![image](https://github.com/ntop/ntopng/assets/63671969/98df4e87-349e-410b-bbff-89595026f394)

**Comment by dkggpeters** [comment] 2024-03-05 14:33
As another example the below works using Host -> Host.  Some do and some do not work.

![image](https://github.com/ntop/ntopng/assets/63671969/ede9a7a7-6eed-4de5-9192-4f07d452e2c6)

![image](https://github.com/ntop/ntopng/assets/63671969/df73145f-60be-4b9d-8fa6-56af3fde238d)

Computer is always on and does not sleep

![image](https://github.com/ntop/ntopng/assets/63671969/c8535d86-0f01-4e89-b7f6-8af99410160b)

**Comment by dkggpeters** [comment] 2024-03-05 14:57
The below is the error log that I get when using Historical -> Flows filtering using Client filters

![image](https://github.com/ntop/ntopng/assets/63671969/69e6b8ed-2013-48ae-a244-a039541b3369)

**Comment by MatteoBiscosi** [comment] 2024-03-18 11:45
Hi @dkggpeters the issue with the historical flows should be fixed, i'm currently checking the hosts timeseries
![image](https://github.com/ntop/ntopng/assets/49585191/6c548385-dd44-434d-90ab-f34c67d08106)

**Comment by lucaderi** [comment] 2024-05-02 19:51
Works for me

**Closed as completed by lucaderi** 2024-05-02 19:51 UTC
Labels: To Be Confirmed, Ready to Test
