### ISSUE TITLE
The topology (table view) on the SNMP Device details page is broken

### ISSUE THREAD

**Issue by NicoMaio** [ntop/ntopng#8219] opened 2024-02-15 10:03 UTC
An empty table error is displayed when clicking on the 'Topology' navbar item in ntopng. 
However, when using the topology icon, data is shown.

**Comment by MatteoBiscosi** [comment] 2024-03-26 10:16
The issue is fixed, however the calculation of Thpt is probably wrong, cannot be NaN value
![image](https://github.com/ntop/ntopng/assets/49585191/493940a1-1967-44fe-8cca-43f0d4acbfd9)

**Comment by MatteoBiscosi** [comment] 2024-04-05 11:00
The issue is fixed now, thanks

**Closed as completed by MatteoBiscosi** 2024-04-05 11:00 UTC
Labels: Ready to Test
