### ISSUE TITLE
Own hosts detected as flooder -> crash

### ISSUE THREAD

**Issue by mahescho** [ntop/ntopng#1540] opened 2017-10-27 07:27 UTC
Hi,

recently hosts of my own net, set by "-m" in ntopng.conf get recorded as flooder in the alerts and so flood the alerts. In consequence Ntopng after some time crashes with:

`25/Oct/2017 14:32:08 [AlertsManager.cpp:814] ERROR: SQL Error: step [INSERT INTO flows_alerts (alert_tstamp, alert_type, alert_severity, alert_json, vlan_id, proto, l7_proto, first_switched, last_switched, cli_country, srv_country, cli_os, srv_os, cli_asn, srv_asn, cli_addr, srv_addr, cli_port, srv_port, cli2srv_bytes, srv2cli_bytes, cli2srv_packets, srv2cli_packets, cli2srv_tcpflags, srv2cli_tcpflags, cli_blacklisted, srv_blacklisted, cli_localhost, srv_localhost) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); ][SQL logic error or missing database]`

Version: v.3.1.171023	[Enterprise/Professional build]

How to workaround this?

TIA
Matthias

**Comment by simonemainardi** [comment] 2017-10-27 12:50
duplicate of https://github.com/ntop/ntopng/issues/1517

**Closed as completed by simonemainardi** 2017-10-27 12:50 UTC
Labels: Duplicate
