### ISSUE TITLE
Script "/usr/share/ntopng/scripts/lua/if_stats.lua" returned an error

### ISSUE THREAD

**Issue by jpgpi250** [ntop/ntopng#3233] opened 2020-01-14 10:04 UTC
Raspbian Buster Lite, Minimal image based on Debian Buster
Version: September 2019
Release date: 2019-09-26
Kernel version: 4.19

install commands:
wget http://packages.ntop.org/RaspberryPI/apt-ntop_1.0.190416-469_all.deb 
sudo dpkg -i apt-ntop_1.0.190416-469_all.deb 
sudo apt-get -y install ntopng nprobe n2n 

ntopng system is running in community edition:
/etc/systemd/system/ntopng.service:
ExecStart=/usr/local/bin/ntopng /run/ntopng.conf --community

ntopng.conf additions:
-i=eth0
--redis="@1"
--packet-filter="port 53"

when clicking on interface, the following error is reported:
/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>'

**Comment by simonemainardi** [comment] 2020-01-14 10:51
duplicate of #3213

**Closed as completed by simonemainardi** 2020-01-14 10:51 UTC
Labels: Duplicate
