### ISSUE TITLE
No localhosts and ntop suddenly stops picking traffic

### ISSUE THREAD

**Issue by Claireshan** [ntop/ntopng#3814] opened 2020-04-21 09:52 UTC
Hello hope this finds you well.i have the latest version of ntop but i can view the local hosts i only see the remote host. Also suddenly the traffic goes to 0Mbps. what could be the problem

**Comment by simonemainardi** [comment] 2020-04-21 12:01
duplicate of https://github.com/ntop/ntopng/issues/3809

**Closed as completed by simonemainardi** 2020-04-21 12:01 UTC
Labels: Duplicate
