### ISSUE TITLE
1d and 1w reports not working

### ISSUE THREAD

**Issue by Orionpex** [ntop/ntopng#130] opened 2015-08-19 17:02 UTC
I can only pull reports for 1h time frames but unable to use the reporting tool; as it is not displaying reports for 1d, 1w and so on. Please help

![ntoperror1](https://cloud.githubusercontent.com/assets/13873129/9363050/09d78d56-4672-11e5-88c8-473259550d81.jpg)
![ntoperror2](https://cloud.githubusercontent.com/assets/13873129/9363091/50596326-4672-11e5-9336-878b77442987.jpg)

![ntoperror](https://cloud.githubusercontent.com/assets/13873129/9362955/90c826b4-4671-11e5-8af3-f5d17105ad74.jpg)

![ntoperror3](https://cloud.githubusercontent.com/assets/13873129/9363119/86a40e18-4672-11e5-8456-daecc6a29186.jpg)

**Comment by kYroL01** [comment] 2015-08-20 13:38
Hello @Orionpex 
This is what I see in my report page for 1d and 1w

![1d](https://cloud.githubusercontent.com/assets/7222956/9384000/74fdb598-474d-11e5-9691-ff73fffdf3fd.jpg)

![1d_1](https://cloud.githubusercontent.com/assets/7222956/9384014/80a99d94-474d-11e5-9612-69b07043d24d.jpg)

![1w](https://cloud.githubusercontent.com/assets/7222956/9384019/8865fad2-474d-11e5-9e3d-32082a41666b.jpg)

Ok, the traffic is not as much as I see from your images, but it works for me.

**Comment by Orionpex** [comment] 2015-08-20 16:21
@kYroL01 

No complaint about amount of data; but I'm not getting any data output for my 1D and 1W graphs in the reporting tool.

**Comment by kYroL01** [comment] 2015-08-20 20:23
Are you using the last version of ntopng ? Did you reconfigure all correctly ? I try to understand why you see this bug.

**Comment by lucaderi** [comment] 2015-08-25 06:01
As I don't see any  feedback and for us the problem does not occurs, we close this bug.

**Comment by lucaderi** [comment] 2015-08-26 15:59
Apparently this issue can be reproduced on centos 7. Need to investigate

**Comment by lucaderi** [comment] 2015-08-26 23:00
Finally fixes in the repository tonight.

**Closed by lucaderi** 2015-08-26 23:00 UTC
