### ISSUE TITLE
New errors after moving too influxdb

### ISSUE THREAD

**Issue by Eugene-Prokhorenko** [ntop/ntopng#3085] opened 2019-11-23 17:26 UTC
There was an error while sending timeseries data to "http://localhost:8086": partial write: max-series-per-database limit exceeded: (1000000) dropped=157

Also some errors in the log:

23/Nov/2019 20:00:11 [NetworkInterface.cpp:1730] Invalid packet received [len: 7056][max len: 1468].
23/Nov/2019 19:34:50 [ParserInterface.cpp:223] WARNING: A flow has been seen from multiple exporters or from multiple IN/OUT interfaces. Check exporters configuration.
23/Nov/2019 19:34:50 [NetworkInterface.cpp:1730] Invalid packet received [len: 65549][max len: 65535].

As for exporters, they are on different physical peerings and can't have identical flows. How I can didagnoze this?

**Comment by simonemainardi** [comment] 2019-11-25 13:59
> There was an error while sending timeseries data to "http://localhost:8086": partial write: max-series-per-database limit exceeded: (1000000) dropped=157

duplicate of https://github.com/ntop/ntopng/issues/2097

> 23/Nov/2019 20:00:11 [NetworkInterface.cpp:1730] Invalid packet received [len: 7056][max len: 1468].

do you have TSO or GRO enabled? which is your ntopng configuration?

> As for exporters, they are on different physical peerings and can't have identical flows. How I can didagnoze this?

it could be that the same flow is seen from multiple interfaces of the same exporter

**Comment by Eugene-Prokhorenko** [comment] 2019-11-26 06:08
After increasing timeseries I'm getting:
/usr/share/ntopng/scripts/lua/system_stats.lua:33: attempt to call a nil value (field 'getTimeseriesMenu')

**Comment by emanuele-f** [comment] 2019-11-26 11:17
Please update again, it should be fixed

**Comment by Eugene-Prokhorenko** [comment] 2019-11-27 05:40
Fixed.
I put ethtool -K ens3 gro off gso off tso off to /etc/init.d, but still getting warning. How can I be sure, that ethtool run before ntop?

**Comment by emanuele-f** [comment] 2019-11-27 07:51
Which distribution are you using? I'm searching it online e.g. https://serverfault.com/questions/463111/how-to-persist-ethtool-settings-through-reboot

**Comment by Eugene-Prokhorenko** [comment] 2019-11-27 10:53
Ubuntu 18.04. They recommend to create rc-local. I created tso-gro :)
Also I find out this messages in my mail:
Date: Wed, 27 Nov 2019 06:25:24 +0400 (+04)
From: Cron Daemon <root@asnet.am>
To: root@asnet.am
Subject: Cron <root@cacti> test -x /usr/sbin/anacron || ( cd / && run-parts --report
    /etc/cron.daily )

/etc/cron.daily/logrotate:
error: Ignoring cento because of bad file mode - must be 0644 or 0444.
error: Ignoring disk2n because of bad file mode - must be 0644 or 0444.
error: Ignoring n2disk because of bad file mode - must be 0644 or 0444.
error: Ignoring nprobe because of bad file mode - must be 0644 or 0444.

**Comment by emanuele-f** [comment] 2020-03-23 16:26
Closing as the original issue is now solved. Please open separate issues if needed.

**Closed as completed by emanuele-f** 2020-03-23 16:26 UTC
Labels: question
