### ISSUE TITLE
NtopNG exiting on OPNsense

### ISSUE THREAD

**Issue by awptechnologies** [ntop/ntopng#8391] opened 2024-05-15 01:10 UTC
Environment:

    OS name: OPNsense
    OS version: OPNsense 24.1.6-amd64, FreeBSD 13.2-RELEASE-p11
    Architecture: amd64
    ntopng version/revision: 6.0.d20240307,1

What happened:
I keep getting these errors
(ntopng), jid 0, uid 288: exited on signal 11

i only have 8 interfaces enabled and i still seem to get these errors. Seems like there is just a problem with ntopng on opnsense. does anyone have a solution?

How did you reproduce it?
Let Ntopng run for any period of time.

**Comment by MatteoBiscosi** [comment] 2024-05-15 07:55
could you please share the logs you have?

**Comment by awptechnologies** [comment] 2024-05-15 17:31
i just enabled ntop trace log so i can produce the logs. As soon as it crashes i will send them.

**Comment by awptechnologies** [comment] 2024-05-16 19:10
It happen again but i had logging set to normal so it didnt show me any useful message about why it exited. Last log was at 245 and it exited at 250. I started ntopng set logging to debug, stopped the service, deleted the logs, and finally restarted the service. When it happens again hopefully i will be able to give you some useful information.

**Comment by awptechnologies** [comment] 2024-05-18 05:54
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:189] ntop_get_interface_id() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:1091] ntop_interface_alert_store_query() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:189] ntop_get_interface_id() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:1091] ntop_interface_alert_store_query() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:32:27 [Ntop.cpp:1336] No allowed interface found for bge1
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:3938] ntop_get_interface_stats() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called

**Comment by awptechnologies** [comment] 2024-05-18 05:55
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:3204] ntop_is_nedge() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:189] ntop_get_interface_id() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:1091] ntop_interface_alert_store_query() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:189] ntop_get_interface_id() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:1091] ntop_interface_alert_store_query() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:32:27 [Ntop.cpp:1336] No allowed interface found for bge1
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:3938] ntop_get_interface_stats() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:2759] ntop_get_interface_host_country() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:578] get_allowed_nets() called
17/May/2024 14:32:27 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:32:27 [LuaEngineInterface.cpp:4281] ntop_checkpoint_host_talker() called
root@OPNsense:/var/db/ntopng # tail -n 100 ntopng.log
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.88
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.88
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:146] ntop_select_interface() called
17/May/2024 14:33:45 [Ntop.cpp:1336] No allowed interface found for ovpnc1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:3938] ntop_get_interface_stats() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:3204] ntop_is_nedge() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:5136] ntop_get_redis() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineInterface.cpp:47] getCurrentInterface() called
17/May/2024 14:33:45 [LuaEngineInterface.cpp:373] ntop_interface_is_packet_interface() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:394] ntop_is_not_empty_file() called
17/May/2024 14:33:45 [LuaEngineNtop.cpp:247] ntop_is_shuttingdown() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [LuaEngineNtop.cpp:1080] ntop_msleep() called
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.80
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.80
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.81
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.81
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.101
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.101
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.100
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.100
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.80
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.80
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.81
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.81
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.101
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.101
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkInterface.cpp:2365] Purged 1/178 idle flows on vlan03
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.100
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.100
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.84
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.84
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.95
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.82
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.82
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkInterface.cpp:2365] Purged 2/366 idle flows on bge1
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.1
17/May/2024 14:33:45 [NetworkInterface.cpp:2369] Purged 5/182 idle hosts on bge1
17/May/2024 14:33:45 [NetworkInterface.cpp:2365] Purged 14/1161 idle flows on bge0
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.98
17/May/2024 14:33:45 [NetworkInterface.cpp:2369] Purged 2/277 idle hosts on bge0
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.98
17/May/2024 14:33:45 [NetworkDiscovery.cpp:273] Received ARP reply from 10.1.1.80
17/May/2024 14:33:45 [LuaEngine.cpp:610] WARNING: attempt to index a string value

**Comment by awptechnologies** [comment] 2024-05-18 05:55
It just says ntop is shutting down no idea whats going on hopefully you can help

**Comment by MatteoBiscosi** [comment] 2024-05-20 15:16
Hi @awptechnologies i've seen that you are currently using the 6.0 version, that is the standard version of ntopng on opnsense which we cannot change/modify (supported by opnsense). Please install our official repo and i can help you (the issue could be already fixed too) https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html#opnsenseintegration

**Comment by awptechnologies** [comment] 2024-05-27 04:04
i did this based on your website and there were all kinds of errors in log about database being read only. I restored my opnsense with a snapshot and reinstalled the ntop in opnsense default plugins and this does not happen. Opnsense just released update i will see if this fixes my problem and if not i will try to install your official repo and diagnose it from there.

**Comment by MatteoBiscosi** [comment] 2024-05-30 09:01
Ok @awptechnologies I'll close the ticket right now, in case those errors still come back please reopen it.

**Comment by awptechnologies** [comment] 2024-06-05 01:39
So it seems this is the error i am getting when ntop crashes.

[LuaEngine.cpp:610] WARNING: attempt to index a boolean value

This is from ntop log and it happens at the exact same time i get this error in opnsense

<6>pid 5254 (ntopng), jid 0, uid 288: exited on signal 11

**Comment by emsofo** [comment] 2024-06-06 10:43
I can confirm that i have the same issue and error - using j4125 baremetal - latest OPNsense release - and standard ntop plugin - which runs fine for several minutes to hours then fails with same error

**Comment by awptechnologies** [comment] 2024-06-08 09:08
at least its not only me. Idk if this matters but i am running opnsense in a vm on proxmox. My ntop instances lasts days sometimes. It is completely random when it crashes.

**Comment by MrHakisak** [comment] 2024-06-13 11:20
I have also been getting the exact same error after about ~15hours, its been happening for more then a week now. but I will try and get the official repo and report back.
mine is bare metal, 2 physical interfaces, 1WAN, 2LAN's (1 is a vLAN).

**Comment by awptechnologies** [comment] 2024-06-16 17:12
I use ntop to look at wan lan vlan 1 2 3 4 and a wiregaurd vpn

**Comment by lucaderi** [comment] 2024-06-18 20:13
Can you please update and report if the issue is still present?

**Comment by emsofo** [comment] 2024-06-19 04:54
After recent updates, I can confirm that the problem persists - running Opnsense 24.1.8 - ntopng starts, but crashes randomly over time . . .

**Comment by MrHakisak** [comment] 2024-06-19 22:15
> Hi @awptechnologies i've seen that you are currently using the 6.0 version, that is the standard version of ntopng on opnsense which we cannot change/modify (supported by opnsense). Please install our official repo and i can help you (the issue could be already fixed too) https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html#opnsenseintegration

I followed the instructions on that page. ntopng would not start, logs say "libsodium.so.23" is missing, I don't know how to install it.

**Comment by cardigliano** [comment] 2024-06-20 07:17
@emsofo please provide ntopng --version

**Comment by emsofo** [comment] 2024-06-20 07:57
ntopng --version
Version:        6.0.240528 [Community build]
GIT rev:        :6.0.240528

As referenced in this post [https://forum.opnsense.org/index.php?topic=36041](url) - the standard NTopNG plugin for OPNSense is no longer supported, so nobody is taking responsibility for keeping it updated or stable for that matter .  Also, many have had issues trying to install it fresh from repositories  . . .

**Comment by cardigliano** [comment] 2024-06-20 08:03
@emsofo please note we cannot support the Community build, please install our repository from https://packages.ntop.org/FreeBSD/

**Comment by emsofo** [comment] 2024-06-20 08:27
That's what I meant from nobody supporting the community plugin fro OPNSense - Doesn't leave a good impression for NTopNG with such a response . . . Thx anyway.

**Comment by cardigliano** [comment] 2024-06-20 08:30
@emsofo please note you can still use ntopng in Community mode, all we require is that you install our package from our repository as we do not have control over the community build provided by OPNsense and we cannot support it or release updates for bug fixes.

**Comment by emsofo** [comment] 2024-06-20 08:35
Understood - I will try - but I have read that others tried to install direct from repositories and failed with errors - and consequently received no support because it's community  . . . It might be in your interest to create an official OPNSense plugin yourselves - if anything, to promote your product further!!  Just an idea . . . .

**Comment by MrHakisak** [comment] 2024-06-20 08:38
I have updated with the repository, its been 6 hours and no crash. I will report again in 12 hours to see if it crashes (it ussually crashed before 10 hours)

**Comment by cardigliano** [comment] 2024-06-20 08:39
@emsofo we actually have an OPNsense plugin, and we will support you with the community issues if anyone arise, even if with lower priority of course. Please check https://www.ntop.org/guides/ntopng/third_party_integrations/opnsense.html

**Comment by emsofo** [comment] 2024-06-20 08:55
The plugin you are referencing is the Enterprise version - The one most end users find first is the one maintained from Maintainer: m.muenz@gmail.com - and is the community edition.  For the average user this is confusing!  If there was a reliable CE version available, it makes for a good "try before you buy" option . . . That's all I'm saying here . . .

**Comment by cardigliano** [comment] 2024-06-20 09:04
@emsofo the plugin is marked as "-enterprise" to distinguish it from the CE-only version, however you can still run it as community (there is a flag to enable that)

**Comment by emsofo** [comment] 2024-06-20 09:08
I will file this under "nice to know" category! ;-)  It's not overly obvious and your average user will fall into the same trap!  If it's named "enterprise" then one assumes it's the enterprise version and requires a license!  Now I know better - THX!

**Comment by cardigliano** [comment] 2024-06-20 15:43
Closing this - please reopen if it applies also to our binaries. Thank you.

**Closed as completed by cardigliano** 2024-06-20 15:43 UTC
Labels: Waiting for Feedback ⌛

**Comment by awptechnologies** [comment] 2024-10-08 20:30
<6>pid 989 (ntopng), jid 0, uid 288: exited on signal 11 (no core dump - bad address)
Got this error for the first time in a long time let me know what else is needed to diagnose.
