### ISSUE TITLE
The downloaded configuration does not contain anything from the default and non-default preferences

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2351] opened 2019-01-31 18:04 UTC
Debian buster
ntopng 3.8+dfsg1-2~1.gbp2947dc
ndpi 2.6-3
curl 7.63.0-1
[About page](https://user-images.githubusercontent.com/13176858/52048581-0c8fbe80-254c-11e9-9a55-c9dc453fd727.png)

1. Modify some configuration items in ```Preferences```
2. Download the configuration with ```Backup Configuration```
3. ```ntopng_conf_backup.tar.gz``` is empty

**Comment by emanuele-f** [comment] 2019-02-01 09:42
I cannot reproduce the issue. This is the top level archive contents:
![2019-02-01_10-32](https://user-images.githubusercontent.com/5488003/52114604-6227a200-2604-11e9-9bff-53ca54592bde.png)

Then going into the `.` directory shows:

![2019-02-01_10-32_1](https://user-images.githubusercontent.com/5488003/52114603-618f0b80-2604-11e9-832b-d622a6294e88.png)

**Comment by jean-christophe-manciot** [comment] 2019-02-01 15:24
@emanuele-f  
What ndpi/ntopng releases are you using?

**Comment by emanuele-f** [comment] 2019-02-01 15:30
nDPI is not an issue here, I've tested it with the latest stable ntopng_3.8.190131-6037 . It seems like you are using the debian maintained version. Please test the version from our repos http://packages.ntop.org/apt-stable/

**Comment by jean-christophe-manciot** [comment] 2019-02-01 16:32
@emanuele-f 
Your link contains only stable builds for ancient distributions. The development builds are not accessible and they are probably not built for the development distributions such as Debian buster and Ubuntu disco.

I've been trying to build the latest ntopng sources containing your recent fixes in the stable branch, but so far unsuccessfully: cf. [FTBFS issue regarding nDPI](https://github.com/ntop/nDPI/issues/667) which is necessary in order to build ntopng.

**Comment by emanuele-f** [comment] 2019-02-01 16:51
You are right, no support for buster yet, sorry for the wrong info. Btw, maybe you can remove dpdk and compile nDPI without it just to test this issue.

**Comment by jean-christophe-manciot** [comment] 2019-02-02 10:58
I was able to build ntopng from sources (76f35c4a3e46c91dd5dc1b219e900efb6735a9a6) without dpdk support, but starting it  as a daemon seems to work, but in reality it is useless: nothing happens
```
# systemctl start ntopng
# systemctl status ntopng
● ntopng.service - LSB: Start ntopng daemon
   Loaded: loaded (/etc/init.d/ntopng; generated)
   Active: active (exited) since Sat 2019-02-02 11:35:48 CET; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 14449 ExecStart=/etc/init.d/ntopng start (code=exited, status=0/SUCCESS)

Feb 02 11:35:48 samsung5-debian systemd[1]: Starting LSB: Start ntopng daemon...
Feb 02 11:35:48 samsung5-debian systemd[1]: Started LSB: Start ntopng daemon.
# /etc/init.d/ntopng status
#
# ps -aux | grep ntopng
root     18488  0.0  0.0   6144   896 pts/2    S+   11:54   0:00 grep --color=auto ntopng
# grep 3000 /etc/ntopng/ntopng.conf
-w=3000
# netstat -tunpevaW|grep 3000
#
```

**Comment by jean-christophe-manciot** [comment] 2019-02-02 11:00
Starting it manually is the same: nothing happens:
```
# ntopng /etc/ntopng/ntopng.conf 
02/Feb/2019 11:59:29 [Ntop.cpp:1902] Setting local networks to 127.0.0.0/8
02/Feb/2019 11:59:29 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
02/Feb/2019 11:59:29 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
02/Feb/2019 11:59:29 [Ntop.cpp:1842] Parent process is exiting (this is normal)
# netstat -tunpevaW|grep 3000
#

**Comment by jean-christophe-manciot** [comment] 2019-02-02 16:17
@emanuele-f 
I've decided to rebuild both ndpi & ntopng from the latest commit on their dev branch and with DPDK support now:
- **ndpi**: 20190131.2ec41c1 (1.8-1004-g2ec41c1) --> [deb available for Debian buster](https://git.sdxlive.com/DR/tree/Debian/pool/unstable/n/ndpi)
- **ntopng**: 20190201.10468d8 (3.0-2876-g10468d83) --> [deb available for Debian buster](https://git.sdxlive.com/DR/tree/Debian/pool/unstable/n/ntopng)

This time, I am able to start ntopng:
```
# ntopng /etc/ntopng/ntopng.conf 
02/Feb/2019 16:56:06 [Ntop.cpp:1913] Setting local networks to 127.0.0.0/8
02/Feb/2019 16:56:06 [Redis.cpp:146] Successfully connected to redis 127.0.0.1:6379@0
02/Feb/2019 16:56:06 [Redis.cpp:146] Successfully connected to redis 127.0.0.1:6379@0
02/Feb/2019 16:56:06 [Ntop.cpp:1853] Parent process is exiting (this is normal)
# netstat -tunpevaW|grep 3000
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      120        6392604    13677/ntopng
```
Accessing the GUI:
1. **About ntopng**:
![about ntopng](https://user-images.githubusercontent.com/13176858/52166481-30026700-270e-11e9-9968-479541e0e544.png)

2. **Modifying some settings**:
![runtime preferences ntopng](https://user-images.githubusercontent.com/13176858/52166484-45779100-270e-11e9-913a-7426026e7903.png)

3. **Backing up configuration**:
```
# ll ntopng_conf_backup.tar.gz 
-rw-r--r-- 1 actionmystique actionmystique 0 Feb  2 17:05 ntopng_conf_backup.tar.gz
```

Log:
```
# mkdir: cannot create directory ‘/tmp/tmp.LVYGdAknR4/__etc_ntopng’: Permission denied
cp: cannot create directory '/tmp/tmp.LVYGdAknR4/__etc_ntopng': Permission denied
mkdir: cannot create directory ‘/tmp/tmp.LVYGdAknR4/__datadir’: Permission denied
cp: cannot create regular file '/tmp/tmp.LVYGdAknR4/__datadir': Permission denied
/usr/share/ntopng/httpdocs/misc/ntopng-utils-manage-config: line 225: /tmp/tmp.LVYGdAknR4/MANIFEST: Permission denied
/usr/share/ntopng/httpdocs/misc/ntopng-utils-manage-config: line 226: /tmp/tmp.LVYGdAknR4/MANIFEST: Permission denied
find: ‘/tmp/tmp.LVYGdAknR4’: Permission denied
find: invalid mode ‘+0111’
find: ‘/tmp/tmp.LVYGdAknR4’: Permission denied
find: ‘/tmp/tmp.LVYGdAknR4’: Permission denied
find: ‘/tmp/tmp.LVYGdAknR4’: Permission denied
find: ‘/tmp/tmp.LVYGdAknR4’: Permission denied
tar: /tmp/tmp.LVYGdAknR4: Cannot open: Permission denied
tar: Error is not recoverable: exiting now
```

**Comment by jean-christophe-manciot** [comment] 2019-02-02 18:09
I purged all related packages to restart from scratch, including without a /var/lib/redis/dump.rdb and reinstalled them.
**I had to manually create a ```/var/lib/ntopng``` with the expected ntopng:ntopng user:group**. I did not see that in the [docs](https://www.ntop.org/guides/ntopng/how_to_start/index.html), maybe I missed something. I noticed that expectation when running ```ntopng -v 6 /etc/ntopng/ntopng.conf```
```
02/Feb/2019 18:45:29 [Utils.cpp:427] WARNING: mkdir(/var/lib/ntopng) failed [13/Permission denied]
02/Feb/2019 18:45:29 [main.cpp:352] ERROR: Unable to write on /var/lib/ntopng as 'ntopng' [/var/lib/ntopng/.test]: No such file or directory. Please specify a different directory (-d)
```
Now I get a non-zero downloaded ```ntopng_conf_backup.tar.gz```, but **it is pretty useless: it does not contain anything from the non-default GUI preferences**:
```
# gzip -d ntopng_conf_backup.tar.gz 
./
./MANIFEST
./__datadir/
./__etc_ntopng/
./__etc_ntopng/ntopng.conf
```

**Comment by emanuele-f** [comment] 2019-02-04 09:40
Please check out `__datadir/runtimeprefs.json`, it contains the preferences dump.

**Comment by jean-christophe-manciot** [comment] 2019-02-07 17:36
That folder is empty.
It seems that this feature is not correctly supported when there is no license.

**Comment by jean-christophe-manciot** [comment] 2019-02-09 16:08
@emanuele-f
I have built ndpi & ntopng for **Ubuntu disco (19.04)** (with DPDK support now): **the same issue is there**; you can see for yourself below for Ubuntu disco or on Debian buster [here](https://github.com/ntop/ntopng/issues/2351#issuecomment-459977551):
- **ndpi**: git20190207.ddf0066 (1.8-1005-gddf0066) --> [deb available for Ubuntu disco](https://git.sdxlive.com/PPA/plain/Ubuntu/dists/disco/unstable/binary-amd64/ndpi_2.6.1~git20190207.ddf0066+b1-19.04_amd64.deb)
- **ntopng**: git20190209.9cb2a3a (3.0-2919-g9cb2a3a8) --> [deb available for Ubuntu disco](https://git.sdxlive.com/PPA/plain/Ubuntu/dists/disco/unstable/binary-amd64/ntopng_3.8.1~git20190209.9cb2a3a-19.04_amd64.deb)

**Comment by emanuele-f** [comment] 2019-02-11 08:44
What's the output of `ls -ld /tmp`? Can a normal user create a temporary file/dir in your system (e.g. with `mkdir /tmp/test`)? What are the contents of `/etc/ntopng/ntopng.conf `?

**Comment by jean-christophe-manciot** [comment] 2019-02-11 11:56
On **debian buster & Ubuntu disco**:
```
# ls -ld /tmp
drwxrwxrwt 22 root root xxxxxxxx Feb 11 12:47 /tmp
# sudo -u ntopng mkdir /tmp/ntopng
# ls -ld /tmp/ntopng
drwxr-xr-x 2 ntopng ntopng 4096 Feb 11 12:51 /tmp/ntopng
# cat /etc/ntopng/ntopng.conf | grep -v ^#
-G=/var/run/ntopng.pid
-e=
-w=3000
-W=3001
-n=1
# ls -ld /var/run/ntopng.pid
-rw-r--r-- 1 ntopng ntopng 6 Feb 11 02:01 /var/run/ntopng.pid
```

**Comment by emanuele-f** [comment] 2019-02-11 13:51
Please try removing the `-e` and `-G` options and starting ntopng with `systemctl start ntopng`

**Comment by cardigliano** [comment] 2019-02-12 11:26
@jean-christophe-manciot could you try running "ntopng -w 3000 -W 3001 -n 1" in foreground, and check if it prints any error when downloading the configuration? (Unfortunately we are not able to reproduce it, we also tried with the community edition compiled from the git dev branch, to reproduce what you are doing)

**Comment by jean-christophe-manciot** [comment] 2019-02-13 14:46
@emanuele-f 
@cardigliano 
Stopping it with ```/tmp# systemctl stop ntopng``` and launching it with ```/tmp# ntopng -w 3000 -W 3001 -n 1``` leads to the same result when backing up the configuration from the GUI and extracting it:
```
# find ntopng_conf_backup
ntopng_conf_backup
ntopng_conf_backup/__datadir
ntopng_conf_backup/__etc_ntopng
ntopng_conf_backup/__etc_ntopng/ntopng.conf
ntopng_conf_backup/MANIFEST
```
I have noticed a probably unrelated issue when I stop it with ```ctrl ^C```
```
[Ntop.cpp:2125] Deleted PID /var/run/ntopng.pid: [rc: -1][Permission denied]
```

**Comment by jean-christophe-manciot** [comment] 2019-02-13 14:54
What calls should I look for in the trace if I run ```/tmp# ntopng -w 3000 -W 3001 -n -v 6```? The debug log is very chatty.

**Comment by cardigliano** [comment] 2019-02-20 14:48
Please run it without "-v 6" and check the output whili clicking on "Backup Configuration", or send us the whole output in a text file. I recommend you to update to latest ntopng before, as we pushed some change to the backup script. 

You cal also try running the backup utility manually and check / provide us the output:
$ ntopng-utils-manage-config -a backup
Backing up to /var/lib/ntopng/conf.tar.gz ...
$ tar -ztvf /var/lib/ntopng/conf.tar.gz 
[content]

Thank you

**Comment by jean-christophe-manciot** [comment] 2019-02-21 12:20
ndpi 1.8-1009-gab3833a (git20190219.ab3833a)
ntopng 3.0-3018-g07ff4dee (git20190221.07ff4de)
Backing up the configuration:
```
/tmp# systemctl stop ntopng
/tmp# ntopng -w 3000 -W 3001 -n 1
21/Feb/2019 13:13:08 [Ntop.cpp:1919] Setting local networks to 127.0.0.0/8
21/Feb/2019 13:13:08 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
21/Feb/2019 13:13:08 [Redis.cpp:152] Successfully connected to redis 127.0.0.1:6379@0
21/Feb/2019 13:13:08 [PcapInterface.cpp:94] Reading packets from interface enp3s0...
21/Feb/2019 13:13:08 [Ntop.cpp:2011] Registered interface enp3s0 [id: 1]
21/Feb/2019 13:13:08 [PcapInterface.cpp:94] Reading packets from interface lo...
21/Feb/2019 13:13:08 [Ntop.cpp:2011] Registered interface lo [id: 2]
21/Feb/2019 13:13:08 [PcapInterface.cpp:94] Reading packets from interface tap0...
21/Feb/2019 13:13:08 [Ntop.cpp:2011] Registered interface tap0 [id: 5]
21/Feb/2019 13:13:08 [PcapInterface.cpp:94] Reading packets from interface docker0...
21/Feb/2019 13:13:08 [Ntop.cpp:2011] Registered interface docker0 [id: 6]
21/Feb/2019 13:13:10 [main.cpp:302] PID stored in file /var/run/ntopng.pid
21/Feb/2019 13:13:10 [Utils.cpp:594] User changed to ntopng
21/Feb/2019 13:13:10 [HTTPserver.cpp:1085] HTTPS Disabled: missing SSL certificate /usr/share/ntopng/httpdocs/ssl/ntopng-cert.pem
21/Feb/2019 13:13:10 [HTTPserver.cpp:1087] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
21/Feb/2019 13:13:10 [HTTPserver.cpp:1322] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
21/Feb/2019 13:13:10 [HTTPserver.cpp:1325] HTTP server listening on 3000
21/Feb/2019 13:13:10 [main.cpp:374] Logging onto /var/lib/ntopng/ntopng.log
21/Feb/2019 13:13:10 [main.cpp:377] Working directory: /var/lib/ntopng
21/Feb/2019 13:13:10 [main.cpp:379] Scripts/HTML pages directory: /usr/share/ntopng
21/Feb/2019 13:13:10 [Ntop.cpp:391] Welcome to ntopng x86_64 v.3.9.190221 - (C) 1998-19 ntop.org
21/Feb/2019 13:13:10 [Ntop.cpp:401] Built on Debian GNU/Linux buster/sid
21/Feb/2019 13:13:10 [Ntop.cpp:723] Adding 127.0.0.1/32 as IPv4 interface address for lo
21/Feb/2019 13:13:10 [Ntop.cpp:731] Adding 127.0.0.0/8 as IPv4 local network for lo
21/Feb/2019 13:13:10 [Ntop.cpp:723] Adding xxxxxxxxxx/32 as IPv4 interface address for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:731] Adding xxxxxxxxxx/24 as IPv4 local network for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:723] Adding xxxxxxxxxx/32 as IPv4 interface address for tap0
21/Feb/2019 13:13:10 [Ntop.cpp:731] Adding xxxxxxxxxx/24 as IPv4 local network for tap0
21/Feb/2019 13:13:10 [Ntop.cpp:723] Adding xxxxxxxxxx/32 as IPv4 interface address for docker0
21/Feb/2019 13:13:10 [Ntop.cpp:731] Adding xxxxxxxxxx/16 as IPv4 local network for docker0
21/Feb/2019 13:13:10 [Ntop.cpp:750] Adding ::1/128 as IPv6 interface address for lo
21/Feb/2019 13:13:10 [Ntop.cpp:759] Adding ::1/128 as IPv6 local network for lo
21/Feb/2019 13:13:10 [Ntop.cpp:750] Adding xxxxxxxxxx/128 as IPv6 interface address for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:759] Adding xxxxxxxxxx/64 as IPv6 local network for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:750] Adding fe80::xxxxxxxxxx/128 as IPv6 interface address for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:759] Adding fe80::xxxxxxxxxx/64 as IPv6 local network for enp3s0
21/Feb/2019 13:13:10 [Ntop.cpp:750] Adding xxxxxxxxxx::1/128 as IPv6 interface address for tap0
21/Feb/2019 13:13:10 [Ntop.cpp:759] Adding xxxxxxxxxx::1/64 as IPv6 local network for tap0
21/Feb/2019 13:13:10 [PeriodicActivities.cpp:72] Started periodic activities loop...
21/Feb/2019 13:13:10 [PeriodicActivities.cpp:113] Each periodic activity script will use 5 threads
21/Feb/2019 13:13:10 [NetworkInterface.cpp:2577] Started packet polling on interface enp3s0 [id: 1]...
21/Feb/2019 13:13:10 [NetworkInterface.cpp:2577] Started packet polling on interface lo [id: 2]...
21/Feb/2019 13:13:10 [NetworkInterface.cpp:2577] Started packet polling on interface tap0 [id: 5]...
21/Feb/2019 13:13:10 [NetworkInterface.cpp:2577] Started packet polling on interface docker0 [id: 6]...
# tar -ztvf ntopng_conf_backup.tar.gz 
drwx------ ntopng/ntopng     0 2019-02-21 13:08 ./
-rw------- ntopng/ntopng    65 2019-02-21 13:08 ./MANIFEST
drwx------ ntopng/ntopng     0 2019-02-21 13:08 ./__datadir/
drwxr-xr-x ntopng/ntopng     0 2019-02-21 11:32 ./__etc_ntopng/
-rw-r--r-- ntopng/ntopng  3328 2019-02-09 14:45 ./__etc_ntopng/ntopng.conf
```
There is nothing in the trace about the backup.

**Comment by jean-christophe-manciot** [comment] 2019-02-23 11:59
@emanuele-f 
@cardigliano 

```ntopng-utils-manage-config -a backup``` leads to the exact same result:
```
# /usr/share/ntopng/httpdocs/misc/ntopng-utils-manage-config -a backup
Backing up to /var/lib/ntopng/conf.tar.gz ...
File /tmp/tmp.AqjokGO1La/__datadir/runtimeprefs.json ignored
# tar -ztvf /var/lib/ntopng/conf.tar.gz
drwx------ root/root         0 2019-02-23 12:54 ./
-rw-r--r-- root/root        65 2019-02-23 12:54 ./MANIFEST
drwxr-xr-x root/root         0 2019-02-23 12:54 ./__datadir/
drwxr-xr-x root/root         0 2019-02-23 12:51 ./__etc_ntopng/
-rw-r--r-- root/root      3328 2019-02-09 14:45 ./__etc_ntopng/ntopng.conf
```

**Comment by emanuele-f** [comment] 2019-02-27 16:02
Please check out if 57b86780606d40d6267e4e219cda272955657b37 fixes the issue. Run ./autogen.sh and ./configure again after pulling the new code

**Comment by jean-christophe-manciot** [comment] 2019-02-28 11:31
@emanuele-f 
@cardigliano 
It is finally working although I cannot say whether all non-default settings have been saved or only some of them: building 0785c81 and running it leads to:
```
tar -ztvf ntopng_conf_backup.tar.gz
drwx------ ntopng/ntopng     0 2019-02-28 12:24 ./
-rw------- ntopng/ntopng    65 2019-02-28 12:24 ./MANIFEST
drwx------ ntopng/ntopng     0 2019-02-28 12:24 ./__datadir/
-rw------- ntopng/ntopng 24657 2019-02-28 12:17 ./__datadir/runtimeprefs.json
drwxr-xr-x ntopng/ntopng     0 2019-02-28 12:16 ./__etc_ntopng/
-rw-r--r-- ntopng/ntopng  3328 2019-02-09 14:45 ./__etc_ntopng/ntopng.conf
```
Also, it is strange that you were able to download them before the commit 
[57b8678](https://github.com/ntop/ntopng/commit/57b86780606d40d6267e4e219cda272955657b37).

**Comment by emanuele-f** [comment] 2019-03-01 09:17
Defaults should not be serialized. The fix I've made is only required in newer versions of the `file` utility (available in disco), while it worked fine with other distros we support (even with ubuntu 18). I'm closing this as the issue is now solved.

**Closed as completed by emanuele-f** 2019-03-01 09:17 UTC
Labels: To Be Confirmed

**Comment by QGB** [comment] 2019-10-26 11:14
dpdk httpserver
