### ISSUE TITLE
Lua out of memory

### ISSUE THREAD

**Issue by chris-good** [ntop/ntopng#26] opened 2015-05-14 09:34 UTC
Running on centos6 against a very busy Cisco ASA ntopng is able to run briefly but once we click on a tab to get any data out of the interface we get messages like the following:

13/May/2015 15:05:19 [src/Lua.cpp:4667] WARNING: Script failure [/tmp/ntopng/scripts/lua/iface_ports_list.lua][not enough memory]
13/May/2015 15:05:19 [src/Lua.cpp:4667] WARNING: Script failure [/tmp/ntopng/scripts/lua/iface_ports_list.lua][not enough memory]
13/May/2015 15:05:19 [src/Lua.cpp:4667] WARNING: Script failure [/tmp/ntopng/scripts/lua/iface_ports_list.lua][not enough memory]
13/May/2015 15:05:19 [src/Lua.cpp:4398] WARNING: Script failure [/tmp/ntopng/scripts/callbacks/minute.lua][not enough memory]

**Comment by alenauta** [comment] 2015-05-14 09:42
@chris-good would you report your system resouces?

**Comment by chris-good** [comment] 2015-05-14 10:00
The machine has 8GB ram, mostly free, lots of swap (unused).  I do not
believe that it is a system limit that we are hitting.  I believe it more
likely that lua by default has a relatively low memory allocation which is
inadequate in this case.

On 14 May 2015 at 10:42, alenauta <notifications@github.com> wrote:

> @chris-good <https://github.com/chris-good> would you report your system
> resouces?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/26#issuecomment-101986796>.
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by ariava** [comment] 2015-05-14 11:39
@chris-good could you please provide info about how you started ntopng? Also, is there any chance to troubleshoot the issue on your server?

**Comment by chris-good** [comment] 2015-05-14 12:18
The command we have run is: ntopng -i tcp://127.0.0.1:5556 -n 3


On 14 May 2015 at 12:39, Arianna Avanzini <notifications@github.com> wrote:

> @chris-good <https://github.com/chris-good> could you please provide info
> about how you started ntopng? Also, is there any chance to troubleshoot the
> issue on your server?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/26#issuecomment-102009569>.
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by chris-good** [comment] 2015-05-18 08:57
Any update on this?

On 14 May 2015 at 13:18, Chris Good <chris.good@grapeshot.com> wrote:

> The command we have run is: ntopng -i tcp://127.0.0.1:5556 -n 3
>
>
> On 14 May 2015 at 12:39, Arianna Avanzini <notifications@github.com>
> wrote:
>
>> @chris-good <https://github.com/chris-good> could you please provide
>> info about how you started ntopng? Also, is there any chance to
>> troubleshoot the issue on your server?
>>
>> --
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ntop/ntopng/issues/26#issuecomment-102009569>.
>>
>
>
>
> --
> Chris Good
> Grapeshot
> www.grapeshot.co.uk
> +44 (0) 1223 790 660
> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
> 8DZ | UK
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by ariava** [comment] 2015-05-18 09:06
@chris-good we are unfortunately not managing to reproduce the issue on any of our systems. Is there any chance to troubleshoot the issue on your machine?

**Comment by chris-good** [comment] 2015-05-18 09:31
A little more data for you.

I restarted ntopng and as long as I don't click on any of the links it
seems to survive for a bit.  To give you an idea of the traffic level we
are seeing here is a screenshot from the counter on the homepage:



100k hosts and 128k flows in just over 2 minutes.  Shortly after the
counters stop incrementing when they hit a 128k limit, it was 4 minutes
before I got another screenshot:



Furthermore I have tried running with -H --disable-host-persistency (as an
aside -P, which should be the shortform for --disable-host-persistency, is
not recognised and yields a "invalid option -- 'P'" error).  Running with
those options things seem to work a little better and we can access a
couple more pages but once we hit the "not enough memory" error on a page
we are unable to do anything.

Regards,

Chris


On 18 May 2015 at 09:57, Chris Good <chris.good@grapeshot.com> wrote:

> Any update on this?
>
> On 14 May 2015 at 13:18, Chris Good <chris.good@grapeshot.com> wrote:
>
>> The command we have run is: ntopng -i tcp://127.0.0.1:5556 -n 3
>>
>>
>> On 14 May 2015 at 12:39, Arianna Avanzini <notifications@github.com>
>> wrote:
>>
>>> @chris-good <https://github.com/chris-good> could you please provide
>>> info about how you started ntopng? Also, is there any chance to
>>> troubleshoot the issue on your server?
>>>
>>> --
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ntop/ntopng/issues/26#issuecomment-102009569>.
>>>
>>
>>
>>
>> --
>> Chris Good
>> Grapeshot
>> www.grapeshot.co.uk
>> +44 (0) 1223 790 660
>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>> CB5 8DZ | UK
>>
>
>
>
> --
> Chris Good
> Grapeshot
> www.grapeshot.co.uk
> +44 (0) 1223 790 660
> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
> 8DZ | UK
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by chris-good** [comment] 2015-05-18 09:57
I suspect that you have already discovered this so apologies if this is not
new information.  I have been digging around and it appears that the "not
enough memory" error is coming from luajit.  A google for 'luajit "not
enough memory"'  suggests that on 64-bit machines luajit has a 1gb memory
limit.

I guess that we must simply be able to generate enough data that it hits
the limit.  Please can you advise a workaround or fix for this issue.

On 18 May 2015 at 10:31, Chris Good <chris.good@grapeshot.com> wrote:

> A little more data for you.
>
> I restarted ntopng and as long as I don't click on any of the links it
> seems to survive for a bit.  To give you an idea of the traffic level we
> are seeing here is a screenshot from the counter on the homepage:
>
>
>
> 100k hosts and 128k flows in just over 2 minutes.  Shortly after the
> counters stop incrementing when they hit a 128k limit, it was 4 minutes
> before I got another screenshot:
>
>
>
> Furthermore I have tried running with -H --disable-host-persistency (as an
> aside -P, which should be the shortform for --disable-host-persistency, is
> not recognised and yields a "invalid option -- 'P'" error).  Running with
> those options things seem to work a little better and we can access a
> couple more pages but once we hit the "not enough memory" error on a page
> we are unable to do anything.
>
> Regards,
>
> Chris
>
>
> On 18 May 2015 at 09:57, Chris Good <chris.good@grapeshot.com> wrote:
>
>> Any update on this?
>>
>> On 14 May 2015 at 13:18, Chris Good <chris.good@grapeshot.com> wrote:
>>
>>> The command we have run is: ntopng -i tcp://127.0.0.1:5556 -n 3
>>>
>>>
>>> On 14 May 2015 at 12:39, Arianna Avanzini <notifications@github.com>
>>> wrote:
>>>
>>>> @chris-good <https://github.com/chris-good> could you please provide
>>>> info about how you started ntopng? Also, is there any chance to
>>>> troubleshoot the issue on your server?
>>>>
>>>> --
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/ntop/ntopng/issues/26#issuecomment-102009569>.
>>>>
>>>
>>>
>>>
>>> --
>>> Chris Good
>>> Grapeshot
>>> www.grapeshot.co.uk
>>> +44 (0) 1223 790 660
>>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>>> CB5 8DZ | UK
>>>
>>
>>
>>
>> --
>> Chris Good
>> Grapeshot
>> www.grapeshot.co.uk
>> +44 (0) 1223 790 660
>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>> CB5 8DZ | UK
>>
>
>
>
> --
> Chris Good
> Grapeshot
> www.grapeshot.co.uk
> +44 (0) 1223 790 660
> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
> 8DZ | UK
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by chris-good** [comment] 2015-05-18 10:28
Just to follow up on that, if we use -x and -X we can get things working.
 128000 seems to work OK but once we get to 256000 hosts/flows we get the
out of memory error.

On 18 May 2015 at 10:57, Chris Good <chris.good@grapeshot.com> wrote:

> I suspect that you have already discovered this so apologies if this is
> not new information.  I have been digging around and it appears that the
> "not enough memory" error is coming from luajit.  A google for 'luajit "not
> enough memory"'  suggests that on 64-bit machines luajit has a 1gb memory
> limit.
>
> I guess that we must simply be able to generate enough data that it hits
> the limit.  Please can you advise a workaround or fix for this issue.
>
> On 18 May 2015 at 10:31, Chris Good <chris.good@grapeshot.com> wrote:
>
>> A little more data for you.
>>
>> I restarted ntopng and as long as I don't click on any of the links it
>> seems to survive for a bit.  To give you an idea of the traffic level we
>> are seeing here is a screenshot from the counter on the homepage:
>>
>>
>>
>> 100k hosts and 128k flows in just over 2 minutes.  Shortly after the
>> counters stop incrementing when they hit a 128k limit, it was 4 minutes
>> before I got another screenshot:
>>
>>
>>
>> Furthermore I have tried running with -H --disable-host-persistency (as
>> an aside -P, which should be the shortform for --disable-host-persistency,
>> is not recognised and yields a "invalid option -- 'P'" error).  Running
>> with those options things seem to work a little better and we can access a
>> couple more pages but once we hit the "not enough memory" error on a page
>> we are unable to do anything.
>>
>> Regards,
>>
>> Chris
>>
>>
>> On 18 May 2015 at 09:57, Chris Good <chris.good@grapeshot.com> wrote:
>>
>>> Any update on this?
>>>
>>> On 14 May 2015 at 13:18, Chris Good <chris.good@grapeshot.com> wrote:
>>>
>>>> The command we have run is: ntopng -i tcp://127.0.0.1:5556 -n 3
>>>>
>>>>
>>>> On 14 May 2015 at 12:39, Arianna Avanzini <notifications@github.com>
>>>> wrote:
>>>>
>>>>> @chris-good <https://github.com/chris-good> could you please provide
>>>>> info about how you started ntopng? Also, is there any chance to
>>>>> troubleshoot the issue on your server?
>>>>>
>>>>> --
>>>>> Reply to this email directly or view it on GitHub
>>>>> <https://github.com/ntop/ntopng/issues/26#issuecomment-102009569>.
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> Chris Good
>>>> Grapeshot
>>>> www.grapeshot.co.uk
>>>> +44 (0) 1223 790 660
>>>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>>>> CB5 8DZ | UK
>>>>
>>>
>>>
>>>
>>> --
>>> Chris Good
>>> Grapeshot
>>> www.grapeshot.co.uk
>>> +44 (0) 1223 790 660
>>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>>> CB5 8DZ | UK
>>>
>>
>>
>>
>> --
>> Chris Good
>> Grapeshot
>> www.grapeshot.co.uk
>> +44 (0) 1223 790 660
>> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge |
>> CB5 8DZ | UK
>>
>
>
>
> --
> Chris Good
> Grapeshot
> www.grapeshot.co.uk
> +44 (0) 1223 790 660
> Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
> 8DZ | UK
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by ariava** [comment] 2015-05-19 10:28
@chris-good thanks for all the info you provided. We understand that luajit's memory limit could be the issue here. There is a major improvement planned in ntopng's roadmap which will address high memory usage by Lua scripts in a proper way. However this improvement will most likely not make it to be included in 2.0.
If you could provide access to your machine, we could troubleshoot the issue properly. In case the issue is actually caused by luajit memory limits we could suggest an ad-hoc workaround; in case it isn't, we could finally get to the cause and address the real problem. In case remote access is not allowed, we'd be forced to ask to just stand by until 2.0 is released and we start working on 2.1.

**Comment by chris-good** [comment] 2015-05-19 10:39
I am afraid that I don't think we will be able to get access to the
machine.  All the indications are that luajit memory limits are the issue.
If you set up a 64bit test bench with similar traffic rates to those we are
seeing I am confident that you will be able to reproduce once you see the
counters start ticking over 200000 hosts/flows.

Do you have any timescales for 2.1?

On 19 May 2015 at 11:28, Arianna Avanzini <notifications@github.com> wrote:

> @chris-good <https://github.com/chris-good> thanks for all the info you
> provided. We understand that luajit's memory limit could be the issue here.
> There is a major improvement planned in ntopng's roadmap which will address
> high memory usage by Lua scripts in a proper way. However this improvement
> will most likely not make it to be included in 2.0.
> If you could provide access to your machine, we could troubleshoot the
> issue properly. In case the issue is actually caused by luajit memory
> limits we could suggest an ad-hoc workaround; in case it isn't, we could
> finally get to the cause and address the real problem. In case remote
> access is not allowed, we'd be forced to ask to just stand by until 2.0 is
> released and we start working on 2.1.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/ntop/ntopng/issues/26#issuecomment-103430475>.
>



-- 
Chris Good
Grapeshot
www.grapeshot.co.uk
+44 (0) 1223 790 660
Grapeshot Limited | 9 Dukes Court | 54-62 Newmarket Road | Cambridge | CB5
8DZ | UK

**Comment by ariava** [comment] 2015-05-19 10:47
@chris-good ntopng 2.0 should be released at the end of the month, so we'd be starting to work on 2.1 immediately after that.

**Comment by hemskgren** [comment] 2015-05-20 17:29
Hello

We get the same problem.
centos7, ntopng stable, asa and netflow.
lua memory issue after 5-30 min dependig on connection/flow.

Have run other netflow v9 device for weeks with out issue. 

Will test -x and -X tomorrow.

Regards 
Christer

**Comment by hemskgren** [comment] 2015-05-21 10:46
The -X make it work for me.

Regards
Christer

**Comment by ariava** [comment] 2015-07-10 21:09
@chris-good we have implemented some possible fixes for this issue. When possible, we have attempted to reduce load on the Lua stack, by fixing some of the scripts and implementing a flexible interface to filter out flows/hosts stats when retrieving them. However, we'd like some feedback so that we know where to apply it. Could you please try the latest dev branch?

**Comment by hemskgren** [comment] 2015-07-11 11:33
Hi

Today i switch from centos7 x64 stable to nightly builds (150711-4723). 

After my May update I have updated to 2.0 stable. It is much better in cpu usage.
What i notice is the ntopng cpu load is now always over 100% from about 30-40% before.

I will check more later in the week. We do not have the same load on this ASA in the summer.

Regards
Christer

**Comment by hemskgren** [comment] 2015-07-20 10:39
Hi

It look like it run clean with 80-90 K conn/netflow from ASA with this spec.

Version	2.0.150711 - Community Edition
Platform	x86_64-unknown-linux-gnu (x86_64) - 64 bit
Uptime	 8 days, 23 h, 31 min, 58 sec

It will properly take a couple if week before we see 130 K conn/netflow.

Regards
Christer

**Comment by hemskgren** [comment] 2015-07-20 10:45
Hi

Should I keep the version or upgrade to latest (150720-264)? 
I will leave it for a couple of weeks to I back to work again.

Regards
Christer

**Comment by ariava** [comment] 2015-07-22 01:07
@hemskgren I believe by updating to the latest nightly you could get some improvement and many bugfixes which haven't been ported to stable yet.

**Comment by lucaderi** [comment] 2015-07-25 09:22
These changes will not go in stable but in the next release. @hemskgren Please check if the fix works so we can close this bug

**Comment by hemskgren** [comment] 2015-08-03 07:48
Hi

This look like it solve the problem. 
Running fine for 22 days with the max 131,072 Flows for at least some time.

Regards
Christer

**Closed** 2015-08-07 12:45 UTC
Labels: bug
