### ISSUE TITLE
Huge ram memory usage with checkmk integration

### ISSUE THREAD

**Issue by adrianmoraru** [ntop/ntopng#6551] opened 2022-04-28 13:18 UTC
Hello Team,

I have a issue with ntopng <-> checkmk integration. The situation is like this:

- If I navigate in ntopng interface everything is ok - form resources point of view (cpu, ram, disk)
- When I navigate in checkmk, on the ntop options that appear after the integration, the ram usage is growing fast to 30-40-50GB ram. 
- The solution is systemctl restart ntopng

**Environment**:
* OS name: Ubuntu
* OS version: 20.04.4
* Architecture: amd64
* ntopng version/revision: 5.2.220425

**Debug Information**:
`root@ntop:~# systemctl status ntopng
● ntopng.service - ntopng high-speed web-based traffic monitoring and analysis tool
     Loaded: loaded (/etc/systemd/system/ntopng.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-04-28 16:04:24 EEST; 5min ago
    Process: 1206061 ExecStartPre=/bin/sh -c /usr/bin/ntopng-utils-manage-config -a check-restore  && /usr/bin/ntopng-utils-manage-config -a restore || true (code=exited, status=0/S>
    Process: 1206094 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf > /run/ntopng.conf.raw (code=exited, status=0/SUCCESS)
    Process: 1206096 ExecStartPre=/bin/sh -c /bin/cat /etc/ntopng/ntopng.conf.d/*.conf >> /run/ntopng.conf.raw 2>/dev/null || true (code=exited, status=0/SUCCESS)
    Process: 1206098 ExecStartPre=/bin/sh -c /bin/sed "/^[ ]*-e.*$\|^[ ]*-G.*\|^[ ]*--daemon.*\|[ ]*--pid.*/s/^/#/" /run/ntopng.conf.raw > /run/ntopng.conf (code=exited, status=0/SU>
   Main PID: 1206100 (4/flow_checks)
      Tasks: 30 (limit: 77043)
     Memory: 23.1G
     CGroup: /system.slice/ntopng.service
             └─1206100 /usr/bin/ntopng /run/ntopng.conf

Apr 28 16:04:39 ntop ntopng[1206100]: 28/Apr/2022 16:04:39 [NtopPro.cpp:800] [LICENSE] License Hash:        42E88DB45C057DE2A7764C1A5A371E181659787856B213626F
Apr 28 16:04:39 ntop ntopng[1206100]: 28/Apr/2022 16:04:39 [NtopPro.cpp:811] [LICENSE] Maintenance:        Until Sat Aug  6 15:10:56 2022 [99 days left]
Apr 28 16:04:40 ntop ntopng[1206100]: 28/Apr/2022 16:04:40 [PeriodicActivities.cpp:109] Started periodic activities loop...
Apr 28 16:04:40 ntop ntopng[1206100]: 28/Apr/2022 16:04:40 [startup.lua:35] Processing startup.lua: please hold on...
Apr 28 16:04:41 ntop ntopng[1206170]: Failed to print the table: Broken pipe
Apr 28 16:04:41 ntop ntopng[1206100]: 28/Apr/2022 16:04:41 [startup.lua:120] [lists_utils.lua:786] Category lists not loaded (offline)
Apr 28 16:04:41 ntop ntopng[1206100]: 28/Apr/2022 16:04:41 [startup.lua:202] Completed startup.lua
Apr 28 16:04:41 ntop ntopng[1206100]: 28/Apr/2022 16:04:41 [PeriodicActivities.cpp:167] Found 10 activities
Apr 28 16:04:41 ntop ntopng[1206100]: 28/Apr/2022 16:04:41 [NetworkInterface.cpp:3198] Started packet polling on interface tcp://*:5556c [id: 4]...
Apr 28 16:04:42 ntop ntopng[1206100]: 28/Apr/2022 16:04:42 [ZMQCollectorInterface.cpp:258] Collecting flows on tcp://*:5556c`

`root@ntop:~# ps faxu | grep ntopng
root     1208421  0.0  0.0   6432   656 pts/1    S+   16:13   0:00                      \_ grep --color=auto ntopng
ntopng   1206100  377 60.1 41451744 39610600 ?   Ssl  16:04  34:49 /usr/bin/ntopng /run/ntopng.conf`

`root@ntop:~# netstat -tupan | grep -i ntopng
tcp        0      0 0.0.0.0:5556            0.0.0.0:*               LISTEN      1206100/ntopng
tcp       14      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      1206100/ntopng
tcp      444      0 10.0.42.96:3000         192.168.141.2:51619     ESTABLISHED 1206100/ntopng
tcp        1      0 10.0.42.96:3000         10.0.42.99:42788        CLOSE_WAIT  1206100/ntopng
tcp      475      0 10.0.42.96:3000         192.168.141.2:51618     ESTABLISHED 1206100/ntopng
tcp      475      0 10.0.42.96:3000         192.168.141.2:51621     ESTABLISHED 1206100/ntopng
tcp        1      0 10.0.42.96:3000         10.0.42.99:42460        CLOSE_WAIT  1206100/ntopng
tcp      444      0 10.0.42.96:3000         192.168.141.2:51627     ESTABLISHED 1206100/ntopng
tcp      498      0 10.0.42.96:3000         192.168.141.2:51617     ESTABLISHED 1206100/ntopng
tcp      422      0 10.0.42.96:3000         192.168.141.2:51620     ESTABLISHED 1206100/ntopng
tcp      444      0 10.0.42.96:3000         192.168.141.2:51623     ESTABLISHED 1206100/ntopng
tcp      422      0 10.0.42.96:3000         192.168.141.2:51629     ESTABLISHED 1206100/ntopng
tcp        0      0 127.0.0.1:5556          127.0.0.1:40648         ESTABLISHED 1206100/ntopng
tcp        1      0 10.0.42.96:3000         10.0.42.99:42140        CLOSE_WAIT  1206100/ntopng
tcp      358      0 10.0.42.96:3000         10.0.42.99:43030        CLOSE_WAIT  1206100/ntopng
tcp      271      0 10.0.42.96:3000         10.0.42.99:42790        CLOSE_WAIT  1206100/ntopng
tcp      278      0 10.0.42.96:3000         10.0.42.99:43024        CLOSE_WAIT  1206100/ntopng
tcp      499      0 10.0.42.96:3000         192.168.141.2:51624     ESTABLISHED 1206100/ntopng
tcp      352      0 10.0.42.96:3000         10.0.42.99:43298        CLOSE_WAIT  1206100/ntopng
tcp      475      0 10.0.42.96:3000         192.168.141.2:51626     ESTABLISHED 1206100/ntopng
tcp      267      0 10.0.42.96:3000         10.0.42.99:42792        CLOSE_WAIT  1206100/ntopng
tcp      422      0 10.0.42.96:3000         192.168.141.2:51625     ESTABLISHED 1206100/ntopng
tcp      352      0 10.0.42.96:3000         10.0.42.99:43026        CLOSE_WAIT  1206100/ntopng
tcp      498      0 10.0.42.96:3000         192.168.141.2:51628     ESTABLISHED 1206100/ntopng
tcp        1      0 10.0.42.96:3000         10.0.42.99:43010        CLOSE_WAIT  1206100/ntopng
tcp        1      0 10.0.42.96:3000         10.0.42.99:43274        CLOSE_WAIT  1206100/ntopng
tcp      278      0 10.0.42.96:3000         10.0.42.99:43296        CLOSE_WAIT  1206100/ntopng`

10.0.42.99 -> is checkmk server

I attached 2 printscreens with normal RAM usage and after a few clicks in checkmk (on ntop options).
![after](https://user-images.githubusercontent.com/81408970/165759995-1f195ce4-61db-42e1-99ed-a2ff25b5cce2.png)
![before](https://user-images.githubusercontent.com/81408970/165760002-fadfc693-01f3-4df6-8022-9d95c5a0196e.png)

If you need anything else from me please tell me.

Thank you,
Adrian Moraru

**Comment by cardigliano** [comment] 2022-04-28 15:05
@adrianmoraru can we schedule a call to take a look at this together?

**Comment by adrianmoraru** [comment] 2022-04-29 06:13
@cardigliano sure, when is ok for you ? Today or next week Monday ?

**Comment by cardigliano** [comment] 2022-04-29 07:34
Today should work for me for a quick one, please drop an email to cardigliano at ntop.org

**Comment by adrianmoraru** [comment] 2022-05-09 06:33
Hello,
Any updates on this issue ?

Thank you,
Adrian Moraru

**Comment by adrianmoraru** [comment] 2022-05-24 06:16
Hello,
Any news on this issue ?

Thank you,
Adrian Moraru

**Comment by cardigliano** [comment] 2022-05-25 09:11
@adrianmoraru sorry for late reply, we are still digging into this, I will try to push this to find a solution asap

**Comment by cardigliano** [comment] 2022-05-25 14:42
@adrianmoraru since I was not able to reproduce your issue, I sent you a binary you can use to provide debug information, and instructions to run it, by email.

**Comment by adrianmoraru** [comment] 2022-05-25 14:48
Hello Alfredo,
I received you email. I will test and come back with news.

**Comment by adrianmoraru** [comment] 2022-06-10 13:19
Hello Alfredo,
I response via email with results.

**Comment by alonek1** [comment] 2022-09-09 07:29
Hi,
I'm experiencing same issue. Is there any update/solution for this?

**Comment by cardigliano** [comment] 2022-09-09 15:54
@alonek1 this is on hold as we were unable to reproduce the same both in our lab and on the customer box using a debug binary (including a memory sanitizer). Are you able to provide ssh access to your box to try to debug this?

**Comment by cardigliano** [comment] 2022-11-28 15:13
No more updates, closing (reopen if still able to reproduce)

**Closed as completed by cardigliano** 2022-11-28 15:13 UTC
Labels: In Progress
