### ISSUE TITLE
GeoMap under Host Page Not working

### ISSUE THREAD

**Issue by simonemainardi** [ntop/ntopng#3693] opened 2020-04-02 13:33 UTC
No flows are shown, just peers

![image](https://user-images.githubusercontent.com/3397663/78255137-36999380-74f7-11ea-9b85-5bc0ed500370.png)

expected behavior is

![image](https://user-images.githubusercontent.com/3397663/78255162-3dc0a180-74f7-11ea-8191-ecd4cd09bd2d.png)

**Comment by simonemainardi** [comment] 2020-04-16 20:22
any news?

**Comment by ShagoY** [comment] 2020-05-04 12:32
I was really disappointed when you migrated to Leaflet because of this regression on the Geomap.
Glad to see that this was not intentional :)

**Comment by gabryon99** [comment] 2020-06-11 16:20
We have also to refactorize the `get_geo_hosts.lua` script

**Comment by gabryon99** [comment] 2020-06-15 08:30
The Lua script `get_geo_hosts.lua` has been refactorized. Now there is no JSON printed with the `print` function but we use a simple Lua table to collect data and then print it with the `json` module. When a user navigates to a host page the map flies to the root server which is marked with the red color. 

See the commit: https://github.com/ntop/ntopng/commit/5b4b55872feb9d9b58018c17184b067220f6b2e7

**Comment by lucaderi** [comment] 2020-06-23 11:48
This bug seems to be fixed Now it works. The problem is that clustering hosts prevents them from being placed at the right place. The picture below shows the problem with 3 hosts belonging to the same subnet and located at 12.109700202942,43.147899627686 and placed in the wrong place

![Screen Shot 2020-06-23 at 13 45 48](https://user-images.githubusercontent.com/4493366/85400094-27efd500-b558-11ea-9696-2179333dc955.png)

**Comment by lucaderi** [comment] 2020-06-25 16:27
![Screen Shot 2020-06-25 at 18 25 49](https://user-images.githubusercontent.com/4493366/85759518-62e93880-b711-11ea-9e2f-b3b3b3705d22.png)
![Screen Shot 2020-06-25 at 18 25 42](https://user-images.githubusercontent.com/4493366/85759534-6381cf00-b711-11ea-9dec-65295c932a9b.png)

Furthermore please
- a consequence of the above geolocation discrepancy is that you put host in places they should be (eg. on a lake)
- you should remove the lines from the center to the hosts

**Comment by gabryon99** [comment] 2020-07-02 12:44
Removed the label below the map

**Comment by gabryon99** [comment] 2020-07-02 12:44
See commit: https://github.com/ntop/ntopng/commit/32dec57efb074d5d8937779385a6b3c6a138b203

**Closed as completed by gabryon99** 2020-07-02 12:44 UTC
Labels: Low-Priority Bug, In Progress

**Comment by ShagoY** [comment] 2020-11-12 13:50
Any chance to see the same behavior before leaflet migration?
I'm talking about the connections/relationship between markers.

Thanks.

**Comment by bre75** [comment] 2021-06-08 13:19
Hello,

Sorry I know the subject is closed, but I'm new to ntopng (on RaspberryPI) and I'm facing the initial issue.
I can see the peers (in my case Quad9) but not the flow from my RaspberryPI (I'm based in Paris, France).

Maybe it's important to notice, I also have Pi-Hole installed on the same RaspberryPI and is acting DHCP Server.

<img width="725" alt="Capture" src="https://user-images.githubusercontent.com/20688640/121191995-c9a52a80-c86c-11eb-83be-b17bfa3881fe.PNG">

Any idea ?

Thanks for any answer.

Regards,

PS :ntopng config below
<img width="614" alt="Capture2" src="https://user-images.githubusercontent.com/20688640/121198745-abdac400-c872-11eb-8a78-f74b66c17f77.PNG">
