### ISSUE TITLE
Global interface traffic graph not in line with real traffic bandwidth usage

### ISSUE THREAD

**Issue by Amanr77** [ntop/ntopng#6876] opened 2022-09-14 07:25 UTC
![ntop-evidence](https://user-images.githubusercontent.com/24620180/193232767-b79812ec-4321-4de1-88bb-e2b91767d1c5.JPG)

**Environment**:
* OS name: Centos
* OS version: 7.9.2009
* Architecture: x64
* ntopng version/revision: ntopng-5.4.220913-18458.x86_64

**What happened**:
the graph on the top left corner is not in line with the sum of the single live flows "Actual Thpt" values and not in line with the values grabbed by pfcount command started behind the scene on the same machine

![live flows](https://user-images.githubusercontent.com/24620180/190088549-36314085-ebd9-4176-824f-39cdacd77753.PNG)
![ntop graph](https://user-images.githubusercontent.com/24620180/190088559-57aaf8d3-e685-444c-9afb-48f6d016ab60.PNG)
![pfcount](https://user-images.githubusercontent.com/24620180/190088563-baf28496-95e7-4df4-9553-da9159df15c9.PNG)

**Comment by Amanr77** [comment] 2022-09-26 06:48
I'm still facing the issue even with the latest ntopng-5.4.220922-18510.x86_64

**Comment by MatteoBiscosi** [comment] 2022-11-15 10:40
The issue is now fixed; the problem is that the various periodical updates on the traffic, flow, ecc are done in a different time, so it happens that when you see a peak on the chart on the upper left part of the GUI, you see old data from the table and viceversa.
Now the issue should be fixed

**Closed as completed by MatteoBiscosi** 2022-11-15 10:40 UTC
Labels: To Be Confirmed, In Progress
