### ISSUE TITLE
interface traffic not working as expected

### ISSUE THREAD

**Issue by bugtoo** [ntop/ntopng#317] opened 2015-12-13 20:48 UTC
The interface traffic displays a spike that account for all flow traffic at the time of the end of the flow, regardless of flow duration - I expect to see the average throughput on the duration timeframe of the flow: is it a bug or is it correct?

<img width="773" alt="cattura1" src="https://cloud.githubusercontent.com/assets/16280306/11769256/eb3e09de-a1e2-11e5-9f6b-77d6fce3d4ee.PNG">
<img width="790" alt="cattura2" src="https://cloud.githubusercontent.com/assets/16280306/11769255/eb3ca922-a1e2-11e5-9cd5-ce935b5aeb98.PNG">

(ntopng Professional v.2.3.151213)
(nProbe Pro v.7.3.151213)

**Comment by lucaderi** [comment] 2016-01-28 14:32
This is a duplicate of https://github.com/ntop/ntopng/issues/57 as the root cause is the same.

**Closed by lucaderi** 2016-01-28 14:32 UTC
