### ISSUE TITLE
Problem about local network

### ISSUE THREAD

**Issue by lhxhanson** [ntop/ntopng#669] opened 2016-07-27 09:28 UTC
Hi all,

My OS is CentOS-6.7, the IP of ntopng-host is 172.26.10.4, and the version of ntopng is 2.5.160629.
I have a problem about "local-networks". I put some subnet in the ntopng conf file.
Like,
--local-networks "172.26.10.0/24, 172.26.8.0/21,172.26.176.0/21"

When I start ntopng, the log says

[Ntop.cpp:1121] Setting local networks to 172.26.10.0/24, 172.26.8.0/21,172.26.176.0/21
[Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
........
[NtopPro.cpp:252] [LICENSE] ntopng is starting without a valid license
[Ntop.cpp:531] _Adding 172.26.10.0/24 as IPv4 local network for eth0_

**Why add 172.26.10.0 again?**

![qq 20160727171926](https://cloud.githubusercontent.com/assets/5568373/17170385/534ccb76-541e-11e6-857f-d5670f58c145.png)

**Why some host has a 172.26.10.0's ip are identify as remote?**

**Comment by simonemainardi** [comment] 2016-07-27 09:42
please update to the latest version we already solved that issue on another architecture. Please let us know

**Comment by lhxhanson** [comment] 2016-07-27 10:13
Hi simone,

After posting this issue, I was doing the update. But looks like, the problem still exist.
![20160727180910](https://cloud.githubusercontent.com/assets/5568373/17171949/6924f746-5425-11e6-96f5-82e6e8b08b81.png)

![20160727181122](https://cloud.githubusercontent.com/assets/5568373/17171972/8ec6fc42-5425-11e6-81b7-1aad48e0e58f.png)

**Comment by simonemainardi** [comment] 2016-07-27 10:15
I noticed you are using a a lot of options: can you try and report the behavior without:
- sticky hosts
- packet filter

thank you

**Comment by lhxhanson** [comment] 2016-07-27 11:40
Thanks for reply.
After comment out the option you mentioned, it looks like the problem has gone.
So I'd like test for about 12 hours,  and will give you the report after the test.

**Comment by simonemainardi** [comment] 2016-07-27 12:26
which option did you commented out?

**Comment by lhxhanson** [comment] 2016-07-27 12:32
I comment out "packet filter", and change "sticky hosts" from "all" to "local".
After some test, I find that, if the host has no traffic through the ntopng, they are identified as remote, but once I make some traffic, like ping, they will change to local if they are match to the option "local-networks"

**Comment by simonemainardi** [comment] 2016-07-27 12:40
thanks for reporting. How can you see an host in ntopng if it has no traffic? What do you mean? Please, explain the exact sequence of steps.

**Comment by lhxhanson** [comment] 2016-07-28 02:00
This is why I was curious.
We have some subnet, for example "192.168.11.0/24". After ntopng start running for a while, I notice that some host like "192.168.11.123" appear in the "remote networks", but the traffic of them were 0. But after I ping the host from ntopng, that host changed from remote to local.
But this issue did not happen again for now. Maybe the option that modified works.

**Comment by lhxhanson** [comment] 2016-07-28 04:19
And if I set “sticky-hosts” in the conf file, the settings in Preference->In-Memory Data are working?
For example, I set sticky-hosts=local, "Local Host Idle Timeout" will not work?

**Comment by simonemainardi** [comment] 2016-07-28 08:18
if you set sticky hosts to local you override the local host idle timeout that is ignored.

So as you can't reproduce the issue, I think it is safe to close it. You should consider reopening that if it occurs again, posting also the exact steps that lead to that.

thank you.

**Closed as completed by simonemainardi** 2016-07-28 08:18 UTC
