### ISSUE TITLE
Network Discovery causes hang of Docker container

### ISSUE THREAD

**Issue by albeec13** [ntop/ntopng#4774] opened 2020-11-23 20:03 UTC
Previous docker image ntop/ntopng:stable was working fine, but I had an update notification for new stable version (77288b0aad73 docker image hash). Downloaded and installed a new clean container, and now every time I run network discovery, the system stops responding. Since I'm running this on a router on the the LAN interface, this causes the entire router to stop bridging traffic, taking the network down.

I've verified that running Network Discovery causes this 100% of the time. I also turned out automatic network discovery with 30 minute interval, and as soon as the time hit, the network went down again.  This was working fine in the previous stable docker image.

Any idea what's going on here? Please direct me to to any logs that would be helpful.

Update:
I restored a backup of my router to get access to the old docker image, and it's working now with the old version. Network discovery is only broken on the latest docker image.

Old docker image hash: fa81df9384e7 (network discovery hangs)
ntopng version: 4.0.201021 (11902) -  Community Edition

New docker image hash: 77288b0aad73 (network discovery works)
ntopng version: 4.2.0 (?)

**Comment by MatteoBiscosi** [comment] 2020-12-11 09:33
I'm not able to reproduce the problem, I'm currently running ntopng version: 4.2.201105 and after running Network Discovery the system seems working fine. If possible, could you please try to upgrade to the new stable version and let me know if the problem persists?

**Comment by albeec13** [comment] 2020-12-11 22:39
Tried with latest stable version at: https://hub.docker.com/r/ntop/ntopng/tags?page=1&ordering=last_updated

Result is the same. When starting network discovery, ntopng hangs, and router stops bridging traffic. I had to restore my backups for the docker folders to recover.

If you can make prior images available on docker hub it would make testing much easier, because I wouldn't have to restore from backup every time which is time consuming.  I've gone back to the old docker image from recovery for now, but the problem still exists in both 4.0.201021 and 4.2.201105 :(

**Comment by lucaderi** [comment] 2020-12-14 08:07
@albeec13 The host where the contaienr runs is a router or  bridge? What is the command you have used to start it?

**Comment by albeec13** [comment] 2020-12-15 07:28
Host is a router. The command I use to start the docker is:
`sudo docker run --name ntopng -itd -p 3000:3000 --net=host ntop/ntopng:stable -i enp2s0 --community`

This is the exact same command I use regardless of which docker image version I'm running.

The system is running arch linux, and enp2s0 is the LAN-side interface, which is using dnsmasq for NAT and the system is doing IPv4 forwarding to the enp1s0 (WAN) interface.

Again, the old version works fine, but the newer versions hang when doing network discovery.

**Comment by lucaderi** [comment] 2020-12-15 08:48
Sorry but we do not use arch linux. If you can troubleshoot it a bit that would help to produce it on our end.

**Comment by lucaderi** [comment] 2020-12-30 08:27
Duplicate of #4861 that shoulf fixed by now

**Closed as completed by lucaderi** 2020-12-30 08:27 UTC
Labels: To Be Confirmed

**Comment by albeec13** [comment] 2021-03-07 01:37
@lucaderi I was hopeful the fix from #4861 would have fixed this, but when I loaded the latest docker container about a week ago it immediately exhibited the same issue when I ran network discovery. Unfortunately I'm no longer running the image because I no longer need it and don't have time to troubleshoot it, but I may try to debug this in the future again.
