### ISSUE TITLE
2.2.151202 - Professional Edition- Can't implement Traffic Policy for Hosts or IP subnets

### ISSUE THREAD

**Issue by Oyepapa** [ntop/ntopng#304] opened 2015-12-04 08:08 UTC
Hi,

I use ntopng in-line to see what's passing through the network and also enforce some traffic policies. I recently updated the software from 2.0 to 2.2.15.12.02 and I can no longer enforce traffic policies on hosts and IP subnets.

[Issue 1.docx](https://github.com/ntop/ntopng/files/51772/Issue.1.docx)

**Comment by simonemainardi** [comment] 2015-12-09 17:58
hi, there were some issues with nDPI that I think were preventing the bridge configuration page from being correctly populated.

You should be able to have it working with the latest dev release. Could you please try and update to the most recent build?

let  me know

**Comment by simonemainardi** [comment] 2015-12-13 13:44
@Oyepapa thanks for dropping me a private mail to confirm the issue is resolved in the latest build. I'm closing this.

**Closed by simonemainardi** 2015-12-13 13:44 UTC

**Comment by Oyepapa** [comment] 2015-12-14 12:27
Hi ntopng team,

 

I have noticed another issue,

 

When looking at a specific host > 

protocols. Under "Application protocol" list it says "Unable to find 

x.x.x.x (data expired ?)"

 

Kindly take a look at it.

 

Regards,

 

Oyedele Soyege

**Comment by simonemainardi** [comment] 2015-12-15 10:03
@Oyepapa if you think this is a bug, please open a separate issue with full details. I can't reproduce.
