### ISSUE TITLE
Flows stay active

### ISSUE THREAD

**Issue by johnydoo** [ntop/ntopng#1006] opened 2017-02-28 12:46 UTC
It looks like flows stay active and do not age out. Ntopng keeps collecting flows until the value of “—max-num-flows” is reached (the default value is 131.072). We tried increasing this number to 1.000.000, but it does not solve the issue, it just takes longer before the limit is reached. It takes about 18 hours to collect 1M flows.

Flow Idle Timeout is 60 seconds (also tried 0 and 1 second without any luck).

Ntopng version 2.4.170215 - Pro Small Business Edition
Built on CentOS Linux release 7.3.1611 (Core)

**Comment by johnydoo** [comment] 2017-02-28 14:33
![image](https://cloud.githubusercontent.com/assets/26087543/23409257/2f7e6b26-fdcb-11e6-856d-0d5191d2d05b.png)

**Comment by emanuele-f** [comment] 2017-03-01 11:14
Hi, I'm not able to reproduce the issue. If you go into the interface graphs and select the "Active Flows" graphs, do you see flows graph line always going up? Do you see errors in the ntopng log? Do you capture flows from a local interface?

**Comment by johnydoo** [comment] 2017-03-01 12:33
We are using nProbe to collect and convert netflows. ntopng is using interface “tcp://127.0.0.1:5556”, so both nProbe and ntopng are on the same server.

The netflow sender is a Cisco ASA firewall, but we also tried a Cisco Catalyst 4500 switch (same result). Active flow timeout on the sending device is configured to 1 minute (default is 30 minutes).

nProbe version 7.4.170215-5334

See attachment for the active flow graph. It looks like there are a few flows timed out, but it is not fast enough.

The ntopng log looks fine.
![flows](https://cloud.githubusercontent.com/assets/26087543/23460076/9135b852-fe83-11e6-9687-e35d49e6e9a2.jpg)
[ntopng.log-20170228.txt](https://github.com/ntop/ntopng/files/810680/ntopng.log-20170228.txt)

**Comment by emanuele-f** [comment] 2017-03-01 14:07
@simonemainardi can this be solved with dev fix 2a68676d93a6bd2046ecf33704f8e4f6591dc769 ?

**Comment by johnydoo** [comment] 2017-03-02 15:11
Any ideas?

**Comment by emanuele-f** [comment] 2017-03-03 11:00
If you check active flows in the gui, is "First / Last Seen" field within a reasonable range?

**Comment by simonemainardi** [comment] 2017-03-03 11:07
@emanuele-f  fix 2a68676  is not related.

@johnydoo please update ntopng and nprobe to their dev versions

**Comment by johnydoo** [comment] 2017-03-03 11:26
@emanuele-f What is reasonable? We just restarted the ntopng daemon 2 hours ago and the oldest flow is first seen since 16 days, 2 h, 17 min, 18 sec ago and last seen 16 days, 2 h, 17 min, 18 sec ago. The server and the Cisco ASA have both synchronized clocks.

@simonemainardi what version do we need? We used the ntop repo for Centos (http://packages.ntop.org/centos/ntop.repo)

**Comment by simonemainardi** [comment] 2017-03-03 11:35
@johnydoo you are using `2.4.170215` thus `http://packages.ntop.org/centos-stable/ntop.repo`

please delete the repos installed and follow the instructions at `http://packages.ntop.org/centos/` to update to dev

**Comment by johnydoo** [comment] 2017-03-03 13:57
Updating to the dev version introduced more problems than we had. Flows are coming in and are visible, but Hosts, Networks and Host Pool stay empty (No Results Found).

Ntopng is giving these errors:

`03/Mar/2017 14:24:58 [Lua.cpp:6272] WARNING: Script failure [/usr/share/ntopng/scripts/lua/network_load.lua][/usr/share/ntopng/scripts/lua/modules/http_lint.lua:861: [LINT] _GET["ifname"] = "all" parameter error: Missing validation]

03/Mar/2017 14:25:00 [Lua.cpp:5893] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/callbacks/5min.lua:10: module '5min' not found:
 no field package.preload['5min']
 no file '/usr/share/ntopng/pro/scripts/callbacks/5min.lua'
 no file '/usr/share/ntopng/scripts/lua/modules/5min.lua'
 no file './5min.lua'
 no file '/usr/local/share/luajit-2.0.3/5min.lua'
 no file '/usr/local/share/lua/5.1/5min.lua'
 no file '/usr/local/share/lua/5.1/5min/init.lua'
 no file './5min.so'
 no file '/usr/local/lib/lua/5.1/5min.so'
 no file '/usr/local/lib/lua/5.1/loadall.so']`

**Comment by simonemainardi** [comment] 2017-03-03 14:00
error shown has been fixed in "https://github.com/ntop/ntopng/commit/adf62c7f6556cf6e280e877451b6d356424f70eb" a new build is in progress, try to update in an hour

@emanuele-f check:
```
[/usr/share/ntopng/scripts/lua/modules/http_lint.lua:861: [LINT] _GET["ifname"] = "all" parameter error: Missing validation] 03/Mar/2017 14:25:00 [Lua.cpp:5893] WARNING: Script failure 
```

**Comment by emanuele-f** [comment] 2017-03-03 15:24
I think the ifname parameter error comes from a browser window running pre-update javascript code, I cannot find any other reference to it in the latest code

**Comment by simonemainardi** [comment] 2017-03-03 15:53
@johnydoo hit ctrl-shit-R to get rid of the LINT error.

**Comment by johnydoo** [comment] 2017-03-06 08:42
Updated to ntopng 2.5.170306 and nprobe 7.5.170306-5675. LINT error and 5min script failure are both solved. It looks like the ZMQ flows purge is much quicker now, so this is hopeful! Not completely sure because the active flow chart is broken:

![flows](https://cloud.githubusercontent.com/assets/26087543/23602521/45bf09c4-0251-11e7-94e4-dce439ab3e0f.jpg)

Nprobe is also complaining about the number of template fields after the update:

> 06/Mar/2017 09:02:25 [collect.c:1010] WARNING: Too many template fields (285): skept [pktId: 2245]

(sending device is Cisco ASA firewall using netflow version 9.)

**Comment by simonemainardi** [comment] 2017-03-07 22:02
@johnydoo num flows updates are performed every minute in the new dev version and this is not compatible with the old rrd file in the stable version.

If you can't afford wiping all the ntopng data dir, just remove the file num_flows.rrd so it will be re-created automatically. The file is located in the data directory, e.g., 

```
Simones-MacBook-Pro:nprobe simone$ ls -lha /var/tmp/ntopng/1/rrd/
...
num_hosts.rrd
...
```

The number of flows will then be updated.

Regarding the template field:

> Nprobe is also complaining about the number of template fields after the update:
06/Mar/2017 09:02:25 [collect.c:1010] WARNING: Too many template fields (285): skept [pktId: 2245]
(sending device is Cisco ASA firewall using netflow version 9.)


This means that nprobe has received a template with more than 128 fields (285 in this case). That is unusual I have to admit. As 128 is the maximum number of fields allowed, the template is discarded. I am not sure that raising this limit in nprobe is meaningful. Maybe you should export multiple templates each one with a subset of the information. Anyway, if you want us to have a look at the template, please open an issue under nProbe and enclose a pcap file of the netflow v9 that contains template.

**Closed as completed by simonemainardi** 2017-03-07 22:02 UTC

**Comment by johnydoo** [comment] 2017-03-08 08:14
Thanks for the support!
