### ISSUE TITLE
C++ debug error in ntopng ( windows)

### ISSUE THREAD

**Issue by srikrishna0130** [ntop/ntopng#1830] opened 2018-06-23 11:22 UTC
I have installed ntopng in windows (2010), and tried out some commands with the /c option but i am facing a c++ debug error and ntopng is exiting after that.
Can you suggest a workaround for this one?

screenshot for the above is attached.
![nropng_c](https://user-images.githubusercontent.com/26489635/41809130-b42738e4-7705-11e8-943a-4eb459b5a2d2.PNG)

**Comment by emanuele-f** [comment] 2018-06-25 08:10
Hello, if you run ntopng without options, does it start properly?

**Comment by srikrishna0130** [comment] 2018-06-25 11:13
It just prompts me to start ntopng as a service from the task manager as I have installed it as a service in Windows.

![ntopng](https://user-images.githubusercontent.com/26489635/41847178-9d470dd4-7868-11e8-8a56-d7a2de478952.png)

**Comment by emanuele-f** [comment] 2018-06-25 12:27
If you only add the `/c` option without `-i`?

**Comment by srikrishna0130** [comment] 2018-06-25 17:30
Yes I have also tried only the /c option but iam getting the same error message i.e c++ debug error

**Comment by emanuele-f** [comment] 2018-06-26 08:00
Are you using the latest version available from http://packages.ntop.org/Windows ?

**Comment by srikrishna0130** [comment] 2018-06-26 08:05
Yes, I am using the latest version available on the ntopng website. ( Ver 3.4180417)

**Comment by emanuele-f** [comment] 2018-06-26 08:09
Sorry, there is a long standing issue with windows, so this is a duplicate of #1781 . Please check it out for updates.

**Closed as completed by emanuele-f** 2018-06-26 08:09 UTC
