### ISSUE TITLE
ntopng/nprobe command line from stable to dev builds

### ISSUE THREAD

**Issue by Niko78** [ntop/ntopng#562] opened 2016-05-16 14:32 UTC
hi,

I used stable with my own command started
with nightly builds, they don't work
someone can "translate" me my lines to get them working ?
# 

ntopng -F "mysql;localhost;ntopng;flows;root;azer" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v >> /dev/null &
# /usr/local/bin/nprobe --collector-port 7002 --zmq tcp://192.168.6.35:5556 >> /dev/null &

thanks

Nico

**Comment by simonemainardi** [comment] 2016-05-16 14:54
duplicate of https://github.com/ntop/ntopng/issues/560

**Comment by simonemainardi** [comment] 2016-05-16 14:56
as already told you, you have to explain what is not working. If you just say " they don't work" no one will be able to help.

Post the configuration files used, any error, logs, everything that could give people evidence of what is not working.

**Comment by Niko78** [comment] 2016-05-16 15:00
ok for nprobe, it seems ok
but with ntopng not 
========================================================================
root@ntop-acad:~# ntopng -F "mysql;localhost;ntopng;flows;root;azer" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v
16/May/2016 16:58:43 [Ntop.cpp:1013] Setting local networks to 127.0.0.0/8
16/May/2016 16:58:43 [AddressTree.cpp:141] Rule 127.0.0.0/8
16/May/2016 16:58:43 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
16/May/2016 16:58:43 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
16/May/2016 16:58:43 [NtopPro.cpp:120] [LICENSE] Read license from Redis [378E9BF793F0ECF663D1636258705A8F149448108335D99D99]
16/May/2016 16:58:43 [NtopPro.cpp:168] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
16/May/2016 16:58:43 [NtopPro.cpp:181] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
16/May/2016 16:58:43 [NtopPro.cpp:183] WARNING: [LICENSE] before returning to community mode
16/May/2016 16:58:43 [NtopPro.cpp:184] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
16/May/2016 16:58:43 [NtopPro.cpp:185] WARNING: [LICENSE] or run ntopng in community mode starting
16/May/2016 16:58:43 [NtopPro.cpp:186] WARNING: [LICENSE] ntopng --community
16/May/2016 16:58:43 [main.cpp:130] System has 4 CPU cores
16/May/2016 16:58:43 [MySQLDB.cpp:444] Attempting to connect to MySQL for interface tcp://192.168.6.35:5556...
16/May/2016 16:58:43 [MySQLDB.cpp:484] Succesfully connected to MySQL [localhost:root] for interface tcp://192.168.6.35:5556
16/May/2016 16:58:43 [MySQLDB.cpp:535] Successfully executed 'CREATE DATABASE IF NOT EXISTS ntopng'
16/May/2016 16:58:43 [MySQLDB.cpp:535] Successfully executed 'CREATE TABLE IF NOT EXISTS `flowsv6` (`idx` int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID` smallint(5) unsigned DEFAULT NULL,`L7_PROTO` smallint(5) unsigned DEFAULT NULL,`IP_SRC_ADDR` varchar(48) DEFAULT NULL,`L4_SRC_PORT` smallint(5) unsigned DEFAULT NULL,`IP_DST_ADDR` varchar(48) DEFAULT NULL,`L4_DST_PORT` smallint(5) unsigned DEFAULT NULL,`PROTOCOL` tinyint(3) unsigned DEFAULT NULL,`BYTES` int(10) unsigned DEFAULT NULL,`PACKETS` int(10) unsigned DEFAULT NULL,`FIRST_SWITCHED` int(10) unsigned DEFAULT NULL,`LAST_SWITCHED` int(10) unsigned DEFAULT NULL,`INFO` varchar(255) DEFAULT NULL,`JSON` blob,`PROFILE` varchar(255) DEFAULT NULL,`NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,`INTERFACE` varchar(64) DEFAULT NULL,KEY `idx` (`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200)),KEY `ix_flowsv6_4_profile` (`PROFILE`),KEY `ix_flowsv6_4_ntopng_instance_name` (`NTOPNG_INSTANCE_NAME`(255)),KEY `ix_flowsv6_4_ntopng_interface` (`INTERFACE`)) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8/*!50100 PARTITION BY HASH (`FIRST_SWITCHED`)PARTITIONS 32 */'
16/May/2016 16:58:43 [MySQLDB.cpp:535] Successfully executed 'CREATE TABLE IF NOT EXISTS `flowsv4` (`idx` int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID` smallint(5) unsigned DEFAULT NULL,`L7_PROTO` smallint(5) unsigned DEFAULT NULL,`IP_SRC_ADDR` int(10) unsigned DEFAULT NULL,`L4_SRC_PORT` smallint(5) unsigned DEFAULT NULL,`IP_DST_ADDR` int(10) unsigned DEFAULT NULL,`L4_DST_PORT` smallint(5) unsigned DEFAULT NULL,`PROTOCOL` tinyint(3) unsigned DEFAULT NULL,`BYTES` int(10) unsigned DEFAULT NULL,`PACKETS` int(10) unsigned DEFAULT NULL,`FIRST_SWITCHED` int(10) unsigned DEFAULT NULL,`LAST_SWITCHED` int(10) unsigned DEFAULT NULL,`INFO` varchar(255) DEFAULT NULL,`JSON` blob,`PROFILE` varchar(255) DEFAULT NULL,`NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,`INTERFACE` varchar(64) DEFAULT NULL,KEY `idx` (`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200)),KEY `ix_flowsv4_4_profile` (`PROFILE`),KEY `ix_flowsv4_4_ntopng_instance_name` (`NTOPNG_INSTANCE_NAME`(255)),KEY `ix_flowsv4_4_ntopng_interface` (`INTERFACE`)) ENGINE=InnoDB AUTO_INCREMENT=520 DEFAULT CHARSET=utf8/*!50100 PARTITION BY HASH (`FIRST_SWITCHED`)PARTITIONS 32 */'
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv4_4` ADD `INFO` varchar(255)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv6_4` ADD `INFO` varchar(255)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv4_4` ADD `PROFILE` varchar(255) DEFAULT NULL,ADD INDEX `ix_flowsv4_4_profile` (PROFILE)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv6_4` ADD `PROFILE` varchar(255) DEFAULT NULL,ADD INDEX `ix_flowsv6_4_profile` (PROFILE)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv4_4` ADD `NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,ADD INDEX `ix_flowsv4_4_ntopng_instance_name` (NTOPNG_INSTANCE_NAME)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv6_4` ADD `NTOPNG_INSTANCE_NAME` varchar(256) DEFAULT NULL,ADD INDEX `ix_flowsv6_4_ntopng_instance_name` (NTOPNG_INSTANCE_NAME)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv4_4` ADD `INTERFACE` varchar(64) DEFAULT NULL,ADD INDEX `ix_flowsv4_4_ntopng_interface` (INTERFACE)
16/May/2016 16:58:43 [MySQLDB.cpp:529] ALTER TABLE `flowsv6_4` ADD `INTERFACE` varchar(64) DEFAULT NULL,ADD INDEX `ix_flowsv6_4_ntopng_interface` (INTERFACE)
============================================================

**Comment by Niko78** [comment] 2016-05-16 15:11
ok so I succeeded to start nprobe but not ntopng

`root@ntop-acad:~# ntopng -F "mysql;localhost;ntopng;flows;root;azer" -i tcp://192.168.6.35:5556 -d /storage/tmp -w 3000 -v
16/May/2016 17:08:18 [Ntop.cpp:1013] Setting local networks to 127.0.0.0/8
16/May/2016 17:08:18 [AddressTree.cpp:141] Rule 127.0.0.0/8
16/May/2016 17:08:18 [Redis.cpp:92] Successfully connected to redis 127.0.0.1:6379@0
16/May/2016 17:08:18 [NtopPro.cpp:122] [LICENSE] Reading license from /etc/ntopng.license
16/May/2016 17:08:18 [NtopPro.cpp:120] [LICENSE] Read license from Redis [378E9BF793F0ECF663D1636258705A8F149448108335D99D99]
16/May/2016 17:08:18 [NtopPro.cpp:168] ERROR: [LICENSE] Invalid or missing ntopng License [License mismatch error]
16/May/2016 17:08:18 [NtopPro.cpp:181] WARNING: [LICENSE] ntopng will now run in pro mode for 10 minutes
16/May/2016 17:08:18 [NtopPro.cpp:183] WARNING: [LICENSE] before returning to community mode
16/May/2016 17:08:18 [NtopPro.cpp:184] WARNING: [LICENSE] You can buy a permanent license at http://shop.ntop.org
16/May/2016 17:08:18 [NtopPro.cpp:185] WARNING: [LICENSE] or run ntopng in community mode starting
16/May/2016 17:08:18 [NtopPro.cpp:186] WARNING: [LICENSE] ntopng --community
16/May/2016 17:08:18 [main.cpp:130] System has 4 CPU cores
16/May/2016 17:08:18 [MySQLDB.cpp:444] Attempting to connect to MySQL for interface tcp://192.168.6.35:5556...
16/May/2016 17:08:18 [MySQLDB.cpp:484] Succesfully connected to MySQL [localhost:root] for interface tcp://192.168.6.35:5556
16/May/2016 17:08:18 [MySQLDB.cpp:535] Successfully executed 'CREATE DATABASE IF NOT EXISTS ntopng'
16/May/2016 17:08:18 [MySQLDB.cpp:535] Successfully executed 'CREATE TABLE IF NOT EXISTS`flowsv6`(`idx`int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID`smallint(5) unsigned DEFAULT NULL,`L7_PROTO`smallint(5) unsigned DEFAULT NULL,`IP_SRC_ADDR`varchar(48) DEFAULT NULL,`L4_SRC_PORT`smallint(5) unsigned DEFAULT NULL,`IP_DST_ADDR`varchar(48) DEFAULT NULL,`L4_DST_PORT`smallint(5) unsigned DEFAULT NULL,`PROTOCOL`tinyint(3) unsigned DEFAULT NULL,`BYTES`int(10) unsigned DEFAULT NULL,`PACKETS`int(10) unsigned DEFAULT NULL,`FIRST_SWITCHED`int(10) unsigned DEFAULT NULL,`LAST_SWITCHED`int(10) unsigned DEFAULT NULL,`INFO`varchar(255) DEFAULT NULL,`JSON`blob,`PROFILE`varchar(255) DEFAULT NULL,`NTOPNG_INSTANCE_NAME`varchar(256) DEFAULT NULL,`INTERFACE`varchar(64) DEFAULT NULL,KEY`idx`(`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200)),KEY`ix_flowsv6_4_profile`(`PROFILE`),KEY`ix_flowsv6_4_ntopng_instance_name`(`NTOPNG_INSTANCE_NAME`(255)),KEY`ix_flowsv6_4_ntopng_interface`(`INTERFACE`)) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8/*!50100 PARTITION BY HASH (`FIRST_SWITCHED`)PARTITIONS 32 */'
16/May/2016 17:09:22 [MySQLDB.cpp:535] Successfully executed 'CREATE TABLE IF NOT EXISTS`flowsv4`(`idx`int(11) NOT NULL AUTO_INCREMENT,`VLAN_ID`smallint(5) unsigned DEFAULT NULL,`L7_PROTO`smallint(5) unsigned DEFAULT NULL,`IP_SRC_ADDR`int(10) unsigned DEFAULT NULL,`L4_SRC_PORT`smallint(5) unsigned DEFAULT NULL,`IP_DST_ADDR`int(10) unsigned DEFAULT NULL,`L4_DST_PORT`smallint(5) unsigned DEFAULT NULL,`PROTOCOL`tinyint(3) unsigned DEFAULT NULL,`BYTES`int(10) unsigned DEFAULT NULL,`PACKETS`int(10) unsigned DEFAULT NULL,`FIRST_SWITCHED`int(10) unsigned DEFAULT NULL,`LAST_SWITCHED`int(10) unsigned DEFAULT NULL,`INFO`varchar(255) DEFAULT NULL,`JSON`blob,`PROFILE`varchar(255) DEFAULT NULL,`NTOPNG_INSTANCE_NAME`varchar(256) DEFAULT NULL,`INTERFACE`varchar(64) DEFAULT NULL,KEY`idx`(`idx`,`IP_SRC_ADDR`,`IP_DST_ADDR`,`FIRST_SWITCHED`,`LAST_SWITCHED`,`INFO`(200)),KEY`ix_flowsv4_4_profile`(`PROFILE`),KEY`ix_flowsv4_4_ntopng_instance_name`(`NTOPNG_INSTANCE_NAME`(255)),KEY`ix_flowsv4_4_ntopng_interface`(`INTERFACE`)) ENGINE=InnoDB AUTO_INCREMENT=520 DEFAULT CHARSET=utf8/*!50100 PARTITION BY HASH (`FIRST_SWITCHED`)PARTITIONS 32 */'
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv4_4`ADD`INFO`varchar(255)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv6_4`ADD`INFO`varchar(255)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv4_4`ADD`PROFILE`varchar(255) DEFAULT NULL,ADD INDEX`ix_flowsv4_4_profile`(PROFILE)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv6_4`ADD`PROFILE`varchar(255) DEFAULT NULL,ADD INDEX`ix_flowsv6_4_profile`(PROFILE)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv4_4`ADD`NTOPNG_INSTANCE_NAME`varchar(256) DEFAULT NULL,ADD INDEX`ix_flowsv4_4_ntopng_instance_name`(NTOPNG_INSTANCE_NAME)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv6_4`ADD`NTOPNG_INSTANCE_NAME`varchar(256) DEFAULT NULL,ADD INDEX`ix_flowsv6_4_ntopng_instance_name`(NTOPNG_INSTANCE_NAME)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv4_4`ADD`INTERFACE`varchar(64) DEFAULT NULL,ADD INDEX`ix_flowsv4_4_ntopng_interface`(INTERFACE)
16/May/2016 17:09:22 [MySQLDB.cpp:529] ALTER TABLE`flowsv6_4`ADD`INTERFACE`varchar(64) DEFAULT NULL,ADD INDEX`ix_flowsv6_4_ntopng_interface`(INTERFACE)`

that stays like that and nothing more, no access in http on port 3000
I think it misses something

**Comment by simonemainardi** [comment] 2016-05-16 15:19
try without option "-F" and report. It that was the problem -- and you don't have any important data inside MySQL -- you can drop the database `ntopng` before adding the -F back.

You upgraded to the dev version and then went back to the stable. MySQL database structure is not backward-compatible.

**Comment by Niko78** [comment] 2016-05-16 15:23
ah it seems to work well now
so now I'm with the dev and all seems ok
thanks for your help Simone.

**Comment by simonemainardi** [comment] 2016-05-16 15:25
@Niko78 you should at least explain what you did or what you were doing wrong. This will help other users like you in the future.

**Comment by Niko78** [comment] 2016-05-16 15:26
well for that I just removed the "-F" like you asked me

**Closed as completed** 2016-05-16 15:31 UTC
Labels: Duplicate
