### ISSUE TITLE
Networks not discovered and added to list

### ISSUE THREAD

**Issue by eliassal** [ntop/ntopng#4808] opened 2020-12-06 09:55 UTC
Hi, ntopng (installed on a win 10 machine on subnet 192.168.1.0/24). Network is managed by a router where I have this 1st network and 2nd vlan2 on 192.168.2.0/24 and it works fine and I can access machines on this 2nd vlan, however, ntopng does not list this 2nd vlan in the networks list, it only lists the 1st one and the IPV6 one of the rounter.
How can I add this vlan2?
Thanks

**Comment by simonemainardi** [comment] 2020-12-06 12:53
Duplicate of you very same issue https://github.com/ntop/ntopng/issues/4807

This is not how you are supposed to use github.

**Closed as completed by simonemainardi** 2020-12-06 12:53 UTC
