### ISSUE TITLE
ntopng pack update is broken

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4555] opened 2020-10-09 10:41 UTC
This is a regression of a long-standing issue

![Screen_Shot_2020-10-09_at_12_11_34](https://user-images.githubusercontent.com/4493366/95573915-76a07c80-0a2c-11eb-8ec1-5f30d7d74af6.png)

Apparently there are no new packages to install, but the package can be updated from the terminal

root@ntopng:/home/deri# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 https://packages.ntop.org/apt/18.04 x64/ InRelease
Hit:3 https://packages.ntop.org/apt/18.04 all/ InRelease
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1681 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1672 kB]
Fetched 3604 kB in 2s (1868 kB/s)
Reading package lists... Done
root@ntopng:/home/deri# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  nprobe ntopng ntopng-data pfring pfring-dkms
5 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 15.2 MB of archives.
After this operation, 7168 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://packages.ntop.org/apt/18.04 x64/ ntopng 4.1.201009-11718 [7849 kB]
Get:2 https://packages.ntop.org/apt/18.04 all/ pfring-dkms 7.7.0 [66.8 kB]
Get:3 https://packages.ntop.org/apt/18.04 x64/ nprobe 9.1.201009-6961 [1601 kB]
Get:4 https://packages.ntop.org/apt/18.04 x64/ pfring 7.7.0-3211 [1752 kB]
Get:5 https://packages.ntop.org/apt/18.04 all/ ntopng-data 4.1.201009 [3960 kB]

**Comment by cardigliano** [comment] 2020-10-09 15:41
I am not able to reproduce this, please mouse over on the triangle when this happens as the actual failure reason should be reported in a tooltip.

**Comment by cardigliano** [comment] 2020-10-12 07:01
Duplicate of https://github.com/ntop/ntopng/issues/4564

**Closed as completed by cardigliano** 2020-10-12 07:01 UTC
