### ISSUE TITLE
Problem with increase flows

### ISSUE THREAD

**Issue by josemanuelmeza** [ntop/ntopng#1840] opened 2018-06-29 16:06 UTC
I ran the command "C:\Program Files\ntopng>ntopng /c -X 1310720" to increase the flows, but It appears an error:

C:\Program Files\ntopng>ntopng /c -X 531072
Starting ntopng
Running ntopng.
28/Jun/2018 16:24:39 [Ntop.cpp:1499] Setting local networks to 127.0.0.0/8
28/Jun/2018 16:24:39 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0
28/Jun/2018 16:24:39 [Redis.cpp:132] Successfully connected to redis 127.0.0.1@0
28/Jun/2018 16:24:39 [NtopPro.cpp:260] [LICENSE] Reading license from Redis
28/Jun/2018 16:24:39 [NtopPro.cpp:172] [LICENSE] 002C5E520E92FF78B776487881040F7D153669244660C89392: unable to validate Enterprise license [License mismatch error]
28/Jun/2018 16:24:39 [NtopPro.cpp:175] [LICENSE] 002C5E520E92FF78B776487881040F7D153669244660C89392: found valid Professional license
28/Jun/2018 16:24:40 [PcapInterface.cpp:91] Reading packets from interface {2A22600F-A38F-4B12-A06D-C8F67FA4268E}...
28/Jun/2018 16:24:40 [Ntop.cpp:1626] Registered interface {2A22600F-A38F-4B12-A06D-C8F67FA4268E} [id: 6]
28/Jun/2018 16:24:41 [PcapInterface.cpp:91] Reading packets from interface {29E62EE2-D9C8-4388-9EE8-013DDC7C78CB}...
28/Jun/2018 16:24:41 [Ntop.cpp:1626] Registered interface {29E62EE2-D9C8-4388-9EE8-013DDC7C78CB} [id: 7]
28/Jun/2018 16:24:43 [HTTPserver.cpp:858] HTTPS Disabled: missing SSL certificate C:\Program Files\ntopng\httpdocs/ssl/ntopng-cert.pem
28/Jun/2018 16:24:43 [HTTPserver.cpp:860] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
28/Jun/2018 16:24:43 [HTTPserver.cpp:931] Web server dirs [C:\Program Files\ntopng\httpdocs][C:\Program Files\ntopng\scripts]
28/Jun/2018 16:24:43 [HTTPserver.cpp:934] HTTP server listening on port(s) 3000
28/Jun/2018 16:24:43 [main.cpp:386] Working directory: C:\Users\Administrator\Documents\ntopng
28/Jun/2018 16:24:43 [main.cpp:388] Scripts/HTML pages directory: C:\Program Files\ntopng
28/Jun/2018 16:24:43 [Ntop.cpp:391] Welcome to ntopng x64 v.3.4.180417 - (C) 1998-18 ntop.org
28/Jun/2018 16:24:43 [Ntop.cpp:401] Built on Windows
28/Jun/2018 16:24:43 [NtopPro.cpp:508] [LICENSE] System Id:     184507384-00600f2d
28/Jun/2018 16:24:43 [NtopPro.cpp:509] [LICENSE] Edition:       Professional
28/Jun/2018 16:24:43 [NtopPro.cpp:510] [LICENSE] License Type:  Permanent License
28/Jun/2018 16:24:43 [NtopPro.cpp:513] [LICENSE] License:       002C5E520E92FF78B776487881040F7D153669244660C89392
28/Jun/2018 16:24:43 [NtopPro.cpp:523] [LICENSE] Maintenance:   Until Tue Sep 11 14:00:46 2018 [74 days left]
28/Jun/2018 16:24:43 [Ntop.cpp:624] Adding 177.234.20.56/30 as IPv4 local network for
28/Jun/2018 16:24:43 [Ntop.cpp:630] Adding 177.234.20.58/32 as IPv4 interface address for {29E62EE2-D9C8-4388-9EE8-013DDC7C78CB}
28/Jun/2018 16:24:44 [PeriodicActivities.cpp:59] Started periodic activities loop...
 
C:\Program Files\ntopng>

![captura de pantalla 2018-06-28 a la s 16 21 41](https://user-images.githubusercontent.com/28447339/42102746-7925d904-7b8c-11e8-83a4-aa327c849a24.png)

**Comment by emanuele-f** [comment] 2018-06-29 18:17
Duplicate of #1781

**Closed as completed by emanuele-f** 2018-06-29 18:17 UTC
