### ISSUE TITLE
[Feature request] Serialization / deserialization of Countries & AS Statistics

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ntop/ntopng#2606] opened 2019-05-23 08:46 UTC
Ubuntu eoan 19.10
ndpi: 2.9.0-1539-53119e7
ntopng: 3.9.190523 - Community Edition

**Runtime preferences**:
![Ntopng Timeseries Settings](https://user-images.githubusercontent.com/13176858/58238392-732d2800-7d47-11e9-8f68-74aa5d639f3d.png)

**AS stats excerpt right before ntopng upgrade**:
![Ntopng AS stats](https://user-images.githubusercontent.com/13176858/58238512-b5ef0000-7d47-11e9-836d-58b926bb759c.png)

**All AS stats right after ntopng upgrade**:
![Ntopng AS stats right after upgrade](https://user-images.githubusercontent.com/13176858/58238561-ce5f1a80-7d47-11e9-9038-04900c3d1ac5.png)

Same issue with countries stats.

Is this expected? If so, is there a way to avoid this situation?

**Comment by simonemainardi** [comment] 2019-05-23 09:03
need to implement serialization / deserialization of AS stats

**Comment by emanuele-f** [comment] 2019-05-27 11:09
Countries serialization implemented in 8fcce457c99c45694288c4c5790037d33e84216c .

**Comment by jean-christophe-manciot** [comment] 2019-05-28 06:52
Nothing has changed regarding the fact that the countries & AS stats are reset at each package upgrade.

**Comment by emanuele-f** [comment] 2019-05-28 08:00
Please try with an upgrade from the current fixed version to the next one (e.g. the tomorrow version)

**Comment by jean-christophe-manciot** [comment] 2019-05-28 17:22
I tried with 9252ead, which is 2 commits downstream from 8fcce45.

**Comment by emanuele-f** [comment] 2019-05-28 17:41
If you manually restart the ntopng service with `sudo systemctl restart ntopng`, are counters properly restored?

**Comment by jean-christophe-manciot** [comment] 2019-05-28 17:46
It has the same effect as an upgrade: all countries & AS counters are lost (reset).

**Comment by emanuele-f** [comment] 2019-05-29 07:48
An empty list of countries and AS is normal during startup, this happens with all the dynamic elements in ntopng (hosts, networks, as, ...). However, when the country appears again (some traffic to/from it is seen by ntopng) its counters will start from the last serialized value

**Comment by jean-christophe-manciot** [comment] 2019-05-29 08:14
As I said multiple times, it's not what happens:
**Some countries stats before restart**:
![Some Countries before restart](https://user-images.githubusercontent.com/13176858/58540776-55a20780-81fa-11e9-806a-08f4ce97400e.png)
**Countries stats after restart**
![Countries after restart](https://user-images.githubusercontent.com/13176858/58540841-766a5d00-81fa-11e9-88ac-b857a7cd40a1.png)

**Comment by emanuele-f** [comment] 2019-05-29 08:43
Is the traffic column restored correctly?

Edit: "seen since" restore fixed in b5ce655cdeaf1dcb80c0a01707c2fd2b01b58f2d .

**Comment by jean-christophe-manciot** [comment] 2019-05-30 06:57
with 3.0-3581-g66e26030 (a few commits ahead from b5ce655):
- same issue with countries & AS stats: 'hosts' and 'seen since'  are reset after restart
- the traffic stats are fine, except for another issue unrelated to the current one

**Comment by emanuele-f** [comment] 2019-05-30 08:33
"3.0-3581-g66e26030" is not a release version by us. The issue on the "seen since" has already been solved in https://github.com/ntop/ntopng/commit/b5ce655cdeaf1dcb80c0a01707c2fd2b01b58f2d . It can be verified by just running ntopng from cli, making a clean shutdown, and starting it again. The "hosts" column is dynamic so it depends on the currently active hosts and cannot be saved/restored. You may also want to look at the `--sticky-hosts` options.

**Comment by jean-christophe-manciot** [comment] 2019-05-30 10:13
> "3.0-3581-g66e26030" is not a release version by us

Of course it is; you are just unaware of that feature::
```
# git config --get remote.origin.url
https://github.com/ntop/ntopng
# git describe --tags
3.0-3581-g66e26030
# git log -1
commit 66e260300e75e0aaf66ed4b63a658053b4459025 (HEAD, origin/dev, origin/HEAD, dev)
Author: emanuele-f <faranda@ntop.org>
Date:   Wed May 29 16:23:42 2019 +0200

    Remove uthash from MacManufacturers
```
Again, the issue on the "seen since" has NOT already been solved. Saying otherwise won't solve it.

> The "hosts" column is dynamic so it depends on the currently active hosts and cannot be saved/restored. You may also want to look at the --sticky-hosts options.

The ```--sticky-hosts``` has nothing to do with the facts that the hosts stats are reset at each restart.
For some reason, you are reluctant to accept the fact that all countries & AS stats are reset at each ```system restart ntopng``` and upgrade as graphically shown in my previous posts, although they should not (when ```Runtime Preferences-->Timeseries-->AS and Countries``` are set to ON).

**Comment by jean-christophe-manciot** [comment] 2019-06-02 08:31
I can see that the "seen since" column is not reset after a restart, but the "hosts" column is alongside the number of rows, so it seems clear that the setting ```Runtime Preferences-->Timeseries-->AS and Countries``` is useless in that regard.

**Comment by emanuele-f** [comment] 2019-06-04 12:57
Your impatient answers will not help us understand the problem. Since this is opensource, you can look at the code and modify it as you want. If you want support please be kind.

`Runtime Preferences-->Timeseries-->AS and Countries` does not affect the realtime data but only the historical data (https://www.ntop.org/guides/ntopng/web_gui/historical.html). This cannot be reproduced with the official ntopng nightly package from http://packages.ntop.org .

Before restart:
![2019-06-04_14-48](https://user-images.githubusercontent.com/5488003/58880521-9650c380-86c7-11e9-939a-cfffc191f3df.png)

After restart:
![2019-06-04_14-48_1](https://user-images.githubusercontent.com/5488003/58880531-9f419500-86c7-11e9-9bd6-505c58cb31c7.png)

The seen since column is properly restored here. If you have a way to reproduce this with the community (the non packaged version from github, otherwise use the http://packages.ntop.org) then tell us how to reproduce and we'll try to help.

**Closed as completed** 2019-06-04 13:52 UTC
