### ISSUE TITLE
Invalid SNMP Filter

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7523] opened 2023-06-06 16:59 UTC
<img width="1077" alt="image" src="https://github.com/ntop/ntopng/assets/4493366/391e026c-0be8-4453-8c89-61d64a58b451">

Clicking on the interface Id a dialog is open but
- the SNMP interface is wrong
- the Apply button does not work (window stays open)
- 
<img width="890" alt="Screenshot 2023-06-06 at 18 58 51" src="https://github.com/ntop/ntopng/assets/4493366/f408aee0-40bd-4106-8a52-1fe069d51089">

**Comment by cardigliano** [comment] 2023-06-20 14:35
Duplicate of #7528

**Closed as completed by cardigliano** 2023-06-20 14:35 UTC
