### ISSUE TITLE
DNS issue in resolving some domain names

### ISSUE THREAD

**Issue by LionHear7** [ntop/ntopng#385] opened 2016-02-09 09:25 UTC
Hi,
I have ntopng v.2.3.160113 [Professional Edition]
Built on:  Ubuntu 14.04.3 LTS
and a bridge connection over 2 interfaces using pfring.

I use the bridge for the 7-Layer policies features.

There's a strange behaviour in resolving some third-level domains. (google related)
Here you are the differences between two requests.

time dig google.com
real    0m0.082s
user    0m0.016s
sys 0m0.000s

time dig mail.google.com
real    0m5.081s
user    0m0.004s
sys 0m0.008s

As you can see it takes 5secs to resolve mail.google.com
There's something I'm missing?

**Comment by lucaderi** [comment] 2016-02-09 09:46
Can you please capture two pcaps, one before and one after ntopng where you capture the DNS traffic, and share them with us?

**Comment by LionHear7** [comment] 2016-02-09 16:00
There's no differences in the output. (or I produced the wrong output :P ) 

without ntopng bridge:
listening on enp2s0, link-type EN10MB (Ethernet), capture size 262144 bytes
13:16:27.927706 IP 172.16.0.119.47827 > 8.8.8.8.53: 48866+ [1au] A? mail.google.com. (44)
13:16:35.459217 IP 172.16.0.119.40760 > 8.8.8.8.53: 6071+ [1au] A? google.com. (39)

with ntopng bridge:
listening on enp2s0, link-type EN10MB (Ethernet), capture size 262144 bytes
13:19:25.344529 IP 172.16.0.119.60559 > 8.8.8.8.53: 61627+ [1au] A? mail.google.com. (44)
13:19:34.065671 IP 172.16.0.119.45177 > 8.8.8.8.53: 54255+ [1au] A? google.com. (39)

I forgot to write that ntopng is running inside a docker container.
However I expected the latency for every domain or not at all.
I'm going to try it directly from the host. Can I move the ntopng license?

**Comment by lucaderi** [comment] 2016-02-09 16:01
I need a pcap (.pcap file) with request and response.

**Comment by whoknowz** [comment] 2016-02-20 13:18
Probably the same as #371 I have the same issue

**Comment by lucaderi** [comment] 2016-02-20 13:20
@whoknowz Can you please capture a pcap to assist with the debugging?

**Comment by whoknowz** [comment] 2016-02-20 13:48
I will try to get a pcap...but since it is happenning on production machines at two clients I had to revert to 2.2. Strangely this is not happenning at my office setup. I have checked several times and the whole topology is similar since I always push updates to clients once I have it working fine locally. The DNS server resides on the local LAN so it probably is having problems getting records from forwarded servers..all three setups running Windows Server 2012 DNS. Do you want a pcap from DNS server or requesting client? Cause i dont see a problem from client side, except the server response saying server not found.

**Comment by mydzen** [comment] 2016-03-03 12:08
Hello!
Also have a problem with dns.
I have ntopng   2.3.160303 - Professional Edition, on Ubuntu. It works in bridge mode.
When ntopng turn on in bridge mode, I have problems with resolving dns names. When I use network without ntopng - it wirks correctly. Screenshot of nslookup in attachement.
Tell me, please, what's happen?

![ntop_fb](https://cloud.githubusercontent.com/assets/15261519/13493792/67d6401c-e151-11e5-8ed6-3d0f4689800a.png)

**Comment by lucaderi** [comment] 2016-03-05 15:19
I need to check what is the traffic your network -> ntopng and ntopng->internet (I need two different pcaps) to understand what is going on. Furthermore I need to see what traffic policy rules you have setup.

**Comment by mydzen** [comment] 2016-03-09 09:42
Hello. pcap files in attachment 

[pcap.zip](https://github.com/ntop/ntopng/files/164856/pcap.zip)

**Comment by mydzen** [comment] 2016-03-14 07:42
Hello! Any ideas about problem?

**Comment by mydzen** [comment] 2016-03-16 08:51
good afternoon
tell me how long it takes for the test? we can not use the purchased product due to this problem.

**Comment by lucaderi** [comment] 2016-03-16 09:01
@mydzen @simonemainardi  Simone is looking at it

**Comment by simonemainardi** [comment] 2016-03-16 20:07
confirmed. I don't even get a DNS reply when trying to resolve `mail.google.com`. It timeouts after 18sec

```
Simones-MacBook-Pro:logs simone$ time dig mail.google.com

; <<>> DiG 9.8.3-P1 <<>> mail.google.com
;; global options: +cmd
;; connection timed out; no servers could be reached

real    0m18.049s
user    0m0.004s
sys 0m0.013s
```

DNS works properly with other domains, i.e., `repubblica.it`

![image](https://cloud.githubusercontent.com/assets/3397663/13827048/e4318c34-ebba-11e5-8a15-62f19ae1c26c.png)

pcap: [dns-pcap.pcapng.zip](https://github.com/ntop/ntopng/files/176803/dns-pcap.pcapng.zip)

**Comment by whoknowz** [comment] 2016-03-16 20:13
This is not Google specific when I tested. Also even more stranger was the fact that directly specifying a global DNS server like 8.8.8.8 or ISP DNS on the client machine resolves the issue, but when configured with a secondary DNS server forwarding queries never works when bridge is up.

**Comment by lucaderi** [comment] 2016-03-16 20:19
@whoknowz @simonemainardi This is correct. When you resolve google addresses, you must enable also the Google protocol, not just DNS. Same for Facebook....

**Comment by simonemainardi** [comment] 2016-03-16 20:35
I have no blacklisted protocols in the ntopng policier.

note this configuration: 

```
 host = en4 <----> eth4 = bridge = eth5 <---> switch <---> router <---> internet
```

This is what I get if I simultaneously capture en4 and eth4

```
Simones-MacBook-Pro:Downloads simone$ sudo  tshark -ien4  -Y "dns.qry.name==mail.google.com"

943  20.982222 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb A mail.google.com
962  21.985280 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb A mail.google.com
1195  26.986661 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb A mail.google.com
1227  27.988624 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb A mail.google.com
1454  32.990743 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb A mail.google.com
1474  33.991378 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb A mail.google.com

root@devel:/home/deri# tshark -ieth4  -Y "dns.qry.name==mail.google.com"

179   4.528553 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb  A mail.google.com
1 184   5.531610 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb  A mail.google.com
2 349  10.533044 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb  A mail.google.com
3 369  11.535030 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb  A mail.google.com
4 528  16.537251 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xa6eb  A mail.google.com
5 536  17.537888 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xa6eb  A mail.google.com
```

This is what I get if I simultaneously capture en4 and eth5

```
Simones-MacBook-Pro:Downloads simone$ sudo  tshark -ien4  -Y "dns.qry.name==mail.google.com"
2798  65.693763 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xd0e9 A mail.google.com
2858  66.694316 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xd0e9 A mail.google.com
3061  71.697260 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xd0e9 A mail.google.com
3115  72.700195 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xd0e9 A mail.google.com
3302  77.701044 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xd0e9 A mail.google.com
3350  78.701142 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xd0e9 A mail.google.com


root@devel:/home/deri# tshark -ieth5  -Y "dns.qry.name==mail.google.com"
114   4.492141 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xe9d0  A mail.google.com[Malformed Packet]
1 160   5.492659 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xe9d0  A mail.google.com[Malformed Packet]
2 295  10.495723 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xd0e9  A mail.google.com
3 335  11.498661 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xd0e9  A mail.google.com
4 456  16.499525 192.168.2.130 -> 131.114.18.19 DNS 75 Standard query 0xd0e9  A mail.google.com
5 490  17.499620 192.168.2.130 -> 8.8.8.8      DNS 75 Standard query 0xd0e9  A mail.google.com
```

Look at the first two DNS going through eth5: they are malformed. I am not sure this is expected.

**Comment by lucaderi** [comment] 2016-03-16 20:48
@simonemainardi How did you start ntopng?

**Comment by simonemainardi** [comment] 2016-03-16 21:54
```
deri@devel 202> less /etc/ntopng/ntopng.conf
-w=3000
-W=0
-g=-1
-m="192.168.2.0/24"
-d=/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=bridge:eth4,eth5
```

**Comment by lucaderi** [comment] 2016-03-17 07:31
Fixed by https://github.com/ntop/nDPI/commit/27d09c33ce881e3104637764f63f4e87018a4866

**Closed as completed by lucaderi** 2016-03-17 07:31 UTC
Labels: To Be Confirmed

**Comment by simonemainardi** [comment] 2016-03-17 13:16
awesome, everything is now working properly, thanks @lucaderi !
