### ISSUE TITLE
Implement automatic alert testing

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#4983] opened 2021-01-29 09:30 UTC
It is requested to create an automated testing system that is used to generate alla alerts, report errors (e.g. script not working), and discrepancies with respect to the previous run.
An idea is to 
- enable all script alerts
- pass ntopng one (or more) pcaps with issues that trigger alerts
- save the expected results at the first run
- in the following runs check that the results are the same as the expected results and that no script error/warnings are produced

**Comment by cardigliano** [comment] 2021-02-03 15:06
Duplicate of #4989

**Closed as completed by cardigliano** 2021-02-03 15:06 UTC
Labels: Feature Request, Priority Ticket
