### ISSUE TITLE
Top Application Traffic Last Day View Not displaying Data

### ISSUE THREAD

**Issue by Artapel** [ntop/ntopng#1319] opened 2017-06-19 07:58 UTC
Hi Guys. I updated to V3 But now i cant see any data in the "Top Application Traffic Last Day View" section.

**My current setup is as follows**

> Linux monitor 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

 **yum list installed | grep ntop**

> cento.x86_64                           1.3.170619-205                  @ntop
> e1000e-zc.noarch                       3.2.7.1.1277-dkms               @ntop-noarch
> i40e-zc.noarch                         1.5.18.1277-1dkms               @ntop-noarch
> igb-zc.noarch                          5.3.3.5.1277-dkms               @ntop-noarch
> ixgbe-zc.noarch                        4.1.5.1277-dkms                 @ntop-noarch
> n2disk.x86_64                          2.9.170619-4819                 @ntop
> nprobe.x86_64                          8.1.170619-5790                 @ntop
> ntopng.x86_64                          3.1.170619-2939                 @ntop
> ntopng-data.noarch                     3.1.170619-2939                 @ntop-noarch
> pfring.x86_64                          6.7.0-1277                      @ntop
> pfring-dkms.noarch                     6.7.0-1277                      @ntop-noarch
> pfring-drivers-zc-dkms.noarch          1.2-0                           @ntop-noarch

**I found this error in the Ntopng.log**

> 19/Jun/2017 09:50:22 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/6/rrd/192/168/1/230@2/SOME/IP.rrd': No such file or directory]
> 19/Jun/2017 09:55:39 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/6/rrd/192/168/1/230@2/SOME/IP.rrd': No such file or directory]

**I tried fo follow the path but the "graph_utils.lua:9899" does not exist**
```
 cd /usr/share/ntopng/scripts/lua/modules/
grafana/     i18n/        resty/       top_scripts/
```
Any Ideas?

**Comment by emanuele-f** [comment] 2017-06-19 08:35
Hi, please delete `/var/tmp/ntopng/6/rrd/192/168/1/230@2/SOME/IP.rrd` from command line and see if you get any other error

**Comment by Artapel** [comment] 2017-06-19 08:37
Fixed

Thank you very much!

Regards
[Corne Kruger]

**Comment by emanuele-f** [comment] 2017-06-19 08:51
You are welcome. I'm closing the issue

**Comment by Artapel** [comment] 2017-06-20 08:48
It seems that the problem WAS fixed but are occurring again. I can see this is true for a 3 my interfaces.

Here is the error i noticed while running a tail -f /var/log/ntopng/ntopng.conf

20/Jun/2017 10:45:01 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:1009: creating '/var/tmp/ntopng/7/rrd/SOME/IP.rrd': No such file or directory]

Deleting the file does make the board collect data again, but it does not last very long before it stops and give the above error again.

**Comment by emanuele-f** [comment] 2017-06-20 08:51
The file which causes the issue is always different or is it always the same?

**Comment by Artapel** [comment] 2017-06-20 12:59
I kept the Tail -g /var/log/ntopng/ntopng.log running for a whiule and it seems to be the same file

> /var/log/ntopng/ntopng.log
> 20/Jun/2017 14:10:02 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:15:04 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:20:02 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:25:03 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:30:03 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:35:02 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:40:01 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:45:08 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:50:03 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
> 20/Jun/2017 14:55:07 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/7/rrd/192/168/62/76/SOME/IP.rrd': No such file or directory]
>

**Comment by Artapel** [comment] 2017-06-20 13:00
Take not of the exact times of all those log entries

**Comment by dpavlin** [comment] 2017-06-27 09:02
We are having same problem here:

var/log/ntopng/ntopng.log.1:26/Jun/2017 06:25:14 [Lua.cpp:6112] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/5min.lua][/usr/share/ntopng/scripts/lua/modules/graph_utils.lua:989: creating '/var/tmp/ntopng/3/rrd/193/198/212/251/SOME/IP.rrd': No such file or directory]`

It happens for multiple IPs:

dpavlin@ntop:~$ grep SOME /var/log/ntopng/ntopng.log.* | cut -d\' -f2 | sort -u
/var/tmp/ntopng/3/rrd/10/5/9/64/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/212/187/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/212/234/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/212/251/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/212/32/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/214/158/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/214/227/SOME/IP.rrd
/var/tmp/ntopng/3/rrd/193/198/215/34/SOME/IP.rrd

I tried erasing those rrd directories but it didn't help. Any hints?

**Comment by simonemainardi** [comment] 2017-06-27 10:13
Thanks for reporting, issue was a collateral effect of nDPI commit https://github.com/ntop/nDPI/commit/348159dc3aff479ca80928f97fdd3de94356591a

It should be solved now. New builds will be available starting from tomorrow.

Before trying again please make sure to remove all the rrds containing ..SOME...

**Comment by simonemainardi** [comment] 2017-07-03 12:34
@Artapel @dpavlin commit should have fixed the issue. Can you confirm you no longer see the SOME/IP.rdd error?

**Comment by dpavlin** [comment] 2017-07-03 12:42
I don't see SOME/IP.rrd errors any more. Thanks.

**Comment by simonemainardi** [comment] 2017-07-03 12:44
thanks for reporting

**Closed as completed by simonemainardi** 2017-07-03 12:44 UTC

**Comment by Artapel** [comment] 2017-07-03 12:47
I also don`t see any error anymore. BUT now my board is freezing again. I did report on the relevant issue that is still open
