### ISSUE TITLE
n2disk integration in ntopng

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#476] opened 2016-04-05 06:30 UTC
ntopng has the ability to integrate with n2disk/nbox, however it is not yet able to instruct n2disk to dump packets on demand (e.g. per host). Instead packet dump happens still with within ntopng at "low rate". ntopng should instrument n2disk to dump selected traffic based on filtering rules set by ntopng via REST API.

**Comment by simonemainardi** [comment] 2018-06-01 15:59
duplicate of #295

**Closed as completed by simonemainardi** 2018-06-01 15:59 UTC
Labels: Enhancement
