### ISSUE TITLE
E2E Rest tests failure

### ISSUE THREAD

**Issue by IvanNardi** [ntop/ntopng#8095] opened 2023-12-13 11:01 UTC
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: current dev 01bd9d153

**What happened**:

It seems all rest tests fail with the same error

```
ivan@ivan-Latitude-E6540:~/svnrepos/ntopng/tests/e2e/rest((HEAD detached at be006dd))$ ./run.sh 
[i] Connectivity ok
[>] Running test 'v2/alert_dns_data_exfiltration_01' (1/53)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_dns_data_exfiltration_01'
13/Dec/2023 11:50:20 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
13/Dec/2023 11:50:24 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
[>] Running test 'v2/alert_dns_data_exfiltration_02' (2/53)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_dns_data_exfiltration_02'
13/Dec/2023 11:51:48 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
13/Dec/2023 11:51:49 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
[>] Running test 'v2/alert_flow_exclusion_lists' (3/53)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_flow_exclusion_lists'
13/Dec/2023 11:52:15 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
13/Dec/2023 11:52:19 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
[>] Running test 'v2/alert_flow_invalid_dns_query_02' (4/53)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_flow_invalid_dns_query_02'
13/Dec/2023 11:52:46 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
13/Dec/2023 11:52:49 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
[>] Running test 'v2/alert_flow_invalid_dns_query_disabled' (5/53)
[!] ntopng Error: ntopng generated errors or warnings running 'v2/alert_flow_invalid_dns_query_disabled'
13/Dec/2023 11:53:09 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
13/Dec/2023 11:53:15 [FlowChecksLoader.cpp:290] WARNING: Unable to find flow check 'connection_failed': skipping it
[>] Running test 'v2/alert_flow_risk_dga_01' (6/53)

```

Is that somehow expected, or is there something wrong in my environment?

**How did you reproduce it?**

Plain compilation of current dev; running e2e rest tests

**Comment by IvanNardi** [comment] 2023-12-24 09:14
Ping

**Comment by cardigliano** [comment] 2024-01-05 14:04
Hi @IvanNardi, did you try pulling latest e2e code? Please note ntopng/tests/e2e is a submodule, please run "git checkout dev && git pull" into that folder before running the tests

**Comment by IvanNardi** [comment] 2024-01-05 17:06
@cardigliano, thanks for looking into that

> Hi @IvanNardi, did you try pulling latest e2e code?

No, I didn't... :(
However, even after updating the submodules, I keep getting the same errors.
To be extra sure, I even make a clean clone: same errors. Full log attached  
[ntopng_tests.txt](https://github.com/ntop/ntopng/files/13844681/ntopng_tests.txt)

**Comment by cardigliano** [comment] 2024-01-08 10:03
I was able to reproduce this on the community build, digging into this..

**Comment by cardigliano** [comment] 2024-01-08 16:40
This has been fixed in 8ea3d4bb59954e871f4ff355434e70207683c453, however please note that running the tests with the community-only binary is not currently supported as the "expected results" have been produced using the "pro" binary, which produces more data.

**Comment by IvanNardi** [comment] 2024-01-08 16:59
Ok, thanks for fixing the issue anyway. Is there any other way to check for ntopng regressions before pushing a PR (and without any license)?

BTW: it might be worthy to update `CONTRIBUTING.md` about this piece of information.
Thanks

**Comment by cardigliano** [comment] 2024-01-08 17:15
I will add a "community" set of tests

**Comment by cardigliano** [comment] 2024-01-09 08:20
@IvanNardi you can now run e2e tests on the community :-)

**Comment by IvanNardi** [comment] 2024-01-09 09:18
Thanks for working on that!
While it seems better now, some tests keep failing...
For example, the first test is ok, but the second one fails; log: [output_test_2.txt…]()
Am I doing something wrong?

[not sure if it is important, but my geo db might be quite old: some tests fails *only* about some geolocation information, and I am fine with that, but the failure on other tests (for example the 2) seems to be more "generic"]

**Comment by cardigliano** [comment] 2024-01-09 09:31
The link to test 2 output is not working

**Comment by IvanNardi** [comment] 2024-01-09 09:48
> The link to test 2 output is not working

Sorry: 
[output_test_2.txt](https://github.com/ntop/ntopng/files/13871911/output_test_2.txt)

**Comment by cardigliano** [comment] 2024-01-09 10:21
It seems this is caused by a non-deterministic execution of the checks, it is not a real issue, but it's causing noice. I will dig more into this asap.

**Closed as completed** 2024-06-20 15:47 UTC
Labels: Enhancement
