### ISSUE TITLE
Unable to enable some behavioral checks

### ISSUE THREAD

**Issue by lucafwp** [ntop/ntopng#7289] opened 2023-03-03 14:07 UTC
**Environment**:
* OS name: Ubuntu
* OS version: 20.04
* Architecture: amd64
* ntopng version/revision: 5.6.230217

**What happened**:
Unable to enable some behavioral checks
![image](https://user-images.githubusercontent.com/36190810/222740510-d872738d-1ae1-46ea-a528-205b41c735a5.png)

**How did you reproduce it?**
- Go to behavioral checks
- Search for "IEC Unexpected TypeID"
- Enable it

**Comment by MatteoBiscosi** [comment] 2023-03-03 15:26
Hi @lucafwp can you please go to the settings -> manage configuration page and send me the behavioral checks configuration? 
There should be some misconfiguration with the json but i'm unable to reproduce it.
Please drop an email at 'biscosi at ntop.org' with the configuration
![image](https://user-images.githubusercontent.com/49585191/222759401-5c0ac48f-0cdc-49cd-be4f-fc258e42c46d.png)

**Comment by sciolto** [comment] 2023-03-06 08:35
Hi @MatteoBiscosi here's the configuration: 

[configuration (1).json.gz](https://github.com/ntop/ntopng/files/10895934/configuration.1.json.gz)

Thanks
 Oreste

**Comment by MatteoBiscosi** [comment] 2023-03-06 11:16
Hi @lucafwp @sciolto even with your configuration, i'm unable to reproduce the issue.
![image](https://user-images.githubusercontent.com/49585191/223095376-0754138c-4787-4b95-ad5e-2f2737a840fb.png)

Could you please check if the inspect reports some error?
![image](https://user-images.githubusercontent.com/49585191/223095616-d755dc10-f052-4368-877e-5491ff9b24f4.png)

**Comment by sciolto** [comment] 2023-03-09 13:22
Hi @MatteoBiscosi, I have tried to debug this on two different systems, and I have more insights: 

The AJAX call to `/lua/get_check_config.lua?check_subdir=flow&script_key=iec_unexpected_type_id&factory=false` returns json data on a system which is not affected by the issue, while the response is empty on an affected system. 

Furthermore in the NTOPNG logs I can see following error, when the user clicks on the toggle:
```
Mar 09 13:11:24 nbox ntopng[33876]: [get_check_config.lua:44] ERROR: Unknown user script: iec_unexpected_type_id
```

The lua files are the same on both systems: 
```
/usr/share/ntopng/scripts/lua/modules/check_definitions/flow/iec_unexpected_type_id.lua
```

Any idea? 

Thanks for your help
 Oreste

**Comment by sciolto** [comment] 2023-03-14 06:35
Hi @MatteoBiscosi any news on this?
Thanks
Oreste

**Comment by MatteoBiscosi** [comment] 2023-03-14 10:20
Hi @sciolto i pushed the fix now.
The problem should be the following: 
that alert is available only for packet interfaces, the user was trying to enable that alert on a non packet interface (flow interface or view interface) and this caused the problem, that alert was not loaded for that specific interface and this caused the problem.
So now the non packet interface alerts are not visible in non packet interfaces.
A new update should be available soon (in a couple of hours) on both dev and stable version

**Comment by sciolto** [comment] 2023-03-14 10:25
Hi @MatteoBiscosi thanks for your efforts. 

Is there a way to tell which checks work with packet interfaces, and which work with _all_ kinds of data ?

**Comment by MatteoBiscosi** [comment] 2023-03-14 10:28
Hi @sciolto 
this icon next to the check name tell to the user which type of interface it analyze, packet or flow interface, if both symbols are present, it means it works for all the interfaces.
![image](https://user-images.githubusercontent.com/49585191/224972139-ec69e381-037d-463e-8ebd-a759679b5ac8.png)

**Comment by lucaderi** [comment] 2023-03-15 14:11
Unfortunately the Apply button does not close the dialog as it should

**Comment by MatteoBiscosi** [comment] 2023-03-15 14:26
Disabled for the system interface.

**Comment by MatteoBiscosi** [comment] 2023-03-16 09:46
Issue fixed with this latest update.
Checks are disabled in the system interface.

**Comment by sciolto** [comment] 2023-03-16 13:45
Hi @MatteoBiscosi, the fix works, thank you.
I have 2 more quick questions about behavioral checks: 

1. Is there a way to tell the interface a checks supports. This list https://www.ntop.org/guides/ntopng/alerts/evaluating_alerts.html does not tell. 
2. Is there a way to tell which fields are missing in the flow-based interfaces, in order to support the check? 
In our case we're using nprobe to feed ntopng, so theoretically we could add some fields and extend the support of the check.

**Comment by sciolto** [comment] 2023-04-20 12:41
Hi @MatteoBiscosi @lucaderi any insights about https://github.com/ntop/ntopng/issues/7289#issuecomment-1471987271 ? 
thanks

**Comment by MatteoBiscosi** [comment] 2023-04-26 15:06
Hi @sciolto from the behavioural check page it is possible to see the interface supported
![image](https://user-images.githubusercontent.com/49585191/234618858-52ba3231-1585-4977-862b-371355bcc1df.png)
![image](https://user-images.githubusercontent.com/49585191/234618899-79d5a3c5-29ca-421a-856c-35320dc7bec4.png)
Theoretically it's possible to add the support to those checks but nprobe has to export those info and currently it is not

**Closed as completed by MatteoBiscosi** 2023-04-26 15:06 UTC
Labels: question
