### ISSUE TITLE
Email notification - dash in mail domain not accepted

### ISSUE THREAD

**Issue by martinscheu** [ntop/ntopng#4577] opened 2020-10-12 22:15 UTC
when the mail domain has a - (dash) in the domain, it is not accepted as input:
(dash in the mail name is ok)

<img width="546" alt="Screenshot 2020-10-13 at 00 11 36" src="https://user-images.githubusercontent.com/38549755/95794781-05412200-0ce9-11eb-8730-fb3391d51006.png">
<img width="543" alt="Screenshot 2020-10-13 at 00 09 23" src="https://user-images.githubusercontent.com/38549755/95794792-0a9e6c80-0ce9-11eb-8e7d-34b034ef431e.png">

**Comment by simonemainardi** [comment] 2020-10-13 06:30
this is a possible duplicate of https://github.com/ntop/ntopng/issues/4538
are you using the latest version?

**Comment by simonemainardi** [comment] 2020-10-14 12:16
I confirm this is resolved. Please update.

![image](https://user-images.githubusercontent.com/3397663/95987442-b948c700-0e27-11eb-9284-b3375a006d54.png)

**Closed as completed by simonemainardi** 2020-10-14 12:16 UTC
