### ISSUE TITLE
Inconsistent VLAN Menu in Flows Analysis

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7263] opened 2023-02-24 11:38 UTC
<img width="568" alt="Screenshot 2023-02-24 at 12 37 11" src="https://user-images.githubusercontent.com/4493366/221169968-ffc4c6e0-e8f2-4611-9f2b-907061fa35d0.png">

**Comment by uccidibuti** [comment] 2023-02-24 15:04
The problem is that the VLAN dropdown is a filter on table rows (and it's also disaligned), while the Protocol select is a way to change all table content. I suggest to put application select outside the table. What do you think about my suggestion @lucaderi ?

**Comment by lucaderi** [comment] 2023-03-03 15:46
You can move it elsewhere, as long as you fix the problem

**Comment by MatteoBiscosi** [comment] 2023-06-07 14:47
Issue fixed by changing the table

**Closed as completed by MatteoBiscosi** 2023-06-07 14:47 UTC
