### ISSUE TITLE
Email alert endpoint configuration doesn't support authentication

### ISSUE THREAD

**Issue by chrisrobinson** [ntop/ntopng#2794] opened 2019-08-30 17:02 UTC
Why is it not possible to specify a username, password, and TCP port? Email alerts as exist today seem to require an SMTP open relay, and who actually has one of those?

I'm using version "ntopng Community Edition v.3.6.190215" in PfSense 2.4.4.

**Comment by simonemainardi** [comment] 2019-09-02 14:56
duplicate of https://github.com/ntop/ntopng/issues/2044

**Closed as completed by simonemainardi** 2019-09-02 14:56 UTC
Labels: Duplicate
