### ISSUE TITLE
How to change First_Switched, Last_Switched fields to date-time?

### ISSUE THREAD

**Issue by nguyenvanthien123** [ntop/ntopng#1200] opened 2017-04-28 10:53 UTC
Hi, 
I used ntopng, How can i change First_Switched, Last_Switched fields to date-time?
Thanks alot!

**Comment by simonemainardi** [comment] 2017-04-28 10:54
duplicate of https://github.com/ntop/ntopng/issues/1199

**Closed as completed by simonemainardi** 2017-04-28 10:54 UTC
Labels: Duplicate
