### ISSUE TITLE
Script failure errors luaEngine

### ISSUE THREAD

**Issue by oktavianq** [ntop/ntopng#3244] opened 2020-01-15 11:02 UTC
Every 3-5 sec i getting erros the below errors logged. 
Jan 15 10:58:18 RAZOR ntopng: [LuaEngine.cpp:11848] WARNING: Script failure [/us                                                 r/share/ntopng/scripts/callbacks/system/housekeeping.lua][/var/lib/ntopng/plugin                                                 s/alert_endpoints/nagios.lua:1: unexpected symbol near '<\135>']
Jan 15 10:58:18 RAZOR ntopng[9633]: 15/Jan/2020 10:58:18 [LuaEngine.cpp:11848] W                                                 ARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/housekeeping.                                                 lua][/var/lib/ntopng/plugins/alert_endpoints/nagios.lua:1: unexpected symbol nea                                                 r '<\135>']
NTOPNG version :

v.3.9.200115    [Enterprise/Professional build]
GIT rev:        dev:212c449e5b29e8b432abc42c1cc3eba220072902:20200115
Pro rev:        r2656
Built on:       Ubuntu 18.04.3 LTS
System Id:      4ADBE7799205A1D6
Platform:       x86_64
Edition:        Enterprise
License Type:   Time-Limited [Empty license file]
Validity:       Until Wed Jan 15 10:58:48 2020

**Comment by cardigliano** [comment] 2020-01-15 11:07
Duplicate of https://github.com/ntop/ntopng/issues/3213

**Closed as completed by cardigliano** 2020-01-15 11:07 UTC
