### ISSUE TITLE
ntopng api

### ISSUE THREAD

**Issue by lulululuej** [ntop/ntopng#4195] opened 2020-07-24 04:45 UTC
Hi,

does anyone know how to call network discovey data from api. Really appreciate if someone can help.

Best regard,
Karen
![Q2](https://user-images.githubusercontent.com/68433978/88361326-40e3e400-cdab-11ea-8943-34744cc5350e.PNG)

**Comment by simonemainardi** [comment] 2020-07-24 04:47
Duplicate of https://github.com/ntop/ntopng/issues/3697

**Closed as completed** 2020-07-24 08:54 UTC
