### ISSUE TITLE
Request to disable disconnection due to inactivity

### ISSUE THREAD

**Issue by shabi61** [ntop/ntopng#8728] opened 2024-09-20 12:23 UTC
Would it be possible to disable the disconnection functionality of a MAC address (IP) in case of inactivity? Despite setting the MAC address cache to 1 day, it seems that users connected with a code are being disconnected after only 10 minutes.

**Comment by lucaderi** [comment] 2024-09-26 07:09
This is a duplicate of https://github.com/ntop/ntopng/issues/8684 implemented more than 3 weeks ago

**Closed as completed by lucaderi** 2024-09-26 07:09 UTC
