### ISSUE TITLE
Dashboard Issues

### ISSUE THREAD

**Issue by SNerone** [ntop/ntopng#3044] opened 2019-11-04 21:30 UTC
Can anyone here assist me with why my dashboard will not show the one graph correctly?  I've rebooted the server several times and still have the same issue.

![NtopNG_Issue_001](https://user-images.githubusercontent.com/36712440/68159694-439e6080-ff20-11e9-8744-10ac9852cffe.jpg)
![NtopNG_Issue_002](https://user-images.githubusercontent.com/36712440/68159695-4436f700-ff20-11e9-8135-0d7be3375fb2.jpg)

**Comment by emanuele-f** [comment] 2019-11-05 08:51
Hi, yesterday I fixed some issues with the dashboard, can you upgrade to the latest version and see if the fix works for you?

**Comment by SNerone** [comment] 2019-11-05 14:37
I've updated to v.3.9.191105 however I still seem to have the issue with the dashboard not displaying.
![DashboardScreenShot_002](https://user-images.githubusercontent.com/36712440/68216999-d803d400-ffaf-11e9-8a6d-011830a9dafa.jpg)

**Comment by SNerone** [comment] 2019-11-05 15:58
Emanuele,

I should mention that if I leave the "Traffic Dashboard" page up long enough... it will show **some** data in it (see the screenshot below) however, if I refresh the page it's gone again.  Is it possible to reset our configuration to factory defaults and see if that will correct the issues that we're having?  Do you think that would help with this as we're okay with losing the current data which we've ingested. 
![DashboardScreenShot_003](https://user-images.githubusercontent.com/36712440/68223519-ef948a00-ffba-11e9-95fd-3b700d253158.jpg)
![DashboardScreenShot_004](https://user-images.githubusercontent.com/36712440/68223523-f15e4d80-ffba-11e9-97ab-482c70d49d69.jpg)

**Comment by emanuele-f** [comment] 2019-11-05 17:54
The problem is probably related to the different number of points in the timeseries. Can you post here the contents of the variable `ifaces_lastday_data` from the javascript console? In chrome you can export it by following the following instructions: https://stackoverflow.com/questions/11849562/how-to-save-the-output-of-a-console-logobject-to-a-file. Please note that resetting to factory will only temporary solve the problem.

**Comment by SNerone** [comment] 2019-11-05 21:50
Thanks for sending this over however I don't see where it is that I can get the output of the commands from the link which you've sent above.  I have saved a log file however it's not showing anything from the variable "ifaces_lastday_data".  All that i have is the log file below... 
[10.1.3.21-1572990296044.log](https://github.com/ntop/ntopng/files/3811395/10.1.3.21-1572990296044.log)

**Comment by emanuele-f** [comment] 2019-11-06 13:44
In the developer console window you should type `ifaces_lastday_data` and press enter. That would print the contents of the javascript variable, then with the method explained in the link above you should be able to export it to file. Sorry for asking you to do these manual steps but currently this is the easiest way to debug this

**Comment by SNerone** [comment] 2019-11-06 14:58
Is this what you’re looking for by chance?  If not I’ll keep on trying, thanks so much for your assistance with this…
[10.1.3.21-1573053030672.log](https://github.com/ntop/ntopng/files/3815141/10.1.3.21-1573053030672.log)

Maybe this file?  Sheesh I wish I knew more about programming so I could not only help here but be more a part of these communities and contribute...
[ntopng_ifaces_lastday_data.txt](https://github.com/ntop/ntopng/files/3815187/ntopng_ifaces_lastday_data.txt)

Here is one more, however I think it's is the same as above...
[ntopng_ifaces_lastday_data.json.txt](https://github.com/ntop/ntopng/files/3815246/ntopng_ifaces_lastday_data.json.txt)

**Comment by emanuele-f** [comment] 2019-11-07 09:17
> [ntopng_ifaces_lastday_data.txt](https://github.com/ntop/ntopng/files/3815187/ntopng_ifaces_lastday_data.txt)

This is the right one, thank you! The problem is the different number of points in the series as expected, we need to fix this.

![2019-11-07_10-15](https://user-images.githubusercontent.com/5488003/68375655-2398b800-013f-11ea-8109-70514e1377eb.png)

**Comment by SNerone** [comment] 2019-11-07 13:17
When you say "we need to fix this" are you stating this is something on your end or on my end which needs to be addressed?  If it's something on my end, please let me know what direction to head so I can get this taken care of.  Thank you for your time in working with me on this.

**Comment by emanuele-f** [comment] 2019-11-07 13:46
This is a ntopng bug, ntop has to fix this on the codebase

**Comment by SNerone** [comment] 2019-11-07 15:38
Okay, thanks I appreciate it

**Comment by emanuele-f** [comment] 2019-11-07 16:20
Issue is now fixed. The fix will be available in the next package in one hour.

**Closed as completed by emanuele-f** 2019-11-07 16:20 UTC
Labels: In Progress

**Comment by SNerone** [comment] 2019-11-07 17:37
Thanks so much for all of your assistance with this, I've updated and everything looks great!

Regards,
Scott Nerone
