### ISSUE TITLE
Unknown application with tcp 0

### ISSUE THREAD

**Issue by flapegue** [ntop/ntopng#5964] opened 2021-10-08 13:24 UTC
Hello,

I can see that when I apply the filter on unknown application, that the tcp ports are rewritten to zero. Why port are set with it ? how can i do to preserve original tcp ports ?
![image](https://user-images.githubusercontent.com/23529050/136564159-2c977bf0-54e7-411b-9a30-2bea7d664ad4.png)

```
root@TOTO:~# nprobe -v

Welcome to nProbe v.9.6.211006 for x86_64-pc-linux-gnu
with native PF_RING acceleration.Built with nDPI 4.0.0-3209-817c00b6

Copyright 2002-21 ntop.org

Version:       9.6.211006
Build OS:      Debian GNU/Linux 11 (bullseye)
SystemID:      XXXX
GIT rev:       9.6-stable:f08d28864b274a4b155a6ccd87f8b2e542c8bb75:20211006
Edition:       nProbe Pro [ntopng Enterprise L License]
License:      XXXXXXXXXXXXXX
License Hash:  XXXXXXXXX [valid license]
License Type:  Permanent License
Maintenance:   Until Sat Oct  1 12:07:24 2022 [357 days left]

nProbe is subject to the terms and conditions defined in
the LICENSE and EULA files that are part of this package.

nProbe also contains third party code:
Radix tree code - (C) The Regents of the University of Michigan
                      ("The Regents") and Merit Network, Inc.
sFlow collector - (C) InMon Inc. 
```

```
root@TOTO:~# grep -v ^# /etc/nprobe/nprobe.conf
-i=none
--collector-port=2055
--zmq=tcp://127.0.0.1:5556
--zmq-disable-buffering
-n=none
--load-custom-fields=/etc/nprobe/paloalto_fields.txt
--flow-templ="%IN_BYTES %IN_PKTS %PROTOCOL %SRC_TOS %TCP_FLAGS %L4_SRC_PORT %IPV4_SRC_ADDR %INPUT_SNMP %L4_DST_PORT %IPV4_DST_ADDR %OUTPUT_SNMP %LAST_SWITCHED %FIRST_SWITCHED %IPV6_SRC_ADDR %IPV6_DST_ADDR %ICMP_TYPE %DIRECTION %FLOW_ID %POST_NAT_SRC_IPV4_ADDR %POST_NAT_DST_IPV4_ADDR %POST_NAPT_SRC_TRANSPORT_PORT %POST_NAPT_DST_TRANSPORT_PORT %FIREWALL_EVENT %POST_NAT_SRC_IPV6_ADDR %POST_NAT_DST_IPV6_ADDR %ENTREPRISE_NUMBER %APPLICATION_NAME %USER_NAME"
--flow-version=9
-G=/var/run/nprobe.pid
--verbose=0

```

```
root@TOTO:~# grep -v ^# /etc/ntopng/ntopng.conf
-G=/var/run/ntopng.pid
--interface=tcp://127.0.0.1:5556
--local-networks=XXXXX
--dns-mode=3
--dump-flows="mysql;localhost;ntopng;flows;ntopng;XXXXXXXXX"
--max-num-flows=524288
--max-num-hosts=524288
```

**Comment by MatteoBiscosi** [comment] 2021-10-11 08:23
Hi @flapegue you probably miss some missing fields in your template, for example the 
`[NFv9 57577][IPFIX 35632.105][Len 2] %FLOW_PROTO_PORT                L7 port that identifies the flow protocol or 0 if unknown`
Take a look at this page to find all the information you can add https://www.ntop.org/guides/nprobe/cli_options.html?highlight=template#netflow-v9-ipfix-format-t

**Comment by afernique** [comment] 2021-10-11 14:02
Hi MatteoBiscosi, thx for the answer.
Guess we're still a bit puzzled here ^_^. Since we're talking tcp traffic and both %L4_SRC_PORT and DEST one are specified in flow template, shouldn't we see the used port instead of "0" in ntopng flow page?
Seems all TCP traffic of UNKOWN apps appear with both source and destination port set to 0 in our case. which certainly dosen't help tagging :-/

![image](https://user-images.githubusercontent.com/77778154/136803056-7ec5dc73-53c2-4613-9eec-5f30a2fd774b.png)

**Comment by MatteoBiscosi** [comment] 2021-10-12 08:37
Hi @afernique please drop an e-mail at `biscosi at ntop.org` with a pcap of the traffic sent to nprobe, in this way i'll try to reproduce the issue in my lab

**Comment by lucaderi** [comment] 2021-10-13 17:39
I have sent nProbe the pcap file you shared with us. As you can see traffic is properly decoded and ports are non zero
![image](https://user-images.githubusercontent.com/4493366/137183999-efd1ed4c-6501-4dd6-942b-e535bf0fdfc2.png)
Instead MAC addresses are empty as you can see
![image](https://user-images.githubusercontent.com/4493366/137184161-b384db2e-5c4e-451c-a959-d0ad668d54ba.png)
because they are not present in the template
![Screen Shot 2021-10-13 at 19 36 00](https://user-images.githubusercontent.com/4493366/137184400-4abe5fd9-4282-4dc5-83f8-f3aae8e2a742.png)

I have updated https://github.com/ntop/nProbe/blob/master/custom_fields/PaloAlto/paloalto_custom_fields.txt with the custom fields you are using

So in essence works for me: the info that is missing was missing in the original flows. I will close this ticket, please reopen if necessary

**Closed as completed by lucaderi** 2021-10-13 17:39 UTC
