### ISSUE TITLE
Very high packet loss on previously working system

### ISSUE THREAD

**Issue by tman24** [ntop/ntopng#760] opened 2016-09-23 13:21 UTC
Recent ntopng + pfring upgrades are now causing extremely high packet loss on interfaces that were working fine about 2 weeks ago. I'm monitoring 4 interfaces, eth0 being the busiest, but that doesn't usually go higher than 100Mb/s. This has never happened before like this. Strangely, the other 3 interfaces being monitored (much lighter use) show normal traffic. 

I did have some problems upgrading pf_ring recently, but resolved that, and lsmod/modinfo show the correct version and loaded ok. ntopng logs look fine (even ran it in debug for a while - no errors I can see). Startup file hasn't changed in months. I've been updating things almost daily to see if a later build resolves it, but not yet. I also ran pfcount from the command line, and that showed no packet loss on eth0!

System information;
O/S: CentOS 6.8 (kernel 2.6.32-642.4.2.el6.x86_64)
ntopng ver: v.2.5.160920 [Enterprise/Professional Edition]
pf_ring ver: v6.5.0.832
NIC: 2 x dual port Intel Pro/1000 PCI-X (82546EB, driver v8.0.35-NAPI)

Startup config:

--dns-mode 1
--interface eth0
--interface eth1
--interface eth2
--interface eth3
--local-networks "<five local subnets>"
--http-port 3000
--data-dir /data/ntopng
--packet-filter="ip and not proto ipv6 and not ether host ff:ff:ff:ff:ff:ff and not net (224.0.0.0/8 or 239.0.0.0/8)"
--sticky-hosts local
--disable-autologout
--user ntop
--pid /data/ntopng/ntopng.pid
--daemon
# --verbose 6

This was working fine for months, but now the system is pretty much unusable due to the packet loss. I've made sure gso/gro/tso are all off as normal.  I've checked all cabling between the switch mirror port and the ntop box, and everything checks out.

**Comment by simonemainardi** [comment] 2016-09-26 10:04
if you comment out the `--packet-filter` option, do you still get an high packet loss?

**Comment by tman24** [comment] 2016-09-26 12:17
No change when removing the --packet-filter option. Packet loss now showing in the range of 98% on this one interface. Could it actually be PFRING causing the problem? Updating from nightly ntopng builds _without_ also updating pfring is difficult because of the dependancies. I wanted to go back and try 6.4.1, which seems to be the current 'stable' version.

**Comment by tman24** [comment] 2016-09-26 12:21
I also tried building a pf_ring enabled version of tcpdump/libpcap. If I run tcpdump on eth0, I can still see dropped packets. A 2 minute capture on eth0 showed;

17275 packets captured
17275 packets received by filter
520128 packets dropped by kernel

So, this tells me it's either the nic, cabling or pf_ring. I tried a different cable direct to the mirror port, but no change at all.

**Comment by cardigliano** [comment] 2016-09-26 12:31
Please try with pfcount -i ethX and show us the output (a few lines).

**Comment by tman24** [comment] 2016-09-26 12:41
Here you go

[root@ntopng network-scripts]# pfcount -i eth0
Using PF_RING v.6.5.0
Capturing from eth0 [mac: 00:04:23:B7:28:2E][if_index: 12][speed: 100Mb/s]

# Device RX channels: 1

# Polling threads:    1

# Dumping statistics on /proc/net/pf_ring/stats/17290-eth0.79

Absolute Stats: [6'840 pkts total][0 pkts dropped][0.0% dropped]

# [6'840 pkts rcvd][5'063'350 bytes rcvd]

# 

Absolute Stats: [12'120 pkts total][0 pkts dropped][0.0% dropped]

# [12'120 pkts rcvd][8'882'369 bytes rcvd][12'118.86 pkt/sec][71.05 Mbit/sec]

# Actual Stats: [5'280 pkts rcvd][1'000.09 ms][5'279.50 pps][0.03 Gbps]

# 

Absolute Stats: [18'996 pkts total][0 pkts dropped][0.0% dropped]

# [18'996 pkts rcvd][14'232'498 bytes rcvd][9'497.16 pkt/sec][56.93 Mbit/sec]

# Actual Stats: [6'876 pkts rcvd][1'000.08 ms][6'875.44 pps][0.04 Gbps]

# 

Absolute Stats: [24'856 pkts total][0 pkts dropped][0.0% dropped]

# [24'856 pkts rcvd][18'554'409 bytes rcvd][8'284.62 pkt/sec][49.47 Mbit/sec]

# Actual Stats: [5'860 pkts rcvd][1'000.08 ms][5'859.51 pps][0.03 Gbps]

# 

Absolute Stats: [30'007 pkts total][0 pkts dropped][0.0% dropped]

# [30'007 pkts rcvd][22'150'729 bytes rcvd][7'501.13 pkt/sec][44.30 Mbit/sec]

# Actual Stats: [5'151 pkts rcvd][1'000.07 ms][5'150.62 pps][0.03 Gbps]

# 

Absolute Stats: [33'584 pkts total][0 pkts dropped][0.0% dropped]

# [33'584 pkts rcvd][24'333'075 bytes rcvd][6'716.25 pkt/sec][38.93 Mbit/sec]

# Actual Stats: [3'577 pkts rcvd][1'000.07 ms][3'576.72 pps][0.02 Gbps]

# 

Absolute Stats: [37'102 pkts total][0 pkts dropped][0.0% dropped]

# [37'102 pkts rcvd][26'503'396 bytes rcvd][6'183.16 pkt/sec][35.33 Mbit/sec]

Actual Stats: [3'518 pkts rcvd][1'000.08 ms][3'517.70 pps][0.02 Gbps]

**Comment by tman24** [comment] 2016-09-26 12:42
Sorry about the font there. Not sure what happened.

**Comment by simonemainardi** [comment] 2016-09-26 13:11
@tman24 any chance you can give us remote SSH access to the box? Please send the credential to mainardi ntop org

**Comment by tman24** [comment] 2016-09-26 15:47
Yeah, that might be difficult. We're a secure site, and that would break a whole load of rules.

**Comment by simonemainardi** [comment] 2016-09-26 16:35
so there are some additional things to try:
1. use ntopng sable (v 2.4.x)
2. check system load: do you see the ntopng process that is eating up one or more cores? This may help in determining if there's a loop
3. check io (`iotop`)
4. attach gdb to the running ntopng process and see (info threads) if there's a thread stuck in a particular function
5. use `strace` and see if there is some unexpected activity (e.g., to many calls)
6. check ntopng alerts. How many alerts do you have? What to you get after clearing them?

**Comment by tman24** [comment] 2016-09-27 09:35
I've now switched from the ntop-dev to ntop-stable repo, uninstalled both ntopng and pfring, then re-installed both stable versions. I've kept the same conf file/data folder. Redis-server was left as is.

Result - now working fine again. Looking at the interface stats, ntop shows (after a few minutes) 10m packets captured, 0 dropped on the main interface. I'll probably stay on stable for the time being.

Where the bug is though - and whether it's in ntop or pfring, I'm not sure. It appeared in a build from about 2 weeks ago. My nic's are standard NAPI (not DNA/ZC) using Intel PCI-X Gb Pro/1000's.

**Comment by lucaderi** [comment] 2016-09-27 17:18
@tman24 @emanuele-f We believe the issue is caused by the host activities calculation. @simonemainardi made a change that activities are disabled (this for the time being until we fix this issue properly) unless you add --enable-flow-activity to the ntopng command line.

**Comment by lucaderi** [comment] 2016-09-27 17:21
@emanuele-f The performance hog is caused by flow->invokeActivityFilter() (in NetworkInterface::processPacket()) that is called for every packet of the flow. I believe you should make a change in your activity code so that the flow moving averages are NOT computed more than once a second, so that we can have a worst case in our code. Can you implement this please?

**Comment by emanuele-f** [comment] 2016-09-27 17:44
@tman24 sorry for the incident. Please checkout new code and report us if the problem is solved. I'll be working to improve activity detection performance.

**Comment by tman24** [comment] 2016-09-28 08:41
Thanks for the update. I'll add that when this was happening there was no observed increase in CPU or disk I/O. Memory usage was actually _lower_ than usual as well. If this 'performance hog' was causing the issue, it wasn't showing in the system stats. I'm assuming the flow -> invokeActivityFilter() thread is the one that pulls the packets off the wire from the ring buffer. Even eth0 (the main interface I'm monitoring) only peaks at just over 100Mb/s, so I'm surprised others monitoring very high throughput interfaces didn't observe this as well.

While I'm tempted to see if the new build fixes this, running the current stable branch is working fine at the moment - 300m packets captured, 0 drops. I'll probably wait until the next stable build before updadting again (I know 2.6 is now being worked on).

**Comment by lucaderi** [comment] 2016-09-28 08:52
@tman24 Please be tempted as this way you will help us with debuggin

**Comment by simonemainardi** [comment] 2016-09-29 17:17
I've had the chance to test the latest ntopng on another large deployment and I've to say that there are no longer performance issues. It's monitoring 2 PF_RING interfaces loaded with 400 and 300 Mpbs respectively. So I guess it is now safe to close the issue. I would encourage @tman24  to try the latest version and give us a feedback.

**Closed as completed by simonemainardi** 2016-09-29 17:17 UTC
