### ISSUE TITLE
Improve Alert Download

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#7112] opened 2023-01-16 11:34 UTC
Currently alerts download in CSV format is implemented in batch mode so when tenth of thousand records are returned, data download is very slow. This needs to be fixed as it takes a lot of time to download many records.

**Comment by MatteoBiscosi** [comment] 2023-03-22 15:19
duplicate of issue #6852

**Closed as completed by MatteoBiscosi** 2023-03-22 15:19 UTC
Labels: Enhancement
