### ISSUE TITLE
Properly report slow hosts allocation with view interfaces in ht_state_update

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#3533] opened 2020-03-10 11:52 UTC
When using view interfaces, the hosts allocation is performed in the ht_state_update activity. If the local hosts cache is enabled, such activity would take a very long time to allocate all the hosts (in particular right after the startup). This produces a "slow activity" warning with no futher information (as explained in https://github.com/ntop/ntopng/issues/3531). It is requested:

1. to report the slow allocation issue as an engaged alert. If the local hosts cache is enabled, advice the user to disable it in order to mitigate the issue.
2. Improve the warning message of the slow ht_state_update activity. It should be clear that ht_state_update can actually last for more than 5 seconds, and that is not a bug.

**Comment by simonemainardi** [comment] 2020-06-26 12:52
duplicate of #2965

**Closed as completed by simonemainardi** 2020-06-26 12:52 UTC
Labels: Enhancement
