### ISSUE TITLE
ntopng crashes on Traffic Report

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#2085] opened 2018-10-07 15:51 UTC
ntopng --version
v.3.7.181007    [Enterprise/Professional build]
GIT rev:        dev:7225bef5c3b727a79483fb50b1c7bf850ba559bc:20181007
Pro rev:        r1958
Built on:       Debian GNU/Linux 8.2 (jessie)
System Id:      390956AE76056206
Platform:       x86_64
Edition:        Enterprise
License Type:   Permanent

When selecting Traffic Reports ntopng crashes and no charts are printed:

opng[2018]: segfault at 8 ip 000000000040e215 sp 00007fc97c0dfb60 error 4 in ntopng[400000+1ef000]

I have some trouble generating a core dump:

ulimit -c
unlimited
root@<hostname>:~# cat /proc/sys/kernel/core_pattern
/var/ntop/data/core-%e-%s-%u-%g-%p-%t
root@<hostname>:~# /usr/bin/ntopng /etc/ntopng/ntopng.conf
07/Oct/2018 14:03:08 [Ntop.cpp:1543] Setting local networks to <network-list>
07/Oct/2018 14:03:08 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
07/Oct/2018 14:03:08 [Redis.cpp:127] Successfully connected to redis 127.0.0.1:6379@0
07/Oct/2018 14:03:08 [NtopPro.cpp:310] [LICENSE] Reading license from Redis
07/Oct/2018 14:03:08 [NtopPro.cpp:208] [LICENSE] x: found valid Enterprise license
07/Oct/2018 14:03:09 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.7.3.0 interface eth1...
07/Oct/2018 14:03:09 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth1...
07/Oct/2018 14:03:09 [MySQLDB.cpp:723] Successfully connected to MySQL [<dbuser>@localhost:3306] for interface eth1
07/Oct/2018 14:03:09 [Ntop.cpp:1637] Registered interface eth1 [id: 2]
07/Oct/2018 14:03:09 [BatchedMySQLDB.cpp:230] Executing queryLoop()
07/Oct/2018 14:03:09 [main.cpp:311] PID stored in file /var/run/ntopng.pid
07/Oct/2018 14:03:09 [Utils.cpp:511] User changed to ntop
07/Oct/2018 14:03:09 [HTTPserver.cpp:1114] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
07/Oct/2018 14:03:09 [HTTPserver.cpp:1117] HTTP server listening on 3000
07/Oct/2018 14:03:09 [MySQLDB.cpp:669] Disconnected from MySQL for interface eth1...
07/Oct/2018 14:03:09 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth1...
07/Oct/2018 14:03:09 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng_user@localhost:3306] for interface eth1
07/Oct/2018 14:03:09 [main.cpp:390] Logging onto /var/ntop/data/ntopng.log
07/Oct/2018 14:03:09 [main.cpp:393] Working directory: /var/ntop/data
07/Oct/2018 14:03:09 [main.cpp:395] Scripts/HTML pages directory: /usr/share/ntopng
07/Oct/2018 14:03:09 [Ntop.cpp:388] Welcome to ntopng x86_64 v.3.7.181007 - (C) 1998-18 ntop.org
07/Oct/2018 14:03:09 [Ntop.cpp:398] Built on Debian GNU/Linux 8.2 (jessie)
07/Oct/2018 14:03:09 [NtopPro.cpp:633] [LICENSE] System Id:     <ID>
07/Oct/2018 14:03:09 [NtopPro.cpp:634] [LICENSE] Edition:       Enterprise
07/Oct/2018 14:03:09 [NtopPro.cpp:635] [LICENSE] License Type:  Permanent License
07/Oct/2018 14:03:09 [NtopPro.cpp:638] [LICENSE] License:       <license>
07/Oct/2018 14:03:09 [NtopPro.cpp:648] [LICENSE] Maintenance:   Until Tue Jun  4 18:27:30 2019 [240 days left]
07/Oct/2018 14:03:09 [PeriodicActivities.cpp:68] Started periodic activities loop...
07/Oct/2018 14:03:10 [PeriodicActivities.cpp:109] Each periodic activity script will use 2 threads
07/Oct/2018 14:03:10 [NetworkInterface.cpp:2600] Started packet polling on interface eth1 [id: 2]...
07/Oct/2018 14:03:10 [MySQLDB.cpp:682] Attempting to connect to MySQL for interface eth1...
07/Oct/2018 14:03:10 [MySQLDB.cpp:723] Successfully connected to MySQL [ntopng_user@localhost:3306] for interface eth1
Speicherzugriffsfehler
root@<hostname>:~# ls -l /var/ntop/data/
insgesamt 96
drwxrwxrwx  8 ntop ntop  4096 Jul 26  2016 0
drwxrwxrwx  7 ntop ntop  4096 Jul 26  2016 1
drwxrwxrwx  5 ntop ntop  4096 Aug  9 23:30 -1
drwxrwxrwx 13 ntop ntop  4096 Aug 25 11:04 2
drwxrwxrwx  3 ntop ntop  4096 Jul 26  2016 46
-rw-------  1 ntop ntop 24511 Okt  7 14:03 ntopng.log
-rw-rw-rw-  1 ntop ntop 41908 Okt  7 13:44 runtimeprefs.json
drwxrwxrwx  4 ntop ntop  4096 Aug 24 16:51 snmpstats

**Comment by simonemainardi** [comment] 2018-10-08 07:30
duplicate of #2079

**Closed as completed by simonemainardi** 2018-10-08 07:30 UTC
Labels: Duplicate
