### ISSUE TITLE
SNMP strange values

### ISSUE THREAD

**Issue by astalush** [ntop/ntopng#5763] opened 2021-08-13 15:45 UTC
Hey. I have a problem/question regarding the SNMP polling of ntopng app.

After I add the device via the snmp add page, how does it know which values to look in the MIB for that device? If's it's a CISCO or a DELL or another one? Regarding this SNMP question I also have a problem with the values and graph shown by ntopng.

The device is :
![image](https://user-images.githubusercontent.com/8401863/129383402-b47133d4-394c-41ef-919c-3bbed549550b.png)

The graph and infos are : 
![image](https://user-images.githubusercontent.com/8401863/129383440-cc7b73df-b0ad-482e-ba5b-2cd6b6c4c76b.png)

I find it hard to believe that the switch does that speed at those random times ( behind that switch is only one user who uses an ip phone and one PC and the bandwidth is at 10 Mbps maxi. ). Why that big speed is categorised like "Other"? What does that mean? Does it look into the wrong OID in the MIB and shows an incorrect value? Does it knosw that it's a DELL and it looks into the good OID - MIB? It strange, and we have this problem into others switches where the speed is to big like in this photo :  
![image](https://user-images.githubusercontent.com/8401863/129384863-2b1baabe-9d98-4283-b875-39bcf37e1e3c.png)

Thanks!

**Comment by simonemainardi** [comment] 2021-08-16 14:10
> how does it know which values to look in the MIB for that device? If's it's a CISCO or a DELL or another one? 

It determines the device type and manufacturer first, and then it uses the right MIB depending on the determined values.

**Comment by simonemainardi** [comment] 2021-08-23 09:14
anyway, that spiky behavior is suspicious. It makes me think there's some issue in the polling or non-standard OIDs. Can you please check if this is only happening with a particular device?

**Comment by simonemainardi** [comment] 2021-08-23 09:43
I have three dell n1524, all behaving nicely

![image](https://user-images.githubusercontent.com/3397663/130426262-31cb0ec5-769e-46fd-bf0f-772a08036edf.png)

![image](https://user-images.githubusercontent.com/3397663/130426408-1793cd5f-b470-4241-ae42-6568fa8a8bc5.png)

**Comment by astalush** [comment] 2021-08-31 09:23
It happens with multiples devices, n1524, n1548, even n3048p. Like in the photo below all the infos are ok except the "Other" info. Where does it look in the MIB for this "Other" info? What OID? Can you look on your N1524 devices on the 1day grafic? And not the 30minutes grafic?

![image](https://user-images.githubusercontent.com/8401863/131476737-b83ed8cd-f1b6-4f1a-8833-95d9b5ef7b36.png)

**Comment by simonemainardi** [comment] 2021-09-06 14:02
"Other" is just the sum of all other interfaces that are not shown. May be a counter wrap due to SNMP v1 with 32bit counters. Can you please tell me the SNMP version you've used when configuring the device?

**Comment by astalush** [comment] 2021-09-07 07:52
We are using snmp v2. I understood that other are the interfaces that are not shown but that doesn't help us to see what interface does that. Thanks.

**Comment by astalush** [comment] 2021-11-29 14:03
Hey Simone. Could you please select for 1d and not for 30 mins? 

It does the same on others machines like this DELL C9010

![image](https://user-images.githubusercontent.com/8401863/143881720-148247e6-be8f-4c42-a6ce-71c93a7810f8.png)

**Comment by MatteoBiscosi** [comment] 2022-05-06 09:53
Hi @astalush please update to the latest ntopng version. Mainly in the 5.3 ntopng version we did a lot of reworks in SNMP and the issue should be fixed. Please reopen the ticket if the issue is not fixed.

**Closed as completed by MatteoBiscosi** 2022-05-06 09:53 UTC
Labels: Waiting for Feedback ⌛
