### ISSUE TITLE
No Data in Network Interfaces: Realtime Traffic Dashboard View

### ISSUE THREAD

**Issue by kenatgcc** [ntop/ntopng#2720] opened 2019-07-15 12:28 UTC
The graph is empty.

![image](https://user-images.githubusercontent.com/50203145/61216070-840c7100-a6da-11e9-9f41-7ea43b7adecd.png)

**Comment by emanuele-f** [comment] 2019-07-15 12:32
What are the contents of your /etc/ntopng/ntopng.conf file?

**Comment by kenatgcc** [comment] 2019-07-15 15:38
My ntopng.conf is below.

[my_ntopng.conf.txt](https://github.com/ntop/ntopng/files/3393052/my_ntopng.conf.txt)

**Comment by cardigliano** [comment] 2019-07-15 15:49
A fix for this has been pushed, a new package will be available in <1h, please update and let us know.

**Comment by cardigliano** [comment] 2019-07-15 15:50
Duplicate of #2719

**Closed as completed by cardigliano** 2019-07-15 15:50 UTC
Labels: To Be Confirmed

**Comment by kenatgcc** [comment] 2019-07-15 17:22
I updated today and the data has returned to Network Interfaces: Realtime Traffic in the dashboard.
Thanks!
