### ISSUE TITLE
getHostPoolsStats nil value

### ISSUE THREAD

**Issue by csammons0x1c** [ntop/ntopng#1700] opened 2018-03-13 20:56 UTC
Hello,

I've recently installed Community Edition v 3.3.180227 and get the following error in the log trace 3 times per second:

13/Mar/2018 15:07:00 [Lua.cpp:7227] WARNING: Script failure [/usr/local/ntopng-3.3/share/ntopng/scripts/callbacks/interface/minute.lua][...png-3.3/share/ntopng/scripts/lua/modules/alert_utils.lua:2151: attempt to call field 'getHostPoolsStats' (a nil value)]

I'm not sure if this is related but I've also noticed that there are no protocol choices in the interface timeseries drop-down (as there was before). It appears that most of the traffic is classified as Unkown/Unspecified.

**Comment by emanuele-f** [comment] 2018-03-14 08:58
Hi, this is a duplicate of #1696 . Please update to fix it.

**Closed as completed by emanuele-f** 2018-03-14 08:58 UTC
