### ISSUE TITLE
Netflow customized reports

### ISSUE THREAD

**Issue by prasanthi97** [ntop/ntopng#2013] opened 2018-09-12 08:48 UTC
currently we are using ntopng for network monitoring.we need to get the below details from net flow. is it possible to arrive using any filters or solution already available.
1.protocol wise break up of traffic max-in,max-0ut,avg-in,avg-out, average total
2.stacked protocol trend-in and out
3.stacked Tos trend-in  and out
4.hosts-summary volume-from
5.host-summary volume-to
6.conversation summary volume-total

**Comment by emanuele-f** [comment] 2018-09-12 09:02
Duplicate of #2014

**Closed as completed by emanuele-f** 2018-09-12 09:02 UTC
