### ISSUE TITLE
FR:  Remove Geolocation popup

### ISSUE THREAD

**Issue by DigiAngel** [ntop/ntopng#4403] opened 2020-09-14 13:19 UTC
This shows up on every screen, all the time:
![Screenshot from 2020-09-14 07-18-07](https://user-images.githubusercontent.com/947191/93090855-96759800-f65a-11ea-8a6a-6a4bdc579820.png)

I have no interest in the Geolocation feature currently...any way to disable this?  Thanks.

**Comment by simonemainardi** [comment] 2020-09-14 13:26
duplicate of https://github.com/ntop/ntopng/issues/4198

**Closed as completed by simonemainardi** 2020-09-14 13:26 UTC
Labels: Duplicate

**Comment by DigiAngel** [comment] 2020-09-14 13:27
Well...that certainly sucks.
