### ISSUE TITLE
Show physical interface statistics

### ISSUE THREAD

**Issue by emanuele-f** [ntop/ntopng#2916] opened 2019-10-07 06:42 UTC
Show physical interfaces statistics, e.g. in router mode show byte sent/recv per WAN interface

**Comment by simonemainardi** [comment] 2020-05-29 09:31
Notes:

- The issue refer to the physical WAN interface.
- nEdge can have multiple gateways sharing the same WAN.

**Comment by simonemainardi** [comment] 2020-05-29 10:09
Duplicate of #2046

**Closed as completed by simonemainardi** 2020-05-29 10:09 UTC
Labels: Feature Request, nEdge
