### ISSUE TITLE
NTOP active monitoring does not send alerts

### ISSUE THREAD

**Issue by darrenp2022a** [ntop/ntopng#6785] opened 2022-07-18 07:08 UTC
**Environment**:
* OS name: Centos
* OS version: Stream 8
* Architecture: Intel
* ntopng version/revision: 5.5.220713 and current 5.4.220711

**What happened**:
NTOP does not send alerts, this has been the case since before August 2021.  This was reported to:

Luca, who created ticket 6405
Alfredo
Matteo

**What did you expect to happen?**
For it to send alerts

**How did you reproduce it?**
Turn the product on,
Configure it to active monitoring Continuous ICMP
Configure the product to send an email or teams webhook alert

Product functions when using IP addresses, or DNS entries.

After 8 months of thinking about this, and not getting a response from NTOP (i.e. being ignored), could this issue be related to NTOP not reading the hosts file (which was mentioned to Matteo several months back)

**Debug Information**:

See previous emails as I've sent this multiple times.

**Comment by cardigliano** [comment] 2022-07-18 07:36
Could you comment more about "could this issue be related to NTOP not reading the hosts file" please?
Which file are you referring to exactly, and what is the relation with the notifications? Thank you.

**Comment by darrenp2022a** [comment] 2022-07-18 07:39
From your last email, you sent a screenshot of notifications against google.com (8.8.8.8) from memory, and the difference is my hosts are not internet based, they are internal, so there is no DNS, I’m using the /etc/hosts file for resolution.

Continuous ICMP works fine with hosts configured in that way, but it’s the only difference I could think off compared with your working example. I have not tried against Internet FQDN hosts, only against /etc/hosts.

Thanks

Darren

**Comment by cardigliano** [comment] 2022-07-18 07:59
Regardless of the host being an IP address, a local defined name, or an internet FQDN, what you configure in the Recipient now is the Active Monitoring entry, which should be value agnostic. Anyway please provide an exact configuration example  and I will try to reproduce the same step by step.

**Comment by cardigliano** [comment] 2022-07-20 07:38
Unable to reproduce with the same configuration. We are scheduling a remote session to debug this.

**Comment by cardigliano** [comment] 2022-09-22 10:10
@darrenp2022a can we close this?

**Closed as completed** 2022-09-22 17:49 UTC
Labels: Waiting for Feedback ⌛

**Comment by darrenp2022a** [comment] 2022-09-22 22:29
This issue is still pending, I set it up for you and enabled logging as requested, I had enabled remote access as discussed so you can view for yourself and heard nothing back.

So, as requested, let me know when you are going to look at tiffs and review the logs.

Regards
________________________________

**Comment by cardigliano** [comment] 2022-09-23 07:37
@darrenp2022a, I actually "heard nothing back", please check our mail conversation:
 
<img width="814" alt="Screen Shot 2022-09-23 at 09 34 30" src="https://user-images.githubusercontent.com/7548711/191912342-6fe32f58-acfd-456b-8f85-e11954af891e.png">

**Comment by darrenp2022a** [comment] 2022-09-23 08:35
We had a conversation and discussed this, it’s available when you wish, I fully opened it up so you can see it. You saw the issue in action and wanted the logs.

Why are you closing the tickets, you personally saw the issue?

This is unbelievable to be honest… I’m gob smacked at this level of customer service.

I will open another ticket I guess and post to discord…

Regards


________________________________

**Comment by cardigliano** [comment] 2022-09-23 08:41
The issue has been closed for inactivity, you can reopen the same one (without creating a new one) if still active.
I sent instructions to gather debug information on Aug 2nd, and I am still waiting for the logs (you said you were going to run the test and send them last time I heard from you).
I am willing to help solve this issue, but it's hard if you behave like this.
