### ISSUE TITLE
Classify IP traffic to new application or category

### ISSUE THREAD

**Issue by ubun3t** [ntop/ntopng#4050] opened 2020-06-16 15:06 UTC
Hi all, I am trying to config ntop to group all traffic from some IP's (CDN) to a new category. Something like "Netflix-CDN or Facebook-CDN" to see quickly how much traffic doesn't leave those CDNs. 

(ntopng Enterprise M Edition v.4.0.200615 )

I add a new application and in "rules box" set the network (x.x.x.x/24 or whatever). 
In rules I am trying with : 
ip:1.1.1.0/24
and
1.1.1.0/24

Ntop need to restart and after that...the new app is missing. 
What are I doing wrong? What is the correct way to accomplish ?

Thanks in advance, 

Regards, 

![ntopng Applications and Categories](https://user-images.githubusercontent.com/16337441/84791882-84e90980-aff3-11ea-83ab-919a1985b686.png)

**Comment by ubun3t** [comment] 2020-06-17 15:39
Hi, Any idea with that? 

Thanks.

**Comment by simonemainardi** [comment] 2020-06-17 15:58
Confirmed. Reproduced.

Due to ntopng failing to properly write ip rules to the file.

**Comment by simonemainardi** [comment] 2020-06-17 16:57
Issue is fixed. Thanks for reporting. New builds are in progress. Please wait a couple of hours and update.

It's safe to specify just the addresses. Examples

![image](https://user-images.githubusercontent.com/3397663/84926882-5428d300-b0cc-11ea-8678-bad06fce15ae.png)

**Comment by ubun3t** [comment] 2020-06-17 18:25
Thanks Simone, I have update and now my version is ntopng Enterprise M Edition v.4.0.200617. 

Now ntop write well in protos.txt but after restart disappears again in web interface. 

Thanks in advance. 


![ntopng_Applications_and_Categories](https://user-images.githubusercontent.com/16337441/84935141-97893e80-b0d8-11ea-90ef-655cf3f1a1c4.png)

**Comment by simonemainardi** [comment] 2020-06-17 19:50
what's the path of your `-p` custom protocol file? I guess the reboot deletes it so you may have put it under /tmp

**Comment by ubun3t** [comment] 2020-06-17 19:53
This is the path : 
-rw------- 1 ntopng ntopng  /var/lib/ntopng/protos.txt

And I haven't rebooted the machine, only restarted the service

**Comment by ubun3t** [comment] 2020-06-18 16:12
Hi Simone, any update? How can I resolve it? 

Regards,

**Comment by simonemainardi** [comment] 2020-06-18 16:30
attach your protos.txt here

**Comment by ubun3t** [comment] 2020-06-18 16:41
root@ntop ~# cat /var/lib/ntopng/protos.txt
FaceBook-CDN
ip:45.228.235.192/26@FaceBook-CDN

NetFlix-CDN
ip:45.5.116.184/29@NetFlix-CDN

YouTube-CDN
ip:45.228.235.140@YouTube-CDN
ip:45.228.235.141@YouTube-CDN
ip:45.5.116.204@YouTube-CDN
ip:45.5.116.205@YouTube-CDN

I have removed #

**Comment by simonemainardi** [comment] 2020-06-19 09:47
Using the file provided, behavior is consistent and new protocols are always present even across multiple ntopng restarts:


```
simone@devel:~/ntopng$ sudo cat /tmp/protos3
# FaceBook-CDN
ip:45.228.235.192/26@FaceBook-CDN

# NetFlix-CDN
ip:45.5.116.184/29@NetFlix-CDN

# YouTube-CDN
ip:45.228.235.140@YouTube-CDN
ip:45.228.235.141@YouTube-CDN
ip:45.5.116.204@YouTube-CDN
ip:45.5.116.205@YouTube-CDN

simone@devel:~/ntopng$ sudo ls -lha  /tmp/protos3
-rw------- 1 ntopng ntopng 227 Jun 19 11:42 /tmp/protos3


simone@devel:~/ntopng$ ./ntopng --version
v.4.0.200619	[Enterprise/Professional build]
GIT rev:	4.0-stable:b0c5fcc3fef67a9670dc351468ef80aa4df1a824:20200619

simone@devel:~/ntopng$ sudo ./ntopng -i eno1 -p /tmp/protos3
```

**Comment by ubun3t** [comment] 2020-06-19 13:37
I don't understand why doesn't works for me

Let me show you :      


`~# ntopng --version`
`v.4.0.200619    [Enterprise/Professional build]`
`GIT rev:        4.0-stable:b0c5fcc3fef67a9670dc351468ef80aa4df1a824:20200619`

My ntopng.conf has : 

`--ndpi-protocols=/var/lib/ntopng/protos.txt`

I have tried to start manually with : 

`ntopng -i "tcp://10.0.41.106:5551" -p /var/lib/ntopng/protos.txt -m 10.0.0.0/8`

Same result :( 
When I start manually only  see a warning, no errors at all : 

` [LuaEngine.cpp:12157] WARNING: Script failure [/usr/share/ntopng/scripts/callbacks/system/startup.lua][/usr/share/ntopng/scripts/lua/modules/lists_utils.lua:466: attempt to index a nil value (local 'list')]`

I have rebooted and update the server. 

What can I check ? 

Thanks Simone.

**Comment by simonemainardi** [comment] 2020-06-22 17:54
Issue turned out to be an invalid rule in a custom category which was causing an exception and, consequently, the lua script wasn't able to complete and load all the rules.

![image](https://user-images.githubusercontent.com/3397663/85306265-83658880-b4ae-11ea-8a75-8fb7a1bc6e59.png).

Issue is now fixed in dev and stable.

**Closed as completed by simonemainardi** 2020-06-22 17:54 UTC
Labels: Low-Priority Bug
