### ISSUE TITLE
Segfault after upgrade to latest dev build (05 oct)

### ISSUE THREAD

**Issue by Alestor** [ntop/ntopng#778] opened 2016-10-05 13:35 UTC
Starting ntopng results in a segfault when using my default config:

ntopng /etc/ntopng/ntopng.conf
05/Oct/2016 15:28:27 [Ntop.cpp:1124] Setting local networks to 192.168.0.1/24,192.168.1.0/24,192.168.3.0/24,192.168.4.0/24,192.168.8.0/24,192.168.10.0/24,172.16.2.0/24,172.16.3.0/24,172.16.4.0/24,172.16.20.0/24
05/Oct/2016 15:28:27 [Redis.cpp:103] Successfully connected to redis 127.0.0.1:6379@0
05/Oct/2016 15:28:27 [NtopPro.cpp:121] [LICENSE] Read license from Redis [key]
05/Oct/2016 15:28:27 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface eth1...
05/Oct/2016 15:28:27 [MySQLDB.cpp:635] Succesfully connected to MySQL [localhost:ntopng_user] for interface eth1
05/Oct/2016 15:28:27 [PF_RINGInterface.cpp:53] Reading packets from PF_RING v.6.5.0 interface eth1...
05/Oct/2016 15:28:27 [Ntop.cpp:1223] Registered interface eth1 [id: 2]
05/Oct/2016 15:28:27 [main.cpp:246] PID stored in file /var/run/ntopng.pid
05/Oct/2016 15:28:27 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
05/Oct/2016 15:28:27 [Utils.cpp:354] User changed to ntop
05/Oct/2016 15:28:27 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
05/Oct/2016 15:28:27 [HTTPserver.cpp:555] HTTP server listening on port 3000
05/Oct/2016 15:28:27 [MySQLDB.cpp:595] Attempting to connect to MySQL for interface eth1...
05/Oct/2016 15:28:27 [MySQLDB.cpp:635] Succesfully connected to MySQL [localhost:ntopng_user] for interface eth1
05/Oct/2016 15:28:27 [main.cpp:307] Working directory: /var/ntop/data
05/Oct/2016 15:28:27 [main.cpp:309] Scripts/HTML pages directory: /usr/share/ntopng
05/Oct/2016 15:28:27 [Ntop.cpp:267] Welcome to ntopng x86_64 v.2.5.161005 - (C) 1998-2016 ntop.org
05/Oct/2016 15:28:27 [Ntop.cpp:272] Built on Debian GNU/Linux 8.2 (jessie)
05/Oct/2016 15:28:27 [PeriodicActivities.cpp:53] Started periodic activities loop...
Speicherzugriffsfehler
ntopng[3050]: segfault at 0 ip 000000000048870f sp 00007ffdcaf5eb70 error 4 in ntopng[400000+21e000]

my config:

-G=/var/run/ntopng.pid
-U=ntop
-d=/var/ntop/data
-i=eth1
-n=0
-m=192.168.x.0/24,192.168.x.0/24,192.168.x.0/24,192.168.x.0/24,192.168.x.0/24,192.168.x.0/24,172.16.x.0/24,172.16.x.0/24,172.16.x.0/24,172.16.x.0/24
--dump-flows=mysql;localhost;<db>;<table>;<user>;<password>
--sticky-hosts local
--dump-hosts all
--disable-alerts

**Comment by b0ns** [comment] 2016-10-05 18:15
I Confirm same behavior.
Segfault started when using the "--sticky-hosts local"

Package details:
`ntopng Pro [Small Business Edition] v.2.5.161004`

System details:
`Linux host 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
Jessie 8.5`

Procedure to reproduce:
- Start with flushed redis
- Start ntopng normally (without any sticky option)
- Stop ntopng
- Start ntopng with "--sticky-hosts local"
- It works
- Stop ntopng
- Start again with "--sticky-hosts local"
- Segfault!
  (the same seems to happen with any sticky option)

Temporary workarounds to run:
- Disable sticky-hosts option and don't use it.
- Flush redis and start with the sticky option, but if process stops it will segfault till sticky is removed.

Crash logs:

With sticky hosts "--sticky-hosts local"
`04/Oct/2016 17:22:49 [Prefs.cpp:962] Flow activity detection enabled
04/Oct/2016 17:22:49 [Ntop.cpp:1124] Setting local networks to x.x.x.x/32
04/Oct/2016 17:22:49 [Redis.cpp:103] Successfully connected to redis 127.0.0.1:6379@0
04/Oct/2016 17:22:49 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
04/Oct/2016 17:22:49 [PcapInterface.cpp:85] Reading packets from interface eth0...
04/Oct/2016 17:22:49 [Ntop.cpp:1223] Registered interface eth0 [id: 0]
04/Oct/2016 17:22:49 [main.cpp:246] PID stored in file /var/run/ntopng.pid
04/Oct/2016 17:22:49 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
04/Oct/2016 17:22:49 [Utils.cpp:354] User changed to nobody
04/Oct/2016 17:22:49 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
04/Oct/2016 17:22:49 [HTTPserver.cpp:555] HTTP server listening on port 3000
04/Oct/2016 17:22:49 [main.cpp:307] Working directory: /var/tmp/ntopng
04/Oct/2016 17:22:49 [main.cpp:309] Scripts/HTML pages directory: /usr/share/ntopng
04/Oct/2016 17:22:49 [Ntop.cpp:267] Welcome to ntopng x86_64 v.2.5.161004 - (C) 1998-2016 ntop.org
04/Oct/2016 17:22:49 [Ntop.cpp:272] Built on Debian GNU/Linux 8.2 (jessie)
04/Oct/2016 17:22:49 [PeriodicActivities.cpp:53] Started periodic activities loop...
Segmentation fault
`

Crash under DDOS attack with working --sticky-hosts local and -v 6 with CLI start:
`ntopng -i eth0 -m "x.x.x.x/32" -n 0 -S local -v 6
04/Oct/2016 17:23:06 [Ntop.cpp:1124] Setting local networks to x.x.x.x/32
04/Oct/2016 17:23:06 [AddressTree.cpp:141] Rule x.x.x.x/32
04/Oct/2016 17:23:06 [Redis.cpp:103] Successfully connected to redis 127.0.0.1:6379@0
04/Oct/2016 17:23:06 [NtopPro.cpp:123] [LICENSE] Reading license from /etc/ntopng.license
04/Oct/2016 17:23:06 [main.cpp:136] System has 8 CPU cores
04/Oct/2016 17:23:06 [Utils.cpp:1462] Interface eth0 has MAC Speed = 1000
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 0 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 1 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 2 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 3 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 4 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 5 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 6 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 7 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 8 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 9 with no shaping max rate
04/Oct/2016 17:23:06 [Profiles.cpp:36] Destroying Profiles
04/Oct/2016 17:23:06 [Utils.cpp:1462] Interface eth0 has MAC Speed = 1000
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 0 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 1 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 2 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 3 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 4 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 5 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 6 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 7 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 8 with no shaping max rate
04/Oct/2016 17:23:06 [L7Policer.cpp:80] Created policer 9 with no shaping max rate
04/Oct/2016 17:23:06 [PcapInterface.cpp:85] Reading packets from interface eth0...
04/Oct/2016 17:23:06 [Ntop.cpp:1223] Registered interface eth0 [id: 0]
04/Oct/2016 17:23:06 [main.cpp:246] PID stored in file /var/run/ntopng.pid
04/Oct/2016 17:23:06 [HTTPserver.cpp:507] Please read https://github.com/ntop/ntopng/blob/dev/doc/README.SSL if you want to enable SSL.
04/Oct/2016 17:23:06 [Utils.cpp:354] User changed to nobody
04/Oct/2016 17:23:06 [HTTPserver.cpp:552] Web server dirs [/usr/share/ntopng/httpdocs][/usr/share/ntopng/scripts]
04/Oct/2016 17:23:06 [HTTPserver.cpp:555] HTTP server listening on port 3000
04/Oct/2016 17:23:06 [main.cpp:307] Working directory: /var/tmp/ntopng
04/Oct/2016 17:23:06 [main.cpp:309] Scripts/HTML pages directory: /usr/share/ntopng
04/Oct/2016 17:23:06 [Ntop.cpp:267] Welcome to ntopng x86_64 v.2.5.161004 - (C) 1998-2016 ntop.org
04/Oct/2016 17:23:06 [Ntop.cpp:272] Built on Debian GNU/Linux 8.2 (jessie)
04/Oct/2016 17:23:06 [PeriodicActivities.cpp:53] Started periodic activities loop...
04/Oct/2016 17:23:06 [PeriodicActivities.cpp:92] Starting script /usr/share/ntopng/scripts/callbacks/startup.lua
04/Oct/2016 17:23:06 [Lua.cpp:3028] ntop_get_dirs() called
04/Oct/2016 17:23:06 [Lua.cpp:2942] ntop_is_pro() called
04/Oct/2016 17:23:06 [Lua.cpp:2629] ntop_get_prefs() called
04/Oct/2016 17:23:06 [Lua.cpp:219] ntop_get_interface_names() called
04/Oct/2016 17:23:06 [Ntop.cpp:755] No allowed interface found for eth0
04/Oct/2016 17:23:06 [Lua.cpp:227] Returning name eth0
04/Oct/2016 17:23:06 [Lua.cpp:275] ntop_select_interface() called
04/Oct/2016 17:23:06 [Ntop.cpp:755] No allowed interface found for eth0
04/Oct/2016 17:23:06 [Lua.cpp:219] ntop_get_interface_names() called
04/Oct/2016 17:23:06 [Ntop.cpp:755] No allowed interface found for eth0
04/Oct/2016 17:23:06 [Lua.cpp:227] Returning name eth0
04/Oct/2016 17:23:06 [Lua.cpp:275] ntop_select_interface() called
04/Oct/2016 17:23:06 [Ntop.cpp:755] No allowed interface found for eth0
04/Oct/2016 17:23:06 [Lua.cpp:254] getCurrentInterface() called
04/Oct/2016 17:23:06 [Lua.cpp:2933] ntop_get_interface_stats() called
04/Oct/2016 17:23:06 [Lua.cpp:4045] ntop_get_keys_redis() called
04/Oct/2016 17:23:06 [Lua.cpp:254] getCurrentInterface() called
04/Oct/2016 17:23:06 [Lua.cpp:1587] ntop_restore_interface_host() called
Segmentation fault`

Stack Trace of SIGSEGV with a working ntopng instance by just activating the sticky option:
`close(27)                               = 0
munmap(0x7f8e1e576000, 4096)            = 0
open("/usr/share/ntopng/pro/scripts/callbacks/dkjson.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/ntopng/scripts/lua/modules/dkjson.lua", O_RDONLY) = 27
close(27)                               = 0
open("/usr/share/ntopng/scripts/lua/modules/dkjson.lua", O_RDONLY) = 27
fstat(27, {st_mode=S_IFREG|0644, st_size=22416, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e1e576000
read(27, "-- Module options:\nlocal always_"..., 4096) = 4096
lseek(27, 0, SEEK_SET)                  = 0
read(27, "-- Module options:\nlocal always_"..., 4096) = 4096
read(27, "end\nend\n\nlocal function fsub (st"..., 4096) = 4096
read(27, " if not ret then return exceptio"..., 4096) = 4096
read(27, "il end\n    local sub2 = strsub ("..., 4096) = 4096
read(27, "  end\n      pos = scanwhite (str"..., 4096) = 4096
read(27, "e LPeg limits.\n  local function "..., 4096) = 1936
read(27, "", 4096)                      = 0
close(27)                               = 0
munmap(0x7f8e1e576000, 4096)            = 0
open("/usr/share/ntopng/pro/scripts/callbacks/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/ntopng/scripts/lua/modules/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("./lpeg.lua", O_RDONLY)            = -1 ENOENT (No such file or directory)
open("/usr/local/share/luajit-2.0.3/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/lua/5.1/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/lua/5.1/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
futex(0x7f8e1dcc20c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
open("/usr/share/ntopng/pro/scripts/callbacks/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/ntopng/scripts/lua/modules/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("./lpeg.lua", O_RDONLY)            = -1 ENOENT (No such file or directory)
open("/usr/local/share/luajit-2.0.3/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/lua/5.1/lpeg.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/share/lua/5.1/lpeg/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("./lpeg.so", O_RDONLY)             = -1 ENOENT (No such file or directory)
open("/usr/local/lib/lua/5.1/lpeg.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/lua/5.1/loadall.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/ntopng/pro/scripts/callbacks/persistence.lua", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/ntopng/scripts/lua/modules/persistence.lua", O_RDONLY) = 27
close(27)                               = 0
open("/usr/share/ntopng/scripts/lua/modules/persistence.lua", O_RDONLY) = 27
fstat(27, {st_mode=S_IFREG|0644, st_size=5650, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e1e576000
read(27, "-- Internal persistence library\n"..., 4096) = 4096
lseek(27, 0, SEEK_SET)                  = 0
read(27, "-- Internal persistence library\n"..., 4096) = 4096
read(27, "= \"Lua\" then\n\t\t\t\tfile:write(\"nil"..., 4096) = 1554
read(27, "", 4096)                      = 0
close(27)                               = 0
munmap(0x7f8e1e576000, 4096)            = 0
mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_32BIT, -1, 0) = 0x408b4000
open("/proc/net/dev", O_RDONLY)         = 27
fstat(27, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e1e576000
read(27, "Inter-|   Receive               "..., 1024) = 1024
close(27)                               = 0
munmap(0x7f8e1e576000, 4096)            = 0
getsockopt(21, SOL_PACKET, PACKET_STATISTICS, {packets=7, drops=0}, [8]) = 0
write(9, "*2\r\n$4\r\nKEYS\r\n$33\r\nntopng.serial"..., 54) = 54
read(9, "*5\r\n$48\r\nntopng.serialized_hosts"..., 16384) = 317
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault
`

Config used:
`
--pid-path=/var/tmp/ntopng.pid
--interface=eth0
--http-port=3000
--local-networks="x.x.x.x/32"
--dns-mode=0
--data-dir=/var/tmp/ntopng
--ndpi-protocols=/etc/ntopng/ntop.protos
--enable-flow-activity
--sticky-hosts local
`

The feeling is that with the sticky option something gets corrupted in redis or some interface data/stats or details cannot be processed correctly ending up in segfault. just a wide guess.

**Comment by alext234** [comment] 2016-10-06 02:11
I think i have the same problem. Using gdb with the dump file shows the location of seg fault:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004951a8 in Utils::macHash (mac=0x0) at src/Utils.cpp:1599
1599        hash += mac[i] << (i+1);
[Current thread is 1 (Thread 0x7f921a43b900 (LWP 4567))]

**Comment by lucaderi** [comment] 2016-10-06 09:06
@alext234 Can you please send a longer trace log (I mean the backtrace)?

**Comment by simonemainardi** [comment] 2016-10-06 09:25
I can confirm it is fixed on my side

**Comment by alext234** [comment] 2016-10-06 09:27
unable to reproduce for now as I have been playing with _stable-2.4_ branch and it does not happen when i switch back to _dev_ branch.
unfortunately I forget to keep the core dump file i had this morning. Will update if it happen again.

**Comment by lucaderi** [comment] 2016-10-06 09:37
Bug fixed. Packages are being rebuilt and will be available within 30 mins

**Closed as completed by lucaderi** 2016-10-06 09:37 UTC
