### ISSUE TITLE
When running ntopng network discovery the traffic report hangs

### ISSUE THREAD

**Issue by StewAlexander-com** [ntop/ntopng#3183] opened 2020-01-02 14:03 UTC
NTOPNG version info:

![image](https://user-images.githubusercontent.com/48565067/71670701-bec49d00-2d3e-11ea-80b9-8ffd453e6059.png)
---
![image](https://user-images.githubusercontent.com/48565067/71670627-7311f380-2d3e-11ea-9e44-8a8c94db09ca.png)

**Comment by simonemainardi** [comment] 2020-01-02 15:43
hi, how can you tell this is due to the network discovery? please give any possible detail

**Comment by StewAlexander-com** [comment] 2020-01-02 15:48
@simonemainardi 

The simplest explanation is that after running network discovery, and before it finishes I go to the traffic report screen and it times out as above.

After the network discovery process is finished, I go to the same traffic discovery page and it loads as expected.

**Comment by simonemainardi** [comment] 2020-01-03 10:26
Do you know at what percentage the discovery is when the report hangs? Does the report page fail to completely load? Can you please open the browser inspector and tell if you see any pending HTTP requests? Is there an heavy redis activity? Please, check it with `redis-cli monitor`

**Comment by StewAlexander-com** [comment] 2020-01-03 12:29
I cannot replicate the problem...

I believe it may be because when I originally saw this, I had just upgraded ntopng. theory is it wasn't at a "steady-state" yet, and so therefore a resource allocation issue occurred -- just conjecture.

Now that the latest ntopng has had a day to collect data, there's no longer the hang.

Could you please attempt a replication?

Thank you ...

**Comment by simonemainardi** [comment] 2020-01-07 09:40
I'm unable to replicate. I've tried to forcefully block the discovery process in the middle and generate reports several times, but under no circumstance I've been able to reproduce. Reports always generate and do not hang. So I am closing this for now but feel free to comment again or reopen if you find additional evidence of a systematic way to reproduce.

**Closed as completed by simonemainardi** 2020-01-07 09:40 UTC
Labels: In Progress
