### ISSUE TITLE
Update Active Monitoring Time Picker

### ISSUE THREAD

**Issue by lucaderi** [ntop/ntopng#6225] opened 2022-01-20 10:08 UTC
![Screenshot 2022-01-20 at 11 07 07](https://user-images.githubusercontent.com/4493366/150317935-9e3dab34-1875-4a8d-b67a-5648eafccb59.png)

**Comment by MatteoBiscosi** [comment] 2022-02-22 12:34
duplicate of #6301

**Closed as completed by MatteoBiscosi** 2022-02-22 12:34 UTC
Labels: Enhancement
