### ISSUE TITLE
ntopng crashing each night at exactly 1:00am

### ISSUE THREAD

**Issue by colinvv2** [ntop/ntopng#754] opened 2016-09-17 15:49 UTC
Not sure why, but after my last release upgrade to '2.4.160913-1653', the ntopng service is just stopping with no specific error. See log: [ntopng.txt](https://github.com/ntop/ntopng/files/478237/ntopng.txt)

**Comment by lucaderi** [comment] 2016-09-17 17:03
Duplicate of https://github.com/ntop/ntopng/issues/751

**Closed as completed by lucaderi** 2016-09-17 17:03 UTC
