### ISSUE TITLE
Webhook Discord time drift

### ISSUE THREAD

**Issue by Zathiel** [ntop/ntopng#4705] opened 2020-11-10 22:29 UTC
Hello issue to a call with luca.

When i received a big amount of flow error.

Time can be drifted

![image](https://user-images.githubusercontent.com/26553418/98741209-881ed080-23ac-11eb-86e0-d2507d7d90c7.png)

Regards

**Comment by simonemainardi** [comment] 2020-11-11 11:13
This is too generic to allow investigation. Give details. Screenshots. Experienced behavior. Add data and timestamps to understand what you mean with drifted.

**Comment by Zathiel** [comment] 2020-11-11 12:11
When a big amount of request is generated time can drift to more than one hour.

**Comment by simonemainardi** [comment] 2020-11-11 13:44
> Add data and timestamps to understand what you mean with drifted.

**Comment by Zathiel** [comment] 2020-11-11 15:52
like in the screenshare i provide message is sent on discord at 23h28 but its a flow of 22h55

**Comment by simonemainardi** [comment] 2020-11-11 16:03
check ntopng logs. To me, you've too many alerts that discord can't receive them and it throttles the messages which stay in queue waiting to be sent. You should increase the severity (> info) to send less alerts to discord.

**Comment by Zathiel** [comment] 2020-11-18 11:16
Hello Simon,

I already increase the severity from info to warning 

Where is located the logfiles that u need ?

Regards

**Comment by Zathiel** [comment] 2020-11-20 00:46
Simon,

i have set the minimum severity to warning but still have a lots of alerts (Flows Blacklist recipients) can cause time drift ~ + 1 hour

Can you have a look when u have some times as per its a blocking issue for me

Regards

**Comment by lucaderi** [comment] 2020-12-18 18:08
The problem is that ntopng does not keep-up with discord export.

**Comment by simonemainardi** [comment] 2020-12-31 09:54
Closing this as everything is working as expected. When sending too many alerts to discord, discord server starts throttling (as also told in an ntopng alert) and alerts remain in the ntopng export queue as the server is not willing to accept them.

You should change the severity and limit the alerts sent do discord. Otherwise, you should switch to email or other endpoints that don't enforce throttling.

**Closed as completed by simonemainardi** 2020-12-31 09:54 UTC
