### ISSUE TITLE
ntopng claims some flows with 136 year duration

### ISSUE THREAD

**Issue by hatclub** [ntop/ntopng#597] opened 2016-06-02 09:40 UTC
Is this an issue with the Cisco exported netflow data, or an nprobe/ntopng error involving an unsigned 32 bit int (as iirc 136 years in seconds is somewhere in the region of the maximum value of an unsigned 32 bit int), or some sort of issue in nprobe not knowing the uptime of the exporting device (as netflow records export in milliseconds since boot, iirc?)

![136 years](https://cloud.githubusercontent.com/assets/5437917/15740768/5723b408-28ae-11e6-89cc-92bf97fc2499.png)

**Comment by Niko78** [comment] 2016-06-02 09:57
yep same for me but Luca already reported it
https://github.com/ntop/ntopng/issues/569

**Comment by lucaderi** [comment] 2016-06-02 10:11
Duplicate of #569

**Closed as completed by lucaderi** 2016-06-02 10:11 UTC
