### ISSUE TITLE
Chrome login error

### ISSUE THREAD

**Issue by Xalaxis** [ntop/ntopng#790] opened 2016-10-20 15:31 UTC
When attempting to login to the NTOpng web interface from a chrome-based browser (So I'd assume this is a webkit-realated bug) validator.js provides this error:

validator.js:83 Pattern attribute value ^[\w\$\!\/()\=\?^*@_-\u0000-\u00ff]{1,}$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^[\w\$\!\/()\=\?^*@_-\u0000-\u00ff]{1,}$/: Invalid escapenative @ validator.js:83(anonymous function) @ validator.js:144proxy @ jquery.js:547each @ jquery.js:391Validator.runValidators @ validator.js:143Validator.validateInput @ validator.js:108proxy @ jquery.js:547dispatch @ jquery.js:4641elemData.handle @ jquery.js:4309

And no login can be used without the 'login' button greying out.

**Comment by simonemainardi** [comment] 2016-10-21 09:02
duplicate of https://github.com/ntop/ntopng/issues/775

**Closed as completed by simonemainardi** 2016-10-21 09:02 UTC
Labels: Duplicate
