### ISSUE TITLE
Install not working on Mac

### ISSUE THREAD

**Issue by kewp** [ntop/ntopng#5855] opened 2021-09-09 08:14 UTC
I downloaded and installed the latest ntopng package (5.1.210826). Everything said it worked fine. However, when I go to localhost:3000 (or 127.0.0.1:3000) it says Unable to connect.

How do I debug this issue? Is there an install log somewhere?

I tried starting it manually with `sudo /usr/local/bin/ntopng` but it says `[Redis.cpp:99] ERROR: Connection error [Connection refused]`

**Comment by simonemainardi** [comment] 2021-09-09 08:51
There must be a Redis instance up and running. This is brought up automatically. My guess is that something is preventing Redis to come up. Can you please check.

Indeed, this command is issued automatically in the postinstall

```
sudo launchctl load -w /Library/LaunchDaemons/io.redis.redis-server.plist
```

Try to execute manually and look for errors.

**Comment by kewp** [comment] 2021-09-09 09:21
Hi. Thanks for replying. I ran the command:

```
sudo launchctl load -w /Library/LaunchDaemons/io.redis.redis-server.plist
/Library/LaunchDaemons/io.redis.redis-server.plist: service already loaded
Load failed: 37: Operation already in progress
```

Any advice on what to do now?

**Comment by lucaderi** [comment] 2021-09-09 10:10
Try `unload` and `load` it again. This said redis is an external component. If not working for you, you can use an external redis package, e.g. the one part of https://brew.sh

**Comment by kewp** [comment] 2021-09-09 10:11
Thanks @lucaderi . I don't follow, unload and load? I did not install redis. Perhaps it was another piece of software I installed?

**Comment by kewp** [comment] 2021-09-09 17:58
I've tried unloading and loading again (same command as above). I've also installed redis via brew. Same thing

```
sudo /usr/local/bin/ntopng
09/Sep/2021 19:57:58 [Ntop.cpp:3371] Added Local Network 127.0.0.0/8
09/Sep/2021 19:57:58 [Ntop.cpp:3371] Added Local Network fe80::/10
09/Sep/2021 19:57:58 [Redis.cpp:99] ERROR: Connection error [Connection refused]
09/Sep/2021 19:57:59 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 14]
09/Sep/2021 19:57:59 [Redis.cpp:99] ERROR: Connection error [Connection refused]
09/Sep/2021 19:58:00 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 13]
09/Sep/2021 19:58:00 [Redis.cpp:99] ERROR: Connection error [Connection refused]
09/Sep/2021 19:58:01 [Redis.cpp:83] Redis has disconnected, reconnecting [remaining attempts: 12]
09/Sep/2021 19:58:01 [Redis.cpp:99] ERROR: Connection error [Connection refused]
```

**Comment by simonemainardi** [comment] 2021-09-10 14:55
You need to investigate the Redis error you are getting: `Load failed: 37: Operation already in progress`.

Try to stop it, then restart it.

```
sudo launchctl unload -w /Library/LaunchDaemons/io.redis.redis-server.plist
sudo launchctl load -w /Library/LaunchDaemons/io.redis.redis-server.plist
```

if Redis isn't running, ntopng can't work.

Check with

```
ps aux | grep redis
```

**Comment by kewp** [comment] 2021-09-10 15:36
Ok so for future reference: I had to edit `/usr/local/etc/redis.conf` and then change `logfile` to point to `/var/log/redis.log`. Then when I do the unload / load commands I get output. Redis crashed. See attached file. Note: it is the `ntopng-redis-server` version. (I suppose I should try get my own redis working? I did try with homebrew but not sure how that all works...).

[redis.log](https://github.com/ntop/ntopng/files/7144863/redis.log)

**Comment by kewp** [comment] 2021-09-10 15:41
I got it working. So I installed redis via homebrew (`brew install redis`) and then started with `brew services start redis`. I then had to shut down ntopng with `sudo launchctl unload /Library/LaunchDaemons/org.ntop.ntopng.plist` and restart with `sudo launchctl load /Library/LaunchDaemons/org.ntop.ntopng.plist`. Now I can browse to `localhost:3000` and all is happy.

Perhaps this is something to do with my mac using the M1 chipset, and the version of redis bundled with ntopng?

**Comment by simonemainardi** [comment] 2021-09-15 07:44
Our tests pipeline doesn't highlight issues with the M1. It would have been nice to see the logs generated when running `sudo launchctl load -w /Library/LaunchDaemons/io.redis.redis-server.plist` to understand what was the issue. Do you think you can provide them?

**Comment by kewp** [comment] 2021-09-15 13:01
Hi @simonemainardi I do provide just this log in my comment above

**Comment by simonemainardi** [comment] 2021-09-16 14:34
Currently, we are unable to reproduce. I am closing this for now and will reopen if necessary. Thanks for providing feedback tough.

**Closed as completed by simonemainardi** 2021-09-16 14:34 UTC
Labels: To Be Confirmed
